package Bounce_v1_5_4
//same as Bounce_v1_0_0 except that it requries Drools 5.4

import org.opencds.vmr.v1_0.internal.ClinicalStatement
import org.opencds.vmr.v1_0.internal.ClinicalStatementRelationship
import org.opencds.vmr.v1_0.internal.EntityBase
import org.opencds.vmr.v1_0.internal.EntityRelationship
import org.opencds.vmr.v1_0.internal.ObservationResult
import org.opencds.vmr.v1_0.internal.ObservationValue
import org.opencds.vmr.v1_0.internal.RelationshipToSource
import org.opencds.vmr.v1_0.internal.datatypes.CD
import org.opencds.vmr.v1_0.internal.datatypes.IVLDate
import org.opencds.vmr.v1_0.internal.concepts.VmrOpenCdsConcept

import java.util.Date
import java.util.List
import java.util.ArrayList

global java.util.Date evalTime
global String clientLanguage
global String clientTimeZoneOffset
global String focalPersonId
global java.util.HashSet assertions
global java.util.HashMap namedObjects



//NOTE:  all demographics about the Patient are always returned in the result 
//			when the result is an outputVMR.

//NOTE2:  all Entities that have a relationship to a ClinicalStatement or to another Entity 
//			are always returned nested within that ClinicalStatement or Entity ONLY if that
//			ClinicalStatement or Entity (or one of its ancestors) is flagged toBeReturned.  

//NOTE3:  all Entities that are related directly to the patient will be returned or not
//			depending on the setting of the toBeReturned flag.

rule "BounceAllEntities"
	dialect "mvel"
	when
		$entityBase : EntityBase()
	then
		$entityBase.setToBeReturned( true );
end


rule "BounceAllClinicalStatements"
	dialect "mvel"
	when
		$cs : ClinicalStatement()
	then
		$cs.setToBeReturned( true );
end

rule "SetNestedAllClinicalStatements"
	dialect "mvel"
	when
		$cs : ClinicalStatement( ClinicalStatementToBeRoot == true )
		$csr : ClinicalStatementRelationship( targetId == $cs.id )
	then
		$cs.setClinicalStatementToBeRoot( false );
end

rule "ReturnAllClinicalConcepts"
	dialect "java"
	when
		$cs : ClinicalStatement()
		$concept : VmrOpenCdsConcept ( conceptTargetId == $cs.getId() )
	then
		IVLDate obsTime = new IVLDate(); 
		obsTime.setLow(new Date()); 
		obsTime.setHigh(new Date()); 
		ObservationResult childObs = new ObservationResult(); 
		childObs.setId($concept.getId()); 
		childObs.setEvaluatedPersonId($cs.getEvaluatedPersonId() ); 
		childObs.setObservationEventTime(obsTime); 
		childObs.setSubjectIsFocalPerson($cs.isSubjectIsFocalPerson() ); 
		CD childObsFocus = new CD(); 
		childObsFocus.setCodeSystem("2.16.840.1.113883.3.795.12.1.1"); 
		childObsFocus.setCodeSystemName("OpenCDS concepts"); 
		childObsFocus.setCode("cs"); 
		childObsFocus.setDisplayName("Concept Codes attached to this clinical statement"); 
		childObs.setObservationFocus(childObsFocus); 
		
		String childObsText = $concept.toString();
		ObservationValue childObsValue = new ObservationValue(); 
		childObsValue.setText(childObsText);
		 
		childObs.setObservationValue(childObsValue);
		childObs.setClinicalStatementToBeRoot(false); 
		childObs.setToBeReturned(true); 
		ClinicalStatementRelationship rel = new ClinicalStatementRelationship(); 
		rel.setSourceId($cs.getId()); 
		rel.setTargetId($concept.getId()); 
		CD relCode = new CD(); 
		relCode.setCodeSystem("2.16.840.1.113883.3.795.12.1.2"); 
		relCode.setCodeSystemName("OpenCDS concepts"); 
		relCode.setCode("PartOf"); 
		relCode.setDisplayName("Part of"); 
		rel.setTargetRelationshipToSource(relCode); 
		java.util.List<RelationshipToSource> childObsRelationshipToSources = new java.util.ArrayList<RelationshipToSource>(); 
		RelationshipToSource childObsRelationshipToSource = new RelationshipToSource(); 
		childObsRelationshipToSource.setSourceId($cs.getId()); 
		childObsRelationshipToSource.setRelationshipToSource(relCode); 
		childObsRelationshipToSources.add(childObsRelationshipToSource); 
		insert(childObs); 
		namedObjects.put("childObs" + $concept.getId(), childObs); 
		insert(rel); 
		namedObjects.put("rel" + $concept.getId(), rel); 		

end

	
rule "ReturnAllEntityConcepts"
	dialect "java"
	when
		$eb : EntityBase()
		$concept : VmrOpenCdsConcept ( conceptTargetId == $eb.getId() )
	then
		IVLDate obsTime = new IVLDate(); 
		obsTime.setLow(new Date()); 
		obsTime.setHigh(new Date()); 
		ObservationResult childObs = new ObservationResult(); 
		childObs.setId($concept.getId()); 
		childObs.setEvaluatedPersonId($eb.getEvaluatedPersonId() ); 
		childObs.setObservationEventTime(obsTime); 
		//childObs.setSubjectIsFocalPerson($eb.isSubjectIsFocalPerson() ); 
		CD childObsFocus = new CD(); 
		childObsFocus.setCodeSystem("2.16.840.1.113883.3.795.12.1.2"); 
		childObsFocus.setCodeSystemName("OpenCDS concepts"); 
		childObsFocus.setCode("eb"); 
		childObsFocus.setDisplayName("Concept Codes attached to this entity"); 
		childObs.setObservationFocus(childObsFocus); 
		
		String childObsText = $concept.toString();
		ObservationValue childObsValue = new ObservationValue(); 
		childObsValue.setText(childObsText);
		 
		childObs.setObservationValue(childObsValue);
		childObs.setClinicalStatementToBeRoot(false); 
		childObs.setToBeReturned(true); 
		ClinicalStatementRelationship rel = new ClinicalStatementRelationship(); 
		rel.setSourceId($eb.getId()); 
		rel.setTargetId($concept.getId()); 
		CD relCode = new CD(); 
		relCode.setCodeSystem("2.16.840.1.113883.3.795.12.1.1"); 
		relCode.setCodeSystemName("OpenCDS concepts"); 
		relCode.setCode("PartOf"); 
		relCode.setDisplayName("Part of"); 
		rel.setTargetRelationshipToSource(relCode); 
		java.util.List<RelationshipToSource> childObsRelationshipToSources = new java.util.ArrayList<RelationshipToSource>(); 
		RelationshipToSource childObsRelationshipToSource = new RelationshipToSource(); 
		childObsRelationshipToSource.setSourceId($eb.getId()); 
		childObsRelationshipToSource.setRelationshipToSource(relCode); 
		childObsRelationshipToSources.add(childObsRelationshipToSource); 
		insert(childObs); 
		namedObjects.put("childObs" + $concept.getId(), childObs); 
		insert(rel); 
		namedObjects.put("rel" + $concept.getId(), rel); 		

end


rule "ReturnAllClinicalStatementRelationshipConcepts"
	dialect "java"
	when
		$csr : ClinicalStatementRelationship( id not contains "relDebug=" )
		$cs : ClinicalStatement( id == $csr.getSourceId() )
		$ct : ClinicalStatement( id == $csr.getTargetId() )
		$concept : VmrOpenCdsConcept ( conceptTargetId == $csr.getId() )
	then
		IVLDate obsTime = new IVLDate(); 
		obsTime.setLow(new Date()); 
		obsTime.setHigh(new Date()); 
		
		ObservationResult childObs = new ObservationResult(); 
		childObs.setId($concept.getId()); 
		childObs.setEvaluatedPersonId($cs.getEvaluatedPersonId() ); 
		childObs.setObservationEventTime(obsTime); 
		//childObs.setSubjectIsFocalPerson($csr.isSubjectIsFocalPerson() ); 
		
		CD childObsFocus = new CD(); 
		childObsFocus.setCodeSystem("2.16.840.1.113883.3.795.12.1.1"); 
		childObsFocus.setCodeSystemName("OpenCDS concepts"); 
		childObsFocus.setCode("csr"); 
		childObsFocus.setDisplayName("Concept Codes attached to this CS relationship"); 
		childObs.setObservationFocus(childObsFocus); 
		
		String childObsText = $concept.toString();
		ObservationValue childObsValue = new ObservationValue(); 
		childObsValue.setText(childObsText);
		 
		childObs.setObservationValue(childObsValue);
		childObs.setClinicalStatementToBeRoot(false); 
		childObs.setToBeReturned(true); 
		
		ClinicalStatementRelationship rel = new ClinicalStatementRelationship(); 
		//rel.setSourceId($csr.getSourceId()); 
		rel.setSourceId($csr.getTargetId());
		rel.setTargetId($concept.getId()); 
		rel.setId("relDebug=" + rel.getSourceId() + "^" + rel.getTargetId());
		
		CD relCode = new CD(); 
		relCode.setCodeSystem("2.16.840.1.113883.3.795.12.1.2"); 
		relCode.setCodeSystemName("OpenCDS concepts"); 
		relCode.setCode("PartOf"); 
		relCode.setDisplayName("Part of"); 
		rel.setTargetRelationshipToSource(relCode); 
		
		java.util.List<RelationshipToSource> childObsRelationshipToSources = new java.util.ArrayList<RelationshipToSource>(); 
		RelationshipToSource childObsRelationshipToSource = new RelationshipToSource(); 
		childObsRelationshipToSource.setSourceId($csr.getSourceId()); 
		childObsRelationshipToSource.setRelationshipToSource(relCode); 
		childObsRelationshipToSources.add(childObsRelationshipToSource); 
		insert(childObs); 
		namedObjects.put("childObs" + $concept.getId(), childObs); 
		insert(rel); 
		namedObjects.put("rel" + $concept.getId(), rel); 		

end

	
rule "ReturnAllEntityRelationshipConcepts"
	dialect "java"
	when
		$er : EntityRelationship( id not contains "relDebug=" )
		$eb : EntityBase( id == $er.getTargetEntityId() )
		$concept : VmrOpenCdsConcept ( conceptTargetId == $er.getId() )
	then
		IVLDate obsTime = new IVLDate(); 
		obsTime.setLow(new Date()); 
		obsTime.setHigh(new Date()); 
		ObservationResult childObs = new ObservationResult(); 
		childObs.setId($concept.getId()); 
		childObs.setEvaluatedPersonId($eb.getEvaluatedPersonId() ); 
		childObs.setObservationEventTime(obsTime); 
		//childObs.setSubjectIsFocalPerson($er.isSubjectIsFocalPerson() ); 
		CD childObsFocus = new CD(); 
		childObsFocus.setCodeSystem("2.16.840.1.113883.3.795.12.1.1"); 
		childObsFocus.setCodeSystemName("OpenCDS concepts"); 
		childObsFocus.setCode("er"); 
		childObsFocus.setDisplayName("Concept Codes attached to this entity relationship"); 
		childObs.setObservationFocus(childObsFocus); 
		
		String childObsText = $concept.toString();
		ObservationValue childObsValue = new ObservationValue(); 
		childObsValue.setText(childObsText);
		 
		childObs.setObservationValue(childObsValue);
		childObs.setClinicalStatementToBeRoot(false); 
		childObs.setToBeReturned(true); 
		ClinicalStatementRelationship rel = new ClinicalStatementRelationship(); 
		rel.setSourceId($er.getSourceId()); 
		rel.setTargetId($concept.getId()); 
		rel.setId("relDebug=" + rel.getSourceId() + "^" + rel.getTargetId());
		CD relCode = new CD(); 
		relCode.setCodeSystem("2.16.840.1.113883.3.795.12.1.2"); 
		relCode.setCodeSystemName("OpenCDS concepts"); 
		relCode.setCode("PartOf"); 
		relCode.setDisplayName("Part of"); 
		rel.setTargetRelationshipToSource(relCode); 
		java.util.List<RelationshipToSource> childObsRelationshipToSources = new java.util.ArrayList<RelationshipToSource>(); 
		RelationshipToSource childObsRelationshipToSource = new RelationshipToSource(); 
		childObsRelationshipToSource.setSourceId($er.getSourceId()); 
		childObsRelationshipToSource.setRelationshipToSource(relCode); 
		childObsRelationshipToSources.add(childObsRelationshipToSource); 
		insert(childObs); 
		namedObjects.put("childObs" + $concept.getId(), childObs); 
		insert(rel); 
		namedObjects.put("rel" + $concept.getId(), rel); 		
	
end



 