<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>opencds-decision-support-rules</artifactId>
    <packaging>kjar</packaging>

    <parent>
        <groupId>org.cdsframework</groupId>
        <artifactId>ice</artifactId>
        <version>1.0.0</version>
    </parent>

    <properties>
        <kie.plugin.phase>none</kie.plugin.phase>
    </properties>

    <profiles>
        <profile>
            <id>compile-rules</id>
            <activation>
                <property>
                    <name>env.ICE_COMPILE_RULES</name>
                    <value>true</value>
                </property>
            </activation>
            <properties>
                <kie.plugin.phase>compile</kie.plugin.phase>
            </properties>
        </profile>
    </profiles>

    <dependencies>
        <dependency>
            <groupId>org.drools</groupId>
            <artifactId>drools-model-compiler</artifactId>
            <version>${drools.version}</version>
        </dependency>

        <dependency>
            <groupId>org.cdsframework</groupId>
            <artifactId>opencds-decision-support-core</artifactId>
            <version>${project.parent.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.kie</groupId>
                <artifactId>kie-maven-plugin</artifactId>
                <version>${drools.version}</version>
                <extensions>true</extensions>
                <executions>
                    <execution>
                        <id>default-build</id>
                        <phase>${kie.plugin.phase}</phase>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <generateModel>YES</generateModel>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
