
package org.omg.dss;

import javax.xml.ws.WebFault;

import org.omg.dss.exception.DSSRuntimeException;


/**
 * This class was generated by Apache CXF 2.2.9
 * Thu Jul 28 08:04:45 MDT 2011
 * Generated source version: 2.2.9
 * 
 */

@WebFault(name = "DSSRuntimeException", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss")
public class DSSRuntimeExceptionFault extends Exception {
    public static final long serialVersionUID = 20110728080445L;
    
    private DSSRuntimeException dssRuntimeException;

    public DSSRuntimeExceptionFault() {
        super();
    }
    
    public DSSRuntimeExceptionFault(String message) {
        super(message);
    }
    
    public DSSRuntimeExceptionFault(String message, Throwable cause) {
        super(message, cause);
    }

    public DSSRuntimeExceptionFault(String message, DSSRuntimeException dssRuntimeException) {
        super(message);
        this.dssRuntimeException = dssRuntimeException;
    }

    public DSSRuntimeExceptionFault(String message, DSSRuntimeException dssRuntimeException, Throwable cause) {
        super(message, cause);
        this.dssRuntimeException = dssRuntimeException;
    }

    public DSSRuntimeException getFaultInfo() {
        return this.dssRuntimeException;
    }
}
