/*
 * Copyright 2011-2020 OpenCDS.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.omg.dss;

import jakarta.xml.ws.WebFault;

import org.omg.dss.exception.DSSRuntimeException;


/**
 * This class was generated by Apache CXF 2.2.9
 * Thu Jul 28 08:04:45 MDT 2011
 * Generated source version: 2.2.9
 *
 */

@WebFault(name = "DSSRuntimeException", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss")
public class DSSRuntimeExceptionFault extends Exception {
    public static final long serialVersionUID = 20110728080445L;

    private DSSRuntimeException dssRuntimeException;

    public DSSRuntimeExceptionFault() {
        super();
    }

    public DSSRuntimeExceptionFault(String message) {
        super(message);
    }

    public DSSRuntimeExceptionFault(String message, Throwable cause) {
        super(message, cause);
    }

    public DSSRuntimeExceptionFault(String message, DSSRuntimeException dssRuntimeException) {
        super(message);
        this.dssRuntimeException = dssRuntimeException;
    }

    public DSSRuntimeExceptionFault(String message, DSSRuntimeException dssRuntimeException, Throwable cause) {
        super(message, cause);
        this.dssRuntimeException = dssRuntimeException;
    }

    public DSSRuntimeException getFaultInfo() {
        return this.dssRuntimeException;
    }
}
