/*
 * Copyright 2011-2020 OpenCDS.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.omg.dss;

import jakarta.xml.ws.WebFault;

import org.omg.dss.exception.EvaluationException;


/**
 * This class was generated by Apache CXF 2.2.9
 * Thu Jul 28 08:04:45 MDT 2011
 * Generated source version: 2.2.9
 * 
 */

@WebFault(name = "EvaluationException", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss")
public class EvaluationExceptionFault extends Exception {
    public static final long serialVersionUID = 20110728080445L;
    
    private EvaluationException evaluationException;

    public EvaluationExceptionFault() {
        super();
    }
    
    public EvaluationExceptionFault(String message) {
        super(message);
    }
    
    public EvaluationExceptionFault(String message, Throwable cause) {
        super(message, cause);
    }

    public EvaluationExceptionFault(String message, EvaluationException evaluationException) {
        super(message);
        this.evaluationException = evaluationException;
    }

    public EvaluationExceptionFault(String message, EvaluationException evaluationException, Throwable cause) {
        super(message, cause);
        this.evaluationException = evaluationException;
    }

    public EvaluationException getFaultInfo() {
        return this.evaluationException;
    }
}
