
package org.omg.dss;

import javax.xml.ws.WebFault;

import org.omg.dss.exception.InvalidTimeZoneOffsetException;


/**
 * This class was generated by Apache CXF 2.2.9
 * Thu Jul 28 08:04:45 MDT 2011
 * Generated source version: 2.2.9
 * 
 */

@WebFault(name = "InvalidTimeZoneOffsetException", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss")
public class InvalidTimeZoneOffsetExceptionFault extends Exception {
    public static final long serialVersionUID = 20110728080445L;
    
    private InvalidTimeZoneOffsetException invalidTimeZoneOffsetException;

    public InvalidTimeZoneOffsetExceptionFault() {
        super();
    }
    
    public InvalidTimeZoneOffsetExceptionFault(String message) {
        super(message);
    }
    
    public InvalidTimeZoneOffsetExceptionFault(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidTimeZoneOffsetExceptionFault(String message, InvalidTimeZoneOffsetException invalidTimeZoneOffsetException) {
        super(message);
        this.invalidTimeZoneOffsetException = invalidTimeZoneOffsetException;
    }

    public InvalidTimeZoneOffsetExceptionFault(String message, InvalidTimeZoneOffsetException invalidTimeZoneOffsetException, Throwable cause) {
        super(message, cause);
        this.invalidTimeZoneOffsetException = invalidTimeZoneOffsetException;
    }

    public InvalidTimeZoneOffsetException getFaultInfo() {
        return this.invalidTimeZoneOffsetException;
    }
}
