
package org.omg.dss;

import javax.xml.ws.WebFault;

import org.omg.dss.exception.InvalidDriDataFormatException;


/**
 * This class was generated by Apache CXF 2.2.9
 * Thu Jul 28 08:04:45 MDT 2011
 * Generated source version: 2.2.9
 * 
 */

@WebFault(name = "InvalidDriDataFormatException", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss")
public class InvalidDriDataFormatExceptionFault extends Exception {
    public static final long serialVersionUID = 20110728080445L;
    
    private InvalidDriDataFormatException invalidDriDataFormatException;

    public InvalidDriDataFormatExceptionFault() {
        super();
    }
    
    public InvalidDriDataFormatExceptionFault(String message) {
        super(message);
    }
    
    public InvalidDriDataFormatExceptionFault(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidDriDataFormatExceptionFault(String message, InvalidDriDataFormatException invalidDriDataFormatException) {
        super(message);
        this.invalidDriDataFormatException = invalidDriDataFormatException;
    }

    public InvalidDriDataFormatExceptionFault(String message, InvalidDriDataFormatException invalidDriDataFormatException, Throwable cause) {
        super(message, cause);
        this.invalidDriDataFormatException = invalidDriDataFormatException;
    }

    public InvalidDriDataFormatException getFaultInfo() {
        return this.invalidDriDataFormatException;
    }
}
