
package org.omg.dss;

import javax.xml.ws.WebFault;

import org.omg.dss.exception.InvalidTraitCriterionDataFormatException;


/**
 * This class was generated by Apache CXF 2.2.9
 * Thu Jul 28 08:04:45 MDT 2011
 * Generated source version: 2.2.9
 * 
 */

@WebFault(name = "InvalidTraitCriterionDataFormatException", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss")
public class InvalidTraitCriterionDataFormatExceptionFault extends Exception {
    public static final long serialVersionUID = 20110728080445L;
    
    private InvalidTraitCriterionDataFormatException invalidTraitCriterionDataFormatException;

    public InvalidTraitCriterionDataFormatExceptionFault() {
        super();
    }
    
    public InvalidTraitCriterionDataFormatExceptionFault(String message) {
        super(message);
    }
    
    public InvalidTraitCriterionDataFormatExceptionFault(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidTraitCriterionDataFormatExceptionFault(String message, InvalidTraitCriterionDataFormatException invalidTraitCriterionDataFormatException) {
        super(message);
        this.invalidTraitCriterionDataFormatException = invalidTraitCriterionDataFormatException;
    }

    public InvalidTraitCriterionDataFormatExceptionFault(String message, InvalidTraitCriterionDataFormatException invalidTraitCriterionDataFormatException, Throwable cause) {
        super(message, cause);
        this.invalidTraitCriterionDataFormatException = invalidTraitCriterionDataFormatException;
    }

    public InvalidTraitCriterionDataFormatException getFaultInfo() {
        return this.invalidTraitCriterionDataFormatException;
    }
}
