/*
 * Copyright 2011-2020 OpenCDS.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.omg.dss;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

import org.omg.dss.metadata.DescribeProfile;
import org.omg.dss.metadata.DescribeProfileResponse;
import org.omg.dss.metadata.DescribeScopingEntity;
import org.omg.dss.metadata.DescribeScopingEntityHierarchy;
import org.omg.dss.metadata.DescribeScopingEntityHierarchyResponse;
import org.omg.dss.metadata.DescribeScopingEntityResponse;
import org.omg.dss.metadata.DescribeSemanticRequirement;
import org.omg.dss.metadata.DescribeSemanticRequirementResponse;
import org.omg.dss.metadata.DescribeSemanticSignifier;
import org.omg.dss.metadata.DescribeSemanticSignifierResponse;
import org.omg.dss.metadata.DescribeTrait;
import org.omg.dss.metadata.DescribeTraitResponse;
import org.omg.dss.metadata.ListProfiles;
import org.omg.dss.metadata.ListProfilesResponse;

/**
 * This class was generated by Apache CXF 2.2.9
 * Thu Jul 28 08:04:45 MDT 2011
 * Generated source version: 2.2.9
 *
 */

@WebService(targetNamespace = "http://www.omg.org/spec/CDSS/201105/dssWsdl", name = "MetadataDiscovery")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MetadataDiscovery {

    @WebResult(name = "describeSemanticSignifierResponse", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss", partName = "parameters")
    @WebMethod(action = "http://www.omg.org/spec/CDSS/201105/dssWsdl:operation:describeSemanticSignifier")
    public DescribeSemanticSignifierResponse describeSemanticSignifier(
        @WebParam(partName = "parameters", name = "describeSemanticSignifier", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss")
        DescribeSemanticSignifier parameters
    ) throws UnrecognizedScopedEntityExceptionFault, DSSRuntimeExceptionFault;

    @WebResult(name = "describeScopingEntityResponse", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss", partName = "parameters")
    @WebMethod(action = "http://www.omg.org/spec/CDSS/201105/dssWsdl:operation:describeScopingEntity")
    public DescribeScopingEntityResponse describeScopingEntity(
        @WebParam(partName = "parameters", name = "describeScopingEntity", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss")
        DescribeScopingEntity parameters
    ) throws UnrecognizedScopingEntityExceptionFault, DSSRuntimeExceptionFault;

    @WebResult(name = "describeScopingEntityHierarchyResponse", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss", partName = "parameters")
    @WebMethod(action = "http://www.omg.org/spec/CDSS/201105/dssWsdl:operation:describeScopingEntityHierarchy")
    public DescribeScopingEntityHierarchyResponse describeScopingEntityHierarchy(
        @WebParam(partName = "parameters", name = "describeScopingEntityHierarchy", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss")
        DescribeScopingEntityHierarchy parameters
    ) throws UnrecognizedScopingEntityExceptionFault, DSSRuntimeExceptionFault;

    @WebResult(name = "describeSemanticRequirementResponse", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss", partName = "parameters")
    @WebMethod(action = "http://www.omg.org/spec/CDSS/201105/dssWsdl:operation:describeScopingEntity")
    public DescribeSemanticRequirementResponse describeSemanticRequirement(
        @WebParam(partName = "parameters", name = "describeSemanticRequirement", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss")
        DescribeSemanticRequirement parameters
    ) throws UnrecognizedScopedEntityExceptionFault, DSSRuntimeExceptionFault;

    @WebResult(name = "describeProfileResponse", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss", partName = "parameters")
    @WebMethod(action = "http://www.omg.org/spec/CDSS/201105/dssWsdl:operation:describeProfile")
    public DescribeProfileResponse describeProfile(
        @WebParam(partName = "parameters", name = "describeProfile", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss")
        DescribeProfile parameters
    ) throws UnrecognizedScopedEntityExceptionFault, DSSRuntimeExceptionFault;

    @WebResult(name = "listProfilesResponse", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss", partName = "parameters")
    @WebMethod(action = "http://www.omg.org/spec/CDSS/201105/dssWsdl:operation:listProfiles")
    public ListProfilesResponse listProfiles(
        @WebParam(partName = "parameters", name = "listProfiles", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss")
        ListProfiles parameters
    ) throws DSSRuntimeExceptionFault;

    @WebResult(name = "describeTraitResponse", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss", partName = "parameters")
    @WebMethod(action = "http://www.omg.org/spec/CDSS/201105/dssWsdl:operation:describeTrait")
    public DescribeTraitResponse describeTrait(
        @WebParam(partName = "parameters", name = "describeTrait", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss")
        DescribeTrait parameters
    ) throws UnrecognizedScopedEntityExceptionFault, DSSRuntimeExceptionFault;
}
