/*
 * Copyright 2011-2020 OpenCDS.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.omg.dss;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

import org.omg.dss.query.FindKMs;
import org.omg.dss.query.FindKMsResponse;
import org.omg.dss.query.GetKMDataRequirements;
import org.omg.dss.query.GetKMDataRequirementsForEvaluationAtSpecifiedTime;
import org.omg.dss.query.GetKMDataRequirementsForEvaluationAtSpecifiedTimeResponse;
import org.omg.dss.query.GetKMDataRequirementsResponse;
import org.omg.dss.query.GetKMDescription;
import org.omg.dss.query.GetKMDescriptionResponse;
import org.omg.dss.query.GetKMEvaluationResultSemantics;
import org.omg.dss.query.GetKMEvaluationResultSemanticsResponse;
import org.omg.dss.query.ListKMs;
import org.omg.dss.query.ListKMsResponse;

/**
 * This class was generated by Apache CXF 2.2.9
 * Thu Jul 28 08:04:45 MDT 2011
 * Generated source version: 2.2.9
 *
 */

@WebService(targetNamespace = "http://www.omg.org/spec/CDSS/201105/dssWsdl", name = "Query")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Query {

    @WebResult(name = "getKMDataRequirementsForEvaluationAtSpecifiedTimeResponse", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss", partName = "parameters")
    @WebMethod(action = "http://www.omg.org/spec/CDSS/201105/dssWsdl:operation:getKMDataRequirementsForEvaluationAtSpecifiedTime")
    public GetKMDataRequirementsForEvaluationAtSpecifiedTimeResponse getKMDataRequirementsForEvaluationAtSpecifiedTime(
        @WebParam(partName = "parameters", name = "getKMDataRequirementsForEvaluationAtSpecifiedTime", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss")
        GetKMDataRequirementsForEvaluationAtSpecifiedTime parameters
    ) throws UnrecognizedScopedEntityExceptionFault, DSSRuntimeExceptionFault;

    @WebResult(name = "getKMDataRequirementsResponse", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss", partName = "parameters")
    @WebMethod(action = "http://www.omg.org/spec/CDSS/201105/dssWsdl:operation:getKMDataRequirements")
    public GetKMDataRequirementsResponse getKMDataRequirements(
        @WebParam(partName = "parameters", name = "getKMDataRequirements", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss")
        GetKMDataRequirements parameters
    ) throws UnrecognizedScopedEntityExceptionFault, DSSRuntimeExceptionFault;

    @WebResult(name = "listKMsResponse", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss", partName = "parameters")
    @WebMethod(action = "http://www.omg.org/spec/CDSS/201105/dssWsdl:operation:listKMs")
    public ListKMsResponse listKMs(
        @WebParam(partName = "parameters", name = "listKMs", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss")
        ListKMs parameters
    ) throws UnrecognizedScopedEntityExceptionFault, UnrecognizedLanguageExceptionFault, DSSRuntimeExceptionFault, UnsupportedLanguageExceptionFault;

    @WebResult(name = "findKMsResponse", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss", partName = "parameters")
    @WebMethod(action = "http://www.omg.org/spec/CDSS/201105/dssWsdl:operation:findKMs")
    public FindKMsResponse findKMs(
        @WebParam(partName = "parameters", name = "findKMs", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss")
        FindKMs parameters
    ) throws InvalidTraitCriterionDataFormatExceptionFault, UnrecognizedScopedEntityExceptionFault, UnrecognizedLanguageExceptionFault, UnrecognizedTraitCriterionExceptionFault, DSSRuntimeExceptionFault;

    @WebResult(name = "getKMEvaluationResultSemanticsResponse", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss", partName = "parameters")
    @WebMethod(action = "http://www.omg.org/spec/CDSS/201105/dssWsdl:operation:getKMEvaluationResultSemantics")
    public GetKMEvaluationResultSemanticsResponse getKMEvaluationResultSemantics(
        @WebParam(partName = "parameters", name = "getKMEvaluationResultSemantics", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss")
        GetKMEvaluationResultSemantics parameters
    ) throws UnrecognizedScopedEntityExceptionFault, DSSRuntimeExceptionFault;

    @WebResult(name = "getKMDescriptionResponse", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss", partName = "parameters")
    @WebMethod(action = "http://www.omg.org/spec/CDSS/201105/dssWsdl:operation:getKMDescription")
    public GetKMDescriptionResponse getKMDescription(
        @WebParam(partName = "parameters", name = "getKMDescription", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss")
        GetKMDescription parameters
    ) throws UnrecognizedScopedEntityExceptionFault, UnrecognizedLanguageExceptionFault, DSSRuntimeExceptionFault, UnsupportedLanguageExceptionFault;
}
