package org.omg.dss;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import org.omg.dss.query.FindKMs;
import org.omg.dss.query.FindKMsResponse;
import org.omg.dss.query.GetKMDataRequirements;
import org.omg.dss.query.GetKMDataRequirementsForEvaluationAtSpecifiedTime;
import org.omg.dss.query.GetKMDataRequirementsForEvaluationAtSpecifiedTimeResponse;
import org.omg.dss.query.GetKMDataRequirementsResponse;
import org.omg.dss.query.GetKMDescription;
import org.omg.dss.query.GetKMDescriptionResponse;
import org.omg.dss.query.GetKMEvaluationResultSemantics;
import org.omg.dss.query.GetKMEvaluationResultSemanticsResponse;
import org.omg.dss.query.ListKMs;
import org.omg.dss.query.ListKMsResponse;

/**
 * This class was generated by Apache CXF 2.2.9
 * Thu Jul 28 08:04:45 MDT 2011
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "http://www.omg.org/spec/CDSS/201105/dssWsdl", name = "Query")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Query {

    @WebResult(name = "getKMDataRequirementsForEvaluationAtSpecifiedTimeResponse", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss", partName = "parameters")
    @WebMethod(action = "http://www.omg.org/spec/CDSS/201105/dssWsdl:operation:getKMDataRequirementsForEvaluationAtSpecifiedTime")
    public GetKMDataRequirementsForEvaluationAtSpecifiedTimeResponse getKMDataRequirementsForEvaluationAtSpecifiedTime(
        @WebParam(partName = "parameters", name = "getKMDataRequirementsForEvaluationAtSpecifiedTime", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss")
        GetKMDataRequirementsForEvaluationAtSpecifiedTime parameters
    ) throws UnrecognizedScopedEntityExceptionFault, DSSRuntimeExceptionFault;

    @WebResult(name = "getKMDataRequirementsResponse", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss", partName = "parameters")
    @WebMethod(action = "http://www.omg.org/spec/CDSS/201105/dssWsdl:operation:getKMDataRequirements")
    public GetKMDataRequirementsResponse getKMDataRequirements(
        @WebParam(partName = "parameters", name = "getKMDataRequirements", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss")
        GetKMDataRequirements parameters
    ) throws UnrecognizedScopedEntityExceptionFault, DSSRuntimeExceptionFault;

    @WebResult(name = "listKMsResponse", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss", partName = "parameters")
    @WebMethod(action = "http://www.omg.org/spec/CDSS/201105/dssWsdl:operation:listKMs")
    public ListKMsResponse listKMs(
        @WebParam(partName = "parameters", name = "listKMs", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss")
        ListKMs parameters
    ) throws UnrecognizedScopedEntityExceptionFault, UnrecognizedLanguageExceptionFault, DSSRuntimeExceptionFault, UnsupportedLanguageExceptionFault;

    @WebResult(name = "findKMsResponse", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss", partName = "parameters")
    @WebMethod(action = "http://www.omg.org/spec/CDSS/201105/dssWsdl:operation:findKMs")
    public FindKMsResponse findKMs(
        @WebParam(partName = "parameters", name = "findKMs", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss")
        FindKMs parameters
    ) throws InvalidTraitCriterionDataFormatExceptionFault, UnrecognizedScopedEntityExceptionFault, UnrecognizedLanguageExceptionFault, UnrecognizedTraitCriterionExceptionFault, DSSRuntimeExceptionFault;

    @WebResult(name = "getKMEvaluationResultSemanticsResponse", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss", partName = "parameters")
    @WebMethod(action = "http://www.omg.org/spec/CDSS/201105/dssWsdl:operation:getKMEvaluationResultSemantics")
    public GetKMEvaluationResultSemanticsResponse getKMEvaluationResultSemantics(
        @WebParam(partName = "parameters", name = "getKMEvaluationResultSemantics", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss")
        GetKMEvaluationResultSemantics parameters
    ) throws UnrecognizedScopedEntityExceptionFault, DSSRuntimeExceptionFault;

    @WebResult(name = "getKMDescriptionResponse", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss", partName = "parameters")
    @WebMethod(action = "http://www.omg.org/spec/CDSS/201105/dssWsdl:operation:getKMDescription")
    public GetKMDescriptionResponse getKMDescription(
        @WebParam(partName = "parameters", name = "getKMDescription", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss")
        GetKMDescription parameters
    ) throws UnrecognizedScopedEntityExceptionFault, UnrecognizedLanguageExceptionFault, DSSRuntimeExceptionFault, UnsupportedLanguageExceptionFault;
}
