
package org.omg.dss;

import javax.xml.ws.WebFault;

import org.omg.dss.exception.RequiredDataNotProvidedException;


/**
 * This class was generated by Apache CXF 2.2.9
 * Thu Jul 28 08:04:45 MDT 2011
 * Generated source version: 2.2.9
 * 
 */

@WebFault(name = "RequiredDataNotProvidedException", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss")
public class RequiredDataNotProvidedExceptionFault extends Exception {
    public static final long serialVersionUID = 20110728080445L;
    
    private RequiredDataNotProvidedException requiredDataNotProvidedException;

    public RequiredDataNotProvidedExceptionFault() {
        super();
    }
    
    public RequiredDataNotProvidedExceptionFault(String message) {
        super(message);
    }
    
    public RequiredDataNotProvidedExceptionFault(String message, Throwable cause) {
        super(message, cause);
    }

    public RequiredDataNotProvidedExceptionFault(String message, RequiredDataNotProvidedException requiredDataNotProvidedException) {
        super(message);
        this.requiredDataNotProvidedException = requiredDataNotProvidedException;
    }

    public RequiredDataNotProvidedExceptionFault(String message, RequiredDataNotProvidedException requiredDataNotProvidedException, Throwable cause) {
        super(message, cause);
        this.requiredDataNotProvidedException = requiredDataNotProvidedException;
    }

    public RequiredDataNotProvidedException getFaultInfo() {
        return this.requiredDataNotProvidedException;
    }
}
