
package org.omg.dss;

import javax.xml.ws.WebFault;

import org.omg.dss.exception.UnrecognizedScopingEntityException;


/**
 * This class was generated by Apache CXF 2.2.9
 * Thu Jul 28 08:04:45 MDT 2011
 * Generated source version: 2.2.9
 * 
 */

@WebFault(name = "UnrecognizedScopingEntityException", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss")
public class UnrecognizedScopingEntityExceptionFault extends Exception {
    public static final long serialVersionUID = 20110728080445L;
    
    private UnrecognizedScopingEntityException unrecognizedScopingEntityException;

    public UnrecognizedScopingEntityExceptionFault() {
        super();
    }
    
    public UnrecognizedScopingEntityExceptionFault(String message) {
        super(message);
    }
    
    public UnrecognizedScopingEntityExceptionFault(String message, Throwable cause) {
        super(message, cause);
    }

    public UnrecognizedScopingEntityExceptionFault(String message, UnrecognizedScopingEntityException unrecognizedScopingEntityException) {
        super(message);
        this.unrecognizedScopingEntityException = unrecognizedScopingEntityException;
    }

    public UnrecognizedScopingEntityExceptionFault(String message, UnrecognizedScopingEntityException unrecognizedScopingEntityException, Throwable cause) {
        super(message, cause);
        this.unrecognizedScopingEntityException = unrecognizedScopingEntityException;
    }

    public UnrecognizedScopingEntityException getFaultInfo() {
        return this.unrecognizedScopingEntityException;
    }
}
