
package org.omg.dss;

import javax.xml.ws.WebFault;

import org.omg.dss.exception.UnrecognizedLanguageException;


/**
 * This class was generated by Apache CXF 2.2.9
 * Thu Jul 28 08:04:45 MDT 2011
 * Generated source version: 2.2.9
 * 
 */

@WebFault(name = "UnrecognizedLanguageException", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss")
public class UnrecognizedLanguageExceptionFault extends Exception {
    public static final long serialVersionUID = 20110728080445L;
    
    private UnrecognizedLanguageException unrecognizedLanguageException;

    public UnrecognizedLanguageExceptionFault() {
        super();
    }
    
    public UnrecognizedLanguageExceptionFault(String message) {
        super(message);
    }
    
    public UnrecognizedLanguageExceptionFault(String message, Throwable cause) {
        super(message, cause);
    }

    public UnrecognizedLanguageExceptionFault(String message, UnrecognizedLanguageException unrecognizedLanguageException) {
        super(message);
        this.unrecognizedLanguageException = unrecognizedLanguageException;
    }

    public UnrecognizedLanguageExceptionFault(String message, UnrecognizedLanguageException unrecognizedLanguageException, Throwable cause) {
        super(message, cause);
        this.unrecognizedLanguageException = unrecognizedLanguageException;
    }

    public UnrecognizedLanguageException getFaultInfo() {
        return this.unrecognizedLanguageException;
    }
}
