
package org.omg.dss;

import javax.xml.ws.WebFault;

import org.omg.dss.exception.UnsupportedLanguageException;


/**
 * This class was generated by Apache CXF 2.2.9
 * Thu Jul 28 08:04:45 MDT 2011
 * Generated source version: 2.2.9
 * 
 */

@WebFault(name = "UnsupportedLanguageException", targetNamespace = "http://www.omg.org/spec/CDSS/201105/dss")
public class UnsupportedLanguageExceptionFault extends Exception {
    public static final long serialVersionUID = 20110728080445L;
    
    private UnsupportedLanguageException unsupportedLanguageException;

    public UnsupportedLanguageExceptionFault() {
        super();
    }
    
    public UnsupportedLanguageExceptionFault(String message) {
        super(message);
    }
    
    public UnsupportedLanguageExceptionFault(String message, Throwable cause) {
        super(message, cause);
    }

    public UnsupportedLanguageExceptionFault(String message, UnsupportedLanguageException unsupportedLanguageException) {
        super(message);
        this.unsupportedLanguageException = unsupportedLanguageException;
    }

    public UnsupportedLanguageExceptionFault(String message, UnsupportedLanguageException unsupportedLanguageException, Throwable cause) {
        super(message, cause);
        this.unsupportedLanguageException = unsupportedLanguageException;
    }

    public UnsupportedLanguageException getFaultInfo() {
        return this.unsupportedLanguageException;
    }
}
