/**
 * Copyright (C) 2016 New York City Department of Health and Mental Hygiene, Bureau of Immunization
 * Contributions by HLN Consulting, LLC
 *
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU
 * Lesser General Public License as published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version. You should have received a copy of the GNU Lesser
 * General Public License along with this program. If not, see <http://www.gnu.org/licenses/> for more
 * details.
 *
 * The above-named contributors (HLN Consulting, LLC) are also licensed by the New York City
 * Department of Health and Mental Hygiene, Bureau of Immunization to have (without restriction,
 * limitation, and warranty) complete irrevocable access and rights to this project.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; THE
 *
 * SOFTWARE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING,
 * BUT NOT LIMITED TO, WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS, IF ANY, OR DEVELOPERS BE LIABLE FOR
 * ANY CLAIM, DAMAGES, OR OTHER LIABILITY OF ANY KIND, ARISING FROM, OUT OF, OR IN CONNECTION WITH
 * THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * For more information about this software, see http://www.hln.com/ice or send
 * correspondence to ice@hln.com.
 */

package org.cdsframework.ice.supportingdatatmp;

import org.opencds.vmr.v1_0.internal.datatypes.CD;

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//This class will be replaced for dynamic import of Supporting Data in a specified format generated by the Rule Authoring Tool         // 
//(e.g. - CAT). See opencds-ice-service-data/src/main/resources/ice-supporting-data/                                                   //
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


public enum SupportedVaccineConcept {

	_HEPB_LESSTHAN_20("ICE08", "HepB peds <20yrs", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "08", "HepB peds, less than 20yrs"), 
	_HEPB_HIGHRISK_INFANT("ICE42", "HepB high risk infant", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "42", "HepB high risk infant"), 
	_HEPB_DIALYSIS("ICE44", "HepB dialysis", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "44", "HepB dialysis"), 
	_HEPB_NOS("ICE45", "HepB NOS", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "45", "HepB NOS"), 
	_HEPB_GREATEREQUAL_20("ICE43", "HepB adult >=20yrs", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "43", "HepB adult, greater than equal to 20yrs"), 
	_HEPB_HIB("ICE51", "HepB-Hib PRP-OMP (ComVAX)", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "51,", "HepB-Hib PRP-OMP (ComVAX)"), 
	_HEPA_PEDADOL_2_DOSE("ICE83", "HepA ped/adol 2 dose", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "83", "HepA ped/adol 2 dose"), 
	_HEPA_PEDADOL_3_DOSE("ICE84", "HepA pediatric/adolescent (3 dose)", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "84", "HepA ped/adol 3 dose"), 
	_HEPA_PED_NOS("ICE31", "HepA pediatric NOS", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "31", "HepA pediatric NOS"), 
	_HEPA_ADULT("ICE52", "HepA Adult", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "52", "HepA Adult"), 
	_HEPA_NOS("ICE85", "HepA NOS", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "85", "HepA NOS"),
	_INFLUENZA_SPLIT("ICE15", "influenza, split", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "15", "influenza, split"),
	_INFLUENZA_WHOLE("ICE16", "influenza, whole", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "16", "influenza, whole"),
	_INFLUENZA_UNSPECIFIED("ICE88", "influenza, unspecified formulation", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "88", "influenza, unspecified formulation"),
	_INFLUENZA_LIVE_INTRANASAL("ICE111", "influenza, live, intranasal", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "111", "influenza, live, intranasal"),
	_INFLUENZA_HIGHDOSE_SEASONAL("ICE135", "influenza, high dose, seasonal", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "135", "influenza, high dose, seasonal"),
	_INFLUENZA_SEASONAL_INJECTABLE_PRESERVATIVEFREE("ICE140", "influenza, seasonal, injectable, preservative free", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "140", "influenza, seasonal, injectable, preservative free"),
	_INFLUENZA_SEASONAL_INJECTABLE("ICE141", "influenza, seasonal, injectable", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "141", "influenza, seasonal, injectable"),
	_INFLUENZA_SEASONAL_INTRADERMAL_PRESERVATIVEFREE("ICE144", "influenza, seasonal, intradermal, preservative free", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "144", "influenza, seasonal, intradermal, preservative free"),
	_INFLUENZA_LIVE_INTRANASAL_QUADRIVALENT("ICE149", "influenza, live, intranasal, quadrivalent", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "149", "influenza, live, intranasal, quadrivalent"),
	_INFLUENZA_INJECTABLE_QUADRIVALENT_PRESERVATIVEFREE("ICE150", "influenza, injectable, quadrivalent, preservative free", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "150", "influenza, injectable, quadrivalent, preservative free"),
	_INFLUENZA_NASAL_UNSPECIFIED("ICE151", "influenza nasal, unspecified formulation", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "151", "influenza nasal, unspecified formulation"),
	_INFLUENZA_INJECTABLE_MDCK_PRESERVATIVEFREE("ICE153", "influenza, injectable, MDCK, preservative free", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "153", "influenza, injectable, MDCK, preservative free"),
	_INFLUENZA_RECOMBINANT_INJECTABLE_PRESERVATIVEFREE("ICE155", "influenza, recombinant, injectable, preservative free", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "155", "influenza, recombinant, injectable, preservative free"),
	_INFLUENZA_INJECTABLE_QUADRIVALENT("ICE158", "influenza, injectable, quadrivalent", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "158", "influenza, injectable, quadrivalent"),
	_INFLUENZA_INJECTABLE_QUADRIVALENT_PRESERVATIVEFREE_PEDIATRIC("ICE161", "influenza, injectable, quadrivalent, preservative free, pediatric", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "161", "Influenza, injectable, quadrivalent, preservative free, pediatric"),
	_INFLUENZA_INTRADERMAL_QUADRIVALENT_PRESERVATIVEFREE_INJECTABLE("ICE166", "influenza, intradermal, quadrivalent, preservative free, injectable", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "166", "Influenza, intradermal, quadrivalent, preservative free, injectable"),	
	_H1N1_09_NASAL("ICE125", "Novel Influenza-H1N1-09, nasal", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "125", "Novel Influenza-H1N1-09, nasal"),
	_H1N1_09_PRESERVATIVEFREE("ICE126", "Novel influenza-H1N1-09, preservative-free", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "126", "Novel influenza-H1N1-09, preservative-free"),
	_H1N1_09("ICE127", "Novel influenza-H1N1-09", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "127", "Novel influenza-H1N1-09"),
	_H1N1_09_ALLFORMULATIONS("ICE128", "Novel Influenza-H1N1-09, all formulations", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "128", "Novel Influenza-H1N1-09, all formulations"),
	_MMR("ICE03", "MMR", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "03", "MMR"),
	_MEASLES("ICE05", "Measles", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "05", "Measles"),
	_RUBELLA("ICE06", "Rubella", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "06", "Rubella"),
	_MUMPS("ICE07", "Mumps", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "07", "Mumps"),
	_MEASLES_RUBELLA("ICE04", "Measles/Rubella", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "04", "Measles/Rubella"),
	_MUMPS_RUBELLA("ICE38", "Mumps/Rubella", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "38", "Mumps/Rubella"),
	_VARICELLA("ICE21", "Varicella", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "21", "Varicella"),
	_MMR_VARICELLA("ICE94", "MMR-Varicella", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "94", "MMR-Varicella"),
	_ROTAVIRUS_RV5("ICE116", "Rotavirus RV5 (RotaTeq, 3 dose)", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "116", "Rotavirus RV5 (RotaTeq, 3 dose)"),
	_ROTAVIRUS_RV1("ICE119", "Rotavirus RV1 (Rotarix, 2 dose)", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "119", "Rotavirus RV1 (Rotarix, 2 dose)"),
	_ROTAVIRUS_NOS("ICE122", "Rotavirus NOS", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "122", "Rotavirus NOS"),
	_ROTAVIRUS("ICE74", "Rotavirus", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "74", "Rotavirus"),
	_HIB_NOS("ICE17", "Hib NOS", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "17", "Hib NOS"),
	_HIB_PRP_D("ICE46", "Hib-PRP-D (ProHIBIT)", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "46", "Hib-PRP-D (ProHIBIT)"),
	_HIB_HBOC("ICE47", "Hib-HbOC (HibTITER)", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "47", "Hib-HbOC (HibTITER)"),
	_HIB_PRP_T("ICE48", "Hib-PRP-T (ActHIB, Hiberix)", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "48", "Hib-PRP-T (ActHIB, Hiverix)"),
	_HIB_PRP_OMP("ICE49", "Hib-PRP-OMP (PedvaxHIB)", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "49", "Hib-PRP-OMP (PedvaxHIB)"),
	_HPV_QUADRIVALENT("ICE62", "HPV Quadrivalent (Gardasil)", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "62", "HPV Quadrivalent (Gardasil)"),
	_HPV_BIVALENT("ICE118", "HPV Bivalent (Cervarix)", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "118", "HPV Bivalent (Cervarix)"),
	_HPV_NOS("ICE137", "HPV NOS", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "137", "HPV NOS"),
	_HPV_9("ICE165", "HPV9", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "165", "HPV9"),
	_PCV_7("ICE100", "Pneumococcal Conjugate 7 valent (PCV 7)", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "100", "Pneumococcal Conjugate 7 valent (PCV 7)"),
	_PCV_13("ICE133", "Pneumococcal Conjugate 13 valent (PCV 13)", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "133", "Pneumococcal Conjugate 13 valent (PCV 13)"),
	_PCV_NOS("ICE152", "Pneumococcal Conjugate NOS", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "152", "Pneumococcal Conjugate NOS"),
	_PCV_NOS109("ICE109", "Pneumococcal NOS", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "109", "Pneumococcal NOS"),
	_PPSV_23VALENT("ICE33", "Pneumococcal Polysaccharide 23 Valent", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "33", "Pneumococcal Polysaccharide 23 Valent"),
	_MENING_HIB("ICE148", "Mening CY-Hib PRP-T (Menhibrix)", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "148", "Mening CY-Hib PRP-T (Menhibrix)"), 
	_MENING_CY("N-ICE-VACCINE_MENING_CY", "Meningococcal C/Y", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "FAKE_MENING_CVX", "Meningococcal C/Y"),
	_MENING_MCV4P("ICE114", "Meningococcal MCV4P (Menactra)", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "114", "Meningococcal MCV4P (Menactra)"),
	_MENING_MCV4O("ICE136", "Meningococcal MCV4O (Menveo)", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "136", "Meningococcal MCV4O (Menveo)"),
	_MENING_MPSV4("ICE32", "Meningococcal MPSV4 (Menomune) ", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "32", "Meningococcal MPSV4 (Menomune)"),
	_MENING_UNSPECIFIED("ICE108", "Meningococcal, unspecified formulation", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "108", "Meningococcal, unspecified formulation"),
	_MENING_MCV4_UNSPECIFIED("ICE147", "Meningococcal MCV4, unspecified formulation", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "147", "Meningococcal MCV4, unspecified formulation"),
	_IPV("ICE10", "IPV", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "10", "IPV"),		
	_OPV("ICE02", "OPV", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "02", "OPV"),		
	_POLIO_UNSPECIFIED("ICE89", "Polio, unspecified formulation", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "89", "Polio, unspecified formulation"),
	_TWINRIX("ICE104", "Twinrix", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "104", "Twinrix"),
	_DTP("ICE01", "DTP", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "01", "DTP"),
	_DTAP("ICE20", "DTaP", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "20", "DTaP"),
	_DT("ICE28", "DT", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "28", "DT"),
	_DTAP_5PERTUSSIS_ANTIGENS("ICE106", "DTaP, 5 pertussis antigens", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "106", "DTaP, 5 pertussis antigens"),
	_DTAP_UNSPECIFIED("ICE107", "DTaP, unspecified formulation", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "107", "DTaP, unspecified formulation"),
	_TDAP("ICE115", "Tdap", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "115", "Tdap"),
	_TD_ABSORBED("ICE09", "Td", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "09", "Td"),
	_TD_PRESERVATIVEFREE("ICE113", "Td (adult) preservative free", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "113", "Td (adult) preservative free"),
	_TD_NOTABSORBED("ICE138", "Td (adult) not absorbed", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "138", "Td (adult not absorbed)"),
	_TD_NOS("ICE139", "Td (adult) NOS", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "139", "Td (adult) NOS"),	
	_DTP_HIB_HEPB("ICE102", "DTP-Hib-HepB", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "102", "DTP-Hib-HepB"),
	_DTAP_HEPB_IPV("ICE110", "DTaP-HepB-IPV (Pediarix)", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "110", "DTaP-HepB-IPV (Pediarix)"),
	_DTAP_HIB("ICE50", "DTaP-Hib (TriHiBit)", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "50", "DTaP-Hib (TriHiBit)"),
	_DTAP_HIB_IPV("ICE120", "DTaP-Hib (PRP-T)-IPV", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "120", "DTaP-Hib (PRP-T)-IPV"), 
	_DTP_HIB("ICE22", "DTP-Hib (Tetramune; OmniHib-DTP)", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "22", "DTP-Hib (Tetramune; OmniHib-DTP)"),
	_DTAP_IPV("ICE130", "DTaP-IPV", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "130", "DTaP-IPV"),
	_DTAP_IPV_HIB_HEPB_HISTORICAL("ICE132", "DTaP-IPV-Hib-HepB, historical", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "132", "DTaP-IPV-Hib-HepB, historical"),
	_DTAP_IPV_HIB_HEPB("ICE146", "DTaP-IPV-Hib-HepB", "2.16.840.1.113883.12.292", "Vaccines administered (CVX)", "146", "DTaP-IPV-Hib-HepB");

	
	private CD supportedVaccineConcept;
	private CD localVaccineCodeConcept;

	// private static Log logger = LogFactory.getLog(SupportedVaccineConcept.class);
	
	
	private SupportedVaccineConcept(String pConceptCodeValue, String pConceptDisplayNameValue) {
		supportedVaccineConcept = new CD();
		localVaccineCodeConcept = new CD();
		supportedVaccineConcept.setCode(pConceptCodeValue);
		supportedVaccineConcept.setDisplayName(pConceptDisplayNameValue);
	}
	
	private SupportedVaccineConcept(String pConceptCodeValue, String pConceptDisplayNameValue, String pLocalCodeSystem, String pLocalCodeSystemName, String pLocalCodeValue, 
			String pLocalCodeDisplayNameValue) {
		supportedVaccineConcept = new CD();
		localVaccineCodeConcept = new CD();
		supportedVaccineConcept.setCode(pConceptCodeValue);
		supportedVaccineConcept.setDisplayName(pConceptDisplayNameValue);
		localVaccineCodeConcept.setCodeSystem(pLocalCodeSystem);
		localVaccineCodeConcept.setCodeSystemName(pLocalCodeSystemName);
		localVaccineCodeConcept.setCode(pLocalCodeValue);
		localVaccineCodeConcept.setDisplayName(pLocalCodeDisplayNameValue);
	}
	
	/**
	 * Return SupportedVaccineConcept for its corresponding conceptCode value
	 * @param conceptCode
	 * @return SupportedVaccineConcept, or null if no such SupportedVaccineConcept exists for the specified concept code value
	 */
	public static SupportedVaccineConcept getSupportedVaccineConceptByConceptCode(String conceptCode) {

		if (conceptCode == null) {
			return null;
		}
		for (SupportedVaccineConcept vc : SupportedVaccineConcept.values()) {
			if (conceptCode.equals(vc.getConceptCodeValue())) {
				return vc;
			}
		}
		
		return null;
	}
	
	/**
	 * Return SupportedVaccineConcept for its corresponding conceptCode value
	 * @param conceptCodeValue
	 * @return SupportedVaccineConcept
	 * @throws IllegalArgumentException if no such SupportedVaccineConcept exists for the specified concept code value
	 */
	/*
	public static SupportedVaccineConcept getSupportedConceptByConceptCodeValue(String conceptCodeValue) {
		
		try {
			SupportedVaccineConcept svc = SupportedVaccineConcept.valueOf(conceptCodeValue);
			return svc;
		}
		catch (IllegalArgumentException iea) {
			String errStr = "No SupportedVaccineConcepts exists for the supplied conceptCodeValue";
			logger.error(errStr);
			throw iea;
		}
	}
	*/
	
	public CD getConcept() {
		return supportedVaccineConcept;
	}
	
	public String getConceptCodeValue() {
		return supportedVaccineConcept.getCode();
	}
	
	public String getConceptDisplayNameValue() {
		return supportedVaccineConcept.getDisplayName();
	}
	
	public CD getLocalCodeConcept() {
		return localVaccineCodeConcept;
	}
	
	public String getLocalCodeSystem() {
		return localVaccineCodeConcept.getCodeSystem();
	}
	
	public String getLocalCodeSystemName() {
		return localVaccineCodeConcept.getCodeSystemName();
	}
	
	public String getLocalCodeValue() {
		return localVaccineCodeConcept.getCode();
	}
	
	public String getLocalCodeDisplayName() {
		return localVaccineCodeConcept.getDisplayName();
	}
	
}
