/**
 * Copyright (C) 2015 New York City Department of Health and Mental Hygiene, Bureau of Immunization
 * Contributions by HLN Consulting, LLC
 *
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU
 * Lesser General Public License as published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version. You should have received a copy of the GNU Lesser
 * General Public License along with this program. If not, see <http://www.gnu.org/licenses/> for more
 * details.
 *
 * The above-named contributors (HLN Consulting, LLC) are also licensed by the New York City
 * Department of Health and Mental Hygiene, Bureau of Immunization to have (without restriction,
 * limitation, and warranty) complete irrevocable access and rights to this project.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; THE
 *
 * SOFTWARE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING,
 * BUT NOT LIMITED TO, WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS, IF ANY, OR DEVELOPERS BE LIABLE FOR
 * ANY CLAIM, DAMAGES, OR OTHER LIABILITY OF ANY KIND, ARISING FROM, OUT OF, OR IN CONNECTION WITH
 * THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * For more information about this software, see http://www.hln.com/ice or send
 * correspondence to ice@hln.com.
 */

package org.cdsframework.ice.supportingdatatmp;

import org.opencds.vmr.v1_0.internal.datatypes.CD;


/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//This class will be replaced for dynamic import of Supporting Data in a specified format generated by the Rule Authoring Tool         // 
//(e.g. - CAT). See opencds-ice-service-data/src/main/resources/ice-supporting-data/                                                   //
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


public enum SupportedDiseaseConcept {
	
	Diphtheria("ICE-DISEASE-101", "Diphtheria"), H1N1("ICE-DISEASE-102", "H1N1 Influenza"), HepA("ICE-DISEASE-103", "Hep A"), HepB("ICE-DISEASE-104", "Hep B"), 
	Hib("ICE-DISEASE-105", "Hib"), Measles("ICE-DISEASE-106", "Measles"), Mumps("ICE-DISEASE-107", "Mumps"), Pertussis("ICE-DISEASE-108", "Pertussis"), 
	Rubella("ICE-DISEASE-109", "Rubella"), Polio("ICE-DISEASE-110", "Polio"), Rotavirus("ICE-DISEASE-111", "Rotavirus"), Tetanus("ICE-DISEASE-112", "Tetanus"), 
	Varicella("ICE-DISEASE-113", "Varicella"), HPV("ICE-DISEASE-114", "HPV"), Pneumococcal("ICE-DISEASE-115", "Penumococcal"), 
	Meningococcal("ICE-DISEASE-116", "Meningococcal"), Influenza("ICE-DISEASE-117", "Influenza");
	
	private CD supportedDiseaseConcept;
	private CD localDiseaseCodeConcept;

	
	private SupportedDiseaseConcept(String pConceptCodeValue, String pConceptDisplayNameValue) {
		supportedDiseaseConcept = new CD();
		supportedDiseaseConcept.setCode(pConceptCodeValue);
		supportedDiseaseConcept.setDisplayName(pConceptDisplayNameValue);
		
		localDiseaseCodeConcept = new CD();
	}
	
	private SupportedDiseaseConcept(String pConceptCodeValue, String pConceptDisplayNameValue, String pLocalCodeSystem, String pLocalCodeSystemName, 
			String pLocalCodeValue, String pLocalCodeDisplayNameValue) {
		
		supportedDiseaseConcept = new CD();
		supportedDiseaseConcept.setCode(pConceptCodeValue);
		supportedDiseaseConcept.setDisplayName(pConceptDisplayNameValue);
		
		localDiseaseCodeConcept = new CD();
		localDiseaseCodeConcept.setCodeSystem(pLocalCodeSystem);
		localDiseaseCodeConcept.setCodeSystemName(pLocalCodeSystemName);
		localDiseaseCodeConcept.setCode(pLocalCodeValue);
		localDiseaseCodeConcept.setDisplayName(pLocalCodeDisplayNameValue);
	}
	
	public CD getConcept() {
		return supportedDiseaseConcept;
	}
	
	public String getConceptCodeValue() {
		return supportedDiseaseConcept.getCode();
	}
	
	public String getConceptDisplayNameValue() {
		return supportedDiseaseConcept.getDisplayName();
	}
	
	public CD getlocalCodeConcept() {
		return localDiseaseCodeConcept;
	}
	
	public String getLocalCodeSystem() {
		return localDiseaseCodeConcept.getCodeSystem();
	}
	
	public String getLocalCodeSystemName() {
		return localDiseaseCodeConcept.getCodeSystemName();
	}
	
	public String getLocalCodeValue() {
		return localDiseaseCodeConcept.getCode();
	}
	
	public String getLocalCodeDisplayName() {
		return localDiseaseCodeConcept.getDisplayName();
	}
	
}
