package knowledgeModule.org.nyc.cir.ice;

import java.util.Iterator;
import java.util.List;
import java.util.Set;
import org.opencds.vmr.v1_0.internal.EvalTime;
import org.opencds.vmr.v1_0.internal.EvaluatedPerson;
import org.cdsframework.ice.service.DiseaseImmunity;
import org.cdsframework.ice.service.DoseStatus;
import org.cdsframework.ice.service.ICEFactTypeFinding;
import org.cdsframework.ice.service.ICELogicHelper;
import org.cdsframework.ice.service.Recommendation;
import org.cdsframework.ice.service.RecommendationStatus;
import org.cdsframework.ice.service.SeriesRules;
import org.cdsframework.ice.supportingdata.BaseDataEvaluationReason;
import org.cdsframework.ice.supportingdatatmp.SupportedFactConcept;
import org.cdsframework.ice.service.TargetDose;
import org.cdsframework.ice.service.TargetSeries;
import org.cdsframework.ice.util.TimePeriod;
import org.cdsframework.ice.util.TimePeriod.DurationType;
import org.cdsframework.ice.service.Vaccine;

global java.time.LocalDate evalTime;

/**
* If a shot is administered < 10/25/2024, then the following Two Shot Same Day Exception Rules for Meningococcal B apply:
*   * If CVX 162 (Meningococcal B FHbp, recombinant (Trumenba)) or CVX 316 (Meningococcal MenABCWY (Penbraya)) and CVX 163 (Meningococcal B 4C, OMV (Bexsero)) or CVX 328 (Meningococcal MenABCWY (Penmenvy)) are reported as administered on the same day, then:
*      * evaluate CVX 162 (Meningococcal B FHbp, recombinant (Trumenba)) as Invalid with a reason code of DUPLICATE_SAME_DAY
*      * evaluate CVX 163 (Meningococcal B 4C, OMV (Bexsero)) as Valid
*
* If a shot is administered >= 10/25/2024, then the following Two Shot Same Day Exception Rules for Meningococcal B apply:
*   * If CVX 162 (Meningococcal B FHbp, recombinant (Trumenba)) or CVX 316 (Meningococcal MenABCWY (Penbraya)) and CVX 163 (Meningococcal B 4C, OMV (Bexsero)) or CVX 328 (Meningococcal MenABCWY (Penmenvy)) are reported as administered on the same day, then:
*       * evaluate CVX 162 (Meningococcal B FHbp, recombinant (Trumenba)) as Invalid with reason codes DUPLICATE_SAME_DAY and SUPPLEMENTAL_TEXT; Descriptive Text: "The patient record indicates that different Meningococcal B products were administered on the same day. Based on the available information, the product administered is undetermined and therefore unable to be evaluated."
*       * evaluate CVX 163 (Meningococcal B 4C, OMV (Bexsero)) as Invalid with a reason codes DUPLICATE_SAME_DAY and SUPPLEMENTAL_TEXT; Descriptive Text: "The patient record indicates that different Meningococcal B products were administered on the same day. Based on the available information, the product administered is undetermined and therefore unable to be evaluated."
*
* However, if both Meningococcal B vaccines are administered on the same day, and one vaccine would complete a Meningococcal B series, then evaluate that vaccine as Valid and the other Meningococcal B vaccine as Invalid with a reason code of DUPLICATE_SAME_DAY. (Example - CVX 162 (Trumenba) or CVX 316 (Meningococcal MenABCWY (Penbraya)) administered at 16 years old. CVX 162 (Trumenba) or CVX 316 (Meningococcal MenABCWY (Penbraya)) and CVX 163 (Bexsero) or CVX 328 (Meningococcal MenABCWY (Penmenvy)) administered on same day (at 16 years, 6 months old). Trumenba 2-dose Series applies/Series Complete. CVX 163 would be evaluated as Invalid/DUPLICATE_SAME_DAY.)
**/
rule "ABSTRACT Duplicate Shots/Same Day(MenB Abstract): If CVX 162 or CVX 316 is administered on the same day as CVX 163 or CVX 328"
	dialect "mvel"
	ruleflow-group "HistoryEvaluation^duplicateShotSameDay"
	auto-focus true
	no-loop true
	when
		$td: TargetDose(
		        hasBeenEvaluated == true,
		        associatedVaccineGroup == "VACCINE_GROUP_CONCEPT.MENINGOCOCCAL_B",
		        doseNumberInSeries <= associatedTargetSeries.seriesRules.numberOfDosesInSeries,
		        administeredVaccine.cdsConceptName in ("VACCINE_CVX_162", "VACCINE_CVX_316"),
		        isDoseStatusOverridden() == false,
		        $ts : associatedTargetSeries,
		        $adminDate : administrationDate)
		$tdother : TargetDose(
		            this != $td,
		            associatedTargetSeries == $ts,
		            administrationDate == $adminDate, // same admin date
		            administeredVaccine.cdsConceptName in ("VACCINE_CVX_163", "VACCINE_CVX_328"), // different vaccine
		            hasBeenEvaluated == true,
		            isDoseStatusOverridden() == false,
			        isDuplicateShotSameDayCheckCompleted() == false || $td.isDuplicateShotSameDayCheckCompleted() == false)
	then
end

rule "Duplicate Shots/Same Day (MenB- Series is Complete; $td Shot is Valid): If CVX 162 or CVX 316 is administered >= 10/25/2024 on the same day as CVX 163 on a date >= 10/25/2024, and the Series is complete, evaluate the shot that completes the Series as Valid and the other shot as Invalid / DUPLICATE_SAME_DAY"
	extends "ABSTRACT Duplicate Shots/Same Day(MenB Abstract): If CVX 162 or CVX 316 is administered on the same day as CVX 163 or CVX 328"
	dialect "mvel"
	auto-focus true
	no-loop true
	when
		TargetSeries(this == $ts, isSeriesComplete() == true)
		TargetDose(this == $td, isValid == true, administrationDate >= "25-Oct-2024")
	then
		modify($td) {
			setDuplicateShotSameDayCheckCompleted(true)
		};
		modify($tdother) {
			setStatus(DoseStatus.INVALID),
			setDuplicateShotSameDayCheckCompleted(true),
			removeAllEvaluationReasonsFromAllReasonSets(),
			addInvalidReason(BaseDataEvaluationReason._DUPLICATE_SAME_DAY_REASON.getCdsListItemName())
		};
		update($ts)
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $td + " in TargetSeries " + $ts);
        ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $tdother + " in TargetSeries " + $ts);
end

rule "Duplicate Shots/Same Day (MenB- Series is Complete; $tdother Shot is Valid): If CVX 162 or CVX 316 is administered >= 10/25/2024 on the same day as a CVX 163 or CVX 328 on a date >= 10/25/2024, and the Series is complete, evaluate the shot that completes the Series as Valid and the other shot as Invalid / DUPLICATE_SAME_DAY"
	extends "ABSTRACT Duplicate Shots/Same Day(MenB Abstract): If CVX 162 or CVX 316 is administered on the same day as CVX 163 or CVX 328"
	dialect "mvel"
	auto-focus true
	no-loop true
	when
		TargetSeries(this == $ts, isSeriesComplete() == true)
		TargetDose(this == $tdother, isValid == true, administrationDate >= "25-Oct-2024")
	then
		modify($tdother) {
			setDuplicateShotSameDayCheckCompleted(true)
		};
		modify($td) {
			setStatus(DoseStatus.INVALID),
			setDuplicateShotSameDayCheckCompleted(true),
			removeAllEvaluationReasonsFromAllReasonSets(),
			addInvalidReason(BaseDataEvaluationReason._DUPLICATE_SAME_DAY_REASON.getCdsListItemName())
		};
		update($ts)
        ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $td + " in TargetSeries " + $ts);
        ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $tdother + " in TargetSeries " + $ts);
end

rule "Duplicate Shots/Same Day (MenB- Series is Not Complete): If CVX 162 or CVX 316 is administered >= 10/25/2024 on the same day as CVX 163 or CVX 328 on a date >= 10/25/2024, and neither Series complete, evaluate the shots as INVALID/DUPLICATE_SAME_DAY"
	extends "ABSTRACT Duplicate Shots/Same Day(MenB Abstract): If CVX 162 or CVX 316 is administered on the same day as CVX 163 or CVX 328"
	dialect "mvel"
	auto-focus true
	no-loop true
	when
		TargetSeries(this == $ts, isSeriesComplete() == false)
        TargetDose(this == $td, administrationDate >= "25-Oct-2024")
		TargetDose(this == $tdother, administrationDate >= "25-Oct-2024")
	then
		modify($tdother) {
			setStatus(DoseStatus.INVALID),
			setDuplicateShotSameDayCheckCompleted(true),
			removeAllEvaluationReasonsFromAllReasonSets(),
			addInvalidReason(BaseDataEvaluationReason._DUPLICATE_SAME_DAY_REASON.getCdsListItemName()),
			addInvalidReason("SUPPLEMENTAL_EVALUATION_REASON_CONCEPT.MENB_SAME_DAY_DIFFERENT_PRODUCTS_UNDETERMINED")
		};
		modify($td) {
			setStatus(DoseStatus.INVALID),
			setDuplicateShotSameDayCheckCompleted(true),
			removeAllEvaluationReasonsFromAllReasonSets(),
			addInvalidReason(BaseDataEvaluationReason._DUPLICATE_SAME_DAY_REASON.getCdsListItemName()),
			addInvalidReason("SUPPLEMENTAL_EVALUATION_REASON_CONCEPT.MENB_SAME_DAY_DIFFERENT_PRODUCTS_UNDETERMINED")
		};
		update($ts)
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $td + " in TargetSeries " + $ts);
        ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $tdother + " in TargetSeries " + $ts);
end

rule "Duplicate Shots/Same Day (MenB- Series is Complete; $td Shot is Valid): If CVX 162 or CVX 316 is administered < 10/25/2024 on the same day as CVX 163 on a date < 10/25/2024, and the Series is complete, evaluate the shot that completes the Series as Valid and the other shot as Invalid / DUPLICATE_SAME_DAY"
    extends "ABSTRACT Duplicate Shots/Same Day(MenB Abstract): If CVX 162 or CVX 316 is administered on the same day as CVX 163 or CVX 328"
	dialect "mvel"
	auto-focus true
	no-loop true
	when
		TargetSeries(this == $ts, isSeriesComplete() == true)
		$validDose : TargetDose(this == $td || this == $tdother, isValid == true, administrationDate < "25-Oct-2024")
		$otherDose : TargetDose(this == $td || this == $tdother, this != $validDose, administrationDate < "25-Oct-2024")
	then
		modify($validDose) {
			setDuplicateShotSameDayCheckCompleted(true)
		};
		modify($otherDose) {
			setStatus(DoseStatus.INVALID),
			setDuplicateShotSameDayCheckCompleted(true),
			removeAllEvaluationReasonsFromAllReasonSets(),
			addInvalidReason(BaseDataEvaluationReason._DUPLICATE_SAME_DAY_REASON.getCdsListItemName())
		};
		update($ts)
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $td + " in TargetSeries " + $ts);
        ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $tdother + " in TargetSeries " + $ts);
end

rule "Duplicate Shots/Same Day (MenB- Series is Not Complete): If CVX 162 or CVX 316 is administered < 10/25/2024 on the same day as CVX 163 or CVX 328 on a date < 10/25/2024, and neither Series complete, evaluate CVX 163/CVX 328 as Valid and the CVX 162/CVX 316 shot as Invalid / DUPLICATE_SAME_DAY"
    extends "ABSTRACT Duplicate Shots/Same Day(MenB Abstract): If CVX 162 or CVX 316 is administered on the same day as CVX 163 or CVX 328"
	dialect "mvel"
	auto-focus true
	no-loop true
	when
		TargetSeries(this == $ts, isSeriesComplete() == false)
		$cvx163Dose : TargetDose(
		                this == $td || this == $tdother,
                        administeredVaccine.cdsConceptName in ("VACCINE_CVX_163", "VACCINE_CVX_328"),
                        administrationDate < "25-Oct-2024")
        $cvx162Dose : TargetDose(
		                this == $td || this == $tdother,
                        administeredVaccine.cdsConceptName in ("VACCINE_CVX_162", "VACCINE_CVX_316"),
                        administrationDate < "25-Oct-2024")
	then
		modify($cvx162Dose) {
			setStatus(DoseStatus.INVALID),
			setDuplicateShotSameDayCheckCompleted(true),
			removeAllEvaluationReasonsFromAllReasonSets(),
			addInvalidReason(BaseDataEvaluationReason._DUPLICATE_SAME_DAY_REASON.getCdsListItemName())
		};
		modify($cvx163Dose) {
			setDuplicateShotSameDayCheckCompleted(true)
		};
		update($ts)
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $td + " in TargetSeries " + $ts);
        ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $tdother + " in TargetSeries " + $ts);
end
