package knowledgeModule.org.nyc.cir.ice;

import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import org.opencds.vmr.v1_0.internal.EvalTime;
import org.opencds.vmr.v1_0.internal.EvaluatedPerson;
import org.cdsframework.ice.service.DiseaseImmunity;
import org.cdsframework.ice.service.DoseStatus;
import org.cdsframework.ice.service.ICEFactTypeFinding;
import org.cdsframework.ice.service.ICELogicHelper;
import org.cdsframework.ice.service.Recommendation;
import org.cdsframework.ice.service.RecommendationStatus;
import org.cdsframework.ice.service.SeriesRules;
import org.cdsframework.ice.supportingdata.BaseDataEvaluationReason;
import org.cdsframework.ice.supportingdatatmp.SupportedFactConcept;
import org.cdsframework.ice.service.TargetDose;
import org.cdsframework.ice.service.TargetSeries;
import org.cdsframework.ice.util.TimePeriod;
import org.cdsframework.ice.util.TimePeriod.DurationType;
import org.cdsframework.ice.service.Vaccine;

global java.util.Date evalTime;

/**
 * If in the child/adult series and the patient receives a pediatric dose at >= 19 years of age, evaluate any adult formulations
 * administered on the same day first.
 * See associated rule: "Switch from 2-Dose HepA series to 3-Dose HepA series if CVX 83 (Hep A, ped/adol, 2 dose) or CVX 84 (Hep A,
 * ped/adol, 3 dose) or CVX 31 (Hep A, pediatric, unspecified formulation) is given to a patient >= 19 years old as dose 1 or dose
 * 2"
 */
rule "Duplicate Shots/Same Day (Hep A): If a pediatric vaccine is administered to an adult >= 19 years of age in the Hep A 2-dose child/adult series and there are adult-formulated vaccines administered on the same day, evaluate the adult-formulated vaccine first"
	dialect "mvel"
	ruleflow-group "HistoryEvaluation^duplicateShotSameDay"
	activation-group "duplicateShotEvaluationOrder"
	auto-focus true
	when
		$td: TargetDose(hasBeenEvaluated == false, status == DoseStatus.PRIMARY_SHOT_DETERMINATION_IN_PROCESS, associatedTargetSeries.vaccineGroup == "VACCINE_GROUP_CONCEPT.HEP_A", associatedSeriesName == "SUPPORTED_SERIES.HepA2DoseChildAdultSeries", vaccineComponent.cdsConceptName in ("VACCINE_CVX_83", "VACCINE_CVX_84", "VACCINE_CVX_31"))
		$tdother : TargetDose(this != $td, hasBeenEvaluated == false, status == DoseStatus.EVALUATION_NOT_STARTED, associatedTargetSeries == $td.associatedTargetSeries, administrationDate == $td.administrationDate, vaccineComponent.cdsConceptName not in ("VACCINE_CVX_83", "VACCINE_CVX_84", "VACCINE_CVX_31"))
		$oEvaluatedPerson : EvaluatedPerson($dtBirthDate : demographics.birthTime)
		eval(TimePeriod.compareElapsedTimePeriodToDateRange($dtBirthDate, $td.administrationDate, "19y") >= 0)
	then
		modify($td) {
			setStatus(DoseStatus.EVALUATION_NOT_STARTED),
			setDuplicateShotSameDayEvaluationOrderCompleted(true)
		};
		modify($tdother) {
			setStatus(DoseStatus.PRIMARY_SHOT_DETERMINATION_IN_PROCESS),
			setDuplicateShotSameDayEvaluationOrderCompleted(true)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $tdother + "will be evaluated before " + $td + " in TargetSeries " + $td.associatedTargetSeries);
end

/**
 * If the patient is >= 19 years at the time of administration, if one of the shots is CVX 83 or CVX 84 (pediatric formulations),
 * then:
 *   + evaluate the CVX 83/CVX 84 as Invalid with a reason code of DUPLICATE_SAME_DAY
 *   + evaluate the CVX 52 (Hep A adult) as Valid
 * If the patient < 19 at the time of administration, if one of the shots is CVX 52 (Hep A adult), then:
 *   + evaluate the CVX 52 as Invalid with a reason code of DUPLICATE_SAME_DAY
 *   + evaluate the other Hep A CVX (pediatric formulation) as Valid
 */
rule "Duplicate Shot/Same Day (Abstract Hep A): Make note if the adult vaccine (CVX 52) and pediatric vaccine (CVX  83 or CVX 84) duplicate shots"
	dialect "mvel"
	ruleflow-group "HistoryEvaluation^duplicateShotSameDay"
	auto-focus true
	salience 10
	when
		$td: TargetDose(associatedTargetSeries.vaccineGroup == "VACCINE_GROUP_CONCEPT.HEP_A", status == DoseStatus.VALID, isDoseStatusOverridden() == false, vaccineComponent.cdsConceptName == "VACCINE_CVX_52")
		$tdother : TargetDose(this != $td, associatedTargetSeries == $td.associatedTargetSeries, administrationDate == $td.administrationDate, status == DoseStatus.VALID, isDoseStatusOverridden() == false,
			vaccineComponent.cdsConceptName in ("VACCINE_CVX_83","VACCINE_CVX_84"), isDuplicateShotSameDayCheckCompleted() == false || $td.isDuplicateShotSameDayCheckCompleted() == false)
		$ts : TargetSeries(this == $tdother.associatedTargetSeries)
	then
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $td + " in TargetSeries VACCINE_GROUP_CONCEPT.HEP_A (Hep A)");
end

rule "Duplicate Shot/Same Day (Hep A): If shot administered at >= 19 years, evalute the adult vaccine (CVX 52) Valid and pediatric vaccine (CVX 83 and/or CVX 84) Invalid / DUPLICATE_SAME_DAY"
	extends "Duplicate Shot/Same Day (Abstract Hep A): Make note if the adult vaccine (CVX 52) and pediatric vaccine (CVX  83 or CVX 84) duplicate shots"
	dialect "mvel"
	ruleflow-group "HistoryEvaluation^duplicateShotSameDay"
	auto-focus true
	salience 10
	when
		$oEvaluatedPerson : EvaluatedPerson($dtBirthDate : demographics.birthTime)
		eval(TimePeriod.compareElapsedTimePeriodToDateRange($dtBirthDate, $td.administrationDate, "19y") >= 0)
	then
		modify($tdother) {
			setStatus(DoseStatus.INVALID),
			setDuplicateShotSameDayCheckCompleted(true),
			addInvalidReason(BaseDataEvaluationReason._DUPLICATE_SAME_DAY_REASON.getCdsListItemName())
		};
		modify($td) {
			setDuplicateShotSameDayCheckCompleted(true)
		};
		update($ts)
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $td + " in TargetSeries " + $td.associatedTargetSeries);
end

rule "Duplicate Shot/Same Day (Hep A): If shot administered at < 19 years, evaluate the pediatric vaccine (CVX 83 or CVX 84) Valid and the adult vaccine (CVX 52) as Invalid / DUPLICATE_SAME_DAY"
	extends "Duplicate Shot/Same Day (Abstract Hep A): Make note if the adult vaccine (CVX 52) and pediatric vaccine (CVX  83 or CVX 84) duplicate shots"
	dialect "mvel"
	ruleflow-group "HistoryEvaluation^duplicateShotSameDay"
	auto-focus true
	salience 10
	when
		$oEvaluatedPerson : EvaluatedPerson($dtBirthDate : demographics.birthTime)
		eval(TimePeriod.compareElapsedTimePeriodToDateRange($dtBirthDate, $td.administrationDate, "19y") < 0)
	then
		modify($td) {
			setStatus(DoseStatus.INVALID),
			setDuplicateShotSameDayCheckCompleted(true),
			addInvalidReason(BaseDataEvaluationReason._DUPLICATE_SAME_DAY_REASON.getCdsListItemName())
		};
		modify($tdother) {
			setDuplicateShotSameDayCheckCompleted(true)
		};
		update($ts)
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $tdother + " in TargetSeries " + $td.associatedTargetSeries);
end