package knowledgeModule.org.nyc.cir.ice;

import java.util.Iterator;
import java.util.List;
import java.util.Set;
import org.opencds.vmr.v1_0.internal.EvalTime;
import org.opencds.vmr.v1_0.internal.EvaluatedPerson;
import org.cdsframework.ice.service.DiseaseImmunity;
import org.cdsframework.ice.service.DoseStatus;
import org.cdsframework.ice.service.ICEFactTypeFinding;
import org.cdsframework.ice.service.ICELogicHelper;
import org.cdsframework.ice.service.Recommendation;
import org.cdsframework.ice.service.RecommendationStatus;
import org.cdsframework.ice.service.SeriesRules;
import org.cdsframework.ice.supportingdata.BaseDataEvaluationReason;
import org.cdsframework.ice.supportingdatatmp.SupportedFactConcept;
import org.cdsframework.ice.service.TargetDose;
import org.cdsframework.ice.service.TargetSeries;
import org.cdsframework.ice.util.TimePeriod;
import org.cdsframework.ice.util.TimePeriod.DurationType;
import org.cdsframework.ice.service.Vaccine;

global java.time.LocalDate evalTime;

/**
 * Duplicate Shots/Same Day Evaluation Order: If one of the shots is pertussis-containing and the other is not, evaluate the
 * pertussis-containing shot first
 */
rule "Duplicate Shots/Same Day DTP: If one of the shots is pertussis-containing and another is not pertussis-containing, evaluate the pertussis-containing shot first"
	dialect "mvel"
	ruleflow-group "HistoryEvaluation^duplicateShotSameDay"
	activation-group "duplicateShotEvaluationOrder"
	auto-focus true
	when
		$td: TargetDose(hasBeenEvaluated == false, status == DoseStatus.PRIMARY_SHOT_DETERMINATION_IN_PROCESS, associatedTargetSeries.vaccineGroup == "VACCINE_GROUP_CONCEPT.DTP",
			vaccineComponent.allDiseasesTargetedForImmunity not contains "SUPPORTED_DISEASE_CONCEPT.PERTUSSIS")
		$tdother : TargetDose(this != $td, hasBeenEvaluated == false, status == DoseStatus.EVALUATION_NOT_STARTED, associatedTargetSeries == $td.associatedTargetSeries, administrationDate == $td.administrationDate,
			vaccineComponent.allDiseasesTargetedForImmunity contains "SUPPORTED_DISEASE_CONCEPT.PERTUSSIS", isDuplicateShotSameDayEvaluationOrderCompleted() == false || $td.isDuplicateShotSameDayEvaluationOrderCompleted() == false)
	then
		modify($td) {
			setStatus(DoseStatus.EVALUATION_NOT_STARTED),
			setDuplicateShotSameDayEvaluationOrderCompleted(true)
		};
		modify($tdother) {
			setStatus(DoseStatus.PRIMARY_SHOT_DETERMINATION_IN_PROCESS),
			setDuplicateShotSameDayEvaluationOrderCompleted(true)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $tdother + "will be evaluted before " + $td + " in TargetSeries " + $td.associatedTargetSeries);
end

rule "Duplicate Shot/Same Day Overview Abstract DTP Rule #4: Make notes if all shots are an NOS CVX and one of them contains Pertussis and the other does not"
	dialect "mvel"
	ruleflow-group "HistoryEvaluation^duplicateShotSameDay"
	auto-focus true
	salience 10
	when
		$td: TargetDose(hasBeenEvaluated == true, status == DoseStatus.VALID, isDoseStatusOverridden() == false, vaccineComponent.isUnspecifiedFormulation() == true,
			vaccineComponent.allDiseasesTargetedForImmunity contains "SUPPORTED_DISEASE_CONCEPT.PERTUSSIS",	associatedTargetSeries.vaccineGroup == "VACCINE_GROUP_CONCEPT.DTP")
		$tdother : TargetDose(hasBeenEvaluated == true, this != $td, administrationDate == $td.administrationDate, status == DoseStatus.VALID, isDoseStatusOverridden() == false, associatedTargetSeries == $td.associatedTargetSeries,
			vaccineComponent.isUnspecifiedFormulation() == true, vaccineComponent.allDiseasesTargetedForImmunity not contains "SUPPORTED_DISEASE_CONCEPT.PERTUSSIS",
			isDuplicateShotSameDayCheckCompleted() == false || $td.isDuplicateShotSameDayCheckCompleted() == false)
        $ts : TargetSeries(this == $tdother.associatedTargetSeries)
	then
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $td + " in TargetSeries VACCINE_GROUP_CONCEPT.DTP (DTP)");
end

rule "Duplicate Shots/Same Day Overview Rule #4-DTP-Pertussis (BOTH Primary Series Doses): If both shots are NOS and one of them contains Pertussis and the other does not, then evaluate shot with Pertussis as Valid and evaluate the other as Invalid with a reason code of DUPLICATE_SAME_DAY"
	extends "Duplicate Shot/Same Day Overview Abstract DTP Rule #4: Make notes if all shots are an NOS CVX and one of them contains Pertussis and the other does not"
	dialect "mvel"
	ruleflow-group "HistoryEvaluation^duplicateShotSameDay"
	auto-focus true
	salience 10
	when
		TargetDose(this == $td, isPrimarySeriesShot() == true)
		TargetDose(this == $tdother, isPrimarySeriesShot() == true)
	then
		modify($tdother) {
			setDuplicateShotSameDayCheckCompleted(true),
			setStatus(DoseStatus.INVALID),
			addInvalidReason(BaseDataEvaluationReason._DUPLICATE_SAME_DAY_REASON.getCdsListItemName())
		};
		modify($td) {
			setDuplicateShotSameDayCheckCompleted(true)
		};
		update($ts)
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $tdother + " in TargetSeries " + $td.associatedTargetSeries);
end

rule "Duplicate Shots/Same Day Overview Rule #4-DTP-Pertussis (NOT Both Primary Series Doses): If neither shot is in the primary series, both are NOS, and one of them contains Pertussis and the other does not, then evaluate shot with Pertussis as Valid and evaluate the other as Invalid with a reason code of DUPLICATE_SAME_DAY"
	extends "Duplicate Shot/Same Day Overview Abstract DTP Rule #4: Make notes if all shots are an NOS CVX and one of them contains Pertussis and the other does not"
	dialect "mvel"
	ruleflow-group "HistoryEvaluation^duplicateShotSameDay"
	auto-focus true
	salience 10
	when
		TargetDose(this == $tdother, ((isPrimarySeriesShot() == true || isPrimarySeriesShot() == false) && $td.isPrimarySeriesShot() == false) || (isPrimarySeriesShot() == false && ($td.isPrimarySeriesShot() == true || $td.isPrimarySeriesShot() == false)))
	then
		modify($tdother) {
			setDuplicateShotSameDayCheckCompleted(true)
		};
		modify($td) {
			setDuplicateShotSameDayCheckCompleted(true)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $tdother + " in TargetSeries " + $td.associatedTargetSeries);
end

rule "Duplicate Shot/Same Day Overview Abstract DTP Rule #5: Make notes if neither shot is an NOS CVX, and neither shot is a combination or both shots are a combination"
	dialect "mvel"
	ruleflow-group "HistoryEvaluation^duplicateShotSameDay"
	activation-group "duplicateShotAbstractRule5"
	auto-focus true
	salience 10
	when
		$td: TargetDose(hasBeenEvaluated == true, status == DoseStatus.VALID, isDoseStatusOverridden() == false, associatedTargetSeries.vaccineGroup == "VACCINE_GROUP_CONCEPT.DTP", vaccineComponent.isUnspecifiedFormulation() == false, $tdIsCombination: administeredVaccine.isCombinationVaccine())
		$tdother : TargetDose(this != $td, hasBeenEvaluated == true, status == DoseStatus.VALID, isDoseStatusOverridden() == false, associatedTargetSeries == $td.associatedTargetSeries, administrationDate == $td.administrationDate, vaccineComponent.isUnspecifiedFormulation() == false,
			$tdOtherIsCombination : administeredVaccine.isCombinationVaccine(), isDuplicateShotSameDayCheckCompleted() == false || $td.isDuplicateShotSameDayCheckCompleted() == false)
		$ts : TargetSeries(this == $tdother.associatedTargetSeries)
		eval($tdIsCombination == true && $tdOtherIsCombination == true || $tdIsCombination == false && $tdOtherIsCombination == false)
	then
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $td + " in TargetSeries VACCINE_GROUP_CONCEPT.DTP (DTP)");
end

rule "Duplicate Shots/Same Day DTP Rule 5a (BOTH Primary Series Doses): If one DTP shot is pertussis-containing vaccine and other is not pertussis-containing, evaluate the non-pertussis containing vaccine as Invalid w/ DUPLICATE_SHOT_SAME_DAY"
	extends "Duplicate Shot/Same Day Overview Abstract DTP Rule #5: Make notes if neither shot is an NOS CVX, and neither shot is a combination or both shots are a combination"
	dialect "mvel"
	ruleflow-group "HistoryEvaluation^duplicateShotSameDay"
	auto-focus true
	salience 10
	when
		TargetDose(this == $td, isPrimarySeriesShot() == true)
		TargetDose(this == $tdother, isPrimarySeriesShot() == true)
		eval($td.getVaccineComponent().getAllDiseasesTargetedForImmunity().contains("SUPPORTED_DISEASE_CONCEPT.PERTUSSIS") && ! $tdother.getVaccineComponent().getAllDiseasesTargetedForImmunity().contains("SUPPORTED_DISEASE_CONCEPT.PERTUSSIS"))
	then
		modify($tdother) {
			setStatus(DoseStatus.INVALID),
			setDuplicateShotSameDayCheckCompleted(true),
			addInvalidReason(BaseDataEvaluationReason._DUPLICATE_SAME_DAY_REASON.getCdsListItemName())
		};
		modify($td) {
			setDuplicateShotSameDayCheckCompleted(true),
			setStatus(DoseStatus.VALID)
		};
		update($ts)
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $tdother + " in TargetSeries DTP vaccine group");
end

/**
 * Duplicate Shots/Same Day DTP Rule 5a(Not Primary Series Does): If one DTP shot is pertussis-containing vaccine another is not
 * pertussis-containing, evaluate both as Valid since there is a 0 day interval between non-pertussis shots
 */
rule "Duplicate Shots/Same Day DTP Rule 5a (_NOT_ BOTH Primary Series Doses): If one DTP shot is pertussis-containing vaccine and other is not pertussis-containing, but neither are primary series doses, evaluate both as Valid"
	extends "Duplicate Shot/Same Day Overview Abstract DTP Rule #5: Make notes if neither shot is an NOS CVX, and neither shot is a combination or both shots are a combination"
	dialect "mvel"
	ruleflow-group "HistoryEvaluation^duplicateShotSameDay"
	auto-focus true
	salience 10
	when
		TargetDose(this == $tdother, ((isPrimarySeriesShot() == true || isPrimarySeriesShot() == false) && $td.isPrimarySeriesShot() == false) || (isPrimarySeriesShot() == false && ($td.isPrimarySeriesShot() == true || $td.isPrimarySeriesShot() == false)))
		eval($td.getVaccineComponent().getAllDiseasesTargetedForImmunity().contains("SUPPORTED_DISEASE_CONCEPT.PERTUSSIS") && ! $tdother.getVaccineComponent().getAllDiseasesTargetedForImmunity().contains("SUPPORTED_DISEASE_CONCEPT.PERTUSSIS"))
	then
		modify($tdother) {
			setDuplicateShotSameDayCheckCompleted(true)
		};
		modify($td) {
			setDuplicateShotSameDayCheckCompleted(true)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $tdother + " in TargetSeries DTP vaccine group");
end

rule "Duplicate Shot/Same Day DTP Rule 5b (BOTH Primary Series Doses): If neither shot contains pertussis or both shots contain pertussis, then evaluate the 1st shot processed as Valid and evaluate the 2nd shot processed as Invalid with a reason code of DUPLICATE_SAME_DAY"
	extends "Duplicate Shot/Same Day Overview Abstract DTP Rule #5: Make notes if neither shot is an NOS CVX, and neither shot is a combination or both shots are a combination"
	dialect "java"
	ruleflow-group "HistoryEvaluation^duplicateShotSameDay"
	auto-focus true
	salience 10
	when
		TargetDose(this == $td, isPrimarySeriesShot() == true)
		TargetDose(this == $tdother, isPrimarySeriesShot() == true)
		eval(($td.getVaccineComponent().getAllDiseasesTargetedForImmunity().contains("SUPPORTED_DISEASE_CONCEPT.PERTUSSIS") &&
			$tdother.getVaccineComponent().getAllDiseasesTargetedForImmunity().contains("SUPPORTED_DISEASE_CONCEPT.PERTUSSIS")) ||
			(! $td.getVaccineComponent().getAllDiseasesTargetedForImmunity().contains("SUPPORTED_DISEASE_CONCEPT.PERTUSSIS") &&
			! $tdother.getVaccineComponent().getAllDiseasesTargetedForImmunity().contains("SUPPORTED_DISEASE_CONCEPT.PERTUSSIS")))
	then
		TargetDose tdToModifyInvalid = null;
		TargetDose tdToModifyValid = null;
		if ($td.getAdministeredShotNumberInSeries() > $tdother.getAdministeredShotNumberInSeries()) {
			tdToModifyInvalid = $td;
			tdToModifyValid = $tdother;
		}
		else {
			tdToModifyInvalid = $tdother;
			tdToModifyValid = $td;
		}
		modify(tdToModifyInvalid) {
			setStatus(DoseStatus.INVALID),
			setDuplicateShotSameDayCheckCompleted(true),
			addInvalidReason(BaseDataEvaluationReason._DUPLICATE_SAME_DAY_REASON.getCdsListItemName())
		};
		modify(tdToModifyValid) {
			setDuplicateShotSameDayCheckCompleted(true),
			setStatus(DoseStatus.VALID)
		};
		update($ts)
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), tdToModifyInvalid + " in TargetSeries DTP vaccine group");
end

/**
 * Duplicate Shot/Same Day DTP Rule 5b: If neither shot contains pertussis or both shots contain pertussis, then evaluate the 1st
 * shot processed as Valid and evaluate the 2nd shot processed as Invalid with a reason code of DUPLICATE_SAME_DAY
 */
rule "Duplicate Shot/Same Day DTP Rule 5b (_NOT_ BOTH Primary Series Doses): If neither shot contains pertussis or both shots contain pertussis, but neither are primary series doses, evaluate both as Valid"
	extends "Duplicate Shot/Same Day Overview Abstract DTP Rule #5: Make notes if neither shot is an NOS CVX, and neither shot is a combination or both shots are a combination"
	dialect "java"
	ruleflow-group "HistoryEvaluation^duplicateShotSameDay"
	auto-focus true
	salience 10
	when
		TargetDose(this == $tdother, ((isPrimarySeriesShot() == true || isPrimarySeriesShot() == false) && $td.isPrimarySeriesShot() == false) || (isPrimarySeriesShot() == false && ($td.isPrimarySeriesShot() == true || $td.isPrimarySeriesShot() == false)))
		eval(($td.getVaccineComponent().getAllDiseasesTargetedForImmunity().contains("SUPPORTED_DISEASE_CONCEPT.PERTUSSIS") &&
			$tdother.getVaccineComponent().getAllDiseasesTargetedForImmunity().contains("SUPPORTED_DISEASE_CONCEPT.PERTUSSIS")) ||
			(! $td.getVaccineComponent().getAllDiseasesTargetedForImmunity().contains("SUPPORTED_DISEASE_CONCEPT.PERTUSSIS") &&
			! $tdother.getVaccineComponent().getAllDiseasesTargetedForImmunity().contains("SUPPORTED_DISEASE_CONCEPT.PERTUSSIS")))
	then
		modify($tdother) {
			setDuplicateShotSameDayCheckCompleted(true)
		};
		modify($td) {
			setDuplicateShotSameDayCheckCompleted(true)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $tdother + " in TargetSeries DTP vaccine group");
end