package knowledgeModule.org.nyc.cir.ice;

import java.util.Iterator;
import java.util.List;
import java.util.Set;
import org.opencds.vmr.v1_0.internal.EvalTime;
import org.opencds.vmr.v1_0.internal.EvaluatedPerson;
import org.opencds.vmr.v1_0.internal.SubstanceAdministrationEvent;
import org.opencds.vmr.v1_0.internal.concepts.ImmunizationConcept;
import org.cdsframework.cds.CdsConcept;
import org.cdsframework.ice.service.DiseaseImmunity;
import org.cdsframework.ice.service.DoseStatus;
import org.cdsframework.ice.service.ICEFactTypeFinding;
import org.cdsframework.ice.service.ICELogicHelper;
import org.cdsframework.ice.service.Recommendation;
import org.cdsframework.ice.service.RecommendationStatus;
import org.cdsframework.ice.service.Schedule;
import org.cdsframework.ice.service.SeriesRules;
import org.cdsframework.ice.supportingdatatmp.SupportedFactConcept;
import org.cdsframework.ice.service.TargetDose;
import org.cdsframework.ice.service.TargetDoseInitializationTracker;
import org.cdsframework.ice.service.TargetSeries;
import org.cdsframework.ice.util.TimePeriod;
import org.cdsframework.ice.util.TimePeriod.DurationType;
import org.cdsframework.ice.service.Vaccine;
import org.cdsframework.ice.service.VaccineComponent;

global java.time.LocalDate evalTime;
global org.cdsframework.ice.service.Schedule schedule;

/**
 * Specialized initialization rule for Meningococcal ACWY and Meningococcal B vaccine group
 * This catchall rule should not fire, because all vaccines should either be explicitly placed into the Meningococcal ACWY or
 * Meningococcal B vaccine group per other rules (below). But if it does fire, it will be placed into the vaccine group if it has at
 * least one series that accepts that vaccine. This is actually more restrictive than the default cdsframework rule, which will
 * initialize a TargetDose into a TargetSeries is both target the same disease (as specified by the disease code)
 */
rule "CandidateDosesIdentification: Initialize TargetDose in Meningococcal ACWY or Meningococcal B Vaccine Group Series"
	dialect "java"
	ruleflow-group "CandidateDosesIdentification^customCandidateDosesIdentificationRule"
	salience 55
	no-loop true
	when
		$i : ImmunizationConcept($ctid : getConceptTargetId(), $occ : getOpenCdsConceptCode(), $occ not in ("VACCINE_CVX_316", "VACCINE_CVX_328"))
		$sae : SubstanceAdministrationEvent(id == $ctid)
		$s : SeriesRules($sseriesName : getSeriesName(), $vg : getVaccineGroup(), getVaccineGroup() == "VACCINE_GROUP_CONCEPT.MENINGOCOCCAL_ACWY" || getVaccineGroup() == "VACCINE_GROUP_CONCEPT.MENINGOCOCCAL_B",
			vaccineIsAllowableInOneOrMoreDoseRules(schedule.getVaccineByCdsConceptValue($i.getOpenCdsConceptCode())))
		$ts : TargetSeries(seriesName == $sseriesName, $tsid : targetSeriesIdentifier)
		$tdit : TargetDoseInitializationTracker(shotAdministeredIsEligibleForInclusionInTargetSeries($i, $vg, $sae, $ts, schedule.getVaccineByCdsConceptValue($occ)) == true)
	then
		Vaccine administeredVaccine = schedule.getVaccineByCdsConceptValue($i.getOpenCdsConceptCode());
		for (TargetDose initializedTargetDose : $tdit.addTargetDoseInitialization(administeredVaccine, $sae, $ts, schedule)) {
			insert(initializedTargetDose);
		}
		update($ts);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "completed");
end

/**
 * Meningococcal B vaccines (CVX 162, 163) always initializes the Meningococcal B vaccine group
 */
rule "CandidateDosesIdentification: Initialize Meningococcal B vaccines (CVX 162, 163, 164) in the Meningococcal B vaccine group"
	dialect "java"
	ruleflow-group "CandidateDosesIdentification^customCandidateDosesIdentificationRule"
	salience 60
	no-loop true
	when
		$i : ImmunizationConcept(
                $ctid : getConceptTargetId(),
                $occ : getOpenCdsConceptCode(),
                $occ in ("VACCINE_CVX_162", "VACCINE_CVX_163", "VACCINE_CVX_164")
             )
		$sae : SubstanceAdministrationEvent(
		        id == $ctid,
		        $saeAdminDate : getAdministrationTimeInterval()
		       )
		$s : SeriesRules(
		        $sseriesName : getSeriesName(),
		        $vg : getVaccineGroup(),
		        getVaccineGroup() == "VACCINE_GROUP_CONCEPT.MENINGOCOCCAL_B",
		        vaccineIsAllowableInOneOrMoreDoseRules(schedule.getVaccineByCdsConceptValue($i.getOpenCdsConceptCode()))
		     )
		$ts : TargetSeries(
		        seriesName == $sseriesName,
		        $tsid : targetSeriesIdentifier
		      )
		$tdit : TargetDoseInitializationTracker(shotAdministeredIsEligibleForInclusionInTargetSeries($i, $vg, $sae, $ts, schedule.getVaccineByCdsConceptValue($occ)) == true)
	then
		Vaccine administeredVaccine = schedule.getVaccineByCdsConceptValue($i.getOpenCdsConceptCode());
		for (TargetDose initializedTargetDose : $tdit.addTargetDoseInitialization(administeredVaccine, $sae, $ts, schedule)) {
			insert(initializedTargetDose);
		}
		update($ts);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetDose initialized in TargetSeries " + $ts.getSeriesName() + " ; vaccine: " + $occ + "; vaccine group " + $vg + "; shotdate " + $saeAdminDate);
end

/**
 * Meningococcal MenABCWY-TT (Penbraya) (CVX 316) initialization in Meningococcal B vaccine group
 */
rule "CandidateDosesIdentification: Initialize Meningococcal vaccine (CVX 316) in the Meningococcal B vaccine group"
	dialect "java"
	ruleflow-group "CandidateDosesIdentification^customCandidateDosesIdentificationRule"
	salience 60
	no-loop true
	when
		$i : ImmunizationConcept($ctid : getConceptTargetId(), getOpenCdsConceptCode() == "VACCINE_CVX_316", $occ : getOpenCdsConceptCode())
		$sae : SubstanceAdministrationEvent(id == $ctid, $saeAdminDate : getAdministrationTimeInterval())
		$s : SeriesRules($sseriesName : getSeriesName(), $vg : getVaccineGroup(), getVaccineGroup() == "VACCINE_GROUP_CONCEPT.MENINGOCOCCAL_B")
		$ts : TargetSeries(seriesName == $sseriesName, $tsid : targetSeriesIdentifier)
		$tdit : TargetDoseInitializationTracker(shotAdministeredIsEligibleForInclusionInTargetSeries($i, $vg, $sae, $ts, schedule.getVaccineByCdsConceptValue($occ)) == true)
		eval($tdit.isTargetDoseInitializedInSeries($sae, new VaccineComponent(new CdsConcept("VACCINE_CVX_162"), schedule.getDiseasesTargetedByVaccineGroup("VACCINE_GROUP_CONCEPT.MENINGOCOCCAL_B")), $ts) == false)

	then
		Vaccine administeredVaccine = schedule.getVaccineByCdsConceptValue($i.getOpenCdsConceptCode());
		VaccineComponent vaccineComponentOfInterest = new VaccineComponent(new CdsConcept("VACCINE_CVX_162"), schedule.getDiseasesTargetedByVaccineGroup("VACCINE_GROUP_CONCEPT.MENINGOCOCCAL_B"));
		for (TargetDose initializedTargetDose : $tdit.addTargetDoseInitialization(administeredVaccine, $sae, $ts, schedule, vaccineComponentOfInterest)) {
			insert(initializedTargetDose);
		}
		update($ts);
		update($tdit);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetDose initialized in TargetSeries " + $ts.getSeriesName() + " ; vaccine: " + $occ + "; vaccine group " + $vg + "; shotdate " + $saeAdminDate);
end

/**
 * Meningococcal MenACWY, MenB (Penmenvy) (CVX 328) initialization in Meningococcal B vaccine group
 */
rule "CandidateDosesIdentification: Initialize Meningococcal vaccine (CVX 328) in the Meningococcal B vaccine group"
	dialect "java"
	ruleflow-group "CandidateDosesIdentification^customCandidateDosesIdentificationRule"
	salience 60
	no-loop true
	when
		$i : ImmunizationConcept($ctid : getConceptTargetId(), getOpenCdsConceptCode() == "VACCINE_CVX_328", $occ : getOpenCdsConceptCode())
		$sae : SubstanceAdministrationEvent(id == $ctid, $saeAdminDate : getAdministrationTimeInterval())
		$s : SeriesRules($sseriesName : getSeriesName(), $vg : getVaccineGroup(), getVaccineGroup() == "VACCINE_GROUP_CONCEPT.MENINGOCOCCAL_B")
		$ts : TargetSeries(seriesName == $sseriesName, $tsid : targetSeriesIdentifier)
		$tdit : TargetDoseInitializationTracker(shotAdministeredIsEligibleForInclusionInTargetSeries($i, $vg, $sae, $ts, schedule.getVaccineByCdsConceptValue($occ)) == true)
		eval($tdit.isTargetDoseInitializedInSeries($sae, new VaccineComponent(new CdsConcept("VACCINE_CVX_163"), schedule.getDiseasesTargetedByVaccineGroup("VACCINE_GROUP_CONCEPT.MENINGOCOCCAL_B")), $ts) == false)
	then
		Vaccine administeredVaccine = schedule.getVaccineByCdsConceptValue($i.getOpenCdsConceptCode());
		VaccineComponent vaccineComponentOfInterest = new VaccineComponent(new CdsConcept("VACCINE_CVX_163"), schedule.getDiseasesTargetedByVaccineGroup("VACCINE_GROUP_CONCEPT.MENINGOCOCCAL_B"));
		for (TargetDose initializedTargetDose : $tdit.addTargetDoseInitialization(administeredVaccine, $sae, $ts, schedule, vaccineComponentOfInterest)) {
			insert(initializedTargetDose);
		}
		update($ts);
		update($tdit);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetDose initialized in TargetSeries " + $ts.getSeriesName() + " ; vaccine: " + $occ + "; vaccine group " + $vg + "; shotdate " + $saeAdminDate);
end

/**
 * Meningococcal ACWY vaccines (CVX 114, 136, 32, 108, 147) always initializes the Meningococcal ACWY vaccine group
 */
rule "CandidateDosesIdentification: Initialize Meningococcal vaccines (CVX 114, 136, 32, 108, 147) in the Meningococcal ACWY vaccine group"
	dialect "java"
	ruleflow-group "CandidateDosesIdentification^customCandidateDosesIdentificationRule"
	salience 60
	no-loop true
	when
		$i : ImmunizationConcept($ctid : getConceptTargetId(), getOpenCdsConceptCode() in ("VACCINE_CVX_114","VACCINE_CVX_136","VACCINE_CVX_32","VACCINE_CVX_108","VACCINE_CVX_147"), $occ : getOpenCdsConceptCode())
		$sae : SubstanceAdministrationEvent(id == $ctid, $saeAdminDate : getAdministrationTimeInterval())
		$s : SeriesRules($sseriesName : getSeriesName(), $vg : getVaccineGroup(), getVaccineGroup() == "VACCINE_GROUP_CONCEPT.MENINGOCOCCAL_ACWY",
			vaccineIsAllowableInOneOrMoreDoseRules(schedule.getVaccineByCdsConceptValue($i.getOpenCdsConceptCode())))
		$ts : TargetSeries(seriesName == $sseriesName, $tsid : targetSeriesIdentifier)
		$tdit : TargetDoseInitializationTracker(shotAdministeredIsEligibleForInclusionInTargetSeries($i, $vg, $sae, $ts, schedule.getVaccineByCdsConceptValue($occ)) == true)
	then
		Vaccine administeredVaccine = schedule.getVaccineByCdsConceptValue($i.getOpenCdsConceptCode());
		for (TargetDose initializedTargetDose : $tdit.addTargetDoseInitialization(administeredVaccine, $sae, $ts, schedule)) {
			insert(initializedTargetDose);
		}
		update($ts);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetDose initialized in TargetSeries " + $ts.getSeriesName() + " ; vaccine: " + $occ + "; vaccine group " + $vg + "; shotdate " + $saeAdminDate);
end

/**
 * Meningococcal MenABCWY-TT (Penbraya) (CVX 316) initialization in Meningococcal ACWY vaccine group
 */
rule "CandidateDosesIdentification: Initialize Meningococcal vaccine (CVX 316) in the Meningococcal ACWY vaccine group"
	dialect "java"
	ruleflow-group "CandidateDosesIdentification^customCandidateDosesIdentificationRule"
	salience 60
	no-loop true
	when
		$i : ImmunizationConcept($ctid : getConceptTargetId(), getOpenCdsConceptCode() == "VACCINE_CVX_316", $occ : getOpenCdsConceptCode())
		$sae : SubstanceAdministrationEvent(id == $ctid, $saeAdminDate : getAdministrationTimeInterval())
		$s : SeriesRules($sseriesName : getSeriesName(), $vg : getVaccineGroup(), getVaccineGroup() == "VACCINE_GROUP_CONCEPT.MENINGOCOCCAL_ACWY")
		$ts : TargetSeries(seriesName == $sseriesName, $tsid : targetSeriesIdentifier)
		$tdit : TargetDoseInitializationTracker(shotAdministeredIsEligibleForInclusionInTargetSeries($i, $vg, $sae, $ts, schedule.getVaccineByCdsConceptValue($occ)) == true)
		eval($tdit.isTargetDoseInitializedInSeries($sae, new VaccineComponent(new CdsConcept("VACCINE_CVX_147"), schedule.getDiseasesTargetedByVaccineGroup("VACCINE_GROUP_CONCEPT.MENINGOCOCCAL_ACWY")), $ts) == false)
	then
		Vaccine administeredVaccine = schedule.getVaccineByCdsConceptValue($i.getOpenCdsConceptCode());
		VaccineComponent vaccineComponentOfInterest = new VaccineComponent(new CdsConcept("VACCINE_CVX_147"), schedule.getDiseasesTargetedByVaccineGroup("VACCINE_GROUP_CONCEPT.MENINGOCOCCAL_ACWY"));
		for (TargetDose initializedTargetDose : $tdit.addTargetDoseInitialization(administeredVaccine, $sae, $ts, schedule, vaccineComponentOfInterest)) {
			insert(initializedTargetDose);
		}
		update($ts);
		update($tdit);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetDose initialized in TargetSeries " + $ts.getSeriesName() + " ; vaccine: " + $occ + "; vaccine group " + $vg + "; shotdate " + $saeAdminDate);
end

/**
 * Meningococcal MenACWY, MenB (Penmenvy) (CVX 328) initialization in Meningococcal ACWY vaccine group
 */
rule "CandidateDosesIdentification: Initialize Meningococcal vaccine (CVX 328) in the Meningococcal ACWY vaccine group"
	dialect "java"
	ruleflow-group "CandidateDosesIdentification^customCandidateDosesIdentificationRule"
	salience 60
	no-loop true
	when
		$i : ImmunizationConcept($ctid : getConceptTargetId(), getOpenCdsConceptCode() == "VACCINE_CVX_328", $occ : getOpenCdsConceptCode())
		$sae : SubstanceAdministrationEvent(id == $ctid, $saeAdminDate : getAdministrationTimeInterval())
		$s : SeriesRules($sseriesName : getSeriesName(), $vg : getVaccineGroup(), getVaccineGroup() == "VACCINE_GROUP_CONCEPT.MENINGOCOCCAL_ACWY")
		$ts : TargetSeries(seriesName == $sseriesName, $tsid : targetSeriesIdentifier)
		$tdit : TargetDoseInitializationTracker(shotAdministeredIsEligibleForInclusionInTargetSeries($i, $vg, $sae, $ts, schedule.getVaccineByCdsConceptValue($occ)) == true)
		eval($tdit.isTargetDoseInitializedInSeries($sae, new VaccineComponent(new CdsConcept("VACCINE_CVX_136"), schedule.getDiseasesTargetedByVaccineGroup("VACCINE_GROUP_CONCEPT.MENINGOCOCCAL_ACWY")), $ts) == false)
	then
		Vaccine administeredVaccine = schedule.getVaccineByCdsConceptValue($i.getOpenCdsConceptCode());
		VaccineComponent vaccineComponentOfInterest = new VaccineComponent(new CdsConcept("VACCINE_CVX_136"), schedule.getDiseasesTargetedByVaccineGroup("VACCINE_GROUP_CONCEPT.MENINGOCOCCAL_ACWY"));
		for (TargetDose initializedTargetDose : $tdit.addTargetDoseInitialization(administeredVaccine, $sae, $ts, schedule, vaccineComponentOfInterest)) {
			insert(initializedTargetDose);
		}
		update($ts);
		update($tdit);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetDose initialized in TargetSeries " + $ts.getSeriesName() + " ; vaccine: " + $occ + "; vaccine group " + $vg + "; shotdate " + $saeAdminDate);
end

/**
 * Any CVX 28 administered in DTP vaccine group on or after 2023-05-01 should be evaluated as CVX 107
 */
rule "CandidateDosesIdentification: Initialize DTP-related DT component (CVX 28) as CVX 107 in DTP vaccine group on or after 2023-05-01"
	dialect "java"
	ruleflow-group "CandidateDosesIdentification^customCandidateDosesIdentificationRule"
	salience 60
	no-loop true
	when
		$i : ImmunizationConcept($ctid : getConceptTargetId(), getOpenCdsConceptCode() == "VACCINE_CVX_28", $occ : getOpenCdsConceptCode())
		$sae : SubstanceAdministrationEvent(id == $ctid, $saeAdminDate : getAdministrationTimeInterval(),
			$shotDate : ICELogicHelper.extractSingularDateValueFromIVLDate(getAdministrationTimeInterval()))
		$s : SeriesRules($sseriesName : getSeriesName(), $vg : getVaccineGroup(), getVaccineGroup() == "VACCINE_GROUP_CONCEPT.DTP")
		$ts : TargetSeries(seriesName == $sseriesName, $tsid : targetSeriesIdentifier)
		$tdit : TargetDoseInitializationTracker(shotAdministeredIsEligibleForInclusionInTargetSeries($i, $vg, $sae, $ts, schedule.getVaccineByCdsConceptValue($occ), "VACCINE_CVX_107") == true)
		eval($shotDate != null && !$shotDate.isBefore(java.time.LocalDate.parse("2023-05-01")))
		eval($tdit.isTargetDoseInitializedInSeries($sae, new VaccineComponent(new CdsConcept("VACCINE_CVX_107"), schedule.getDiseasesTargetedByVaccineGroup("VACCINE_GROUP_CONCEPT.DTP")), $ts) == false)
	then
		Vaccine vaccineForTargetDoseInitialization = schedule.getVaccineByCdsConceptValue("VACCINE_CVX_107");
		VaccineComponent vaccineComponentOfInterest = new VaccineComponent(new CdsConcept("VACCINE_CVX_107"), schedule.getDiseasesTargetedByVaccineGroup("VACCINE_GROUP_CONCEPT.DTP"));
		for (TargetDose initializedTargetDose : $tdit.addTargetDoseInitialization(vaccineForTargetDoseInitialization, $sae, $ts, schedule, vaccineComponentOfInterest, "VACCINE_CVX_28")) {
			insert(initializedTargetDose);
			insert(new ICEFactTypeFinding(SupportedFactConcept._DT_ADMINISTERED_ON_OR_AFTER_20230501_EVALUATE_AS_CVX_107.getConceptCodeValue(), initializedTargetDose));
		}
		update($ts);
		update($tdit);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetDose initialized in TargetSeries " + $ts.getSeriesName() + " ; vaccine: " + $occ + "; vaccine group " + $vg + "; shotdate " + $saeAdminDate);
end
