package knowledgeModule.org.nyc.cir.ice;

import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import org.opencds.vmr.v1_0.internal.EvalTime;
import org.opencds.vmr.v1_0.internal.EvaluatedPerson;
import org.cdsframework.ice.service.DiseaseImmunity;
import org.cdsframework.ice.service.DoseStatus;
import org.cdsframework.ice.service.ICEFactTypeFinding;
import org.cdsframework.ice.service.ICELogicHelper;
import org.cdsframework.ice.service.Recommendation;
import org.cdsframework.ice.service.RecommendationStatus;
import org.cdsframework.ice.service.SeriesRules;
import org.cdsframework.ice.supportingdata.BaseDataEvaluationReason;
import org.cdsframework.ice.supportingdatatmp.SupportedFactConcept;
import org.cdsframework.ice.service.TargetDose;
import org.cdsframework.ice.service.TargetSeries;
import org.cdsframework.ice.util.TimePeriod;
import org.cdsframework.ice.util.TimePeriod.DurationType;
import org.cdsframework.ice.service.Vaccine;

global java.util.Date evalTime;

/**
 * If shot is administered >=10/25/2024, then the following Two Shot Same Day Exception Rules for Meningococcal B rules apply:
 *   If CVX 162 (Meningococcal B FHbp, recombinant (Trumenba)) or CVX 316 (Meningococcal MenABCWY (Penbraya)) and CVX 163
 *   (Meningococcal B 4C, OMV (Bexsero)) are reported as administered on the same day, then:
 *     + evaluate CVX 162 (Meningococcal B FHbp, recombinant (Trumenba)) as Invalid with reason codes DUPLICATE_SAME_DAY and
 *       SUPPLEMENTAL_TEXT; Descriptive Text: "The patient record indicates that different Meningococcal B products were
 *       administered on the same day. Based on the available information, the product administered is undetermined and therefore
 *       unable to be evaluated."
 *     + evaluate CVX 163 (Meningococcal B 4C, OMV (Bexsero)) as Invalid with a reason codes DUPLICATE_SAME_DAY and
 *       SUPPLEMENTAL_TEXT; Descriptive Text: "The patient record indicates that different Meningococcal B products were
 *       administered on the same day. Based on the available information, the product administered is undetermined and therefore
 *       unable to be evaluated."
 */
rule "Duplicate Shots/Same Day(MenB Abstract): If CVX 162 or CVX 316 is administered >= 10/25/2024 and on the same day as CVX 163 or CVX 328"
	dialect "mvel"
	ruleflow-group "HistoryEvaluation^duplicateShotSameDay"
	auto-focus true
	no-loop true
	when
		$td: TargetDose(hasBeenEvaluated == true, associatedVaccineGroup == "VACCINE_GROUP_CONCEPT.MENINGOCOCCAL_B", administrationDate >= "25-Oct-2024", doseNumberInSeries <= associatedTargetSeries.seriesRules.numberOfDosesInSeries, isDoseStatusOverridden() == false)
		$tdother : TargetDose(this != $td, associatedTargetSeries == $td.associatedTargetSeries, administrationDate == $td.administrationDate, administeredVaccine.cdsConceptName != $td.administeredVaccine.cdsConceptName, hasBeenEvaluated == true, isDoseStatusOverridden() == false,
			doseNumberInSeries == $td.doseNumberInSeries, isDuplicateShotSameDayCheckCompleted() == false || $td.isDuplicateShotSameDayCheckCompleted() == false)
        $ts : TargetSeries(this == $tdother.associatedTargetSeries)
	then
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $tdother + " in TargetSeries " + $td.associatedTargetSeries);
end

rule "Duplicate Shots/Same Day (MenB- Series is Complete; $td Shot is Valid): If CVX 162 or CVX 316 is administered >= 10/25/2024 on the same day as CVX 163 on a date >= 10/25/2024, and the Series is complete, evaluate the shot that completes the Series as Valid and the other shot as Invalid / DUPLICATE_SAME_DAY"
	extends "Duplicate Shots/Same Day(MenB Abstract): If CVX 162 or CVX 316 is administered >= 10/25/2024 and on the same day as CVX 163 or CVX 328"
	dialect "mvel"
	auto-focus true
	no-loop true
	when
		TargetSeries(this == $td.associatedTargetSeries, isSeriesComplete() == true)
		TargetDose(this == $td, isValid == true)
	then
		modify($td) {
			setDuplicateShotSameDayCheckCompleted(true)
		};
		modify($tdother) {
			setStatus(DoseStatus.INVALID),
			setDuplicateShotSameDayCheckCompleted(true),
			removeAllEvaluationReasonsFromAllReasonSets(),
			addInvalidReason(BaseDataEvaluationReason._DUPLICATE_SAME_DAY_REASON.getCdsListItemName())
		};
		update($ts)
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetSeries " + $td.associatedTargetSeries);
end

rule "Duplicate Shots/Same Day (MenB- Series is Complete; $tdother Shot is Valid): If CVX 162 or CVX 316 is administered >= 10/25/2024 on the same day as a CVX 163 or CVX 328 on a date >= 10/25/2024, and the Series is complete, evaluate the shot that completes the Series as Valid and the other shot as Invalid / DUPLICATE_SAME_DAY"
	extends "Duplicate Shots/Same Day(MenB Abstract): If CVX 162 or CVX 316 is administered >= 10/25/2024 and on the same day as CVX 163 or CVX 328"
	dialect "mvel"
	auto-focus true
	no-loop true
	when
		TargetSeries(this == $td.associatedTargetSeries, isSeriesComplete() == true)
		TargetDose(this == $tdother, isValid == true)
	then
		modify($tdother) {
			setDuplicateShotSameDayCheckCompleted(true)
		};
		modify($td) {
			setStatus(DoseStatus.INVALID),
			setDuplicateShotSameDayCheckCompleted(true),
			removeAllEvaluationReasonsFromAllReasonSets(),
			addInvalidReason(BaseDataEvaluationReason._DUPLICATE_SAME_DAY_REASON.getCdsListItemName())
		};
		update($ts)
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetSeries " + $td.associatedTargetSeries);
end

rule "Duplicate Shots/Same Day (MenB- Series is Not Complete): If CVX 162 or CVX 316 is administered >= 10/25/2024 on the same day as CVX 163 or CVX 328 on a date >= 10/25/2024, and neither Series complete, evaluate the shot that completes the Series as Valid and the other shot as Invalid / DUPLICATE_SAME_DAY"
	extends "Duplicate Shots/Same Day(MenB Abstract): If CVX 162 or CVX 316 is administered >= 10/25/2024 and on the same day as CVX 163 or CVX 328"
	dialect "mvel"
	auto-focus true
	no-loop true
	when
		TargetSeries(this == $td.associatedTargetSeries, isSeriesComplete() == false)
	then
		modify($tdother) {
			setStatus(DoseStatus.INVALID),
			setDuplicateShotSameDayCheckCompleted(true),
			removeAllEvaluationReasonsFromAllReasonSets(),
			addInvalidReason(BaseDataEvaluationReason._DUPLICATE_SAME_DAY_REASON.getCdsListItemName()),
			addInvalidReason("SUPPLEMENTAL_EVALUATION_REASON_CONCEPT.MENB_SAME_DAY_DIFFERENT_PRODUCTS_UNDETERMINED")
		};
		modify($td) {
			setStatus(DoseStatus.INVALID),
			setDuplicateShotSameDayCheckCompleted(true),
			removeAllEvaluationReasonsFromAllReasonSets(),
			addInvalidReason(BaseDataEvaluationReason._DUPLICATE_SAME_DAY_REASON.getCdsListItemName()),
			addInvalidReason("SUPPLEMENTAL_EVALUATION_REASON_CONCEPT.MENB_SAME_DAY_DIFFERENT_PRODUCTS_UNDETERMINED")
		};
		update($ts)
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $td + " in TargetSeries " + $td.associatedTargetSeries);

end

/**
 * If shot is administered < 10/25/2024, then the following Two Shot Same Day Exception Rules for Meningococcal B rules apply:
 *   If CVX 162 (Meningococcal B FHbp, recombinant (Trumenba)) and CVX 163 (Meningococcal B 4C, OMV (Bexsero)) are reported as
 *   administered on the same day, then:
 *     + evaluate CVX 163 (Meningococcal B 4C, OMV (Bexsero)) as Valid
 *     + recommend based on the MenB 4C 2-dose Series.
 * However, if both Meningococcal B vaccines are administered on the same day, and one vaccine would complete a Meningococcal B
 * series, then evaluate that vaccine as Valid and the other Meningococcal B vaccine as Invalid with a reason code of
 * DUPLICATE_SAME_DAY.
 */
rule "Duplicate Shots/Same Day MeningB Rule: If CVX 162 (or CVX 316) / CVX 163 (or CVX 328) reported on same day in the 4C 2-dose Series on a date < 10/25/2024, evaluate the CVX 162 as Invalid with reason DUPLICATE_SAME_DAY"
	dialect "mvel"
	ruleflow-group "HistoryEvaluation^duplicateShotSameDay"
	auto-focus true
	no-loop true
	when
		$td: TargetDose(hasBeenEvaluated == true, associatedTargetSeries.vaccineGroup == "VACCINE_GROUP_CONCEPT.MENINGOCOCCAL_B", associatedTargetSeries.seriesName == "SUPPORTED_SERIES.MEN_B_4_C_2_DOSE_SERIES", vaccineComponent.cdsConceptName == "VACCINE_CVX_163",
			administrationDate < "25-Oct-2024", isDoseStatusOverridden() == false)
		$tdother : TargetDose(this != $td, associatedTargetSeries == $td.associatedTargetSeries, administrationDate == $td.administrationDate, hasBeenEvaluated == true, doseNumberInSeries == $td.doseNumberInSeries,
			vaccineComponent.cdsConceptName == "VACCINE_CVX_162", isDoseStatusOverridden() == false, isDuplicateShotSameDayCheckCompleted() == false || $td.isDuplicateShotSameDayCheckCompleted() == false)
        $ts : TargetSeries(this == $tdother.associatedTargetSeries)
	then
		modify($tdother) {
			setStatus(DoseStatus.INVALID),
			setDuplicateShotSameDayCheckCompleted(true),
			removeAllEvaluationReasonsFromAllReasonSets(),
			addInvalidReason(BaseDataEvaluationReason._DUPLICATE_SAME_DAY_REASON.getCdsListItemName())
		};
		modify($td) {
			setDuplicateShotSameDayCheckCompleted(true)
		};
		update($ts)
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $tdother + " in TargetSeries " + $td.associatedTargetSeries);
end

rule "Duplicate Shots/Same Day MeningB Rule: If CVX 162 (or CVX 316) / CVX 163 (or CVX 328) reported on same day in FBhp 2-dose or FBhp 3-dose Series < 10/25/2024, evaluate the CVX 163 as Invalid with reason DUPLICATE_SAME_DAY"
	dialect "mvel"
	ruleflow-group "HistoryEvaluation^duplicateShotSameDay"
	auto-focus true
	no-loop true
	when
		$td: TargetDose(hasBeenEvaluated == true, associatedTargetSeries.vaccineGroup == "VACCINE_GROUP_CONCEPT.MENINGOCOCCAL_B", vaccineComponent.cdsConceptName == "VACCINE_CVX_162", administrationDate < "25-Oct-2024", isDoseStatusOverridden() == false,
			associatedTargetSeries.seriesName == "SUPPORTED_SERIES.MEN_BF_HBP_2_DOSE_SERIES" || associatedTargetSeries.seriesName == "SUPPORTED_SERIES.MEN_BF_HBP_3_DOSE_SERIES")
		$tdother : TargetDose(this != $td, associatedTargetSeries == $td.associatedTargetSeries, administrationDate == $td.administrationDate, hasBeenEvaluated == true, isDoseStatusOverridden() == false,
			doseNumberInSeries == $td.doseNumberInSeries, vaccineComponent.cdsConceptName == "VACCINE_CVX_163", isDuplicateShotSameDayCheckCompleted() == false || $td.isDuplicateShotSameDayCheckCompleted() == false)
	    $ts : TargetSeries(this == $tdother.associatedTargetSeries)
	then
		modify($tdother) {
			setStatus(DoseStatus.INVALID),
			setDuplicateShotSameDayCheckCompleted(true),
			removeAllEvaluationReasonsFromAllReasonSets(),
			addInvalidReason(BaseDataEvaluationReason._DUPLICATE_SAME_DAY_REASON.getCdsListItemName())
		};
		modify($td) {
			setDuplicateShotSameDayCheckCompleted(true)
		};
		update($ts)
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $tdother + " in TargetSeries " + $td.associatedTargetSeries);
end