spring:
  application:
    name: ice
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    access:
      max-permitted: none

server:
  servlet:
    context-path: /opencds-decision-support-service

cxf:
  path: /evaluate

logging:
  level:
    org.drools: ERROR

ice:
  ice-base-rules-scoping-entity-id: org.cdsframework
  ice-base-rules-version: 1.0.0
  output-earliest-and-overdue-dates: true
  enable-dose-override-feature: false
  output-supplemental-text: true
  enable-unsupported-vaccines-group: false
  vaccine-group-exclusions:
    - ANTHRAX
    - MOSQUITO_BORNE
    - CHOLERA
    - JAPANESE_ENCEPHALITIS
    - TYPHOID
    - YELLOW_FEVER
  disable-covid19-sep2023-dose-number-reset: false
  enable-drools-event-logging: false
  supplemental-text-mode: LEGACY
  fire-limit: 25000
  ice-version: ICE_2.53.2
