package Bounce_v7

import org.opencds.vmr.v1_0.internal.ClinicalStatement
import org.opencds.vmr.v1_0.internal.ClinicalStatementRelationship
import org.opencds.vmr.v1_0.internal.EntityBase


global java.util.Date evalTime
global String clientLanguage
global String clientTimeZoneOffset
global String focalPersonId
global java.util.HashSet assertions
global java.util.HashMap namedObjects



//NOTE:  all demographics about the Patient are always returned in the result
//			when the result is an outputVMR.

//NOTE2:  all Entities that have a relationship to a ClinicalStatement or to another Entity
//			are always returned nested within that ClinicalStatement or Entity ONLY if that
//			ClinicalStatement or Entity (or org.drools.compiler.rule.builder.util.AccumulateUtilone of its ancestors) is flagged toBeReturned.

//NOTE3:  all Entities that are related directly to the patient will be returned or not
//			depending on the setting of the toBeReturned flag.

rule "BounceAllEntities"
	dialect "mvel"
	when
		$entityBase : EntityBase()
	then
		$entityBase.setToBeReturned( true );
end


rule "BounceAllClinicalStatements"
	dialect "mvel"
	when
		$cs : ClinicalStatement()
	then
		$cs.setToBeReturned( true );
end

rule "SetNestedAllClinicalStatements"
	dialect "mvel"
	when
		$cs : ClinicalStatement( clinicalStatementToBeRoot == true )
		$csr : ClinicalStatementRelationship( targetId == $cs.id )
	then
		$cs.setClinicalStatementToBeRoot( false );
end

