<?xml version="1.0" encoding="UTF-8"?>
<!-- 
 * #%L
 * org.hl7.fhir.r5
 * %%
 * Copyright (C) 2014 - 2019 Health Level 7
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

/*
  Copyright (c) 2011+, HL7, Inc.
  All rights reserved.
  
  Redistribution and use in source and binary forms, with or without modification, 
  are permitted provided that the following conditions are met:
  
   * Redistributions of source code must retain the above copyright notice, this 
     list of conditions and the following disclaimer.
   * Redistributions in binary form must reproduce the above copyright notice, 
     this list of conditions and the following disclaimer in the documentation 
     and/or other materials provided with the distribution.
   * Neither the name of HL7 nor the names of its contributors may be used to 
     endorse or promote products derived from this software without specific 
     prior written permission.
  
  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
  IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT 
  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
  POSSIBILITY OF SUCH DAMAGE.
  

  Generated on Tue, Apr 1, 2025 12:16+1100 for FHIR v6.0.0-ballot3 

  Note: the schemas &amp; schematrons do not contain all of the rules about what makes resources
  valid. Implementers will still need to be familiar with the content of the specification and with
  any profiles that apply to the resources in order to make a conformant implementation.

-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://hl7.org/fhir"
           targetNamespace="http://hl7.org/fhir" elementFormDefault="qualified" version="1.0">
    <xs:include schemaLocation="fhir-base.xsd"/>
    <xs:element name="ArtifactAssessment" type="ArtifactAssessment">
        <xs:annotation>
            <xs:documentation xml:lang="en">This Resource provides one or more comments, classifiers or ratings about a Resource and
                supports attribution and rights management metadata for the added content.
            </xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:complexType name="ArtifactAssessment">
        <xs:annotation>
            <xs:documentation xml:lang="en">This Resource provides one or more comments, classifiers or ratings about a Resource and
                supports attribution and rights management metadata for the added content.
            </xs:documentation>
            <xs:documentation xml:lang="en">If the element is present, it must have either a @value, an @id, or extensions
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="DomainResource">
                <xs:sequence>
                    <xs:element name="identifier" minOccurs="0" maxOccurs="unbounded" type="Identifier">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A formal identifier that is used to identify this artifact assessment
                                when it is represented in other formats, or referenced in a specification, model, design or an
                                instance.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="title" minOccurs="0" maxOccurs="1" type="string">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A label for use in displaying and selecting the artifact assessment.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="citeAs" minOccurs="0" maxOccurs="1" type="markdown">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Display of the bibliographic citation of the comment, classifier, or
                                rating.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:choice minOccurs="1" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A reference to a resource, canonical resource, or non-FHIR resource
                                which the comment or assessment is about.
                            </xs:documentation>
                        </xs:annotation>
                        <xs:element name="artifactReference" type="Reference"/>
                        <xs:element name="artifactCanonical" type="canonical"/>
                        <xs:element name="artifactUri" type="uri"/>
                    </xs:choice>
                    <xs:element name="relatesTo" type="ArtifactAssessment.RelatesTo" minOccurs="0" maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Relationship that this ArtifactAssessment has with other FHIR or
                                non-FHIR resources that already exist.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="date" minOccurs="0" maxOccurs="1" type="dateTime">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The date (and optionally time) when the artifact assessment was
                                published. The date must change when the disposition changes and it must change if the workflow
                                status code changes. In addition, it should change when the substantive content of the artifact
                                assessment changes.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="copyright" minOccurs="0" maxOccurs="1" type="markdown">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A copyright statement relating to the artifact assessment and/or its
                                contents. Copyright statements are generally legal restrictions on the use and publishing of the
                                artifact assessment.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="approvalDate" minOccurs="0" maxOccurs="1" type="date">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The date on which the resource content was approved by the publisher.
                                Approval happens once when the content is officially approved for usage.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="lastReviewDate" minOccurs="0" maxOccurs="1" type="date">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The date on which the resource content was last reviewed. Review happens
                                periodically after approval but does not change the original approval date.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="content" type="ArtifactAssessment.Content" minOccurs="0" maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A component comment, classifier, or rating of the artifact.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="workflowStatus" minOccurs="0" maxOccurs="1" type="ArtifactAssessmentWorkflowStatus">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Indicates the workflow status of the comment or change request.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="disposition" minOccurs="0" maxOccurs="1" type="ArtifactAssessmentDisposition">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Indicates the disposition of the responsible party to the comment or
                                change request.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="ArtifactAssessment.RelatesTo">
        <xs:annotation>
            <xs:documentation xml:lang="en">This Resource provides one or more comments, classifiers or ratings about a Resource and
                supports attribution and rights management metadata for the added content.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="type" minOccurs="1" maxOccurs="1" type="ArtifactRelationshipType">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The type of relationship to the related artifact.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:choice minOccurs="1" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The artifact that is related to this ArtifactAssessment Resource.
                            </xs:documentation>
                        </xs:annotation>
                        <xs:element name="targetUri" type="uri"/>
                        <xs:element name="targetAttachment" type="Attachment"/>
                        <xs:element name="targetCanonical" type="canonical"/>
                        <xs:element name="targetReference" type="Reference"/>
                        <xs:element name="targetMarkdown" type="markdown"/>
                    </xs:choice>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="ArtifactAssessment.Content">
        <xs:annotation>
            <xs:documentation xml:lang="en">This Resource provides one or more comments, classifiers or ratings about a Resource and
                supports attribution and rights management metadata for the added content.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="summary" minOccurs="0" maxOccurs="1" type="markdown">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A brief summary of the content of this component.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="type" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Indicates what type of content this component represents.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="classifier" minOccurs="0" maxOccurs="unbounded" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Represents a rating, classifier, or assessment of the artifact.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="quantity" minOccurs="0" maxOccurs="1" type="Quantity">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A quantitative rating of the artifact.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="author" minOccurs="0" maxOccurs="unbounded" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Indicates who or what authored the content.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="path" minOccurs="0" maxOccurs="unbounded" type="uri">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A URI that points to what the comment is about, such as a line of text
                                in the CQL, or a specific element in a resource.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="relatesTo" type="ArtifactAssessment.RelatesTo" minOccurs="0" maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Relationship that this content component has with other FHIR or non-FHIR
                                resources that already exist.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="freeToShare" minOccurs="0" maxOccurs="1" type="boolean">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Acceptable to publicly share the comment, classifier or rating.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="component" type="ArtifactAssessment.Content" minOccurs="0" maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A component comment, classifier, or rating of the artifact.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:simpleType name="ArtifactAssessmentDispositionEnum">
        <xs:restriction base="code-primitive">
            <xs:enumeration value="unresolved">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Unresolved</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="not-persuasive">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Not Persuasive</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="persuasive">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Persuasive</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="persuasive-with-modification">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Persuasive with Modification</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="not-persuasive-with-modification">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Not Persuasive with Modification</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="ArtifactAssessmentDisposition">
        <xs:annotation>
            <xs:documentation xml:lang="en"></xs:documentation>
            <xs:documentation xml:lang="en">If the element is present, it must have either a @value, an @id, or extensions
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="Element">
                <xs:attribute name="value" type="ArtifactAssessmentDispositionEnum" use="optional"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:simpleType name="ArtifactAssessmentWorkflowStatusEnum">
        <xs:restriction base="code-primitive">
            <xs:enumeration value="submitted">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Submitted</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="triaged">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Triaged</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="waiting-for-input">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Waiting for Input</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="resolved-no-change">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Resolved - No Change</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="resolved-change-required">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Resolved - Change Required</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="deferred">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Deferred</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="duplicate">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Duplicate</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="applied">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Applied</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="published">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Published</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="entered-in-error">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Entered in Error</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="ArtifactAssessmentWorkflowStatus">
        <xs:annotation>
            <xs:documentation xml:lang="en"></xs:documentation>
            <xs:documentation xml:lang="en">If the element is present, it must have either a @value, an @id, or extensions
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="Element">
                <xs:attribute name="value" type="ArtifactAssessmentWorkflowStatusEnum" use="optional"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:simpleType name="ArtifactRelationshipTypeEnum">
        <xs:restriction base="code-primitive">
            <xs:enumeration value="documentation">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Documentation</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="justification">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Justification</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="predecessor">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Predecessor</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="successor">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Successor</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="derived-from">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Derived From</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="depends-on">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Depends On</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="composed-of">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Composed Of</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="part-of">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Part Of</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="amends">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Amends</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="amended-with">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Amended With</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="appends">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Appends</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="appended-with">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Appended With</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="cites">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Cites</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="cited-by">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Cited By</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="comments-on">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Is Comment On</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="comment-in">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Has Comment In</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="contains">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Contains</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="contained-in">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Contained In</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="corrects">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Corrects</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="correction-in">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Correction In</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="replaces">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Replaces</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="replaced-with">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Replaced With</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="retracts">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Retracts</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="retracted-by">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Retracted By</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="signs">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Signs</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="similar-to">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Similar To</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="supports">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Supports</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="supported-with">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Supported With</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="transforms">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Transforms</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="transformed-into">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Transformed Into</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="transformed-with">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Transformed With</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="specification-of">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Specification Of</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="created-with">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Created With</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="cite-as">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Cite As</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="summarizes">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Summarizes</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="ArtifactRelationshipType">
        <xs:annotation>
            <xs:documentation xml:lang="en"></xs:documentation>
            <xs:documentation xml:lang="en">If the element is present, it must have either a @value, an @id, or extensions
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="Element">
                <xs:attribute name="value" type="ArtifactRelationshipTypeEnum" use="optional"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>
