<?xml version="1.0" encoding="UTF-8"?>
<!-- 
 * #%L
 * org.hl7.fhir.r5
 * %%
 * Copyright (C) 2014 - 2019 Health Level 7
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

/*
  Copyright (c) 2011+, HL7, Inc.
  All rights reserved.
  
  Redistribution and use in source and binary forms, with or without modification, 
  are permitted provided that the following conditions are met:
  
   * Redistributions of source code must retain the above copyright notice, this 
     list of conditions and the following disclaimer.
   * Redistributions in binary form must reproduce the above copyright notice, 
     this list of conditions and the following disclaimer in the documentation 
     and/or other materials provided with the distribution.
   * Neither the name of HL7 nor the names of its contributors may be used to 
     endorse or promote products derived from this software without specific 
     prior written permission.
  
  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
  IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT 
  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
  POSSIBILITY OF SUCH DAMAGE.
  

  Generated on Tue, Apr 1, 2025 12:16+1100 for FHIR v6.0.0-ballot3 

  Note: the schemas &amp; schematrons do not contain all of the rules about what makes resources
  valid. Implementers will still need to be familiar with the content of the specification and with
  any profiles that apply to the resources in order to make a conformant implementation.

-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://hl7.org/fhir"
           targetNamespace="http://hl7.org/fhir" elementFormDefault="qualified" version="1.0">
    <xs:include schemaLocation="fhir-base.xsd"/>
    <xs:element name="DetectedIssue" type="DetectedIssue">
        <xs:annotation>
            <xs:documentation xml:lang="en">Indicates an actual or potential clinical issue with or between one or more active or
                proposed clinical actions for a patient; e.g. Drug-drug interaction, Ineffective treatment frequency,
                Procedure-condition conflict, gaps in care, etc.
            </xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:complexType name="DetectedIssue">
        <xs:annotation>
            <xs:documentation xml:lang="en">Indicates an actual or potential clinical issue with or between one or more active or
                proposed clinical actions for a patient; e.g. Drug-drug interaction, Ineffective treatment frequency,
                Procedure-condition conflict, gaps in care, etc.
            </xs:documentation>
            <xs:documentation xml:lang="en">If the element is present, it must have either a @value, an @id, or extensions
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="DomainResource">
                <xs:sequence>
                    <xs:element name="identifier" minOccurs="0" maxOccurs="unbounded" type="Identifier">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Business identifiers assigned to this detected issue by the performer
                                and/or other systems. These identifiers remain constant as the resource is updated and propagates
                                from server to server.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="status" minOccurs="1" maxOccurs="1" type="DetectedIssueStatus">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The current state of the detected issue.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="category" minOccurs="0" maxOccurs="unbounded" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Partitions the detected issue into one or more categories that can be
                                used to filter searching, to govern access control and/or to guide system behavior.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="code" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A code that identifies the specific type of issue detected.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="severity" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Indicates the degree of importance associated with the identified issue
                                based on the potential impact on the patient.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="subject" minOccurs="0" maxOccurs="1" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Indicates the subject whose record the detected issue is associated
                                with.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="encounter" minOccurs="0" maxOccurs="1" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The Encounter during which this detected issue was created or to which
                                the creation of this record is tightly associated.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:choice minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The date, period or timing when the detected issue did occur or is
                                occurring.
                            </xs:documentation>
                        </xs:annotation>
                        <xs:element name="identifiedDateTime" type="dateTime"/>
                        <xs:element name="identifiedPeriod" type="Period"/>
                        <xs:element name="identifiedTiming" type="Timing"/>
                    </xs:choice>
                    <xs:element name="author" minOccurs="0" maxOccurs="1" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Individual or device responsible for the issue being raised. For
                                example, a decision support application or a pharmacist conducting a medication review.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="implicated" minOccurs="0" maxOccurs="unbounded" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Indicates the resource representing the current activity or proposed
                                activity that is potentially problematic.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="evidence" type="DetectedIssue.Evidence" minOccurs="0" maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Supporting evidence or manifestations that provide the basis for
                                identifying the detected issue such as a GuidanceResponse or MeasureReport.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="detail" minOccurs="0" maxOccurs="1" type="markdown">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A textual explanation of the detected issue.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="reference" minOccurs="0" maxOccurs="1" type="uri">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The literature, knowledge-base or similar reference that describes the
                                propensity for the detected issue identified.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="qualityOfEvidence" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The quality of the evidence supporting identification of the detected
                                issue. The code system used specifies the quality scale used to grade this evidence source while the
                                code specifies the actual quality score (represented as a coded value) associated with the evidence.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="managementCode" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">An indication of the importance or type of step that should or may be
                                taken in order to address the detected issue. This is different than mitigation in that it is not
                                specifically providing actions to be taken, rather general suggestions about approach.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="mitigation" type="DetectedIssue.Mitigation" minOccurs="0" maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Indicates an action that has been taken or is committed to reduce or
                                eliminate the likelihood of the risk identified by the detected issue from manifesting. Can also
                                reflect an observation of known mitigating factors that may reduce/eliminate the need for any
                                action.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="DetectedIssue.Evidence">
        <xs:annotation>
            <xs:documentation xml:lang="en">Indicates an actual or potential clinical issue with or between one or more active or
                proposed clinical actions for a patient; e.g. Drug-drug interaction, Ineffective treatment frequency,
                Procedure-condition conflict, gaps in care, etc.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="code" minOccurs="0" maxOccurs="unbounded" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A manifestation that led to the recording of this detected issue.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="detail" minOccurs="0" maxOccurs="unbounded" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Links to resources that constitute evidence for the detected issue such
                                as a GuidanceResponse or MeasureReport.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="DetectedIssue.Mitigation">
        <xs:annotation>
            <xs:documentation xml:lang="en">Indicates an actual or potential clinical issue with or between one or more active or
                proposed clinical actions for a patient; e.g. Drug-drug interaction, Ineffective treatment frequency,
                Procedure-condition conflict, gaps in care, etc.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="action" minOccurs="1" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Describes the action that was taken or the observation that was made
                                that reduces/eliminates the risk associated with the identified issue.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="date" minOccurs="0" maxOccurs="1" type="dateTime">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Indicates when the mitigating action was documented.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="author" minOccurs="0" maxOccurs="1" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Identifies the practitioner who determined the mitigation and takes
                                responsibility for the mitigation step occurring.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="note" minOccurs="0" maxOccurs="unbounded" type="Annotation">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Clinicians may add additional notes or justifications about the
                                mitigation action. For example, patient can have this drug because they have had it before without
                                any issues. Multiple justifications may be provided.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:simpleType name="DetectedIssueStatusEnum">
        <xs:restriction base="code-primitive">
            <xs:enumeration value="preliminary">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Preliminary</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="final">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Final</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="entered-in-error">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Entered in Error</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="unknown">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Unknwon</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="mitigated">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Mitigated</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="DetectedIssueStatus">
        <xs:annotation>
            <xs:documentation xml:lang="en"></xs:documentation>
            <xs:documentation xml:lang="en">If the element is present, it must have either a @value, an @id, or extensions
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="Element">
                <xs:attribute name="value" type="DetectedIssueStatusEnum" use="optional"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>
