<?xml version="1.0" encoding="UTF-8"?>
<!-- 
 * #%L
 * org.hl7.fhir.r5
 * %%
 * Copyright (C) 2014 - 2019 Health Level 7
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

/*
  Copyright (c) 2011+, HL7, Inc.
  All rights reserved.
  
  Redistribution and use in source and binary forms, with or without modification, 
  are permitted provided that the following conditions are met:
  
   * Redistributions of source code must retain the above copyright notice, this 
     list of conditions and the following disclaimer.
   * Redistributions in binary form must reproduce the above copyright notice, 
     this list of conditions and the following disclaimer in the documentation 
     and/or other materials provided with the distribution.
   * Neither the name of HL7 nor the names of its contributors may be used to 
     endorse or promote products derived from this software without specific 
     prior written permission.
  
  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
  IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT 
  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
  POSSIBILITY OF SUCH DAMAGE.
  

  Generated on Tue, Apr 1, 2025 12:16+1100 for FHIR v6.0.0-ballot3 

  Note: the schemas &amp; schematrons do not contain all of the rules about what makes resources
  valid. Implementers will still need to be familiar with the content of the specification and with
  any profiles that apply to the resources in order to make a conformant implementation.

-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://hl7.org/fhir"
           targetNamespace="http://hl7.org/fhir" elementFormDefault="qualified" version="1.0">
    <xs:include schemaLocation="fhir-base.xsd"/>
    <xs:element name="DeviceMetric" type="DeviceMetric">
        <xs:annotation>
            <xs:documentation xml:lang="en">Describes a measurement, calculation or setting capability of a device.
            </xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:complexType name="DeviceMetric">
        <xs:annotation>
            <xs:documentation xml:lang="en">Describes a measurement, calculation or setting capability of a device.
            </xs:documentation>
            <xs:documentation xml:lang="en">If the element is present, it must have either a @value, an @id, or extensions
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="DomainResource">
                <xs:sequence>
                    <xs:element name="identifier" minOccurs="0" maxOccurs="unbounded" type="Identifier">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Instance identifiers assigned to a device, by the device or gateway
                                software, manufacturers, other organizations or owners. For example, handle ID.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="type" minOccurs="1" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Describes the type of the metric. For example: Heart Rate, PEEP Setting,
                                etc.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="unit" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Describes the unit that an observed value determined for this metric
                                will have. For example: Percent, Seconds, etc.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="device" minOccurs="1" maxOccurs="1" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Describes the link to the Device. This is also known as a channel
                                device.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="operationalStatus" minOccurs="0" maxOccurs="1" type="DeviceMetricOperationalStatus">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Indicates current operational state of the device. For example: On, Off,
                                Standby, etc.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="color" minOccurs="0" maxOccurs="1" type="ColorCodesOrRGB">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The preferred color associated with the metric (e.g., display color).
                                This is often used to aid clinicians to track and identify parameter types by color. In practice,
                                consider a Patient Monitor that has ECG/HR and Pleth; the metrics are displayed in different
                                characteristic colors, such as HR in blue, BP in green, and PR and SpO2 in magenta.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="category" minOccurs="1" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Indicates the category of the observation generation process. A
                                DeviceMetric can be, for example, a setting, measurement, or calculation.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="measurementFrequency" minOccurs="0" maxOccurs="1" type="Quantity">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The frequency at which the metric is taken or recorded. Devices measure
                                metrics at a wide range of frequencies; for example, an ECG might sample measurements in the
                                millisecond range, while an NIBP might trigger only once an hour. Less often, the
                                measurementFrequency may be based on a unit other than time, such as distance (e.g. for a measuring
                                wheel). The update period may be different than the measurement frequency, if the device does not
                                update the published observed value with the same frequency as it was measured.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="calibration" type="DeviceMetric.Calibration" minOccurs="0" maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Describes the calibrations that have been performed or that are required
                                to be performed.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="DeviceMetric.Calibration">
        <xs:annotation>
            <xs:documentation xml:lang="en">Describes a measurement, calculation or setting capability of a device.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="type" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Describes the type of the calibration method.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="state" minOccurs="0" maxOccurs="1" type="DeviceMetricCalibrationState">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Describes the state of the calibration.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="time" minOccurs="0" maxOccurs="1" type="instant">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Describes the time last calibration has been performed.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:simpleType name="ColorCodesOrRGBEnum">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:pattern value="[\s\S]+"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="ColorCodesOrRGB">
        <xs:annotation>
            <xs:documentation xml:lang="en"></xs:documentation>
            <xs:documentation xml:lang="en">If the element is present, it must have either a @value, an @id, or extensions
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="Element">
                <xs:attribute name="value" type="ColorCodesOrRGBEnum" use="optional"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:simpleType name="DeviceMetricCalibrationStateEnum">
        <xs:restriction base="code-primitive">
            <xs:enumeration value="not-calibrated">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Not Calibrated</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="calibration-required">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Calibration Required</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="calibrated">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Calibrated</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="unspecified">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Unspecified</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="DeviceMetricCalibrationState">
        <xs:annotation>
            <xs:documentation xml:lang="en"></xs:documentation>
            <xs:documentation xml:lang="en">If the element is present, it must have either a @value, an @id, or extensions
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="Element">
                <xs:attribute name="value" type="DeviceMetricCalibrationStateEnum" use="optional"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:simpleType name="DeviceMetricOperationalStatusEnum">
        <xs:restriction base="code-primitive">
            <xs:enumeration value="on">
                <xs:annotation>
                    <xs:documentation xml:lang="en">On</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="off">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Off</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="standby">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Standby</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="entered-in-error">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Entered In Error</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="DeviceMetricOperationalStatus">
        <xs:annotation>
            <xs:documentation xml:lang="en"></xs:documentation>
            <xs:documentation xml:lang="en">If the element is present, it must have either a @value, an @id, or extensions
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="Element">
                <xs:attribute name="value" type="DeviceMetricOperationalStatusEnum" use="optional"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>
