<?xml version="1.0" encoding="UTF-8"?>
<!-- 
 * #%L
 * org.hl7.fhir.r5
 * %%
 * Copyright (C) 2014 - 2019 Health Level 7
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

/*
  Copyright (c) 2011+, HL7, Inc.
  All rights reserved.
  
  Redistribution and use in source and binary forms, with or without modification, 
  are permitted provided that the following conditions are met:
  
   * Redistributions of source code must retain the above copyright notice, this 
     list of conditions and the following disclaimer.
   * Redistributions in binary form must reproduce the above copyright notice, 
     this list of conditions and the following disclaimer in the documentation 
     and/or other materials provided with the distribution.
   * Neither the name of HL7 nor the names of its contributors may be used to 
     endorse or promote products derived from this software without specific 
     prior written permission.
  
  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
  IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT 
  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
  POSSIBILITY OF SUCH DAMAGE.
  

  Generated on Tue, Apr 1, 2025 12:16+1100 for FHIR v6.0.0-ballot3 

  Note: the schemas &amp; schematrons do not contain all of the rules about what makes resources
  valid. Implementers will still need to be familiar with the content of the specification and with
  any profiles that apply to the resources in order to make a conformant implementation.

-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://hl7.org/fhir"
           targetNamespace="http://hl7.org/fhir" elementFormDefault="qualified" version="1.0">
    <xs:include schemaLocation="fhir-base.xsd"/>
    <xs:element name="EvidenceVariable" type="EvidenceVariable">
        <xs:annotation>
            <xs:documentation xml:lang="en">The EvidenceVariable resource describes an element that knowledge (Evidence) is about.
            </xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:complexType name="EvidenceVariable">
        <xs:annotation>
            <xs:documentation xml:lang="en">The EvidenceVariable resource describes an element that knowledge (Evidence) is about.
            </xs:documentation>
            <xs:documentation xml:lang="en">If the element is present, it must have either a @value, an @id, or extensions
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="MetadataResource">
                <xs:sequence>
                    <xs:element name="url" minOccurs="0" maxOccurs="1" type="uri">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">An absolute URI that is used to identify this evidence variable when it
                                is referenced in a specification, model, design or an instance; also called its canonical
                                identifier. This SHOULD be globally unique and SHOULD be a literal address at which an authoritative
                                instance of this evidence variable is (or will be) published. This URL can be the target of a
                                canonical reference. It SHALL remain the same when the evidence variable is stored on different
                                servers.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="identifier" minOccurs="0" maxOccurs="unbounded" type="Identifier">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A formal identifier that is used to identify this evidence variable when
                                it is represented in other formats, or referenced in a specification, model, design or an instance.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="version" minOccurs="0" maxOccurs="1" type="string">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The identifier that is used to identify this version of the evidence
                                variable when it is referenced in a specification, model, design or instance. This is an arbitrary
                                value managed by the evidence variable author and is not expected to be globally unique. For
                                example, it might be a timestamp (e.g. yyyymmdd) if a managed version is not available. There is
                                also no expectation that versions can be placed in a lexicographical sequence. To provide a version
                                consistent with the Decision Support Service specification, use the format Major.Minor.Revision
                                (e.g. 1.0.0). For more information on versioning knowledge assets, refer to the Decision Support
                                Service specification. Note that a version is required for non-experimental active artifacts.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:choice minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Indicates the mechanism used to compare versions to determine which is
                                more current.
                            </xs:documentation>
                        </xs:annotation>
                        <xs:element name="versionAlgorithmString" type="string"/>
                        <xs:element name="versionAlgorithmCoding" type="Coding"/>
                    </xs:choice>
                    <xs:element name="name" minOccurs="0" maxOccurs="1" type="string">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A natural language name identifying the evidence variable. This name
                                should be usable as an identifier for the module by machine processing applications such as code
                                generation.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="title" minOccurs="0" maxOccurs="1" type="string">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A short, descriptive, user-friendly title for the evidence variable.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="shortTitle" minOccurs="0" maxOccurs="1" type="string">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The short title provides an alternate title for use in informal
                                descriptive contexts where the full, formal title is not necessary.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="citeAs" minOccurs="0" maxOccurs="1" type="markdown">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Display of the suggested method of how to cite this EvidenceVariable.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="status" minOccurs="1" maxOccurs="1" type="PublicationStatus">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The status of this EvidenceVariable. Enables tracking the life-cycle of
                                the content.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="experimental" minOccurs="0" maxOccurs="1" type="boolean">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A Boolean value to indicate that this resource is authored for testing
                                purposes (or education/evaluation/marketing) and no version of this resource will ever be intended
                                for genuine usage.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="date" minOccurs="0" maxOccurs="1" type="dateTime">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The date (and optionally time) when the evidence variable was last
                                significantly changed. The date must change when the business version changes and it must change if
                                the status code changes. In addition, it should change when the substantive content of the evidence
                                variable changes.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="author" minOccurs="0" maxOccurs="unbounded" type="ContactDetail">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">An individiual or organization primarily involved in the creation and
                                maintenance of the content.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="publisher" minOccurs="0" maxOccurs="1" type="string">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The name of the organization or individual responsible for the release
                                and ongoing maintenance of the evidence variable.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="contact" minOccurs="0" maxOccurs="unbounded" type="ContactDetail">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Contact details to assist a user in finding and communicating with the
                                publisher.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="recorder" minOccurs="0" maxOccurs="unbounded" type="ContactDetail">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The person or entity that entered the data into the EvidenceVariable
                                Resource instance, if different than the author or creator of the intellectual property contained
                                within the EvidenceVariable Resource instance.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="editor" minOccurs="0" maxOccurs="unbounded" type="ContactDetail">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">An individual or organization primarily responsible for internal
                                coherence of the content.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="reviewer" minOccurs="0" maxOccurs="unbounded" type="ContactDetail">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">An individual or organization asserted by the publisher to be primarily
                                responsible for review of some aspect of the content.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="endorser" minOccurs="0" maxOccurs="unbounded" type="ContactDetail">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">An individual or organization asserted by the publisher to be
                                responsible for officially endorsing the content for use in some setting.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="description" minOccurs="0" maxOccurs="1" type="markdown">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A natural language summary of the evidence variable.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="note" minOccurs="0" maxOccurs="unbounded" type="Annotation">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A human-readable string to clarify or explain concepts about the
                                resource.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="useContext" minOccurs="0" maxOccurs="unbounded" type="UsageContext">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The content was developed with a focus and intent of supporting the
                                contexts that are listed. These contexts may be general categories (gender, age, ...) or may be
                                references to specific programs (insurance plans, studies, ...) and may be used to assist with
                                indexing and searching for appropriate evidence variable instances.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="purpose" minOccurs="0" maxOccurs="1" type="markdown">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Explanation of why this EvidenceVariable is needed and why it has been
                                designed as it has.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="copyright" minOccurs="0" maxOccurs="1" type="markdown">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A copyright statement relating to the EvidenceVariable and/or its
                                contents. Copyright statements are legal notices of intellectual property ownership and may include
                                restrictions on the use and publishing of the EvidenceVariable.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="copyrightLabel" minOccurs="0" maxOccurs="1" type="string">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A short string (&lt;50 characters), suitable for inclusion in a page
                                footer that identifies the copyright holder, effective period, and optionally whether rights are
                                restricted . (e.g. 'All rights reserved', 'Some rights reserved').
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="approvalDate" minOccurs="0" maxOccurs="1" type="date">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The date on which the resource content was approved by the publisher.
                                Approval happens once when the content is officially approved for usage.

                                See guidance around (not) making local changes to elements
                                [here](canonicalresource.html#localization).
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="lastReviewDate" minOccurs="0" maxOccurs="1" type="date">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The date on which the resource content was last reviewed. Review happens
                                periodically after approval but does not change the original approval date.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="effectivePeriod" minOccurs="0" maxOccurs="1" type="Period">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The period during which the resource content was or is planned to be in
                                active use.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="relatesTo" type="EvidenceVariable.RelatesTo" minOccurs="0" maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Relationships that this EvidenceVariable has with other FHIR or non-FHIR
                                resources that already exist.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="actual" minOccurs="0" maxOccurs="1" type="boolean">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">True if the actual variable measured, false if a conceptual
                                representation of the intended variable.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="definition" minOccurs="0" maxOccurs="1" type="CodeableReference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The meaning of the evidence variable.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="definitionModifier" type="EvidenceVariable.DefinitionModifier" minOccurs="0"
                                maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Further specification of the definition.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="handling" minOccurs="0" maxOccurs="1" type="EvidenceVariableHandling">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The method of handling in statistical analysis.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="category" type="EvidenceVariable.Category" minOccurs="0" maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A grouping for dichotomous, ordinal, or polychotomouos variables.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="conditional" minOccurs="0" maxOccurs="1" type="Expression">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The context, situation, or parameters that determine whether the data is
                                obtained to determine the value of the variable.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="classifier" minOccurs="0" maxOccurs="unbounded" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Classification of the variable.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="dataStorage" type="EvidenceVariable.DataStorage" minOccurs="0" maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">How the data element is organized and where the data element (expressing
                                the value of the variable) is found in the dataset.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="timing" minOccurs="0" maxOccurs="1" type="RelativeTime">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">When the variable is observed in relation to a reference point in time
                                defined by context or event.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="period" minOccurs="0" maxOccurs="1" type="Period">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">When the variable is observed in relation to calendar dates and times.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="constraint" type="EvidenceVariable.Constraint" minOccurs="0" maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Limit on acceptability of data used to express values of the variable.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="missingDataMeaning" minOccurs="0" maxOccurs="unbounded" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A method or transformation applied for missing data.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="unacceptableDataHandling" minOccurs="0" maxOccurs="unbounded" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A method or transformation applied for data that does not match required
                                patterns.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="EvidenceVariable.RelatesTo">
        <xs:annotation>
            <xs:documentation xml:lang="en">The EvidenceVariable resource describes an element that knowledge (Evidence) is about.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="type" minOccurs="1" maxOccurs="1" type="ArtifactRelationshipType">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The type of relationship to the related artifact.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:choice minOccurs="1" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The artifact that is related to this EvidenceVariable Resource.
                            </xs:documentation>
                        </xs:annotation>
                        <xs:element name="targetUri" type="uri"/>
                        <xs:element name="targetAttachment" type="Attachment"/>
                        <xs:element name="targetCanonical" type="canonical"/>
                        <xs:element name="targetReference" type="Reference"/>
                        <xs:element name="targetMarkdown" type="markdown"/>
                    </xs:choice>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="EvidenceVariable.DefinitionModifier">
        <xs:annotation>
            <xs:documentation xml:lang="en">The EvidenceVariable resource describes an element that knowledge (Evidence) is about.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="code" minOccurs="1" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Attribute of the definition.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:choice minOccurs="1" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Specification of the definition attribute.</xs:documentation>
                        </xs:annotation>
                        <xs:element name="valueCodeableConcept" type="CodeableConcept"/>
                        <xs:element name="valueBoolean" type="boolean"/>
                        <xs:element name="valueQuantity" type="Quantity"/>
                        <xs:element name="valueRange" type="Range"/>
                        <xs:element name="valuePeriod" type="Period"/>
                        <xs:element name="valueRelativeTime" type="RelativeTime"/>
                        <xs:element name="valueReference" type="Reference"/>
                        <xs:element name="valueExpression" type="Expression"/>
                        <xs:element name="valueUri" type="uri"/>
                    </xs:choice>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="EvidenceVariable.Category">
        <xs:annotation>
            <xs:documentation xml:lang="en">The EvidenceVariable resource describes an element that knowledge (Evidence) is about.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="name" minOccurs="0" maxOccurs="1" type="string">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Description of the grouping.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:choice minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Definition of the grouping.</xs:documentation>
                        </xs:annotation>
                        <xs:element name="valueCodeableConcept" type="CodeableConcept"/>
                        <xs:element name="valueQuantity" type="Quantity"/>
                        <xs:element name="valueRange" type="Range"/>
                        <xs:element name="valueReference" type="Reference"/>
                    </xs:choice>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="EvidenceVariable.DataStorage">
        <xs:annotation>
            <xs:documentation xml:lang="en">The EvidenceVariable resource describes an element that knowledge (Evidence) is about.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="datatype" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The type of data used to express values of the variable.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="path" minOccurs="0" maxOccurs="1" type="string">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The mapping (order of elements) to reach the element containing the data
                                element in the dataset.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="delimiter" minOccurs="0" maxOccurs="1" type="string">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A character or series of characters that is used within a string to
                                signal the separation of discrete values.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="component" type="EvidenceVariable.DataStorage" minOccurs="0" maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A part of the value for a variable that is stored in 2 or more parts.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="EvidenceVariable.Constraint">
        <xs:annotation>
            <xs:documentation xml:lang="en">The EvidenceVariable resource describes an element that knowledge (Evidence) is about.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="conditional" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The context, situation, or parameters that determine whether this
                                constraint applies.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="minimumQuantity" minOccurs="0" maxOccurs="1" type="Quantity">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The lowest permissible value of the variable, used with variables that
                                have a number-based datatype (with or without units).
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="maximumQuantity" minOccurs="0" maxOccurs="1" type="Quantity">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The highest permissible value of the variable, used with variables that
                                have a number-based datatype (with or without units).
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="earliestDateTime" minOccurs="0" maxOccurs="1" type="dateTime">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The earliest permissible value of the variable, used with variables that
                                have a date-based or dateTime-based datatype.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="latestDateTime" minOccurs="0" maxOccurs="1" type="dateTime">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The latest permissible value of the variable, used with variables that
                                have a date-based or dateTime-based datatype.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="minimumStringLength" minOccurs="0" maxOccurs="1" type="unsignedInt">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The lowest number of characters allowed for a value of the variable,
                                used with variables that have a string-based datatype.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="maximumStringLength" minOccurs="0" maxOccurs="1" type="positiveInt">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The highest number of characters allowed for a value of the variable,
                                used with variables that have a string-based datatype.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="code" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A rule, such as a format or other expectation, for the data values.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="expression" minOccurs="0" maxOccurs="1" type="Expression">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A rule, such as a format or other expectation, for the data values,
                                expressed as an Expression.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="expectedValueSet" minOccurs="0" maxOccurs="1" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">List of anticipated values used to express value of the variable, used
                                with variables that have a codeable concept-based datatype.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="expectedUnitsValueSet" minOccurs="0" maxOccurs="1" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">List of anticipated values used to express units for the value of the
                                variable, used with variables that have a Quantity-based datatype.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="anyValueAllowed" minOccurs="0" maxOccurs="1" type="boolean">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Whether the value expressed for a variable is allowed to not be
                                restricted to the expected value set.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>
