<?xml version="1.0" encoding="UTF-8"?>
<!-- 
 * #%L
 * org.hl7.fhir.r5
 * %%
 * Copyright (C) 2014 - 2019 Health Level 7
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

/*
  Copyright (c) 2011+, HL7, Inc.
  All rights reserved.
  
  Redistribution and use in source and binary forms, with or without modification, 
  are permitted provided that the following conditions are met:
  
   * Redistributions of source code must retain the above copyright notice, this 
     list of conditions and the following disclaimer.
   * Redistributions in binary form must reproduce the above copyright notice, 
     this list of conditions and the following disclaimer in the documentation 
     and/or other materials provided with the distribution.
   * Neither the name of HL7 nor the names of its contributors may be used to 
     endorse or promote products derived from this software without specific 
     prior written permission.
  
  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
  IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT 
  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
  POSSIBILITY OF SUCH DAMAGE.
  

  Generated on Tue, Apr 1, 2025 12:16+1100 for FHIR v6.0.0-ballot3 

  Note: the schemas &amp; schematrons do not contain all of the rules about what makes resources
  valid. Implementers will still need to be familiar with the content of the specification and with
  any profiles that apply to the resources in order to make a conformant implementation.

-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://hl7.org/fhir"
           targetNamespace="http://hl7.org/fhir" elementFormDefault="qualified" version="1.0">
    <xs:include schemaLocation="fhir-base.xsd"/>
    <xs:element name="Group" type="Group">
        <xs:annotation>
            <xs:documentation xml:lang="en">Represents a defined collection of entities that may be discussed or acted upon
                collectively but which are not typically expected to act collectively. These collections are also not typically
                formally or legally recognized.

                NOTE: Group may be used to define families or households, which in some circumstances may act collectively or have a
                degree of legal or formal recognition. This should be considered an exception. When Group is used for types of
                entities other than Patient or RelatedPerson, the expectation remains that the Group will not act collectively or
                have formal recognition - use Organization if these behaviors are needed.

                For example, it is possible for a 'family' Group to be a performer of an Observation or owner of a Task. However,
                this is not permitted for a Group made up of Practitioners, PractitionerRoles or Organizations. Organization or
                CareTeam would need to be used instead. A Group of Practitioners could, however, be a subject of an Observation.
            </xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:complexType name="Group">
        <xs:annotation>
            <xs:documentation xml:lang="en">Represents a defined collection of entities that may be discussed or acted upon
                collectively but which are not typically expected to act collectively. These collections are also not typically
                formally or legally recognized.

                NOTE: Group may be used to define families or households, which in some circumstances may act collectively or have a
                degree of legal or formal recognition. This should be considered an exception. When Group is used for types of
                entities other than Patient or RelatedPerson, the expectation remains that the Group will not act collectively or
                have formal recognition - use Organization if these behaviors are needed.

                For example, it is possible for a 'family' Group to be a performer of an Observation or owner of a Task. However,
                this is not permitted for a Group made up of Practitioners, PractitionerRoles or Organizations. Organization or
                CareTeam would need to be used instead. A Group of Practitioners could, however, be a subject of an Observation.
            </xs:documentation>
            <xs:documentation xml:lang="en">If the element is present, it must have either a @value, an @id, or extensions
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="CanonicalResource">
                <xs:sequence>
                    <xs:element name="url" minOccurs="0" maxOccurs="1" type="uri">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">An absolute URI that is used to identify this Group when it is
                                referenced in a specification, model, design or an instance; also called its canonical identifier.
                                This SHOULD be globally unique and SHOULD be a literal address at which an authoritative instance of
                                this Group is (or will be) published. This URL can be the target of a canonical reference. It SHALL
                                remain the same when the Group is stored on different servers.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="identifier" minOccurs="0" maxOccurs="unbounded" type="Identifier">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Business identifiers assigned to this participant by one of the
                                applications involved. These identifiers remain constant as the resource is updated and propagates
                                from server to server.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="version" minOccurs="0" maxOccurs="1" type="string">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The identifier that is used to identify this version of the Group when
                                it is referenced in a specification, model, design or instance. This is an arbitrary value managed
                                by the Group author and is not expected to be globally unique. For example, it might be a timestamp
                                (e.g. yyyymmdd) if a managed version is not available. There is also no expectation that versions
                                can be placed in a lexicographical sequence without additional knowledge.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:choice minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Indicates the mechanism used to compare versions to determine which is
                                more current.
                            </xs:documentation>
                        </xs:annotation>
                        <xs:element name="versionAlgorithmString" type="string"/>
                        <xs:element name="versionAlgorithmCoding" type="Coding"/>
                    </xs:choice>
                    <xs:element name="name" minOccurs="0" maxOccurs="1" type="string">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A label assigned to the group for human identification and
                                communication.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="title" minOccurs="0" maxOccurs="1" type="string">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A short, descriptive, user-friendly title for the Group.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="status" minOccurs="0" maxOccurs="1" type="PublicationStatus">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The current state of this Group.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="experimental" minOccurs="0" maxOccurs="1" type="boolean">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A Boolean value to indicate that this Group is authored for testing
                                purposes (or education/evaluation/marketing) and no version of this resource will ever be intended
                                for genuine usage.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="date" minOccurs="0" maxOccurs="1" type="dateTime">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The date (and optionally time) when the Group was last significantly
                                changed. The date must change when the business version changes and it must change if the status
                                code changes. In addition, it should change when the substantive content of the Group changes.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="publisher" minOccurs="0" maxOccurs="1" type="string">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The name of the organization or individual responsible for the release
                                and ongoing maintenance of the Group.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="contact" minOccurs="0" maxOccurs="unbounded" type="ContactDetail">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Contact details to assist a user in finding and communicating with the
                                publisher.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="description" minOccurs="0" maxOccurs="1" type="markdown">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Explanation of what the group represents and how it is intended to be
                                used.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="useContext" minOccurs="0" maxOccurs="unbounded" type="UsageContext">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The content was developed with a focus and intent of supporting the
                                contexts that are listed. These contexts may be general categories (gender, age, ...) or may be
                                references to specific programs (insurance plans, studies, ...) and may be used to assist with
                                indexing and searching for appropriate Groups.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="purpose" minOccurs="0" maxOccurs="1" type="markdown">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Explanation of why this Group is needed and why it has been designed as
                                it has.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="copyright" minOccurs="0" maxOccurs="1" type="markdown">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A copyright statement relating to the Group and/or its contents.
                                Copyright statements are generally legal restrictions on the use and publishing of the Group.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="copyrightLabel" minOccurs="0" maxOccurs="1" type="string">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A short string (&lt;50 characters), suitable for inclusion in a page
                                footer that identifies the copyright holder, effective period, and optionally whether rights are
                                resctricted. (e.g. 'All rights reserved', 'Some rights reserved').
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="type" minOccurs="0" maxOccurs="1" type="GroupType">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Identifies the broad classification of the kind of resources the group
                                includes.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="membership" minOccurs="1" maxOccurs="1" type="GroupMembershipBasis">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Basis for membership in the Group:

                                * 'definitional': The Group.characteristics specified are both necessary and sufficient to determine
                                membership. All entities that meet the criteria are considered to be members of the group, whether
                                referenced by the group or not. If members are present, they are individuals that happen to be known
                                as meeting the Group.characteristics. The list cannot be presumed to be complete.
                                * 'conceptual': The Group.characteristics specified are both necessary and sufficient to determine
                                membership. The 'conceptual' Group is a 'definitional' Group in which the Group.type is not bound to
                                FHIR types.
                                * 'enumerated': The Group.characteristics are necessary but not sufficient to determine membership.
                                Membership is determined by being listed as one of the Group.member.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="code" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A code that describes the use of the group. The use of the group usually
                                dictates what kind of entities can be members of the group.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="quantity" minOccurs="0" maxOccurs="1" type="unsignedInt">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A count of the number of resource instances that are part of the
                                group.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="managingEntity" minOccurs="0" maxOccurs="1" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Entity responsible for defining and maintaining Group characteristics
                                and/or registered members.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="combinationMethod" minOccurs="0" maxOccurs="1" type="GroupCharacteristicCombination">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Used to specify how two or more characteristics are combined.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="combinationThreshold" minOccurs="0" maxOccurs="1" type="positiveInt">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Provides the value of &quot;n&quot; when &quot;at-least&quot; or &quot;at-most&quot;
                                codes are used for combinationMethod.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="characteristic" type="Group.Characteristic" minOccurs="0" maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Identifies traits whose presence r absence is shared by members of the
                                group.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="member" type="Group.Member" minOccurs="0" maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Identifies the resource instances that are members of the group.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="Group.Characteristic">
        <xs:annotation>
            <xs:documentation xml:lang="en">Represents a defined collection of entities that may be discussed or acted upon
                collectively but which are not typically expected to act collectively. These collections are also not typically
                formally or legally recognized.

                NOTE: Group may be used to define families or households, which in some circumstances may act collectively or have a
                degree of legal or formal recognition. This should be considered an exception. When Group is used for types of
                entities other than Patient or RelatedPerson, the expectation remains that the Group will not act collectively or
                have formal recognition - use Organization if these behaviors are needed.

                For example, it is possible for a 'family' Group to be a performer of an Observation or owner of a Task. However,
                this is not permitted for a Group made up of Practitioners, PractitionerRoles or Organizations. Organization or
                CareTeam would need to be used instead. A Group of Practitioners could, however, be a subject of an Observation.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="code" minOccurs="1" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A code that identifies the kind of trait being asserted.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:choice minOccurs="1" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The value of the trait that holds (or does not hold - see 'exclude') for
                                members of the group.
                            </xs:documentation>
                        </xs:annotation>
                        <xs:element name="valueCodeableConcept" type="CodeableConcept"/>
                        <xs:element name="valueBoolean" type="boolean"/>
                        <xs:element name="valueQuantity" type="Quantity"/>
                        <xs:element name="valueRange" type="Range"/>
                        <xs:element name="valueReference" type="Reference"/>
                        <xs:element name="valueUri" type="uri"/>
                        <xs:element name="valueExpression" type="Expression"/>
                    </xs:choice>
                    <xs:element name="exclude" minOccurs="1" maxOccurs="1" type="boolean">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">If true, indicates the characteristic is one that is NOT held by members
                                of the group.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="description" minOccurs="0" maxOccurs="1" type="markdown">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A short, natural language description of the characteristic that could
                                be used to communicate the criteria to an end-user.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="method" minOccurs="0" maxOccurs="unbounded" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Method for how the characteristic value was determined.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:choice minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Defines the characteristic (without using type and value) by either a
                                Reference or an Expression.
                            </xs:documentation>
                        </xs:annotation>
                        <xs:element name="determinedByReference" type="Reference"/>
                        <xs:element name="determinedByExpression" type="Expression"/>
                    </xs:choice>
                    <xs:element name="offset" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Defines the reference point for comparison when other than 0.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:choice minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Number of occurrences meeting the characteristic.</xs:documentation>
                        </xs:annotation>
                        <xs:element name="instancesUnsignedInt" type="unsignedInt"/>
                        <xs:element name="instancesRange" type="Range"/>
                    </xs:choice>
                    <xs:choice minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Length of time in which the characteristic is met.</xs:documentation>
                        </xs:annotation>
                        <xs:element name="durationDuration" type="Duration"/>
                        <xs:element name="durationRange" type="Range"/>
                    </xs:choice>
                    <xs:element name="period" minOccurs="0" maxOccurs="1" type="Period">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The period over which the characteristic is tested; e.g. the patient had
                                an operation during the month of June.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="timing" minOccurs="0" maxOccurs="unbounded" type="RelativeTime">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Timing in which the characteristic is determined.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="Group.Member">
        <xs:annotation>
            <xs:documentation xml:lang="en">Represents a defined collection of entities that may be discussed or acted upon
                collectively but which are not typically expected to act collectively. These collections are also not typically
                formally or legally recognized.

                NOTE: Group may be used to define families or households, which in some circumstances may act collectively or have a
                degree of legal or formal recognition. This should be considered an exception. When Group is used for types of
                entities other than Patient or RelatedPerson, the expectation remains that the Group will not act collectively or
                have formal recognition - use Organization if these behaviors are needed.

                For example, it is possible for a 'family' Group to be a performer of an Observation or owner of a Task. However,
                this is not permitted for a Group made up of Practitioners, PractitionerRoles or Organizations. Organization or
                CareTeam would need to be used instead. A Group of Practitioners could, however, be a subject of an Observation.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="entity" minOccurs="1" maxOccurs="1" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A reference to the entity that is a member of the group. Must be
                                consistent with Group.type. If the entity is another group, then the type must be the same.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="involvement" minOccurs="0" maxOccurs="unbounded" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A code that describes how a user is involved in the group. Some groups
                                (e.g. exposure-group) typically don't have variance between members, or it is not tracked, while for
                                other groups (e.g. family, household) this may be meaningful.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="period" minOccurs="0" maxOccurs="1" type="Period">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The period that the member was in the group, if known.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="inactive" minOccurs="0" maxOccurs="1" type="boolean">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A flag to indicate that the member is no longer in the group, but
                                previously may have been a member.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:simpleType name="GroupTypeEnum">
        <xs:restriction base="code-primitive">
            <xs:enumeration value="person">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Person</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="animal">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Animal</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="practitioner">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Practitioner</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="device">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Device</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="careteam">
                <xs:annotation>
                    <xs:documentation xml:lang="en">CareTeam</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="healthcareservice">
                <xs:annotation>
                    <xs:documentation xml:lang="en">HealthcareService</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="location">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Location</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="organization">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Organization</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="relatedperson">
                <xs:annotation>
                    <xs:documentation xml:lang="en">RelatedPerson</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="specimen">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Specimen</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="medication">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Medication</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="substance">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Substance</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="biologicallyDerivedProduct">
                <xs:annotation>
                    <xs:documentation xml:lang="en">BiologicallyDerivedProduct</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="nutritionProduct">
                <xs:annotation>
                    <xs:documentation xml:lang="en">NutritionProduct</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="GroupType">
        <xs:annotation>
            <xs:documentation xml:lang="en"></xs:documentation>
            <xs:documentation xml:lang="en">If the element is present, it must have either a @value, an @id, or extensions
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="Element">
                <xs:attribute name="value" type="GroupTypeEnum" use="optional"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:simpleType name="GroupMembershipBasisEnum">
        <xs:restriction base="code-primitive">
            <xs:enumeration value="definitional">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Definitional</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="conceptual">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Conceptual</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="enumerated">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Enumerated</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="GroupMembershipBasis">
        <xs:annotation>
            <xs:documentation xml:lang="en"></xs:documentation>
            <xs:documentation xml:lang="en">If the element is present, it must have either a @value, an @id, or extensions
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="Element">
                <xs:attribute name="value" type="GroupMembershipBasisEnum" use="optional"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:simpleType name="GroupCharacteristicCombinationEnum">
        <xs:restriction base="code-primitive">
            <xs:enumeration value="all-of">
                <xs:annotation>
                    <xs:documentation xml:lang="en">All of</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="any-of">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Any of</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="at-least">
                <xs:annotation>
                    <xs:documentation xml:lang="en">At least</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="at-most">
                <xs:annotation>
                    <xs:documentation xml:lang="en">At most</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="except-subset">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Except subset</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="GroupCharacteristicCombination">
        <xs:annotation>
            <xs:documentation xml:lang="en"></xs:documentation>
            <xs:documentation xml:lang="en">If the element is present, it must have either a @value, an @id, or extensions
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="Element">
                <xs:attribute name="value" type="GroupCharacteristicCombinationEnum" use="optional"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>
