<?xml version="1.0" encoding="UTF-8"?>
<!-- 
 * #%L
 * org.hl7.fhir.r5
 * %%
 * Copyright (C) 2014 - 2019 Health Level 7
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

/*
  Copyright (c) 2011+, HL7, Inc.
  All rights reserved.
  
  Redistribution and use in source and binary forms, with or without modification, 
  are permitted provided that the following conditions are met:
  
   * Redistributions of source code must retain the above copyright notice, this 
     list of conditions and the following disclaimer.
   * Redistributions in binary form must reproduce the above copyright notice, 
     this list of conditions and the following disclaimer in the documentation 
     and/or other materials provided with the distribution.
   * Neither the name of HL7 nor the names of its contributors may be used to 
     endorse or promote products derived from this software without specific 
     prior written permission.
  
  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
  IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT 
  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
  POSSIBILITY OF SUCH DAMAGE.
  

  Generated on Tue, Apr 1, 2025 12:16+1100 for FHIR v6.0.0-ballot3 

  Note: the schemas &amp; schematrons do not contain all of the rules about what makes resources
  valid. Implementers will still need to be familiar with the content of the specification and with
  any profiles that apply to the resources in order to make a conformant implementation.

-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://hl7.org/fhir"
           targetNamespace="http://hl7.org/fhir" elementFormDefault="qualified" version="1.0">
    <xs:include schemaLocation="fhir-base.xsd"/>
    <xs:element name="MolecularDefinition" type="MolecularDefinition">
        <xs:annotation>
            <xs:documentation xml:lang="en">Definitional content for a molecular entity, such as a nucleotide or protein sequence.
            </xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:complexType name="MolecularDefinition">
        <xs:annotation>
            <xs:documentation xml:lang="en">Definitional content for a molecular entity, such as a nucleotide or protein sequence.
            </xs:documentation>
            <xs:documentation xml:lang="en">If the element is present, it must have either a @value, an @id, or extensions
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="DomainResource">
                <xs:sequence>
                    <xs:element name="identifier" minOccurs="0" maxOccurs="unbounded" type="Identifier">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A unique identifier for a particular instance of this resource.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="description" minOccurs="0" maxOccurs="1" type="markdown">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A description of the molecular entity in a human friendly format.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="moleculeType" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The type of molecule (e.g., DNA, RNA, amino acid). This is a broad
                                concept that refers to the general physical composition of the molecule, intended to facilitate
                                searching and to provide domain context for profiles and instances. The terminology binding may be
                                expanded to support additional types of molecules in the future (e.g., peptide nucleic acids,
                                oligosaccharides).
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="type" minOccurs="0" maxOccurs="unbounded" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Classifications of an instance of the resource into arbitrary types,
                                based on domain semantics. For example, this element could indicate that an instance of moleculeType
                                'RNA' could have a type of 'mRNA' or 'siRNA'.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="topology" minOccurs="0" maxOccurs="unbounded" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The structural topology of the molecular entity. For sequences (e.g.,
                                DNA), this could specify 'linear' and 'circular'. More complex entities might be branched or have a
                                quaternary structure.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="member" minOccurs="0" maxOccurs="unbounded" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Constituents of an aggregate molecular concept (e.g., haplotype,
                                genotype).
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="location" type="MolecularDefinition.Location" minOccurs="0" maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A defined location on a molecular entity. Location definitions may vary
                                with respect to coordinate space and precision or level of granularity.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="representation" type="MolecularDefinition.Representation" minOccurs="0" maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A representation of a molecular entity, specifically including sequence.
                                Note this element is intended to define the entity primarily through computable, discrete elements
                                that express domain semantics rather than replicating a particular file format or relational schema.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="MolecularDefinition.Location">
        <xs:annotation>
            <xs:documentation xml:lang="en">Definitional content for a molecular entity, such as a nucleotide or protein sequence.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="sequenceLocation" type="MolecularDefinition.SequenceLocation" minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A location on a sequence, defined using a nucleotide coordinate
                                system.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="cytobandLocation" type="MolecularDefinition.CytobandLocation" minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A location on a sequence, defined using cytobands.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="MolecularDefinition.SequenceLocation">
        <xs:annotation>
            <xs:documentation xml:lang="en">Definitional content for a molecular entity, such as a nucleotide or protein sequence.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="sequenceContext" minOccurs="1" maxOccurs="1" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A reference to a sequence on which the location is defined.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="coordinateInterval" type="MolecularDefinition.CoordinateInterval" minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">An interval on a sequence, defined by coordinate-based start and end
                                coordinates.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="strand" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The specific strand at the coordinateInterval, when the interval alone
                                is not sufficient to define a location (e.g., double stranded DNA). Example values include 'forward'
                                and 'reverse'.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="MolecularDefinition.CoordinateInterval">
        <xs:annotation>
            <xs:documentation xml:lang="en">Definitional content for a molecular entity, such as a nucleotide or protein sequence.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="coordinateSystem" type="MolecularDefinition.CoordinateSystem" minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A definition of the coordinate system. Examples include 1-based
                                character counting, and 0-based interval counting.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:choice minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The start location of the interval expressed as a precise coordinate
                                (Quantity) or expressed as a range (Range) that is defined by low (range start) and high (range
                                end). Open-ended ranges, where one end is unbounded, may be supported.
                            </xs:documentation>
                        </xs:annotation>
                        <xs:element name="startQuantity" type="Quantity"/>
                        <xs:element name="startRange" type="Range"/>
                    </xs:choice>
                    <xs:choice minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The end location of the interval expressed as a precise coordinate
                                (Quantity) or as a range (Range) that is defined by low (range start) and high (range end).
                                Open-ended ranges, where one end is unbounded, may be supported..
                            </xs:documentation>
                        </xs:annotation>
                        <xs:element name="endQuantity" type="Quantity"/>
                        <xs:element name="endRange" type="Range"/>
                    </xs:choice>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="MolecularDefinition.CoordinateSystem">
        <xs:annotation>
            <xs:documentation xml:lang="en">Definitional content for a molecular entity, such as a nucleotide or protein sequence.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="system" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A definition of the coordinate system. Examples include 1-based
                                character counting, and 0-based interval counting.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="origin" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The location of the origin (0 or 1, depending on the coordinate system).
                                For example, this could specify the origin is at the start of the sequence (e.g., 5’ end or
                                N-terminus), the beginning of a designated feature (e.g., A in the ATG translation initiation
                                codon), or the end of a designated feature (e.g., 3’ end of an exon, from which an offset is
                                calculated into the following intron).
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="normalizationMethod" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The normalization method used for determining a location within the
                                coordinate system. Examples include left shift (e.g., VCF), right shift (e.g., HGVS), or fully
                                justified (e.g., VOCA).
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="MolecularDefinition.CytobandLocation">
        <xs:annotation>
            <xs:documentation xml:lang="en">Definitional content for a molecular entity, such as a nucleotide or protein sequence.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="genomeAssembly" type="MolecularDefinition.GenomeAssembly" minOccurs="1" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The reference genome assemble.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="cytobandInterval" type="MolecularDefinition.CytobandInterval" minOccurs="1" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The Cytoband Interval.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="MolecularDefinition.GenomeAssembly">
        <xs:annotation>
            <xs:documentation xml:lang="en">Definitional content for a molecular entity, such as a nucleotide or protein sequence.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="organism" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Species of the organism.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="build" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The build number of this genome assemble.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="accession" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The accession of this genome assemble.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:choice minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The description of this genome assembly.</xs:documentation>
                        </xs:annotation>
                        <xs:element name="descriptionMarkdown" type="markdown"/>
                        <xs:element name="descriptionString" type="string"/>
                    </xs:choice>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="MolecularDefinition.CytobandInterval">
        <xs:annotation>
            <xs:documentation xml:lang="en">Definitional content for a molecular entity, such as a nucleotide or protein sequence.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="chromosome" minOccurs="1" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The chromosome where this cytoband interval occurs.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="startCytoband" type="MolecularDefinition.StartCytoband" minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The start of this cytoband Interval.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="endCytoband" type="MolecularDefinition.EndCytoband" minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The end of this cytoband Interval.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="MolecularDefinition.StartCytoband">
        <xs:annotation>
            <xs:documentation xml:lang="en">Definitional content for a molecular entity, such as a nucleotide or protein sequence.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:choice minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The arm of this start interval.</xs:documentation>
                        </xs:annotation>
                        <xs:element name="armCode" type="code"/>
                        <xs:element name="armString" type="string"/>
                    </xs:choice>
                    <xs:choice minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The region of this start interval.</xs:documentation>
                        </xs:annotation>
                        <xs:element name="regionCode" type="code"/>
                        <xs:element name="regionString" type="string"/>
                    </xs:choice>
                    <xs:choice minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The band of this start interval.</xs:documentation>
                        </xs:annotation>
                        <xs:element name="bandCode" type="code"/>
                        <xs:element name="bandString" type="string"/>
                    </xs:choice>
                    <xs:choice minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The sub-band of this start interval.</xs:documentation>
                        </xs:annotation>
                        <xs:element name="subBandCode" type="code"/>
                        <xs:element name="subBandString" type="string"/>
                    </xs:choice>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="MolecularDefinition.EndCytoband">
        <xs:annotation>
            <xs:documentation xml:lang="en">Definitional content for a molecular entity, such as a nucleotide or protein sequence.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:choice minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The arm of this end interval.</xs:documentation>
                        </xs:annotation>
                        <xs:element name="armCode" type="code"/>
                        <xs:element name="armString" type="string"/>
                    </xs:choice>
                    <xs:choice minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The region of this end interval.</xs:documentation>
                        </xs:annotation>
                        <xs:element name="regionCode" type="code"/>
                        <xs:element name="regionString" type="string"/>
                    </xs:choice>
                    <xs:choice minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The band of this end interval.</xs:documentation>
                        </xs:annotation>
                        <xs:element name="bandCode" type="code"/>
                        <xs:element name="bandString" type="string"/>
                    </xs:choice>
                    <xs:choice minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The sub-band of this end interval.</xs:documentation>
                        </xs:annotation>
                        <xs:element name="subBandCode" type="code"/>
                        <xs:element name="subBandString" type="string"/>
                    </xs:choice>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="MolecularDefinition.Representation">
        <xs:annotation>
            <xs:documentation xml:lang="en">Definitional content for a molecular entity, such as a nucleotide or protein sequence.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="focus" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The domain concept that is the focus of the representation. This element
                                is used to disambiguate the representations of the “reference” and the “alternate” alleles at a
                                given location, for example.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="code" minOccurs="0" maxOccurs="unbounded" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A code (e.g., sequence accession number) used to represent a molecular
                                entity.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="literal" type="MolecularDefinition.Literal" minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A molecular entity defined as a string literal.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="resolvable" minOccurs="0" maxOccurs="1" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A resolvable representation of a molecular entity, which may be
                                specified as a URI and/or attached document (in a defined format).
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="extracted" type="MolecularDefinition.Extracted" minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A molecular entity that is represented as a portion of a different
                                entity. For example, this element can represent a subsequence (e.g., genetic region) that is part of
                                and conceptually extracted from a longer sequence (e.g., chromosome sequence). The “parent” entity
                                is specified in startingMolecule and the location of the intended molecular entity on the parent
                                entity is defined by coordinateInterval.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="repeated" type="MolecularDefinition.Repeated" minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A representation of a molecular entity that is expressed as a number of
                                copies of a repeated motif.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="concatenated" type="MolecularDefinition.Concatenated" minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A representation comprised of an ordered concatenation of two or more
                                molecular entities.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="relative" type="MolecularDefinition.Relative" minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A molecular entity represented as an ordered series of edits on a
                                specified starting entity. This representation can be used to define one entity relative to another.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="MolecularDefinition.Literal">
        <xs:annotation>
            <xs:documentation xml:lang="en">Definitional content for a molecular entity, such as a nucleotide or protein sequence.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="encoding" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The encoding used for the expression of the entity. For a primary
                                sequence, this element represents the alphabet used (e.g., 1 character DNA without ambiguity codes,
                                3 character amino acid codes).
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="value" minOccurs="1" maxOccurs="1" type="string">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A string literal representation of the molecular entity, using a
                                specific encoding. For example, this may be the primary sequence of a strand of DNA.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="MolecularDefinition.Extracted">
        <xs:annotation>
            <xs:documentation xml:lang="en">Definitional content for a molecular entity, such as a nucleotide or protein sequence.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="startingMolecule" minOccurs="1" maxOccurs="1" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A reference to the molecular entity that serves as the conceptual
                                'parent' from which the intended entity is derived. For example, this could be a chromosome sequence
                                on which a coordinateInterval is defined.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="coordinateInterval" type="MolecularDefinition.CoordinateInterval1" minOccurs="0"
                                maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The interval on startingMolecule that defines the portion to be
                                extracted in order to create the intended entity.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="reverseComplement" minOccurs="0" maxOccurs="1" type="boolean">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A flag that indicates whether the extracted sequence should be reverse
                                complemented in order to produce the intended entity. This element is only relevant to molecular
                                entities that support the concept of reverse complement (e.g., double stranded DNA).
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="MolecularDefinition.CoordinateInterval1">
        <xs:annotation>
            <xs:documentation xml:lang="en">Definitional content for a molecular entity, such as a nucleotide or protein sequence.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="coordinateSystem" type="MolecularDefinition.CoordinateSystem1" minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The coordinate system used to define the location, which may vary
                                depending on application or context of use.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:choice minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The start location of the interval expressed as a precise coordinate
                                (Quantity) or expressed as a range (Range) that is defined by low (range start) and high (range
                                end). Open-ended ranges, where one end is unbounded, may be supported.
                            </xs:documentation>
                        </xs:annotation>
                        <xs:element name="startQuantity" type="Quantity"/>
                        <xs:element name="startRange" type="Range"/>
                    </xs:choice>
                    <xs:choice minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The end location of the interval expressed as a precise coordinate
                                (Quantity) or as a range (Range) that is defined by low (range start) and high (range end).
                                Open-ended ranges, where one end is unbounded, may be supported..
                            </xs:documentation>
                        </xs:annotation>
                        <xs:element name="endQuantity" type="Quantity"/>
                        <xs:element name="endRange" type="Range"/>
                    </xs:choice>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="MolecularDefinition.CoordinateSystem1">
        <xs:annotation>
            <xs:documentation xml:lang="en">Definitional content for a molecular entity, such as a nucleotide or protein sequence.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="system" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A definition of the coordinate system. Examples include 1-based
                                character counting, and 0-based interval counting.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="origin" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The location of the origin (0 or 1, depending on the coordinate system).
                                For example, this could specify the origin is at the start of the sequence (e.g., 5’ end or
                                N-terminus), the beginning of a designated feature (e.g., A in the ATG translation initiation
                                codon), or the end of a designated feature (e.g., 3’ end of an exon, from which an offset is
                                calculated into the following intron).
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="normalizationMethod" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The normalization method used for determining a location within the
                                coordinate system. Examples include left shift (e.g., VCF), right shift (e.g., HGVS), or fully
                                justified (e.g., VOCA).
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="MolecularDefinition.Repeated">
        <xs:annotation>
            <xs:documentation xml:lang="en">Definitional content for a molecular entity, such as a nucleotide or protein sequence.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="sequenceMotif" minOccurs="1" maxOccurs="1" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The motif that is repeated in tandem, which ultimately defines the
                                intended molecular entity.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="copyCount" minOccurs="1" maxOccurs="1" type="integer">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The number of times the motif is repeated to create the intended
                                molecular entity.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="MolecularDefinition.Concatenated">
        <xs:annotation>
            <xs:documentation xml:lang="en">Definitional content for a molecular entity, such as a nucleotide or protein sequence.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="sequenceElement" type="MolecularDefinition.SequenceElement" minOccurs="1"
                                maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">One of the concatenated entities within the concatenated
                                representation.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="MolecularDefinition.SequenceElement">
        <xs:annotation>
            <xs:documentation xml:lang="en">Definitional content for a molecular entity, such as a nucleotide or protein sequence.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="sequence" minOccurs="1" maxOccurs="1" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A reference to the sequence that defines this specific concatenated
                                element.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="ordinalIndex" minOccurs="1" maxOccurs="1" type="integer">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The ordinal index of the element within the concatenated
                                representation.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="MolecularDefinition.Relative">
        <xs:annotation>
            <xs:documentation xml:lang="en">Definitional content for a molecular entity, such as a nucleotide or protein sequence.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="startingMolecule" minOccurs="1" maxOccurs="1" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The molecular entity that serves as the starting point, on which edits
                                will be applied.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="edit" type="MolecularDefinition.Edit" minOccurs="0" maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A defined edit (change) to be applied to the molecular entity.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="MolecularDefinition.Edit">
        <xs:annotation>
            <xs:documentation xml:lang="en">Definitional content for a molecular entity, such as a nucleotide or protein sequence.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="editOrder" minOccurs="0" maxOccurs="1" type="integer">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Defines the order of edits when multiple edits are to be applied to the
                                startingMolecule. This is important when edits may overlap (intervals) or when edits change the
                                length of the entity.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="coordinateInterval" type="MolecularDefinition.CoordinateInterval2" minOccurs="0"
                                maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The interval on startingMolecule that defines the portion to be
                                extracted in order to create the intended entity.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="replacementMolecule" minOccurs="1" maxOccurs="1" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The molecular entity that serves as the replacement in the edit
                                operation. After the edit has been applied, the state of the entity at the specified
                                coordinateInterval is defined by the state of the replacementMolecule.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="replacedMolecule" minOccurs="0" maxOccurs="1" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The portion of the molecular entity that is replaced by the
                                replacementMolecule as a result of the edit. The value of this element can be derived as the state
                                of the entity at the specified coordinateInterval, prior to the edit being applied. It is provided
                                for convenience.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="MolecularDefinition.CoordinateInterval2">
        <xs:annotation>
            <xs:documentation xml:lang="en">Definitional content for a molecular entity, such as a nucleotide or protein sequence.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="coordinateSystem" type="MolecularDefinition.CoordinateSystem2" minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The coordinate system used to define the location, which may vary
                                depending on application or context of use.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:choice minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The start location of the interval expressed as a precise coordinate
                                (Quantity) or expressed as a range (Range) that is defined by low (range start) and high (range
                                end). Open-ended ranges, where one end is unbounded, may be supported.
                            </xs:documentation>
                        </xs:annotation>
                        <xs:element name="startQuantity" type="Quantity"/>
                        <xs:element name="startRange" type="Range"/>
                    </xs:choice>
                    <xs:choice minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The end location of the interval expressed as a precise coordinate
                                (Quantity) or as a range (Range) that is defined by low (range start) and high (range end).
                                Open-ended ranges, where one end is unbounded, may be supported..
                            </xs:documentation>
                        </xs:annotation>
                        <xs:element name="endQuantity" type="Quantity"/>
                        <xs:element name="endRange" type="Range"/>
                    </xs:choice>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="MolecularDefinition.CoordinateSystem2">
        <xs:annotation>
            <xs:documentation xml:lang="en">Definitional content for a molecular entity, such as a nucleotide or protein sequence.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="system" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A definition of the coordinate system. Examples include 1-based
                                character counting, and 0-based interval counting.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="origin" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The location of the origin (0 or 1, depending on the coordinate system).
                                For example, this could specify the origin is at the start of the sequence (e.g., 5’ end or
                                N-terminus), the beginning of a designated feature (e.g., A in the ATG translation initiation
                                codon), or the end of a designated feature (e.g., 3’ end of an exon, from which an offset is
                                calculated into the following intron).
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="normalizationMethod" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The normalization method used for determining a location within the
                                coordinate system. Examples include left shift (e.g., VCF), right shift (e.g., HGVS), or fully
                                justified (e.g., VOCA).
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>
