<?xml version="1.0" encoding="UTF-8"?>
<!-- 
 * #%L
 * org.hl7.fhir.r5
 * %%
 * Copyright (C) 2014 - 2019 Health Level 7
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

/*
  Copyright (c) 2011+, HL7, Inc.
  All rights reserved.
  
  Redistribution and use in source and binary forms, with or without modification, 
  are permitted provided that the following conditions are met:
  
   * Redistributions of source code must retain the above copyright notice, this 
     list of conditions and the following disclaimer.
   * Redistributions in binary form must reproduce the above copyright notice, 
     this list of conditions and the following disclaimer in the documentation 
     and/or other materials provided with the distribution.
   * Neither the name of HL7 nor the names of its contributors may be used to 
     endorse or promote products derived from this software without specific 
     prior written permission.
  
  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
  IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT 
  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
  POSSIBILITY OF SUCH DAMAGE.
  

  Generated on Tue, Apr 1, 2025 12:16+1100 for FHIR v6.0.0-ballot3 

  Note: the schemas &amp; schematrons do not contain all of the rules about what makes resources
  valid. Implementers will still need to be familiar with the content of the specification and with
  any profiles that apply to the resources in order to make a conformant implementation.

-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://hl7.org/fhir"
           targetNamespace="http://hl7.org/fhir" elementFormDefault="qualified" version="1.0">
    <xs:include schemaLocation="fhir-base.xsd"/>
    <xs:element name="NutritionOrder" type="NutritionOrder">
        <xs:annotation>
            <xs:documentation xml:lang="en">A request to supply a diet, formula feeding (enteral) or oral nutritional supplement to
                an individual or group.
            </xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:complexType name="NutritionOrder">
        <xs:annotation>
            <xs:documentation xml:lang="en">A request to supply a diet, formula feeding (enteral) or oral nutritional supplement to
                an individual or group.
            </xs:documentation>
            <xs:documentation xml:lang="en">If the element is present, it must have either a @value, an @id, or extensions
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="DomainResource">
                <xs:sequence>
                    <xs:element name="identifier" minOccurs="0" maxOccurs="unbounded" type="Identifier">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Identifiers assigned to this order by the order sender or by the order
                                receiver.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="instantiatesCanonical" minOccurs="0" maxOccurs="unbounded" type="canonical">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The URL pointing to a FHIR-defined protocol, guideline, orderset or
                                other definition that is adhered to in whole or in part by this NutritionOrder.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="basedOn" minOccurs="0" maxOccurs="unbounded" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A plan or request that is fulfilled in whole or in part by this
                                nutrition order.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="groupIdentifier" minOccurs="0" maxOccurs="1" type="Identifier">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A shared identifier common to all nutrition orders that were authorized
                                more or less simultaneously by a single author, representing the composite or group identifier.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="status" minOccurs="1" maxOccurs="1" type="RequestStatus">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The workflow status of the nutrition order/request.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="intent" minOccurs="1" maxOccurs="1" type="RequestIntent">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Indicates the level of authority/intentionality associated with the
                                NutrionOrder and where the request fits into the workflow chain.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="priority" minOccurs="0" maxOccurs="1" type="RequestPriority">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Indicates how quickly the Nutrition Order should be addressed with
                                respect to other requests.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="subject" minOccurs="1" maxOccurs="1" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The person or set of individuals who needs the nutrition order for an
                                oral diet, nutritional supplement and/or enteral or formula feeding.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="encounter" minOccurs="0" maxOccurs="1" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">An encounter that provides additional information about the healthcare
                                context in which this request is made.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="supportingInformation" minOccurs="0" maxOccurs="unbounded" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Information to support fulfilling (i.e. dispensing or administering) of
                                the nutrition, for example, patient height and weight).
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="dateTime" minOccurs="1" maxOccurs="1" type="dateTime">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The date and time that this nutrition order was requested.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="requester" minOccurs="0" maxOccurs="1" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The practitioner that holds legal responsibility for ordering the diet,
                                nutritional supplement, or formula feedings.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="performer" minOccurs="0" maxOccurs="unbounded" type="CodeableReference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The specified desired performer of the nutrition order.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="allergyIntolerance" minOccurs="0" maxOccurs="unbounded" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A link to a record of allergies or intolerances which should be included
                                in the nutrition order.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="foodPreferenceModifier" minOccurs="0" maxOccurs="unbounded" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">This modifier is used to convey order-specific modifiers about the type
                                of food (i.e. solid and/or liquid) that should be given. These can be derived from patient
                                allergies, intolerances, or preferences such as Halal, Vegan or Kosher. This modifier applies to the
                                entire nutrition order inclusive of the oral diet, nutritional supplements and enteral formula
                                feedings.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="excludeFoodModifier" minOccurs="0" maxOccurs="unbounded" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">This modifier is used to convey Order-specific modifiers that should not
                                be given. These can be derived from patient allergies, intolerances, or preferences such as No Red
                                Meat, No Soy or No Wheat or Gluten-Free. While it should not be necessary to repeat allergy or
                                intolerance information captured in the referenced AllergyIntolerance resource in the
                                excludeFoodModifier, this element may be used to convey additional specificity related to what
                                should be eliminated from the patient’s diet for any reason. This modifier applies to the entire
                                nutrition order inclusive of the oral diet, nutritional supplements and enteral formula feedings.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="outsideFoodAllowed" minOccurs="0" maxOccurs="1" type="boolean">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">This modifier is used to convey whether a food item, brought in by the
                                patient, family, and/or caregiver, can be consumed by the patient. If set to true, indicates that
                                the receiving system does not need to supply the food item.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="oralDiet" type="NutritionOrder.OralDiet" minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Diet given orally that may include texture modification, such as
                                International Dysphagia Diet Standardisation Initiative Framework - Slightly Thick Level 1 drinks
                                and Minced and International Dysphagia Diet Standardisation Initiative Framework - Minced and Moist
                                Level 5 food as well as, for example, Decreased potassium diet (ie, nutrient modification), Halal
                                diet (ie, cultural modification), and/or Low microbial diet (eg, other modification).
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="supplement" type="NutritionOrder.Supplement" minOccurs="0" maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Oral nutritional products given in order to add further nutritional
                                value to the patient's diet.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="enteralFormula" type="NutritionOrder.EnteralFormula" minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Feeding provided through the gastrointestinal tract via a tube,
                                catheter, or stoma that delivers nutrition distal to the oral cavity.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="additive" type="NutritionOrder.Additive" minOccurs="0" maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Indicates modular components to be provided in addition or mixed with
                                the oral diet, supplement, and/or enteral feeding.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="note" minOccurs="0" maxOccurs="unbounded" type="Annotation">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Comments made about the nutrition order by the requester, performer,
                                subject or other participants.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="NutritionOrder.OralDiet">
        <xs:annotation>
            <xs:documentation xml:lang="en">A request to supply a diet, formula feeding (enteral) or oral nutritional supplement to
                an individual or group.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="type" minOccurs="0" maxOccurs="unbounded" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The kind of diet or dietary restriction such as fiber restricted diet or
                                diet for diabetes.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="schedule" type="NutritionOrder.Schedule" minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Schedule information for an oral diet.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="nutrient" type="NutritionOrder.Nutrient" minOccurs="0" maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Defines the quantity and the nutrient modified (for example
                                carbohydrate, fiber or sodium) in the oral diet.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="texture" type="NutritionOrder.Texture" minOccurs="0" maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Class that describes any texture modifications in addition to the oral
                                diet type required for the patient to safely consume various types of foods (i.e. solid and/or
                                liquid).
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="instruction" minOccurs="0" maxOccurs="1" type="string">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Free text or additional instructions or information pertaining to the
                                oral diet.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="caloricDensity" minOccurs="0" maxOccurs="1" type="Quantity">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The amount of energy (calories or kilojoules) that the oral diet should
                                provide. For example, an infant formula feeding of 30 ounces of 20 kcal/ounce (67 kcal/100 mL)
                                formula per day.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="NutritionOrder.Schedule">
        <xs:annotation>
            <xs:documentation xml:lang="en">A request to supply a diet, formula feeding (enteral) or oral nutritional supplement to
                an individual or group.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="timing" minOccurs="0" maxOccurs="unbounded" type="Timing">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The time period and frequency at which the diet should be given. The
                                diet should be given for the combination of all schedules if more than one schedule is present.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="asNeeded" minOccurs="0" maxOccurs="1" type="boolean">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Indicates whether the diet is only taken when needed within a specific
                                administration schedule.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="asNeededFor" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Indicates whether the diet is only taken based on a precondition for
                                taking the diet.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="NutritionOrder.Nutrient">
        <xs:annotation>
            <xs:documentation xml:lang="en">A request to supply a diet, formula feeding (enteral) or oral nutritional supplement to
                an individual or group.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="modifier" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The nutrient that is being modified such as carbohydrate or sodium.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="amount" minOccurs="0" maxOccurs="1" type="Quantity">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The quantity of the specified nutrient to include in diet.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="NutritionOrder.Texture">
        <xs:annotation>
            <xs:documentation xml:lang="en">A request to supply a diet, formula feeding (enteral) or oral nutritional supplement to
                an individual or group.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="modifier" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Texture modifications in the addition to the oral diet type that should
                                be made, e.g. easy to chew, chopped, ground, and pureed.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="type" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The food (i.e. solid and/or liquid) type(s) (e.g. meats, all foods) that
                                the texture modification applies to.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="NutritionOrder.Supplement">
        <xs:annotation>
            <xs:documentation xml:lang="en">A request to supply a diet, formula feeding (enteral) or oral nutritional supplement to
                an individual or group.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="type" minOccurs="0" maxOccurs="1" type="CodeableReference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The kind of nutritional supplement product required such as a high
                                protein or pediatric clear liquid supplement.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="productName" minOccurs="0" maxOccurs="1" type="string">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The product or brand name of the nutritional supplement such as &quot;Acme
                                Protein Shake&quot;.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="schedule" type="NutritionOrder.Schedule1" minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Schedule information for a supplement.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="quantity" minOccurs="0" maxOccurs="1" type="Quantity">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The amount of the nutritional supplement to be given.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="instruction" minOccurs="0" maxOccurs="1" type="string">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Free text or additional instructions or information pertaining to the
                                oral supplement.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="caloricDensity" minOccurs="0" maxOccurs="1" type="Quantity">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The amount of energy (calories or kilojoules) that the supplement should
                                provide per specified volume, typically per ml or fluid oz. For example, a patient may required a
                                supplement that provides 24 calories per fluid ounce.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="NutritionOrder.Schedule1">
        <xs:annotation>
            <xs:documentation xml:lang="en">A request to supply a diet, formula feeding (enteral) or oral nutritional supplement to
                an individual or group.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="timing" minOccurs="0" maxOccurs="unbounded" type="Timing">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The time period and frequency at which the supplement should be given.
                                The supplement should be given for the combination of all schedules if more than one schedule is
                                present.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="asNeeded" minOccurs="0" maxOccurs="1" type="boolean">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Indicates whether the supplement is only taken when needed within a
                                specific dosing schedule.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="asNeededFor" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Indicates whether the supplement is only taken based on a precondition
                                for taking the supplement.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="NutritionOrder.EnteralFormula">
        <xs:annotation>
            <xs:documentation xml:lang="en">A request to supply a diet, formula feeding (enteral) or oral nutritional supplement to
                an individual or group.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="type" minOccurs="0" maxOccurs="1" type="CodeableReference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The type of adult or pediatric enteral feeding such as an adult standard
                                formula with fiber or a soy-based infant feeding.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="productName" minOccurs="0" maxOccurs="1" type="string">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The product or brand name of the enteral feeding product such as &quot;ACME
                                Adult Standard Formula&quot;.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="deliveryDevice" minOccurs="0" maxOccurs="unbounded" type="CodeableReference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The intended type of device that is to be used for the administration of
                                the enteral formula.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="caloricDensity" minOccurs="0" maxOccurs="1" type="Quantity">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The amount of energy (calories or kilojoules) that the feeding should
                                provide per specified volume, typically per mL or fluid oz. For example, an infant may require a
                                formula that provides 24 calories per fluid ounce or an adult may require an enteral formula that
                                provides 1.5 calorie/mL.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="routeOfAdministration" minOccurs="0" maxOccurs="unbounded" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The administration into the patient's gastrointestinal tract for
                                purposes of providing the formula feeding, e.g. nasogastric tube, oral.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="administration" type="NutritionOrder.Administration" minOccurs="0" maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Formula feeding administration instructions as structured data. This
                                repeating structure allows for changing the administration rate or volume over time for both bolus
                                and continuous feeding. An example of this would be an instruction to increase the rate of
                                continuous feeding every 2 hours.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="maxVolumeToAdminister" minOccurs="0" maxOccurs="1" type="Quantity">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The maximum total quantity of formula feeding that may be administered
                                to a subject over the period of time, e.g. 1440 mL over 24 hours.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="administrationInstruction" minOccurs="0" maxOccurs="1" type="markdown">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Free text formula administration, feeding instructions or additional
                                instructions or information.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="NutritionOrder.Administration">
        <xs:annotation>
            <xs:documentation xml:lang="en">A request to supply a diet, formula feeding (enteral) or oral nutritional supplement to
                an individual or group.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="schedule" type="NutritionOrder.Schedule2" minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Schedule information for an enteral feeding.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="quantity" minOccurs="0" maxOccurs="1" type="Quantity">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The volume of formula feeding to provide to the patient per the
                                specified administration schedule.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:choice minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The rate of administration of formula feeding via a feeding pump, e.g.
                                60 mL per hour, according to the specified schedule.
                            </xs:documentation>
                        </xs:annotation>
                        <xs:element name="rateQuantity" type="Quantity"/>
                        <xs:element name="rateRatio" type="Ratio"/>
                    </xs:choice>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="NutritionOrder.Schedule2">
        <xs:annotation>
            <xs:documentation xml:lang="en">A request to supply a diet, formula feeding (enteral) or oral nutritional supplement to
                an individual or group.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="timing" minOccurs="0" maxOccurs="unbounded" type="Timing">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The time period and frequency at which the enteral feeding should be
                                given. The enteral feeding should be given for the combination of all schedules if more than one
                                schedule is present.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="asNeeded" minOccurs="0" maxOccurs="1" type="boolean">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Indicates whether the enteral feeding is only taken when needed within a
                                specific dosing schedule.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="asNeededFor" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Indicates whether the enteral feeding is only taken based on a
                                precondition for taking the enteral feeding.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="NutritionOrder.Additive">
        <xs:annotation>
            <xs:documentation xml:lang="en">A request to supply a diet, formula feeding (enteral) or oral nutritional supplement to
                an individual or group.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="modularType" minOccurs="0" maxOccurs="1" type="CodeableReference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Indicates the type of modular component such as protein, carbohydrate,
                                fat or fiber to be provided in addition to or mixed with the oral diet, supplement, and/or enteral
                                feeding.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="productName" minOccurs="0" maxOccurs="1" type="string">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The product or brand name of the type of modular additive to be added to
                                the oral diet, supplement, and/or enteral feeding.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="quantity" minOccurs="0" maxOccurs="1" type="Quantity">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The amount of additive to be given in addition or to be mixed in with
                                the oral diet, supplement, and/or enteral feeding.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="routeOfAdministration" minOccurs="0" maxOccurs="unbounded" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The administration into the patient's gastrointestinal tract for
                                purposes of providing the additive, e.g. nasogastric tube, oral.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>
