<?xml version="1.0" encoding="UTF-8"?>
<!-- 
 * #%L
 * org.hl7.fhir.r5
 * %%
 * Copyright (C) 2014 - 2019 Health Level 7
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

/*
  Copyright (c) 2011+, HL7, Inc.
  All rights reserved.
  
  Redistribution and use in source and binary forms, with or without modification, 
  are permitted provided that the following conditions are met:
  
   * Redistributions of source code must retain the above copyright notice, this 
     list of conditions and the following disclaimer.
   * Redistributions in binary form must reproduce the above copyright notice, 
     this list of conditions and the following disclaimer in the documentation 
     and/or other materials provided with the distribution.
   * Neither the name of HL7 nor the names of its contributors may be used to 
     endorse or promote products derived from this software without specific 
     prior written permission.
  
  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
  IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT 
  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
  POSSIBILITY OF SUCH DAMAGE.
  

  Generated on Tue, Apr 1, 2025 12:16+1100 for FHIR v6.0.0-ballot3 

  Note: the schemas &amp; schematrons do not contain all of the rules about what makes resources
  valid. Implementers will still need to be familiar with the content of the specification and with
  any profiles that apply to the resources in order to make a conformant implementation.

-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://hl7.org/fhir"
           targetNamespace="http://hl7.org/fhir" elementFormDefault="qualified" version="1.0">
    <xs:include schemaLocation="fhir-base.xsd"/>
    <xs:element name="ResearchStudy" type="ResearchStudy">
        <xs:annotation>
            <xs:documentation xml:lang="en">A scientific study intended to increase health-related knowledge. For example, clinical
                trials are research studies that involve people. These studies may be related to new ways to screen, prevent,
                diagnose, and treat disease. They may also study certain outcomes and certain groups of people by looking at data
                collected in the past or future.
            </xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:complexType name="ResearchStudy">
        <xs:annotation>
            <xs:documentation xml:lang="en">A scientific study intended to increase health-related knowledge. For example, clinical
                trials are research studies that involve people. These studies may be related to new ways to screen, prevent,
                diagnose, and treat disease. They may also study certain outcomes and certain groups of people by looking at data
                collected in the past or future.
            </xs:documentation>
            <xs:documentation xml:lang="en">If the element is present, it must have either a @value, an @id, or extensions
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="DomainResource">
                <xs:sequence>
                    <xs:element name="url" minOccurs="0" maxOccurs="1" type="uri">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Canonical identifier for this study resource, represented as a globally
                                unique URI.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="identifier" minOccurs="0" maxOccurs="unbounded" type="Identifier">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Identifiers assigned to this research study by the sponsor or other
                                systems.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="version" minOccurs="0" maxOccurs="1" type="string">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The business version for the study record.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="name" minOccurs="0" maxOccurs="1" type="string">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Name for this study (computer friendly).</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="title" minOccurs="0" maxOccurs="1" type="string">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The human readable name of the research study.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="label" type="ResearchStudy.Label" minOccurs="0" maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Additional names for the study.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="protocol" minOccurs="0" maxOccurs="unbounded" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The set of steps expected to be performed as part of the execution of
                                the study.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="partOf" minOccurs="0" maxOccurs="unbounded" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A larger research study of which this particular study is a component or
                                step.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="citeAs" minOccurs="0" maxOccurs="1" type="markdown">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Display of the bibliographic citation of this ResearchStudy.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="relatesTo" type="ResearchStudy.RelatesTo" minOccurs="0" maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Relationships that this ResearchStudy has with other FHIR or non-FHIR
                                resources that already exist.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="date" minOccurs="0" maxOccurs="1" type="dateTime">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The date (and optionally time) when the ResearchStudy Resource was last
                                significantly changed. The date must change when the business version changes and it must change if
                                the status code changes. In addition, it should change when the substantive content of the
                                ResearchStudy Resource changes.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="status" minOccurs="1" maxOccurs="1" type="PublicationStatus">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The publication state of the resource (not of the study).
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="primaryPurposeType" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The type of study based upon the intent of the study activities. A
                                classification of the intent of the study.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="phase" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The stage in the progression of a therapy from initial experimental use
                                in humans in clinical trials to post-market evaluation.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="studyDesign" minOccurs="0" maxOccurs="unbounded" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Codes categorizing the type of study such as investigational vs.
                                observational, type of blinding, type of randomization, safety vs. efficacy, etc.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="focus" minOccurs="0" maxOccurs="unbounded" type="CodeableReference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The medication(s), food(s), therapy(ies), device(s) or other concerns or
                                interventions that the study is seeking to gain more information about.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="condition" minOccurs="0" maxOccurs="unbounded" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The condition that is the focus of the study. For example, In a study to
                                examine risk factors for Lupus, might have as an inclusion criterion &quot;healthy volunteer&quot;,
                                but the target condition code would be a Lupus SNOMED code.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="keyword" minOccurs="0" maxOccurs="unbounded" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Key terms to aid in searching for or filtering the study.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="region" minOccurs="0" maxOccurs="unbounded" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A country, state or other area where the study is taking place rather
                                than its precise geographic location or address.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="descriptionSummary" minOccurs="0" maxOccurs="1" type="markdown">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A brief text for explaining the study.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="description" minOccurs="0" maxOccurs="1" type="markdown">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A detailed and human-readable narrative of the study. E.g., study
                                abstract.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="period" minOccurs="0" maxOccurs="1" type="Period">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Identifies the start date and the expected (or actual, depending on
                                status) end date for the study.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="site" minOccurs="0" maxOccurs="unbounded" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A facility in which study activities are conducted.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="note" minOccurs="0" maxOccurs="unbounded" type="Annotation">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Comments made about the study by the performer, subject or other
                                participants.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="classifier" minOccurs="0" maxOccurs="unbounded" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Additional grouping mechanism or categorization of a research study.
                                Example: FDA regulated device, FDA regulated drug, MPG Paragraph 23b (a German legal requirement),
                                IRB-exempt, etc. Implementation Note: do not use the classifier element to support existing
                                semantics that are already supported thru explicit elements in the resource.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="associatedParty" type="ResearchStudy.AssociatedParty" minOccurs="0" maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Sponsors, collaborators, and other parties.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="progressStatus" type="ResearchStudy.ProgressStatus" minOccurs="0" maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Status of study with time for that status.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="whyStopped" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A description and/or code explaining the premature termination of the
                                study.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="recruitment" type="ResearchStudy.Recruitment" minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Target or actual group of participants enrolled in study.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="comparisonGroup" type="ResearchStudy.ComparisonGroup" minOccurs="0" maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Describes an expected event or sequence of events for one of the
                                subjects of a study. E.g. for a living subject: exposure to drug A, wash-out, exposure to drug B,
                                wash-out, follow-up. E.g. for a stability study: {store sample from lot A at 25 degrees for 1
                                month}, {store sample from lot A at 40 degrees for 1 month}.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="objective" type="ResearchStudy.Objective" minOccurs="0" maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A goal that the study is aiming to achieve in terms of a scientific
                                question to be answered by the analysis of data collected during the study.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="result" minOccurs="0" maxOccurs="unbounded" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Link to one or more sets of results generated by the study. Could also
                                link to a research registry holding the results such as ClinicalTrials.gov.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="ResearchStudy.Label">
        <xs:annotation>
            <xs:documentation xml:lang="en">A scientific study intended to increase health-related knowledge. For example, clinical
                trials are research studies that involve people. These studies may be related to new ways to screen, prevent,
                diagnose, and treat disease. They may also study certain outcomes and certain groups of people by looking at data
                collected in the past or future.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="type" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Kind of name.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="value" minOccurs="0" maxOccurs="1" type="string">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The name.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="ResearchStudy.RelatesTo">
        <xs:annotation>
            <xs:documentation xml:lang="en">A scientific study intended to increase health-related knowledge. For example, clinical
                trials are research studies that involve people. These studies may be related to new ways to screen, prevent,
                diagnose, and treat disease. They may also study certain outcomes and certain groups of people by looking at data
                collected in the past or future.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="type" minOccurs="1" maxOccurs="1" type="ArtifactRelationshipType">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The type of relationship to the related artifact.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:choice minOccurs="1" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The artifact that is related to this ResearchStudy Resource.
                            </xs:documentation>
                        </xs:annotation>
                        <xs:element name="targetUri" type="uri"/>
                        <xs:element name="targetAttachment" type="Attachment"/>
                        <xs:element name="targetCanonical" type="canonical"/>
                        <xs:element name="targetReference" type="Reference"/>
                        <xs:element name="targetMarkdown" type="markdown"/>
                    </xs:choice>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="ResearchStudy.AssociatedParty">
        <xs:annotation>
            <xs:documentation xml:lang="en">A scientific study intended to increase health-related knowledge. For example, clinical
                trials are research studies that involve people. These studies may be related to new ways to screen, prevent,
                diagnose, and treat disease. They may also study certain outcomes and certain groups of people by looking at data
                collected in the past or future.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="name" minOccurs="0" maxOccurs="1" type="string">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Name of associated party.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="role" minOccurs="1" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Type of association.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="period" minOccurs="0" maxOccurs="unbounded" type="Period">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Identifies the start date and the end date of the associated party in
                                the role.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="classifier" minOccurs="0" maxOccurs="unbounded" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">A categorization other than role for the associated party.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="party" minOccurs="0" maxOccurs="1" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Individual or organization associated with study (use practitionerRole
                                to specify their organisation).
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="ResearchStudy.ProgressStatus">
        <xs:annotation>
            <xs:documentation xml:lang="en">A scientific study intended to increase health-related knowledge. For example, clinical
                trials are research studies that involve people. These studies may be related to new ways to screen, prevent,
                diagnose, and treat disease. They may also study certain outcomes and certain groups of people by looking at data
                collected in the past or future.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="state" minOccurs="1" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Label for status or state (e.g. recruitment status).</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="actual" minOccurs="0" maxOccurs="1" type="boolean">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">An indication of whether or not the date is a known date when the state
                                changed or will change. A value of true indicates a known date. A value of false indicates an
                                estimated date.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="period" minOccurs="0" maxOccurs="1" type="Period">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Date range.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="ResearchStudy.Recruitment">
        <xs:annotation>
            <xs:documentation xml:lang="en">A scientific study intended to increase health-related knowledge. For example, clinical
                trials are research studies that involve people. These studies may be related to new ways to screen, prevent,
                diagnose, and treat disease. They may also study certain outcomes and certain groups of people by looking at data
                collected in the past or future.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="targetNumber" minOccurs="0" maxOccurs="1" type="unsignedInt">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Estimated total number of participants to be enrolled.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="actualNumber" minOccurs="0" maxOccurs="1" type="unsignedInt">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Actual total number of participants enrolled in study.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="eligibility" minOccurs="0" maxOccurs="1" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Inclusion and exclusion criteria. The referenced Group Resource should
                                have a membership element value of either 'definitional' or 'conceptual'.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="actualGroup" minOccurs="0" maxOccurs="1" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Group of participants who were enrolled in study. The referenced Group
                                Resource should have a membership element value of 'enumerated'.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="ResearchStudy.ComparisonGroup">
        <xs:annotation>
            <xs:documentation xml:lang="en">A scientific study intended to increase health-related knowledge. For example, clinical
                trials are research studies that involve people. These studies may be related to new ways to screen, prevent,
                diagnose, and treat disease. They may also study certain outcomes and certain groups of people by looking at data
                collected in the past or future.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="targetNumber" minOccurs="0" maxOccurs="1" type="unsignedInt">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Estimated total number of participants to be enrolled in the comparison
                                group.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="actualNumber" minOccurs="0" maxOccurs="1" type="unsignedInt">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Actual total number of participants enrolled in the comparison group.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="eligibility" minOccurs="0" maxOccurs="1" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Inclusion and exclusion criteria for the comparison group as a subset of
                                the eligibility for the overall study. The referenced Group Resource should have a membership
                                element value of either 'definitional' or 'conceptual'.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="observedGroup" minOccurs="0" maxOccurs="1" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Group of participants who were enrolled in the comparison group as a
                                subset of those enrolled in the overall study. The referenced Group Resource should have a
                                membership element value of 'enumerated'.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="ResearchStudy.Objective">
        <xs:annotation>
            <xs:documentation xml:lang="en">A scientific study intended to increase health-related knowledge. For example, clinical
                trials are research studies that involve people. These studies may be related to new ways to screen, prevent,
                diagnose, and treat disease. They may also study certain outcomes and certain groups of people by looking at data
                collected in the past or future.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="name" minOccurs="0" maxOccurs="1" type="string">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Unique, human-readable label for this objective of the study.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="type" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The kind of study objective.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="description" minOccurs="0" maxOccurs="1" type="markdown">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Free text description of the objective of the study. This is what the
                                study is trying to achieve rather than how it is going to achieve it (see
                                ResearchStudy.description).
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="outcomeMeasure" type="ResearchStudy.OutcomeMeasure" minOccurs="0" maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">An &quot;outcome measure&quot;, &quot;endpoint&quot;, &quot;effect
                                measure&quot; or &quot;measure of effect&quot; is a specific measurement or observation used to
                                quantify the effect of experimental variables on the participants in a study, or for observational
                                studies, to describe patterns of diseases or traits or associations with exposures, risk factors or
                                treatment.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="ResearchStudy.OutcomeMeasure">
        <xs:annotation>
            <xs:documentation xml:lang="en">A scientific study intended to increase health-related knowledge. For example, clinical
                trials are research studies that involve people. These studies may be related to new ways to screen, prevent,
                diagnose, and treat disease. They may also study certain outcomes and certain groups of people by looking at data
                collected in the past or future.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="name" minOccurs="0" maxOccurs="1" type="string">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Label for the outcome measure.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="type" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The kind of outcome measure.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="description" minOccurs="0" maxOccurs="1" type="markdown">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Description of the outcome measure.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="endpoint" minOccurs="1" maxOccurs="1" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Definition of the outcome measure.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="population" minOccurs="0" maxOccurs="1" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Population for this estimand.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="intervention" minOccurs="0" maxOccurs="1" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Comparison group of interest.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="comparator" minOccurs="0" maxOccurs="1" type="Reference">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Comparison group for comparison.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="summaryMeasure" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Statistical measure for treatment effect estimate.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="eventHandling" type="ResearchStudy.EventHandling" minOccurs="0" maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Handling of intercurrent event.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="ResearchStudy.EventHandling">
        <xs:annotation>
            <xs:documentation xml:lang="en">A scientific study intended to increase health-related knowledge. For example, clinical
                trials are research studies that involve people. These studies may be related to new ways to screen, prevent,
                diagnose, and treat disease. They may also study certain outcomes and certain groups of people by looking at data
                collected in the past or future.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BackboneElement">
                <xs:sequence>
                    <xs:element name="event" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The event.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="group" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">The group that is affected by this event handling.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="handling" minOccurs="0" maxOccurs="1" type="CodeableConcept">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">How the data is handled.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="description" minOccurs="0" maxOccurs="1" type="markdown">
                        <xs:annotation>
                            <xs:documentation xml:lang="en">Text summary of event handling.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>
