package org.opencds.config.migrate;

public enum ConfigResourceType {
	CODE_SYSTEMS,
	CONCEPT_TYPES,
	EXECUTION_ENGINES,
	KNOWLEDGE_MODULES,
	KNOWLEDGE_PACKAGE,
	SEMANTIC_SIGNIFIERS,
	SUPPORTED_CONCEPTS,
	AUTOGEN_CONCEPT_MAPPINGS_SPEC,
	MANUAL_CONCEPT_MAPPINGS_SPEC,
	EXECUTION_ENGINE_MODULES,
	CONCEPT_DETERMINATION_METHOD;
}