//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.05 at 09:07:42 PM EDT 
//


package org.opencds.config.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KMStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="KMStatus"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="APPROVED"/&gt;
 *     &lt;enumeration value="DEFINED"/&gt;
 *     &lt;enumeration value="DRAFT"/&gt;
 *     &lt;enumeration value="PROMOTED"/&gt;
 *     &lt;enumeration value="REJECTED"/&gt;
 *     &lt;enumeration value="RETIRED"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "KMStatus")
@XmlEnum
public enum KMStatus {


    /**
     * The KM successfully passed the QA
     *                         tests.
     *                     
     * 
     */
    APPROVED,

    /**
     * Can be executed. Precondition: the
     *                         KM is syntactically valid. When a defined KM
     *                         changes, a new version should be created.
     *                     
     * 
     */
    DEFINED,

    /**
     * Draft KM.
     * 
     */
    DRAFT,

    /**
     * The KM can be used in the
     *                         production environment.
     *                     
     * 
     */
    PROMOTED,

    /**
     * The KM definition doesn't match
     *                         the KM specification.
     *                     
     * 
     */
    REJECTED,

    /**
     * The KM was historically promoted,
     *                         but should not be used any more.
     *                     
     * 
     */
    RETIRED;

    public String value() {
        return name();
    }

    public static KMStatus fromValue(String v) {
        return valueOf(v);
    }

}
