//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.05 at 09:07:42 PM EDT 
//


package org.opencds.config.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OperationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OperationType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="EVALUATION.EVALUATE"/&gt;
 *     &lt;enumeration value="EVALUATION.EVALUATE_AT_SPECIFIED_TIME"/&gt;
 *     &lt;enumeration value="EVALUATION.EVALUATE_ITERATIVELY"/&gt;
 *     &lt;enumeration value="EVALUATION.EVALUATE_ITERATIVELY_AT_SPECIFIED_TIME"/&gt;
 *     &lt;enumeration value="METADATA_DISCOVERY.DESCRIBE_PROFILE"/&gt;
 *     &lt;enumeration value="METADATA_DISCOVERY.DESCRIBE_SCOPING_ENTITY"/&gt;
 *     &lt;enumeration value="METADATA_DISCOVERY.DESCRIBE_SCOPING_ENTITY_HIERARCHY"/&gt;
 *     &lt;enumeration value="METADATA_DISCOVERY.DESCRIBE_SEMANTIC_REQUIREMENT"/&gt;
 *     &lt;enumeration value="METADATA_DISCOVERY.DESCRIBE_SEMANTIC_SIGNIFIER"/&gt;
 *     &lt;enumeration value="METADATA_DISCOVERY.DESCRIBE_TRAIT"/&gt;
 *     &lt;enumeration value="METADATA_DISCOVERY.LIST_PROFILES"/&gt;
 *     &lt;enumeration value="QUERY.FIND_KMS"/&gt;
 *     &lt;enumeration value="QUERY.GET_KM_DATA_REQUIREMENTS"/&gt;
 *     &lt;enumeration value="QUERY.GET_KM_DATA_REQUIREMENTS_FOR_EVALUATION_AT_SPECIFIED_TIME"/&gt;
 *     &lt;enumeration value="QUERY.GET_KM_DESCRIPTION"/&gt;
 *     &lt;enumeration value="QUERY.GET_KM_EVALUATION_RESULT_SEMANTICS"/&gt;
 *     &lt;enumeration value="QUERY.LIST_KMS"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "OperationType")
@XmlEnum
public enum OperationType {

    @XmlEnumValue("EVALUATION.EVALUATE")
    EVALUATION_EVALUATE("EVALUATION.EVALUATE"),
    @XmlEnumValue("EVALUATION.EVALUATE_AT_SPECIFIED_TIME")
    EVALUATION_EVALUATE_AT_SPECIFIED_TIME("EVALUATION.EVALUATE_AT_SPECIFIED_TIME"),
    @XmlEnumValue("EVALUATION.EVALUATE_ITERATIVELY")
    EVALUATION_EVALUATE_ITERATIVELY("EVALUATION.EVALUATE_ITERATIVELY"),
    @XmlEnumValue("EVALUATION.EVALUATE_ITERATIVELY_AT_SPECIFIED_TIME")
    EVALUATION_EVALUATE_ITERATIVELY_AT_SPECIFIED_TIME("EVALUATION.EVALUATE_ITERATIVELY_AT_SPECIFIED_TIME"),
    @XmlEnumValue("METADATA_DISCOVERY.DESCRIBE_PROFILE")
    METADATA_DISCOVERY_DESCRIBE_PROFILE("METADATA_DISCOVERY.DESCRIBE_PROFILE"),
    @XmlEnumValue("METADATA_DISCOVERY.DESCRIBE_SCOPING_ENTITY")
    METADATA_DISCOVERY_DESCRIBE_SCOPING_ENTITY("METADATA_DISCOVERY.DESCRIBE_SCOPING_ENTITY"),
    @XmlEnumValue("METADATA_DISCOVERY.DESCRIBE_SCOPING_ENTITY_HIERARCHY")
    METADATA_DISCOVERY_DESCRIBE_SCOPING_ENTITY_HIERARCHY("METADATA_DISCOVERY.DESCRIBE_SCOPING_ENTITY_HIERARCHY"),
    @XmlEnumValue("METADATA_DISCOVERY.DESCRIBE_SEMANTIC_REQUIREMENT")
    METADATA_DISCOVERY_DESCRIBE_SEMANTIC_REQUIREMENT("METADATA_DISCOVERY.DESCRIBE_SEMANTIC_REQUIREMENT"),
    @XmlEnumValue("METADATA_DISCOVERY.DESCRIBE_SEMANTIC_SIGNIFIER")
    METADATA_DISCOVERY_DESCRIBE_SEMANTIC_SIGNIFIER("METADATA_DISCOVERY.DESCRIBE_SEMANTIC_SIGNIFIER"),
    @XmlEnumValue("METADATA_DISCOVERY.DESCRIBE_TRAIT")
    METADATA_DISCOVERY_DESCRIBE_TRAIT("METADATA_DISCOVERY.DESCRIBE_TRAIT"),
    @XmlEnumValue("METADATA_DISCOVERY.LIST_PROFILES")
    METADATA_DISCOVERY_LIST_PROFILES("METADATA_DISCOVERY.LIST_PROFILES"),
    @XmlEnumValue("QUERY.FIND_KMS")
    QUERY_FIND_KMS("QUERY.FIND_KMS"),
    @XmlEnumValue("QUERY.GET_KM_DATA_REQUIREMENTS")
    QUERY_GET_KM_DATA_REQUIREMENTS("QUERY.GET_KM_DATA_REQUIREMENTS"),
    @XmlEnumValue("QUERY.GET_KM_DATA_REQUIREMENTS_FOR_EVALUATION_AT_SPECIFIED_TIME")
    QUERY_GET_KM_DATA_REQUIREMENTS_FOR_EVALUATION_AT_SPECIFIED_TIME("QUERY.GET_KM_DATA_REQUIREMENTS_FOR_EVALUATION_AT_SPECIFIED_TIME"),
    @XmlEnumValue("QUERY.GET_KM_DESCRIPTION")
    QUERY_GET_KM_DESCRIPTION("QUERY.GET_KM_DESCRIPTION"),
    @XmlEnumValue("QUERY.GET_KM_EVALUATION_RESULT_SEMANTICS")
    QUERY_GET_KM_EVALUATION_RESULT_SEMANTICS("QUERY.GET_KM_EVALUATION_RESULT_SEMANTICS"),
    @XmlEnumValue("QUERY.LIST_KMS")
    QUERY_LIST_KMS("QUERY.LIST_KMS");
    private final String value;

    OperationType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OperationType fromValue(String v) {
        for (OperationType c: OperationType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
