//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.05 at 09:07:42 PM EDT 
//


package org.opencds.config.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PluginLoadContext.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PluginLoadContext"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CLASSPATH"/&gt;
 *     &lt;enumeration value="IMPORTED"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PluginLoadContext")
@XmlEnum
public enum PluginLoadContext {


    /**
     * Plugin jar has been placed on the same classpath as the OpenCDS service.
     * 
     */
    CLASSPATH,

    /**
     * Plugin jar has been uploaded to/imported into OpenCDS via the REST service.
     * 
     */
    IMPORTED;

    public String value() {
        return name();
    }

    public static PluginLoadContext fromValue(String v) {
        return valueOf(v);
    }

}
