//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.05 at 09:07:42 PM EDT 
//


package org.opencds.config.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Attributes of individual semantic
 *                 signifiers (SSs).
 *             
 * 
 * <p>Java class for SemanticSignifier complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SemanticSignifier"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="link" type="{org.opencds.dss.config.v1_0}Link" minOccurs="0"/&gt;
 *         &lt;element name="identifier" type="{org.opencds.dss.config.v1_0}SemanticSignifierId"/&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="xsdComputableDefinition" type="{org.opencds.dss.config.v1_0}XSDComputableDefinition"/&gt;
 *         &lt;element name="entryPoint" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="exitPoint" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="factListsBuilder" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="resultSetBuilder" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="userId" type="{org.opencds.dss.config.v1_0}UserId"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SemanticSignifier", propOrder = {
    "link",
    "identifier",
    "name",
    "description",
    "xsdComputableDefinition",
    "entryPoint",
    "exitPoint",
    "factListsBuilder",
    "resultSetBuilder",
    "timestamp",
    "userId"
})
public class SemanticSignifier {

    protected Link link;
    @XmlElement(required = true)
    protected SemanticSignifierId identifier;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected XSDComputableDefinition xsdComputableDefinition;
    @XmlElement(required = true)
    protected String entryPoint;
    @XmlElement(required = true)
    protected String exitPoint;
    @XmlElement(required = true)
    protected String factListsBuilder;
    @XmlElement(required = true)
    protected String resultSetBuilder;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timestamp;
    @XmlElement(required = true)
    protected String userId;

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link Link }
     *     
     */
    public Link getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link Link }
     *     
     */
    public void setLink(Link value) {
        this.link = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link SemanticSignifierId }
     *     
     */
    public SemanticSignifierId getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link SemanticSignifierId }
     *     
     */
    public void setIdentifier(SemanticSignifierId value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the xsdComputableDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link XSDComputableDefinition }
     *     
     */
    public XSDComputableDefinition getXsdComputableDefinition() {
        return xsdComputableDefinition;
    }

    /**
     * Sets the value of the xsdComputableDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link XSDComputableDefinition }
     *     
     */
    public void setXsdComputableDefinition(XSDComputableDefinition value) {
        this.xsdComputableDefinition = value;
    }

    /**
     * Gets the value of the entryPoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryPoint() {
        return entryPoint;
    }

    /**
     * Sets the value of the entryPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryPoint(String value) {
        this.entryPoint = value;
    }

    /**
     * Gets the value of the exitPoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExitPoint() {
        return exitPoint;
    }

    /**
     * Sets the value of the exitPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExitPoint(String value) {
        this.exitPoint = value;
    }

    /**
     * Gets the value of the factListsBuilder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFactListsBuilder() {
        return factListsBuilder;
    }

    /**
     * Sets the value of the factListsBuilder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFactListsBuilder(String value) {
        this.factListsBuilder = value;
    }

    /**
     * Gets the value of the resultSetBuilder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultSetBuilder() {
        return resultSetBuilder;
    }

    /**
     * Sets the value of the resultSetBuilder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultSetBuilder(String value) {
        this.resultSetBuilder = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserId(String value) {
        this.userId = value;
    }

}
