//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.05 at 09:07:42 PM EDT 
//


package org.opencds.config.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for XSDComputableDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XSDComputableDefinition"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="xsdRootGlobalElementName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="xsdURL" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="schematronURL" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="narrativeModelRestrictionGuideURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XSDComputableDefinition", propOrder = {
    "xsdRootGlobalElementName",
    "xsdURL",
    "schematronURL",
    "narrativeModelRestrictionGuideURL"
})
public class XSDComputableDefinition {

    @XmlElement(required = true)
    protected String xsdRootGlobalElementName;
    @XmlElement(required = true)
    protected String xsdURL;
    protected List<String> schematronURL;
    protected String narrativeModelRestrictionGuideURL;

    /**
     * Gets the value of the xsdRootGlobalElementName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXsdRootGlobalElementName() {
        return xsdRootGlobalElementName;
    }

    /**
     * Sets the value of the xsdRootGlobalElementName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXsdRootGlobalElementName(String value) {
        this.xsdRootGlobalElementName = value;
    }

    /**
     * Gets the value of the xsdURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXsdURL() {
        return xsdURL;
    }

    /**
     * Sets the value of the xsdURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXsdURL(String value) {
        this.xsdURL = value;
    }

    /**
     * Gets the value of the schematronURL property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the schematronURL property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSchematronURL().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSchematronURL() {
        if (schematronURL == null) {
            schematronURL = new ArrayList<String>();
        }
        return this.schematronURL;
    }

    /**
     * Gets the value of the narrativeModelRestrictionGuideURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNarrativeModelRestrictionGuideURL() {
        return narrativeModelRestrictionGuideURL;
    }

    /**
     * Sets the value of the narrativeModelRestrictionGuideURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNarrativeModelRestrictionGuideURL(String value) {
        this.narrativeModelRestrictionGuideURL = value;
    }

}
