package knowledgeCommon.org.cdsframework.ice;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import org.opencds.vmr.v1_0.internal.AdministrableSubstance;
import org.opencds.vmr.v1_0.internal.ClinicalStatement;
import org.opencds.vmr.v1_0.internal.ClinicalStatementRelationship;
import org.opencds.vmr.v1_0.internal.EntityBase;
import org.opencds.vmr.v1_0.internal.EvaluatedPerson;
import org.opencds.vmr.v1_0.internal.EvalTime;
import org.opencds.vmr.v1_0.internal.ObservationResult;
import org.opencds.vmr.v1_0.internal.ObservationValue;
import org.opencds.vmr.v1_0.internal.SubstanceAdministrationEvent;
import org.opencds.vmr.v1_0.internal.SubstanceAdministrationProposal;
import org.opencds.vmr.v1_0.internal.concepts.ImmunizationConcept;
import org.opencds.vmr.v1_0.internal.concepts.ObservationCodedValueConcept;
import org.opencds.vmr.v1_0.internal.concepts.ObservationFocusConcept;
import org.opencds.vmr.v1_0.internal.datatypes.BL;
import org.opencds.vmr.v1_0.internal.datatypes.CD;
import org.opencds.vmr.v1_0.internal.datatypes.INT;
import org.opencds.vmr.v1_0.internal.datatypes.IVLDate;
import org.cdsframework.ice.service.DateFactType;
import org.cdsframework.ice.service.DiseaseImmunity;
import org.cdsframework.ice.service.DoseRule;
import org.cdsframework.ice.service.DoseStatus;
import org.cdsframework.ice.service.ICEFactTypeFinding;
import org.cdsframework.ice.service.ICEIntervalFactTypeFinding;
import org.cdsframework.ice.service.ICEIntervalFactTypeFinding.IntervalFactType;
import org.cdsframework.ice.service.LiveVirusFact;
import org.cdsframework.ice.service.InconsistentConfigurationException;
import org.cdsframework.ice.service.ICELogicHelper;
import org.cdsframework.ice.service.PayloadHelper;
import org.cdsframework.ice.service.Recommendation;
import org.cdsframework.ice.service.RecommendationStatus;
import org.cdsframework.ice.service.Schedule;
import org.cdsframework.ice.service.Season;
import org.cdsframework.ice.service.SeriesRules;
import org.cdsframework.ice.service.SeriesDisplaySelection;
import org.cdsframework.ice.service.SeriesDisplaySelection.SeriesDisplaySelectionType;
import org.cdsframework.ice.service.TargetDose;
import org.cdsframework.ice.service.TargetDoseInitializationTracker;
import org.cdsframework.ice.service.TargetSeasons;
import org.cdsframework.ice.service.TargetSeries;
import org.cdsframework.ice.service.TargetSeriesSelection;
import org.cdsframework.ice.service.TargetSeriesSelection.SeriesSelectionStatus;
import org.cdsframework.ice.supportingdata.BaseDataEvaluationReason;
import org.cdsframework.ice.supportingdata.BaseDataRecommendationReason;
import org.cdsframework.ice.supportingdatatmp.SupportedFactConcept;
import org.cdsframework.ice.util.TimePeriod;
import org.cdsframework.ice.util.TimePeriod.DurationType;
import org.cdsframework.ice.service.Vaccine;
import org.cdsframework.ice.service.VaccineComponent;
import accumulate org.cdsframework.ice.service.DateMinAccumulateFunction minDate;
import accumulate org.cdsframework.ice.service.DateMaxAccumulateFunction maxDate;

global java.lang.String clientLanguage;
global java.lang.String clientTimeZoneOffset;
global java.lang.String focalPersonId;
global java.util.Date evalTime;
global java.util.Set assertions;
global java.util.Map namedObjects;

global java.util.Date patientAgeTimeOfInterest;
global org.cdsframework.ice.service.Schedule schedule;
global java.lang.Boolean outputEarliestOverdueDates;
global java.lang.Boolean doseOverrideFeatureEnabled;
global java.lang.Boolean outputSupplementalText;
global java.util.List vaccineGroupExclusions;
global java.lang.Boolean enableUnsupportedVaccinesGroup;
global java.lang.Boolean outputNumberOfDosesRemaining;
global java.lang.Boolean disableCovid19DoseNumberReset;
global java.lang.Boolean disableOutputEarliestOverdueDatesForPneumococcalAdultSeries;
global java.lang.String iceVersion;

rule "ImmunizationReferenceData.Initialize Immunization Schedule and Supporting Data"
	ruleflow-group "ImmunizationReferenceData"
	dialect "mvel"
   	when
		eval(patientAgeTimeOfInterest == null)
	then
		kcontext.getKieRuntime().setGlobal("patientAgeTimeOfInterest", evalTime);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Initialized patientAgeTimeOfInterest" + evalTime);
end

rule "ImmunizationReferenceData.Initialize Focal Person Id"
	ruleflow-group "ImmunizationReferenceData"
	no-loop true
	dialect "mvel"
	salience 10
   	when
   		not LiveVirusFact()
   		not TargetSeasons()
		$evaluatedPerson : EvaluatedPerson(isFocalPerson() == true)
		eval(focalPersonId == null || focalPersonId.length() == 0)
	then
		kcontext.getKieRuntime().setGlobal("focalPersonId", $evaluatedPerson.getId());
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Initialized Focal Person ID" + $evaluatedPerson.getId());
end

rule "ImmunizationReferenceData: Initialize Live Virus Fact Object"
	ruleflow-group "ImmunizationReferenceData"
	dialect "mvel"
	when
		not (LiveVirusFact())
	then
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Live Virus Fact Object Initialized");
		insert(new LiveVirusFact());
end

rule "ImmunizationReferenceData: Initialize Select Adjuvant Product Fact Object"
	ruleflow-group "ImmunizationReferenceData"
	dialect "mvel"
	when
		not DateFactType(factName == "SELECT_ADJUVANT_PRODUCT_INTERVAL")
	then
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Select Adjuvant Product Interval Fact Object Initialized");
		insert(new DateFactType("SELECT_ADJUVANT_PRODUCT_INTERVAL"));
end

rule "ImmunizationReferenceData: Initialize Dose Override Feature Fact Object"
	ruleflow-group "ImmunizationReferenceData"
	dialect "mvel"
	when
		not ICEFactTypeFinding(iceResultFinding == "DOSE_OVERRIDE_FEATURE_ENABLED")
		eval(doseOverrideFeatureEnabled != null && doseOverrideFeatureEnabled.booleanValue() == true)
	then
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Dose Override Feature Fact Object Initialized");
		insert(new ICEFactTypeFinding("DOSE_OVERRIDE_FEATURE_ENABLED"));
end

rule "ImmunizationReferenceData: Initialize Unsupported Vaccines Group Feature Fact Object"
	ruleflow-group "ImmunizationReferenceData"
	dialect "mvel"
	when
		not ICEFactTypeFinding(iceResultFinding == "UNSUPPORTED_VACCINES_GROUP_FEATURE_ENABLED")
		eval(enableUnsupportedVaccinesGroup != null && enableUnsupportedVaccinesGroup.booleanValue() == true)
	then
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Unsupported Vaccines Group Feature Fact Object Initialized");
		insert(new ICEFactTypeFinding("UNSUPPORTED_VACCINES_GROUP_FEATURE_ENABLED"));
end

rule "ImmunizationReferenceData: Initialize COVID-19 Sep2023 Dose Number Reset Feature Fact Object"
	ruleflow-group "ImmunizationReferenceData"
	dialect "mvel"
	when
		not ICEFactTypeFinding(iceResultFinding == "COVID19_SEP2023_DOSE_NUMBER_RESET_DISABLED")
		eval(disableCovid19DoseNumberReset != null && disableCovid19DoseNumberReset.booleanValue() == true)
	then
		ICEFactTypeFinding ift = new ICEFactTypeFinding("COVID19_SEP2023_DOSE_NUMBER_RESET_DISABLED");
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "COVID19 Sep2023 Dose Number Reset Feature Fact Object Initialized");
		insert(ift);
end

rule "InitializeReferenceData: Output Number of Doses Remaining Fact Object"
	ruleflow-group "ImmunizationReferenceData"
	dialect "mvel"
    when
        not ICEFactTypeFinding(iceResultFinding == SupportedFactConcept._OUTPUT_NUMBER_OF_DOSES_REMAINING.conceptCodeValue)
        eval(outputNumberOfDosesRemaining != null && outputNumberOfDosesRemaining.booleanValue() == true)
    then
        insert(new ICEFactTypeFinding(SupportedFactConcept._OUTPUT_NUMBER_OF_DOSES_REMAINING.conceptCodeValue));
        ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Output number of doses remaining? Initialized");
end

rule "ImmunizationReferenceData: Initalize Output of Earliest and Overdue Dates for Pneumococcal Adult Series Fact Object"
	ruleflow-group "ImmunizationReferenceData"
	dialect "mvel"
	when
		not ICEFactTypeFinding(iceResultFinding == "DISABLE_OUTPUT_EARLIEST_OVERDUE_DATES_FOR_PNEUMOCOCCAL_ADULT_SERIES")
		eval(disableOutputEarliestOverdueDatesForPneumococcalAdultSeries != null && disableOutputEarliestOverdueDatesForPneumococcalAdultSeries.booleanValue() == true)
	then
		ICEFactTypeFinding ift = new ICEFactTypeFinding("DISABLE_OUTPUT_EARLIEST_OVERDUE_DATES_FOR_PNEUMOCOCCAL_ADULT_SERIES");
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Disable Output of Earliest and Overdue Dates for Pneumococcal Adult Initialized");
		insert(ift);
end

rule "ImmunizationReferenceData: Initialize Target Seasons Fact Object"
	ruleflow-group "ImmunizationReferenceData"
	dialect "mvel"
	when
		not (TargetSeasons())
	then
		TargetSeasons tseasons = new TargetSeasons(evalTime);
		insert(tseasons);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetSeasons Fact Object Initialized");
end

rule "InitializeSeriesAndSeasons: Load SeriesRules and TargetDoseInitializationTracker on to Fact List"
	ruleflow-group "InitializeSeriesAndSeasons"
	dialect "java"
	salience 20
	when
		not SeriesRules()
	then
		List<SeriesRules> allCandidates = schedule.getSeriesRulesExcludingVaccineGroupExclusions(vaccineGroupExclusions);
		if (allCandidates != null) {
			Iterator<SeriesRules> iter = allCandidates.iterator();
			if (iter == null) {
				ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "iter is null");
			}
			while(iter.hasNext()) {
				SeriesRules s = iter.next();
				if (s == null) {
					ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "SeriesRules S == null");
				}
				insert(s);
				ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Loaded SeriesRules object on the fact list: " + s.getSeriesName());
			}
		}
		TargetDoseInitializationTracker tdit = new TargetDoseInitializationTracker();
		insert(tdit);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Eval Time provided by OpenCDS: " + evalTime.toString());
end

rule "InitializeSeriesAndSeasons: Insert SeriesRules Seasons into TargetSeasons"
	ruleflow-group "InitializeSeriesAndSeasons"
	dialect "mvel"
	salience 20
	when
		$tseasons : TargetSeasons()
		$sr : SeriesRules(seasons.size() > 0)
		$season : Season() from $sr.seasons
		not (Season(this == $season))
	then
		$tseasons.addTargetSeason($season);
		insert($season);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Initial season inserted into working memory; TargetSeasons updated with Season: " + $season.toString());
end

rule "InitializeSeriesAndSeasons: Load Default Seasons on to FactList if not already there"
	ruleflow-group "InitializeSeriesAndSeasons"
	dialect "mvel"
	salience 15
	when
		$defaultSeason : Season(isDefaultSeason() == true) from schedule.getSeasonsExcludingVaccineGroupExclusions(vaccineGroupExclusions)
		not Season(this == $defaultSeason)
		$tseasons : TargetSeasons()
	then
		$tseasons.addTargetSeason($defaultSeason);
		insert($defaultSeason);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Initial season inserted into working memory; TargetSeasons updated with Season: " + $defaultSeason.toString());
end

rule "InitializeSeriesAndSeasons: Update Seasons in Working Memory with Information from TargetSeasons"
	ruleflow-group "InitializeSeriesAndSeasons"
	dialect "mvel"
	salience 10
	no-loop true
	when
		$season : Season(isDefaultSeason() == false)
		$tseasons : TargetSeasons(containsTargetSeason($season))
	then
		$tseasons.updateFullySpecifiedSeasonWithOffSeasonDates($season);
		update($season);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Season **updated** in working memory: " + $season.toString());
end

rule "InitializeSeriesAndSeasons: Update Fully-Specified Seasons in Series with Information from TargetSeasons"
	ruleflow-group "InitializeSeriesAndSeasons"
	dialect "mvel"
	salience 5
	no-loop true
	when
		$tseasons : TargetSeasons()
		$sr : SeriesRules(seasons.size() > 0)
		$season : Season(isDefaultSeason() == false) from $sr.seasons
	then
		$tseasons.updateFullySpecifiedSeasonWithOffSeasonDates($season);
		update($sr);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "SeriesRules Season **updated**: " + $season.toString());
end

rule "InitializeSeriesAndSeasons: Log TargetSeasons Tracked for this Request"
	ruleflow-group "InitializeSeriesAndSeasons"
	dialect "mvel"
	salience -1
	when
		$tseasons : TargetSeasons()
	then
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetSeasons: " + $tseasons.toString());
end

rule "CandidateSeriesIdentification: Initialize TargetSeries Custom Rules Invocation"
	ruleflow-group "CandidateSeriesIdentification"
	dialect "mvel"
	salience 110
	when
		$s : SeriesRules()
		not ICEFactTypeFinding(iceResultFinding == SupportedFactConcept._CANDIDATE_SERIES_IDENTIFICATION_DEFAULT_RULE_OVERRIDE.conceptCodeValue, associatedSeriesRules == $s)
	then
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Invoke Custom CandidateSeriesIdentificationRule for SeriesRules: " + $s.getSeriesName());
		drools.setFocus("CandidateSeriesIdentification^customCandidateSeriesIdentificationRule");
end

rule "CandidateSeriesIdentification: Initialize TargetSeries for non-seasonal vaccine groups"
	ruleflow-group "CandidateSeriesIdentification"
	dialect "mvel"
	salience 100
	when
		$s : SeriesRules(seasons == null || seasons.isEmpty())
		not ICEFactTypeFinding(iceResultFinding == SupportedFactConcept._CANDIDATE_SERIES_IDENTIFICATION_DEFAULT_RULE_OVERRIDE.conceptCodeValue, associatedSeriesRules == $s)
		$evaluatedPerson : EvaluatedPerson()
	then
		TargetSeries ts = new TargetSeries($s, schedule, $evaluatedPerson);
		insert(ts);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetSeries initialized: " + ts.toString());
end

rule "CandidateSeriesIdentification: Initialize TargetSeries for *Current* Season with Fully-Specified Season Parameters (if defined)"
	ruleflow-group "CandidateSeriesIdentification"
	dialect "mvel"
	salience 100
	when
		$s : SeriesRules(seasons != null, seasons.size() > 0, $vg : vaccineGroup)
		not ICEFactTypeFinding(iceResultFinding == SupportedFactConcept._CANDIDATE_SERIES_IDENTIFICATION_DEFAULT_RULE_OVERRIDE.conceptCodeValue, associatedSeriesRules == $s)
		$season : Season(isDefaultSeason() == false, isDefinedBySeriesTableRules() == true, dateIsApplicableToSeason(evalTime)) from $s.seasons
		not (TargetSeries(seriesName == $s.seriesName, targetSeason != null, targetSeason.isDefaultSeason() == false, targetSeason == $season))
		$evaluatedPerson : EvaluatedPerson($birthDate : demographics.birthTime)
		eval(($s.seriesEndAge == null || $s.seriesEndAge != null && TimePeriod.compareElapsedTimePeriodToDateRange($birthDate, evalTime, new TimePeriod($s.seriesEndAge.getTimePeriodStringRepresentation() + "+1d")) < 0) &&
			($s.seriesStartAge == null || $s.seriesStartAge != null && TimePeriod.compareElapsedTimePeriodToDateRange($birthDate, evalTime, $s.seriesStartAge) >= 0))
	then
		TargetSeries ts = new TargetSeries($s, schedule, $season, $evaluatedPerson);
		insert(ts);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "*Seasonal* TargetSeries initialized: " + ts.toString());
end

rule "CandidateSeriesIdentification: Initialize *Current* Season TargetSeries with Default Season Parameters if Current Not Defined for the Vaccine Group"
	ruleflow-group "CandidateSeriesIdentification"
	dialect "mvel"
	salience 90
	when
		$s : SeriesRules($vg : vaccineGroup, seasons != null, seasons.size() > 0)
		$season : Season(isDefaultSeason() == true, dateIsApplicableToSeason(evalTime)) from $s.seasons
		not (Season(isDefaultSeason() == false, vaccineGroup == $vg, dateIsApplicableToSeason(evalTime)))
		not ICEFactTypeFinding(iceResultFinding == SupportedFactConcept._CANDIDATE_SERIES_IDENTIFICATION_DEFAULT_RULE_OVERRIDE.conceptCodeValue, associatedSeriesRules == $s)
		not (TargetSeries(seriesName == $s.seriesName, targetSeason != null, targetSeason == $season))
		$evaluatedPerson : EvaluatedPerson($birthDate : demographics.birthTime)
		eval(($s.seriesEndAge == null || $s.seriesEndAge != null && TimePeriod.compareElapsedTimePeriodToDateRange($birthDate, evalTime, new TimePeriod($s.seriesEndAge.getTimePeriodStringRepresentation() + "+1d")) < 0) &&
			($s.seriesStartAge == null || $s.seriesStartAge != null	&& TimePeriod.compareElapsedTimePeriodToDateRange($birthDate, evalTime, $s.seriesStartAge) >= 0))
		$tseasons : TargetSeasons()
	then
		Season fullySpecified = Season.constructFullySpecifiedSeasonFromDefaultSeasonAndDate($season, evalTime);
		$tseasons.addTargetSeason(fullySpecified);
		TargetSeries ts = new TargetSeries($s, schedule, fullySpecified, $evaluatedPerson);
		$s.addFullySpecifiedSeason(fullySpecified);
		insert(ts);
		insert(fullySpecified);
		update($s);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "*Seasonal* TargetSeries initialized: " + ts.toString());
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "*Updated* TargetSeasons: " + $tseasons.toString());
end

rule "CandidateSeriesIdentification: Initialize *Past* Season TargetSeries when Shots Administered with Fully-Specified Season Parameters if Fully-Specified Season Parameters Defined for the Season"
	ruleflow-group "CandidateSeriesIdentification"
	dialect "mvel"
	salience 80
	when
		ImmunizationConcept($ctid : conceptTargetId, $occ : openCdsConceptCode)
		SubstanceAdministrationEvent(id == $ctid, $shotDate : ICELogicHelper.extractSingularDateValueFromIVLDate(administrationTimeInterval))
		$s : SeriesRules($vg : vaccineGroup, seasons.size() > 0)
		not ICEFactTypeFinding(iceResultFinding == SupportedFactConcept._CANDIDATE_SERIES_IDENTIFICATION_DEFAULT_RULE_OVERRIDE.conceptCodeValue, associatedSeriesRules == $s)
		$season : Season(isDefaultSeason() == false, isDefinedBySeriesTableRules() == true, $season.dateIsApplicableToSeason($shotDate)) from $s.seasons
		not (TargetSeries(seriesName == $s.seriesName, targetSeason != null, targetSeason == $season))
		eval(schedule.vaccineTargetsOneOrMoreOfSpecifiedDiseases(schedule.getVaccineByCdsConceptValue($occ), schedule.getDiseasesTargetedByVaccineGroup($vg)) == true)
		$evaluatedPerson : EvaluatedPerson($birthDate : demographics.birthTime)
		eval(($s.seriesEndAge == null || $s.seriesEndAge != null && TimePeriod.compareElapsedTimePeriodToDateRange($birthDate, $shotDate, new TimePeriod($s.seriesEndAge.getTimePeriodStringRepresentation() + "+1d")) < 0) &&
			($s.seriesStartAge == null || $s.seriesStartAge != null	&& TimePeriod.compareElapsedTimePeriodToDateRange($birthDate, $shotDate, $s.seriesStartAge) >= 0))
	then
		TargetSeries ts = new TargetSeries($s, schedule, $season, $evaluatedPerson);
		insert(ts);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "*Seasonal* TargetSeries initialized: " + ts.toString());
end

rule "CandidateSeriesIdentification: Initialize *Past* Season TargetSeries when Shots Administered with Default Season Parameters if No Fully-Specified Season Parameters Defined for the Season"
	ruleflow-group "CandidateSeriesIdentification"
	dialect "mvel"
	salience 70
	when
		ImmunizationConcept($ctid : conceptTargetId, $occ : openCdsConceptCode)
		SubstanceAdministrationEvent(id == $ctid, $shotDate : ICELogicHelper.extractSingularDateValueFromIVLDate(administrationTimeInterval))
		$s : SeriesRules($vg : vaccineGroup, seasons.size() > 0)

		$season : Season(isDefaultSeason() == true) from $s.seasons
		not Season(isDefaultSeason() == false, vaccineGroup == $vg, dateIsApplicableToSeason($shotDate))

		not (TargetSeries(targetSeason != null, targetSeason == Season.constructFullySpecifiedSeasonFromDefaultSeasonAndDate($season, $shotDate)))
		$tseasons : TargetSeasons()
		eval(schedule.vaccineTargetsOneOrMoreOfSpecifiedDiseases(schedule.getVaccineByCdsConceptValue($occ), schedule.getDiseasesTargetedByVaccineGroup($vg)) == true)
		$evaluatedPerson : EvaluatedPerson($birthDate : demographics.birthTime)
		eval(($s.seriesEndAge == null || $s.seriesEndAge != null && TimePeriod.compareElapsedTimePeriodToDateRange($birthDate, $shotDate, new TimePeriod($s.seriesEndAge.getTimePeriodStringRepresentation() + "+1d")) < 0) &&
			($s.seriesStartAge == null || $s.seriesStartAge != null	&& TimePeriod.compareElapsedTimePeriodToDateRange($birthDate, $shotDate, $s.seriesStartAge) >= 0))
	then
		Season fullySpecified = Season.constructFullySpecifiedSeasonFromDefaultSeasonAndDate($season, $shotDate);
		$tseasons.addTargetSeason(fullySpecified);
		TargetSeries ts = new TargetSeries($s, schedule, fullySpecified, $evaluatedPerson);
		$s.addFullySpecifiedSeason(fullySpecified);
		insert(ts);
		insert(fullySpecified);
		update($s);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "*Seasonal* TargetSeries initialized: " + ts.toString());
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "*Updated* TargetSeasons: " + $tseasons.toString());
end

rule "CandidateSeriesIdentification: Initialize TargetSeries when Shots Administered when One and Only One Season for Vaccine Group exists and no matching Fully-Specified Season Parameters or Default Season Defined for the Season"
	ruleflow-group "CandidateSeriesIdentification"
	dialect "mvel"
	salience 70
	when
		ImmunizationConcept($ctid : conceptTargetId, $occ : openCdsConceptCode)
		SubstanceAdministrationEvent(id == $ctid, $shotDate : ICELogicHelper.extractSingularDateValueFromIVLDate(administrationTimeInterval))
		$s : SeriesRules($vg : vaccineGroup, seasons.size() > 0)
		not ICEFactTypeFinding(iceResultFinding == SupportedFactConcept._CANDIDATE_SERIES_IDENTIFICATION_DEFAULT_RULE_OVERRIDE.conceptCodeValue, associatedSeriesRules == $s)
		not Season(isDefaultSeason() == true, vaccineGroup == $vg)

		accumulate($accSeason : Season(vaccineGroup == $vg); $count : count($accSeason); $count == 1)
		$season : Season(isDefaultSeason() == false, vaccineGroup == $vg, dateIsApplicableToSeason($shotDate) == false)
		not (TargetSeries(seriesName == $s.seriesName, targetSeason != null, targetSeason == $season))
		eval(schedule.vaccineTargetsOneOrMoreOfSpecifiedDiseases(schedule.getVaccineByCdsConceptValue($occ), schedule.getDiseasesTargetedByVaccineGroup($vg)) == true)
		$evaluatedPerson : EvaluatedPerson($birthDate : demographics.birthTime)
		eval(($s.seriesEndAge == null || $s.seriesEndAge != null && TimePeriod.compareElapsedTimePeriodToDateRange($birthDate, $shotDate, new TimePeriod($s.seriesEndAge.getTimePeriodStringRepresentation() + "+1d")) < 0) &&
			($s.seriesStartAge == null || $s.seriesStartAge != null	&& TimePeriod.compareElapsedTimePeriodToDateRange($birthDate, $shotDate, $s.seriesStartAge) >= 0))
	then
		TargetSeries ts = new TargetSeries($s, schedule, $season, $evaluatedPerson);
		insert(ts);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "*Seasonal* TargetSeries initialized: " + ts.toString());
end

rule "CandidateDosesIdentification: Initialize TargetDose Custom Rules Invocation"
	ruleflow-group "CandidateDosesIdentification"
	dialect "mvel"
	salience 110
	when
		$i : ImmunizationConcept($ctid : conceptTargetId)
		$sae : SubstanceAdministrationEvent(id == $ctid)
	then
		drools.setFocus("CandidateDosesIdentification^customCandidateDosesIdentificationRule");
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Invoke Custom CandidateSeriesIdentificationRule for SubstanceAdministrationEvent: " + $sae.toString());
end

rule "CandidateDosesIdentification: Initialize TargetDose in *Non-Seasonal* TargetSeries"
	ruleflow-group "CandidateDosesIdentification"
	dialect "mvel"
	salience 50
	no-loop true
	when
		$i : ImmunizationConcept($ctid : conceptTargetId, $occ : openCdsConceptCode, $occ not in ("ICE316", "ICE328"))
		$sae : SubstanceAdministrationEvent(id == $ctid, $shotDate : ICELogicHelper.extractSingularDateValueFromIVLDate(administrationTimeInterval))
		$ts : TargetSeries($vg : vaccineGroup, targetSeasonExists() == false, $tsid : targetSeriesIdentifier)

		$tdit : TargetDoseInitializationTracker(shotAdministeredIsEligibleForInclusionInTargetSeries($i, $vg, $sae, $ts, schedule.getVaccineByCdsConceptValue($occ)) == true)

		eval(schedule.vaccineTargetsOneOrMoreOfSpecifiedDiseases(schedule.getVaccineByCdsConceptValue($occ), schedule.getDiseasesTargetedByVaccineGroup($vg)) == true)

	then
		Vaccine administeredVaccine = schedule.getVaccineByCdsConceptValue($i.getOpenCdsConceptCode());
		for (TargetDose initializedTargetDose : $tdit.addTargetDoseInitialization(administeredVaccine, $sae, $ts, schedule)) {
			insert(initializedTargetDose);
		}
		update($ts);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetDose initialized in TargetSeries " + $ts.seriesName + " ; vaccine: " + $occ + "; vaccine group " + $vg + "; shotdate " + $shotDate);

end

rule "CandidateDosesIdentification: Initialize TargetDose in *Seasonal* TargetSeries"
	ruleflow-group "CandidateDosesIdentification"
	dialect "mvel"
	salience 50
	no-loop true
	when
		$i : ImmunizationConcept($ctid : conceptTargetId, $occ : openCdsConceptCode)
		$sae : SubstanceAdministrationEvent(id == $ctid, $shotDate : ICELogicHelper.extractSingularDateValueFromIVLDate(administrationTimeInterval))
		$ts : TargetSeries($vg : vaccineGroup, targetSeason != null && targetSeason.dateIsApplicableToSeason($shotDate), $tsid : targetSeriesIdentifier)

		$tdit : TargetDoseInitializationTracker(shotAdministeredIsEligibleForInclusionInTargetSeries($i, $vg, $sae, $ts, schedule.getVaccineByCdsConceptValue($occ)) == true)

		eval(schedule.vaccineTargetsOneOrMoreOfSpecifiedDiseases(schedule.getVaccineByCdsConceptValue($occ), schedule.getDiseasesTargetedByVaccineGroup($vg)) == true)
	then
		Vaccine administeredVaccine = schedule.getVaccineByCdsConceptValue($i.getOpenCdsConceptCode());
		for (TargetDose initializedTargetDose : $tdit.addTargetDoseInitialization(administeredVaccine, $sae, $ts, schedule)) {
			insert(initializedTargetDose);
		}
		update($ts);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetDose initialized in TargetSeries " + $ts.seriesName + " ; vaccine: " + $occ + "; vaccine group " + $vg + "; shotdate " + $shotDate);

end

rule "CandidateDosesIdentification: Initialize Outlier TargetDose into Existing TargetSeries"
	ruleflow-group "CandidateDosesIdentification"
	dialect "mvel"
	salience 50
	no-loop true
	when
		$i : ImmunizationConcept($ctid : conceptTargetId, $occ : openCdsConceptCode)
		$sae : SubstanceAdministrationEvent(id == $ctid, $shotDate : ICELogicHelper.extractSingularDateValueFromIVLDate(administrationTimeInterval))
		$ts : TargetSeries($vg : vaccineGroup, targetSeason != null && targetSeason.dateIsApplicableToSeason($shotDate) == false, $tsid : targetSeriesIdentifier)

		not Season(vaccineGroup == $vg, isDefaultSeason() == true)

		accumulate($accSeason : Season(vaccineGroup == $vg); $count : count($accSeason); $count == 1)

		$tdit : TargetDoseInitializationTracker(shotAdministeredIsEligibleForInclusionInTargetSeries($i, $vg, $sae, $ts, schedule.getVaccineByCdsConceptValue($occ)) == true)

		eval(schedule.vaccineTargetsOneOrMoreOfSpecifiedDiseases(schedule.getVaccineByCdsConceptValue($occ), schedule.getDiseasesTargetedByVaccineGroup($vg)) == true)
	then
		Vaccine administeredVaccine = schedule.getVaccineByCdsConceptValue($i.getOpenCdsConceptCode());
		for (TargetDose initializedTargetDose : $tdit.addTargetDoseInitialization(administeredVaccine, $sae, $ts, schedule, true)) {
			insert(initializedTargetDose);
		}
		update($ts);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetDose initialized in TargetSeries " + $ts.seriesName + " ; vaccine: " + $occ + "; vaccine group " + $vg + "; shotdate " + $shotDate);

end

rule "CandidateDosesRevisions: Initialize Series Aggregation Custom Rules Invocation"
	ruleflow-group "CandidateDosesRevisions"
	dialect "mvel"
	when
		exists ICEFactTypeFinding(iceResultFinding == SupportedFactConcept._CANDIDATE_SERIES_IDENTIFICATION_DEFAULT_RULE_OVERRIDE.conceptCodeValue)

	then
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Invoke Custom Candidate Dose Revisions for All Series");
		drools.setFocus("CandidateDosesRevisions^customCandidateDoseRevisionRule");
end

rule "DiseaseImmunityRecord.MarkImmuneToDiseaseIfOnOrAfterImmunityDate"
	ruleflow-group "DiseaseImmunityRecord"
	dialect "mvel"
	no-loop
	when
		$di : DiseaseImmunity($disease : disease, $immunityDate : dateOfImmunity <= evalTime)
		$targetSeries : TargetSeries($disease memberOf diseasesSupportedByThisSeries, targetSeason == null || targetSeason != null && ICELogicHelper.toDate(targetSeason.fullySpecifiedSeasonStartDate) <= evalTime)
	then
		$targetSeries.markImmunityToSpecifiedDisease($disease, $immunityDate);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "for disease " + $disease + ", immunity date " + $immunityDate + " in TargetSeries " + $targetSeries.getSeriesName());
		update($targetSeries);
end

rule "HistoryEvaluation.evaluateNonSeasonalSeriesWhenNoTargetDosesForEvaluation"
	ruleflow-group "HistoryEvaluation"
	dialect "mvel"
	when
		not TargetDose(status == DoseStatus.EVALUATION_IN_PROCESS || status == DoseStatus.PRIMARY_SHOT_DETERMINATION_IN_PROCESS)
		$ts : TargetSeries(targetSeasonExists() == false, numberOfShotsAdministeredInSeries == 0, isHistoryEvaluationInitiated() == false)
	then
		modify ($ts) {
			setHistoryEvaluationInitiated(true)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "in TargetSeries " + $ts.seriesName);
		drools.setFocus("HistoryEvaluation^customEvaluationRule");
end

rule "HistoryEvaluation.setNonSeasonalNextTargetDoseNonNOSInSeriesForEvaluation"
	ruleflow-group "HistoryEvaluation"
	dialect "mvel"
	when
		not TargetDose(status == DoseStatus.EVALUATION_IN_PROCESS || status == DoseStatus.PRIMARY_SHOT_DETERMINATION_IN_PROCESS)
		$td : TargetDose(status == DoseStatus.EVALUATION_NOT_STARTED, vaccineComponent.isUnspecifiedFormulation() == false, associatedTargetSeries.targetSeasonExists() == false)
		not TargetDose(status == DoseStatus.EVALUATION_NOT_STARTED, administrationDate < $td.administrationDate, associatedTargetSeries == $td.associatedTargetSeries || associatedTargetSeries.seriesRules.seriesGroup < $td.associatedTargetSeries.seriesRules.seriesGroup)
		$ts : TargetSeries(this == $td.associatedTargetSeries)
	then
		modify($td) {
			setStatus(DoseStatus.PRIMARY_SHOT_DETERMINATION_IN_PROCESS)
		};
		modify($ts) {
			setHistoryEvaluationInitiated(true)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $td.toString() + " in TargetSeries " + $ts.seriesName);
end

rule "HistoryEvaluation.setNonSeasonalNextTargetDoseNOSInSeriesForEvaluation"
	ruleflow-group "HistoryEvaluation"
	dialect "mvel"
	when
		not TargetDose(status == DoseStatus.EVALUATION_IN_PROCESS || status == DoseStatus.PRIMARY_SHOT_DETERMINATION_IN_PROCESS)
		$td : TargetDose(status == DoseStatus.EVALUATION_NOT_STARTED, vaccineComponent.isUnspecifiedFormulation() == true, associatedTargetSeries.targetSeasonExists() == false)
		not TargetDose(status == DoseStatus.EVALUATION_NOT_STARTED, administrationDate < $td.administrationDate, associatedTargetSeries == $td.associatedTargetSeries || associatedTargetSeries.seriesRules.seriesGroup < $td.associatedTargetSeries.seriesRules.seriesGroup)
		not TargetDose(status == DoseStatus.EVALUATION_NOT_STARTED, associatedTargetSeries == $td.associatedTargetSeries, uniqueId != $td.uniqueId, administrationDate == $td.administrationDate, vaccineComponent.isUnspecifiedFormulation() == false)
		$ts : TargetSeries(this == $td.associatedTargetSeries)
	then
		modify($td) {
			setStatus(DoseStatus.PRIMARY_SHOT_DETERMINATION_IN_PROCESS)
		};
		modify($ts) {
			setHistoryEvaluationInitiated(true)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $td.toString() + " in TargetSeries " + $ts.seriesName);
end

rule "HistoryEvaluation.evaluateSeasonalSeriesWhenNoTargetDosesForEvaluation"
	ruleflow-group "HistoryEvaluation"
	dialect "mvel"
	when
		not TargetDose(status == DoseStatus.EVALUATION_IN_PROCESS || status == DoseStatus.PRIMARY_SHOT_DETERMINATION_IN_PROCESS)
		$ts : TargetSeries(numberOfShotsAdministeredInSeries == 0, isHistoryEvaluationInitiated() == false, targetSeasonExists() == true)
		not TargetSeries(isHistoryEvaluationInitiated() == false, targetSeasonExists() == true, seasonStartDate < $ts.seasonStartDate)
		not TargetDose(status == DoseStatus.EVALUATION_NOT_STARTED, associatedTargetSeries != $ts, associatedTargetSeries.targetSeasonExists() == true, associatedTargetSeries.seasonStartDate < $ts.seasonStartDate)
	then
		modify ($ts) {
			setHistoryEvaluationInitiated(true)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "in TargetSeries " + $ts.seriesName);
		drools.setFocus("HistoryEvaluation^customEvaluationRule");
end

rule "HistoryEvaluation.setNextSeasonalTargetDoseNonNOSInSeriesForEvaluation"
	ruleflow-group "HistoryEvaluation"
	dialect "mvel"
	when
		not TargetDose(status == DoseStatus.EVALUATION_IN_PROCESS || status == DoseStatus.PRIMARY_SHOT_DETERMINATION_IN_PROCESS)
		$ts : TargetSeries(targetSeasonExists() == true)
		exists TargetDose(associatedVaccineGroup == $ts.vaccineGroup, status == DoseStatus.EVALUATION_NOT_STARTED) from $ts.targetDoses
		not TargetSeries(isHistoryEvaluationInitiated() == false, targetSeasonExists() == true, seasonStartDate < $ts.seasonStartDate)
		not TargetDose(status == DoseStatus.EVALUATION_NOT_STARTED, associatedTargetSeries != $ts, associatedTargetSeries.targetSeasonExists() == true, associatedTargetSeries.seasonStartDate < $ts.seasonStartDate)
		$td : TargetDose(associatedTargetSeries == $ts, status == DoseStatus.EVALUATION_NOT_STARTED, vaccineComponent.isUnspecifiedFormulation() == false)
		not TargetDose(status == DoseStatus.EVALUATION_NOT_STARTED, associatedTargetSeries == $td.associatedTargetSeries, administrationDate < $td.administrationDate)
	then
		modify($td) {
			setStatus(DoseStatus.PRIMARY_SHOT_DETERMINATION_IN_PROCESS)
		};
		modify($ts) {
			setHistoryEvaluationInitiated(true)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $td.toString() + " in TargetSeries " + $ts.seriesName);
end

rule "HistoryEvaluation.setNextSeasonalTargetDoseNOSInSeriesForEvaluation"
	ruleflow-group "HistoryEvaluation"
	dialect "mvel"
	when
		not TargetDose(status == DoseStatus.EVALUATION_IN_PROCESS || status == DoseStatus.PRIMARY_SHOT_DETERMINATION_IN_PROCESS)
		$ts : TargetSeries(targetSeasonExists() == true)
		exists TargetDose(associatedVaccineGroup == $ts.vaccineGroup, status == DoseStatus.EVALUATION_NOT_STARTED) from $ts.targetDoses
		not TargetSeries(isHistoryEvaluationInitiated() == false, targetSeasonExists() == true, seasonStartDate < $ts.seasonStartDate)
		not TargetDose(status == DoseStatus.EVALUATION_NOT_STARTED, associatedTargetSeries != $ts, associatedTargetSeries.targetSeasonExists() == true, associatedTargetSeries.seasonStartDate < $ts.seasonStartDate)
		$td : TargetDose(associatedTargetSeries == $ts, status == DoseStatus.EVALUATION_NOT_STARTED, vaccineComponent.isUnspecifiedFormulation() == true)
		not TargetDose(status == DoseStatus.EVALUATION_NOT_STARTED, associatedTargetSeries == $td.associatedTargetSeries, administrationDate < $td.administrationDate)
		not TargetDose(status == DoseStatus.EVALUATION_NOT_STARTED, associatedTargetSeries == $td.associatedTargetSeries, uniqueId != $td.uniqueId, administrationDate == $td.administrationDate, vaccineComponent.isUnspecifiedFormulation() == false)
	then
		modify($td) {
			setStatus(DoseStatus.PRIMARY_SHOT_DETERMINATION_IN_PROCESS)
		};
		modify($ts) {
			setHistoryEvaluationInitiated(true)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $td.toString() + " in TargetSeries " + $ts.seriesName);
end

rule "HistoryEvaluation: If Dose Override Specified, set Dose Evaluation Status Accordingly and Bypass Evaluation Logic"
	ruleflow-group "HistoryEvaluation"
	dialect "mvel"
	salience 10
	when
		exists ICEFactTypeFinding(iceResultFinding == "DOSE_OVERRIDE_FEATURE_ENABLED")
		not TargetDose(status == DoseStatus.EVALUATION_IN_PROCESS || status == DoseStatus.PRIMARY_SHOT_DETERMINATION_IN_PROCESS)
		$td : TargetDose(status == DoseStatus.EVALUATION_NOT_STARTED)
		not TargetDose(status == DoseStatus.EVALUATION_NOT_STARTED, associatedTargetSeries == $td.associatedTargetSeries, administrationDate < $td.administrationDate)
		$sae : SubstanceAdministrationEvent(id == $td.doseId, isValid != null)
		$ts : TargetSeries(this == $td.associatedTargetSeries)
		$tdsEvaluated : List() from accumulate($tdacc : TargetDose(associatedTargetSeries == $td.associatedTargetSeries, hasBeenEvaluated == true), collectList($tdacc))
	then
		DoseStatus evaluationStatus = $sae.getIsValid().isValue() == true ? DoseStatus.VALID : DoseStatus.INVALID;
		String evaluationStatusReason = $sae.getIsValid().isValue() == true ? BaseDataEvaluationReason._DOSE_OVERRIDE_VALID.getCdsListItemName(): BaseDataEvaluationReason._DOSE_OVERRIDE_INVALID.getCdsListItemName();
		modify ($td) {
			setDoseStatusOverridden(true),
			setIsPrimarySeriesShot(! $ts.isSeriesComplete()),
			setDoseNumberCount($ts.determineNumberOfDosesAdministeredInSeries()+1),
			setAdministeredShotNumberInSeries($tdsEvaluated.size()+1),
			setStatus(evaluationStatus),
			addValidReason(evaluationStatusReason)
		};
		modify($ts) {
			setHistoryEvaluationInitiated(true)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Dose Override Check Complete for TargetDose " + $td + " in TargetSeries " + $ts.seriesName);
end

rule "HistoryEvaluation: Determine & Record if the Selected TargetDose to be Evaluated is a Primary Shot of the Series, and Initialize the TargetDose Shot Number and Dose Number"
	ruleflow-group "HistoryEvaluation"
	dialect "mvel"
	when
		$td : TargetDose(status == DoseStatus.PRIMARY_SHOT_DETERMINATION_IN_PROCESS)
		$tdsEvaluated : List() from accumulate($tdacc : TargetDose(associatedTargetSeries == $td.associatedTargetSeries, hasBeenEvaluated == true), collectList($tdacc))
	then
		int tddosenumber = $td.getAssociatedTargetSeries().determineDoseNumberInSeries();
		int tdshotnumber = $tdsEvaluated.size()+1;
		boolean isSeriesComplete = $td.getAssociatedTargetSeries().isSeriesComplete();
		boolean isSeriesNotComplete = ! isSeriesComplete;
		modify($td) {
			setStatus(DoseStatus.EVALUATION_IN_PROCESS),
			setIsPrimarySeriesShot(isSeriesNotComplete),
			setDoseNumberInSeries(tddosenumber),
			setAdministeredShotNumberInSeries(tdshotnumber)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $td.toString() + " in TargetSeries " + $td.getAssociatedTargetSeries().getSeriesName());
		drools.setFocus("HistoryEvaluation^makeNoteOfDuplicateShotSameDayIfAny");
		drools.setFocus("HistoryEvaluation^customMakeNoteOfDuplicateShotSameDayIfAny");
		drools.setFocus("HistoryEvaluation^preEvaluationValidation");
end

rule "HistoryEvaluation: Check if Shot should be marked Accepted and Series Complete if Administered On or After Immunity Date"
	dialect "mvel"
	ruleflow-group "HistoryEvaluation^preEvaluationValidation"
	when
		$targetDose : TargetDose(status == DoseStatus.EVALUATION_IN_PROCESS, $diseasesTargetedByThisDose : vaccineComponent.allDiseasesTargetedForImmunity, $doseAdministrationDate : administrationDate)
		$targetSeries : TargetSeries(this == $targetDose.associatedTargetSeries)
		$diseaseImmunityList : List(size == $diseasesTargetedByThisDose.size()) from
			accumulate($di : DiseaseImmunity($d : getDisease(), getDateOfImmunity() <= $doseAdministrationDate, $r : getImmunityReason(), disease memberOf $diseasesTargetedByThisDose), collectList($di))
	then
		Iterator dilIter = $diseaseImmunityList.iterator();
		while (dilIter.hasNext()) {
			$targetDose.addAcceptedReason(((DiseaseImmunity) dilIter.next()).getEvaluationReasonResult());
		}
		modify ($targetDose) {
		    setStatus(DoseStatus.EVALUATION_COMPLETE)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Marking Evaluation Complete for TargetDose " + $targetDose.toString() + " in TargetSeries " + $targetSeries .getSeriesName());
end

rule "Duplicate Shot/Same Day (Abstract): 2 shots administered on the same day"
	dialect "mvel"
	ruleflow-group "HistoryEvaluation^makeNoteOfDuplicateShotSameDayIfAny"
	no-loop true
	when
		$td: TargetDose(isPreEvaluationCheckCompleted() == false, status == DoseStatus.EVALUATION_IN_PROCESS, $administrationDate : administrationDate, $tdAdministeredShotNumber : administeredShotNumberInSeries,
			$doseNumber : doseNumberInSeries)
		$tdprev : TargetDose(administrationDate == $administrationDate, hasBeenEvaluated == true, administeredShotNumberInSeries == $tdAdministeredShotNumber-1, $tdprevDoseNumber: doseNumberInSeries, $tdprevDoseNumber <= $doseNumber)
		$targetSeries : TargetSeries(this == $td.associatedTargetSeries, this == $tdprev.associatedTargetSeries)
	then
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $td.toString() + " in TargetSeries " + $targetSeries.seriesName);
end

rule "Duplicate Shot/Same Day: If this is a duplicate shot/same day, mark the dose number of the shot being evaluated as equal to prior shots administered on the same date; Invoke custom evaluation rules"
		extends "Duplicate Shot/Same Day (Abstract): 2 shots administered on the same day"
	dialect "mvel"
	ruleflow-group "HistoryEvaluation^makeNoteOfDuplicateShotSameDayIfAny"
	no-loop true
	when
		eval(
			$tdprev.isShotIgnored() == false &&
			($doseNumber > $targetSeries.getSeriesRules().getNumberOfDosesInSeries() && $targetSeries.getSeriesRules().recurringDosesOccurAfterSeriesComplete() == false) ||
			($tdprev.getAssociatedTargetSeries().obtainDoseRuleForSeriesByDoseNumber($tdprevDoseNumber) != null &&
			$tdprev.getAssociatedTargetSeries().obtainDoseRuleForSeriesByDoseNumber($tdprevDoseNumber).getAbsoluteMinimumInterval() != null &&
			! $tdprev.getAssociatedTargetSeries().obtainDoseRuleForSeriesByDoseNumber($tdprevDoseNumber).getAbsoluteMinimumInterval().isEqualTo(new TimePeriod(0, DurationType.DAYS))))
	then
		modify ($td) {
			setDoseNumberInSeries($tdprevDoseNumber),
			setPreEvaluationCheckCompleted(true)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $td.toString() + " in TargetSeries " + $targetSeries.seriesName);
		drools.setFocus("HistoryEvaluation^customEvaluationRule");
end

rule "Duplicate Shot/Same Day: duplicate shots on same day where interval is 0 days are not marked with the same dose number; Invoke custom evaluation rules"
		extends "Duplicate Shot/Same Day (Abstract): 2 shots administered on the same day"
	dialect "mvel"
	ruleflow-group "HistoryEvaluation^makeNoteOfDuplicateShotSameDayIfAny"
	no-loop true
	when
		eval($tdprev.isShotIgnored() == true ||
			(($doseNumber <= $targetSeries.getSeriesRules().getNumberOfDosesInSeries() || $targetSeries.getSeriesRules().recurringDosesOccurAfterSeriesComplete() == true) &&
			($tdprev.getAssociatedTargetSeries().obtainDoseRuleForSeriesByDoseNumber($tdprevDoseNumber) == null ||
			$tdprev.getAssociatedTargetSeries().obtainDoseRuleForSeriesByDoseNumber($tdprevDoseNumber).getAbsoluteMinimumInterval() == null ||
			$tdprev.getAssociatedTargetSeries().obtainDoseRuleForSeriesByDoseNumber($tdprevDoseNumber).getAbsoluteMinimumInterval().isEqualTo(new TimePeriod(0, DurationType.DAYS)))))
	then
		modify ($td) {
			setPreEvaluationCheckCompleted(true)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $td.toString() + " in TargetSeries " + $targetSeries.seriesName);
		drools.setFocus("HistoryEvaluation^customEvaluationRule");
end

rule "Not Duplicate Shot/Same Day: No duplicate shots to shot being evaluated; Invoke custom evaluation rules"
	dialect "mvel"
	ruleflow-group "HistoryEvaluation^makeNoteOfDuplicateShotSameDayIfAny"
	when
		$td: TargetDose(isPreEvaluationCheckCompleted() == false, status == DoseStatus.EVALUATION_IN_PROCESS)
		not TargetDose(this != $td, administrationDate == $td.administrationDate, administeredShotNumberInSeries < $td.administeredShotNumberInSeries, associatedTargetSeries == $td.associatedTargetSeries)
	then
		modify ($td) {
			setPreEvaluationCheckCompleted(true)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $td.toString() + " in TargetSeries " + $td.associatedTargetSeries.seriesName);
		drools.setFocus("HistoryEvaluation^customEvaluationRule");
end

rule "HistoryEvaluation.setDoseEvaluationStatusInvalid"
	ruleflow-group "HistoryEvaluation"
	dialect "mvel"
	salience 10
	when
		$td : TargetDose(status == DoseStatus.EVALUATION_COMPLETE, invalidReasons.empty == false, $ts : associatedTargetSeries)
	then
		modify($td) {
			setDoseNumberCount($td.associatedTargetSeries.determineNumberOfDosesAdministeredInSeries()+1),
			setStatus(DoseStatus.INVALID),
			addDoseRuleProcessed(drools.getRule().getName())
		};
		update($ts);

		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $td.toString() + " in TargetSeries " + $td.associatedTargetSeries.seriesName);
		drools.setFocus("HistoryEvaluation^postEvaluationCheck");
end

rule "HistoryEvaluation.setDoseEvaluationStatusNotEvaluated"
	ruleflow-group "HistoryEvaluation"
	dialect "mvel"
	salience 10
	when
		$td : TargetDose(status == DoseStatus.EVALUATION_COMPLETE, invalidReasons.empty, notEvaluatedReasons.empty == false, $ts : associatedTargetSeries)
	then
		modify($td) {
			setDoseNumberCount($td.associatedTargetSeries.determineNumberOfDosesAdministeredInSeries()+1),
			setStatus(DoseStatus.NOT_EVALUATED),
			addDoseRuleProcessed(drools.getRule().getName())
		};

		update($ts);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $td.toString() + " in TargetSeries " + $td.associatedTargetSeries.seriesName);
		drools.setFocus("HistoryEvaluation^postEvaluationCheck");
end

rule "HistoryEvaluation.setDoseEvaluationStatusAccepted"
	ruleflow-group "HistoryEvaluation"
	dialect "mvel"
	salience 10
	when
		$td : TargetDose(status == DoseStatus.EVALUATION_COMPLETE, invalidReasons.empty, notEvaluatedReasons.empty, acceptedReasons.empty == false)
		$ts : TargetSeries(this == $td.associatedTargetSeries)
	then
		modify($td) {
			setDoseNumberCount($ts.determineNumberOfDosesAdministeredInSeries()+1),
			setStatus(DoseStatus.ACCEPTED),
			addDoseRuleProcessed(drools.getRule().getName())
		};
		update($ts);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $td.toString() + " in TargetSeries " + $td.associatedTargetSeries.seriesName);
		drools.setFocus("HistoryEvaluation^postEvaluationCheck");
end

rule "HistoryEvaluation.setDoseEvaluationStatusValid"
	ruleflow-group "HistoryEvaluation"
	dialect "java"
	salience 10
	when
		$td : TargetDose(status == DoseStatus.EVALUATION_COMPLETE, invalidReasons.empty, acceptedReasons.empty, notEvaluatedReasons.empty)
		$ts : TargetSeries(this == $td.associatedTargetSeries)
	then
		modify($td) {
			setDoseNumberCount($ts.determineNumberOfDosesAdministeredInSeries()+1),
			addDoseRuleProcessed(drools.getRule().getName()),
			setStatus(DoseStatus.VALID)
		};
		update($ts);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $td.toString() + " in TargetSeries " + $ts.getSeriesName());
		drools.setFocus("HistoryEvaluation^postEvaluationCheck");
end

rule "HistoryEvaluation.denoteDoseReadyForFinalEvaluationStatus"
	ruleflow-group "HistoryEvaluation"
	dialect "mvel"
	salience 60
	when
		$td : TargetDose(status == DoseStatus.EVALUATION_IN_PROCESS)
	then
		modify($td) {
			setStatus(DoseStatus.EVALUATION_COMPLETE)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $td.toString() + " in TargetSeries " + $td.associatedTargetSeries.seriesName);
end

rule "HistoryEvaluation.markExtraneousDosesAcceptedIfCompleteForAllDiseaseTargetedByThisDose"
	ruleflow-group "HistoryEvaluation"
	dialect "mvel"
	salience 100
	activation-group "extraDoseCheck"
	when
		$td : TargetDose(status == DoseStatus.EVALUATION_IN_PROCESS, $doseNumber : doseNumberInSeries)
		$ts : TargetSeries(this == $td.associatedTargetSeries, isSeriesComplete() == true || seriesRules.numberOfDosesInSeries < determineDoseNumberInSeriesForDiseasesTargetedByThisDose($td))
	then
		$td.addAcceptedReason(BaseDataEvaluationReason._EXTRA_DOSE_EVALUATION_REASON.getCdsListItemName());
		$td.addDoseRuleProcessed(drools.getRule().getName());
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $td.toString() + " in TargetSeries " + $ts.seriesName);
end

rule "HistoryEvaluation.checkIsAllowableVaccine"
	ruleflow-group "HistoryEvaluation"
	dialect "mvel"
	salience 100
	activation-group "allowableVaccineCheck"
	when
		$td : TargetDose(status == DoseStatus.EVALUATION_IN_PROCESS, $vaccine : administeredVaccine, $doseNumber : doseNumberInSeries)
		$ts : TargetSeries(this == $td.associatedTargetSeries, $doseNumber <= seriesRules.numberOfDosesInSeries, seriesRules.isAllowableVaccineForDoseRule($vaccine, $doseNumber) == false)
	then
		ICEFactTypeFinding hef = new ICEFactTypeFinding(SupportedFactConcept._INVALID_VACCINE.getConceptCodeValue(), $td);
		insert(hef);
		$td.addInvalidReason(BaseDataEvaluationReason._VACCINE_NOT_ALLOWED_FOR_THIS_DOSE.getCdsListItemName());
		$td.addDoseRuleProcessed(drools.getRule().getName());
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $td.toString() + " in TargetSeries " + $ts.seriesName);
end

rule "HistoryEvaluation.checkMinimumAgeVaccine"
	ruleflow-group "HistoryEvaluation"
	dialect "mvel"
	salience 100
	activation-group "minimumAgeVaccineCheck"
	when
		$td : TargetDose(status == DoseStatus.EVALUATION_IN_PROCESS, $adminage : vaccineComponent.validMinimumAgeForUse != null, $tdVaccineComponent : vaccineComponent)
		$ts : TargetSeries(this == $td.associatedTargetSeries)
		not DoseRule(encompassingSeriesRules == $ts.seriesRules, doseNumber == $td.doseNumberInSeries, getAllowableVaccineMinimumAge($tdVaccineComponent) != null) from $ts.seriesRules.seriesDoseRules
		$person : EvaluatedPerson()
		eval(TimePeriod.compareElapsedTimePeriodToDateRange($person.getDemographics().getBirthTime(), $td.getAdministrationDate(), $adminage) < 0)
	then
		ICEFactTypeFinding hef = new ICEFactTypeFinding(SupportedFactConcept._INVALID_VACCINE.getConceptCodeValue(), $td);
		insert(hef);
		$td.addInvalidReason(BaseDataEvaluationReason._BELOW_MINIMUM_AGE_VACCINE_REASON.getCdsListItemName());
		$td.addDoseRuleProcessed(drools.getRule().getName());
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $td.toString() + " in TargetSeries " + $ts.seriesName);
end

rule "HistoryEvaluation.checkMinimumAgeVaccineDoseRule"
	ruleflow-group "HistoryEvaluation"
	dialect "mvel"
	salience 100
	activation-group "minimumAgeVaccineCheck"
	when
		$td : TargetDose(status == DoseStatus.EVALUATION_IN_PROCESS, $tdVaccineComponent : vaccineComponent)
		$ts : TargetSeries(this == $td.associatedTargetSeries)
		$dr : DoseRule(encompassingSeriesRules == $ts.seriesRules, doseNumber == $td.doseNumberInSeries, getAllowableVaccineMinimumAge($tdVaccineComponent) != null) from $ts.seriesRules.seriesDoseRules
		$person : EvaluatedPerson()
		eval(! TimePeriod.isTimePeriodANegativeDuration($dr.getAllowableVaccineMinimumAge($tdVaccineComponent).getTimePeriodStringRepresentation()) &&
			TimePeriod.compareElapsedTimePeriodToDateRange($person.getDemographics().getBirthTime(), $td.getAdministrationDate(), $dr.getAllowableVaccineMinimumAge($tdVaccineComponent)) < 0)
	then
		ICEFactTypeFinding hef = new ICEFactTypeFinding(SupportedFactConcept._INVALID_VACCINE.getConceptCodeValue(), $td);
		insert(hef);
		$td.addInvalidReason(BaseDataEvaluationReason._BELOW_MINIMUM_AGE_VACCINE_REASON.getCdsListItemName());
		$td.addDoseRuleProcessed(drools.getRule().getName());
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $td.toString() + " in TargetSeries " + $ts.seriesName);
end

rule "HistoryEvaluation.checkMaximumAgeVaccine"
	ruleflow-group "HistoryEvaluation"
	dialect "mvel"
	salience 100
	activation-group "maximumAgeVaccineCheck"
	when
		$td : TargetDose(status == DoseStatus.EVALUATION_IN_PROCESS, $adminage : vaccineComponent.validMaximumAgeForUse != null, $tdVaccineComponent : vaccineComponent)
		$ts : TargetSeries(this == $td.associatedTargetSeries)
		not DoseRule(encompassingSeriesRules == $ts.seriesRules, doseNumber == $td.doseNumberInSeries, getAllowableVaccineMaximumAge($tdVaccineComponent) != null) from $ts.seriesRules.seriesDoseRules
		$person : EvaluatedPerson()
		eval(TimePeriod.compareElapsedTimePeriodToDateRange($person.getDemographics().getBirthTime(), $td.getAdministrationDate(), $adminage) > 0)
	then
		ICEFactTypeFinding hef = new ICEFactTypeFinding(SupportedFactConcept._INVALID_VACCINE.getConceptCodeValue(), $td);
		insert(hef)
		$td.addInvalidReason(BaseDataEvaluationReason._ABOVE_MAXIMUM_AGE_VACCINE.getCdsListItemName());
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $td.toString() + " in TargetSeries " + $ts.seriesName);
end

rule "HistoryEvaluation.checkMaximumAgeVaccineDoseRuleDoseRule"
	ruleflow-group "HistoryEvaluation"
	dialect "mvel"
	salience 100
	activation-group "maximumAgeVaccineCheck"
	when
		$td : TargetDose(status == DoseStatus.EVALUATION_IN_PROCESS, $tdVaccineComponent : vaccineComponent)
		$ts : TargetSeries(this == $td.associatedTargetSeries)
		$dr : DoseRule(encompassingSeriesRules == $ts.seriesRules, doseNumber == $td.doseNumberInSeries, getAllowableVaccineMaximumAge($tdVaccineComponent) != null) from $ts.seriesRules.seriesDoseRules
		$person : EvaluatedPerson()
		eval(! TimePeriod.isTimePeriodANegativeDuration($dr.getAllowableVaccineMaximumAge($tdVaccineComponent).getTimePeriodStringRepresentation()) &&
			TimePeriod.compareElapsedTimePeriodToDateRange($person.getDemographics().getBirthTime(), $td.getAdministrationDate(), $dr.getAllowableVaccineMaximumAge($tdVaccineComponent)) > 0)
	then
		ICEFactTypeFinding hef = new ICEFactTypeFinding(SupportedFactConcept._INVALID_VACCINE.getConceptCodeValue(), $td);
		insert(hef)
		$td.addInvalidReason(BaseDataEvaluationReason._ABOVE_MAXIMUM_AGE_VACCINE.getCdsListItemName());
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $td.toString() + " in TargetSeries " + $ts.seriesName);
end

rule "HistoryEvaluation.evaluateVaccineGroupMaximumAge"
	ruleflow-group "HistoryEvaluation"
	dialect "mvel"
	activation-group "doseMaximumAgeCheck"
	salience 100
	when
		$td : TargetDose(status == DoseStatus.EVALUATION_IN_PROCESS, $doseNumber : doseNumberInSeries)
		$ts : TargetSeries(this == $td.associatedTargetSeries, seriesRules.numberOfDosesInSeries >= $doseNumber)
		$person : EvaluatedPerson()
	then
		$ts.evaluateVaccineGroupMaximumAgeandRecordReason($person.demographics.birthTime, $td);
		if ($td.containsInvalidReason(BaseDataEvaluationReason._ABOVE_MAXIMUM_AGE_EVALUATION_REASON.getCdsListItemName()) ||
			$td.containsInvalidReason(BaseDataEvaluationReason._INVALID_AGE_EVALUATION_REASON.getCdsListItemName())) {
			ICEFactTypeFinding hef = new ICEFactTypeFinding(SupportedFactConcept._ABOVE_MAXIMUM_AGE.getConceptCodeValue(), $td);
			insert(hef)
		}
		$td.addDoseRuleProcessed(drools.getRule().getName());
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $td.toString() + " in TargetSeries " + $ts.seriesName);
end

rule "HistoryEvaluation.evaluateVaccineGroupMinimumAge"
	ruleflow-group "HistoryEvaluation"
	dialect "mvel"
	activation-group "doseAgeCheck"
	salience 100
	when
		$td : TargetDose(status == DoseStatus.EVALUATION_IN_PROCESS, $doseNumber : doseNumberInSeries)
		$ts : TargetSeries(this == $td.associatedTargetSeries, seriesRules.numberOfDosesInSeries >= $doseNumber)
		$person : EvaluatedPerson()
	then
		$ts.evaluateVaccineGroupMinimumAgeandRecordReason($person.demographics.birthTime, $td);
		if ($td.containsInvalidReason(BaseDataEvaluationReason._BELOW_MINIMUM_AGE_EVALUATION_REASON.getCdsListItemName()) ||
			$td.containsInvalidReason(BaseDataEvaluationReason._INVALID_AGE_EVALUATION_REASON.getCdsListItemName())) {
			ICEFactTypeFinding hef = new ICEFactTypeFinding(SupportedFactConcept._BELOW_MINIMUM_AGE.getConceptCodeValue(), $td);
			insert(hef)
		}
		$td.addDoseRuleProcessed(drools.getRule().getName());
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $td.toString() + " in TargetSeries " + $ts.seriesName);
end

rule "HistoryEvaluation.evaluateVaccineGroupMinimumInterval"
	ruleflow-group "HistoryEvaluation"
	dialect "mvel"
	activation-group "doseIntervalCheck"
	salience 100
	when
		$td : TargetDose(status == DoseStatus.EVALUATION_IN_PROCESS, $admindose: administeredShotNumberInSeries >= 2, $doseNumber : doseNumberInSeries, $tddate : administrationDate, $tdAssociatedTargetSeries : associatedTargetSeries)
		$tdprev : TargetDose(associatedTargetSeries == $tdAssociatedTargetSeries, administeredShotNumberInSeries < $admindose, administrationDate < $tddate, isShotIgnored() == false, $tdprevdate : administrationDate)
		not TargetDose(associatedTargetSeries == $tdAssociatedTargetSeries, administrationDate > $tdprevdate, administrationDate < $tddate, isShotIgnored() == false)
		$ts : TargetSeries(this == $td.associatedTargetSeries, this == $tdprev.associatedTargetSeries, seriesRules.numberOfDosesInSeries >= $doseNumber)
		not (ICEFactTypeFinding(iceResultFinding == SupportedFactConcept._BELOW_MINIMUM_AGE.conceptCodeValue, associatedTargetDose == $tdprev, associatedTargetDose.doseNumberInSeries == 1, associatedTargetDose.administeredShotNumberInSeries == $admindose-1))
		not ICEIntervalFactTypeFinding(intervalFactType == IntervalFactType.EVALUATION, iceResultFinding == SupportedFactConcept._DOSE_INTERVAL_OVERRIDE.conceptCodeValue, associatedCurrentTargetDose != null && associatedCurrentTargetDose == $td,
			associatedPreviousTargetDose != null && associatedPreviousTargetDose == $tdprev)
	then
		$ts.evaluateVaccineGroupMinimumIntervalAndRecordReason($td, $tdprev);
		if ($td.containsInvalidReason(BaseDataEvaluationReason._BELOW_MINIMUM_INTERVAL_EVALUATION_REASON.getCdsListItemName())) {
			ICEFactTypeFinding hef = new ICEFactTypeFinding(SupportedFactConcept._BELOW_MINIMUM_INTERVAL.getConceptCodeValue(), $td);
			insert(hef)
		}
		$td.addDoseRuleProcessed(drools.getRule().getName());
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $td.toString() + " in TargetSeries " + $ts.seriesName);
end

rule "HistoryEvaluation: Evaluate minimum interval between first shot in seasonal series and most recent shot from a prior season"
	ruleflow-group "HistoryEvaluation"
	dialect "mvel"
	activation-group "doseIntervalCheckFromPreviousSeason"
	salience 100
	when
		$td : TargetDose(status == DoseStatus.EVALUATION_IN_PROCESS, administeredShotNumberInSeries == 1, $doseNumber : doseNumberInSeries)
		$ts : TargetSeries(this == $td.associatedTargetSeries, seriesRules.numberOfDosesInSeries >= $doseNumber, targetSeason != null, $tseason : targetSeason,	$vaccineGroup : vaccineGroup, $tsid : targetSeriesIdentifier)
		$tsprev : TargetSeries(vaccineGroup == $vaccineGroup, targetDoses.size() > 0, targetSeriesIdentifier != $tsid, targetSeason != null, $tseasonPrev : targetSeason, targetSeason.getFullySpecifiedSeasonStartDate().isBefore($tseason.getFullySpecifiedSeasonStartDate()))
		not TargetSeries(targetSeriesIdentifier != $tsprev.targetSeriesIdentifier, targetSeason != null, vaccineGroup == $vaccineGroup,	targetDoses.size() > 0, targetSeason.fullySpecifiedSeasonStartDate.isAfter($tseasonPrev.getFullySpecifiedSeasonStartDate()) &&
			targetSeason.fullySpecifiedSeasonStartDate.isBefore($tseason.getFullySpecifiedSeasonStartDate()))
		$lastFromPrev: TargetDose(associatedTargetSeries == $tsprev, isShotIgnored() == false, $shotNumber: administeredShotNumberInSeries)
		not TargetDose(associatedTargetSeries == $tsprev, isShotIgnored() == false, administeredShotNumberInSeries > $shotNumber)
	then
		$ts.evaluateVaccineGroupMinimumIntervalAndRecordReason($td, $lastFromPrev);
		if ($td.containsInvalidReason(BaseDataEvaluationReason._BELOW_MINIMUM_INTERVAL_EVALUATION_REASON.getCdsListItemName())) {
			ICEFactTypeFinding hef = new ICEFactTypeFinding(SupportedFactConcept._BELOW_MINIMUM_INTERVAL.getConceptCodeValue(), $td);
			insert(hef);
		}
		$td.addDoseRuleProcessed(drools.getRule().getName());
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $td.toString() + " in " + $ts + "; Prior Dose " + $lastFromPrev + " in " + $tsprev);
end

rule "HistoryEvaluation: Evaluate Shot as Invalid if it is not between the Season Start and End Dates"
	ruleflow-group "HistoryEvaluation"
	dialect "mvel"
	activation-group "doseInSeasonCheck"
	salience 100
	when
		$td : TargetDose(status == DoseStatus.EVALUATION_IN_PROCESS, $administrationDate : administrationDate)
		$ts : TargetSeries(this == $td.associatedTargetSeries, targetSeason != null, targetSeason.dateIsApplicableToSeason($administrationDate, false) == false)
	then
		$td.addInvalidReason(BaseDataEvaluationReason._OUTSIDE_SEASON_REASON.getCdsListItemName());
		$td.addDoseRuleProcessed(drools.getRule().getName());
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), $td.toString() + " in TargetSeries " + $ts.seriesName);
end

rule "HistoryEvaluation: If all shots have been evaluated, take immunity dates into account to determine if series is complete"
	ruleflow-group "HistoryEvaluation"
	dialect "mvel"
	when
		$ts : TargetSeries(isSeriesComplete() == false)
		not TargetDose(hasBeenEvaluated == false) from $ts.targetDoses
		$diseaseImmunitiesRecordedForTargetSeries : List(size > 0) from accumulate(DiseaseImmunity($diseaseacc : disease memberOf $ts.diseasesSupportedByThisSeries), collectList($diseaseacc))
		TargetSeries(this == $ts, $numberOfDosesInSeries : seriesRules.numberOfDosesInSeries, $diseasesOfInterest : allEvaluationValidityCountsByDisease.keySet())
		eval($diseasesOfInterest.removeAll($diseaseImmunitiesRecordedForTargetSeries) == true && $ts.determineEffectiveNumberOfDosesInSeriesForSpecifiedDiseasesOnly($diseasesOfInterest) == $ts.seriesRules.numberOfDosesInSeries)
	then
		modify($ts) {
			setSeriesComplete(true)
		};
		for (String diseaseImmunityRecorded : $diseaseImmunitiesRecordedForTargetSeries) {
			ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "in TargetSeries " + $ts.seriesName + "; Disease Immunity Recorded: " + diseaseImmunityRecorded);
		}
		Set lDiseasesOfInterest = $ts.getAllEvaluationValidityCountsByDisease.keySet();
		lDiseasesOfInterest.removeAll($diseaseImmunitiesRecordedForTargetSeries);
		for (String disease : lDiseasesOfInterest) {
			ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "in TargetSeries " + $ts.seriesName + "; disease of interest: " + disease);
		}
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "in TargetSeries " + $ts.seriesName + "; determineEffective..." + $ts.determineEffectiveNumberOfDosesInSeriesForSpecifiedDiseasesOnly(lDiseasesOfInterest));
end

rule "HistoryEvaluation: Set Disease Immunity Flag in Series to True if Immune to All Diseases Tracked by this Series as of the Evaluation Time"
	ruleflow-group "HistoryEvaluation"
	dialect "mvel"
	when
		$ts : TargetSeries($diseasesSupportedByThisSeries : diseasesSupportedByThisSeries, isImmunityToAllDiseasesRecorded() == false)
		not TargetDose(hasBeenEvaluated == false) from $ts.targetDoses
		Set(size == $diseasesSupportedByThisSeries.size()) from accumulate($di : DiseaseImmunity(dateOfImmunity <= evalTime, disease memberOf $diseasesSupportedByThisSeries), collectSet($di.disease))
	then
		modify($ts) {
			setImmunityToAllDiseasesRecorded(true)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetSeries immunityToAllDiseasesRecorded set to true for " + $ts.seriesName);
end

rule "SeriesSelection: Insert TargetSeriesSelection (Tracker) on to the Fact List for each Vaccine Group/Season"
	ruleflow-group "SeriesSelection"
	dialect "java"
	salience 10
	when
		$tseries : TargetSeries($vg : getVaccineGroup(), $tseason : getTargetSeason())
		not (TargetSeriesSelection(getSeriesSelectionVaccineGroup() == $vg, getSeriesSelectionSeason() == $tseason))
	then
		TargetSeriesSelection tss = new TargetSeriesSelection($tseries, schedule);
		insert(tss);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetSeriesSelection added to fact list: " + tss.toString());
end

rule "SeriesSelection: Initialize Next Non-Seasonal TargetSeriesSelection"
	ruleflow-group "SeriesSelection"
	dialect "mvel"
	when
		$tss : TargetSeriesSelection(seriesSelectionStatus == SeriesSelectionStatus.SERIES_SELECTION_NOT_STARTED, seriesSelectionSeason == null)

		not TargetSeriesSelection(seriesSelectionStatus == SeriesSelectionStatus.SERIES_SELECTION_NOT_STARTED, seriesSelectionVaccineGroup != $tss.seriesSelectionVaccineGroup, seriesSelectionPriority > $tss.seriesSelectionPriority, seriesGroup < $tss.seriesGroup)
	then
		modify ($tss) {
			setSeriesSelectionStatus(SeriesSelectionStatus.SERIES_SELECTION_IN_PREPROCESS)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetSeriesSelection Initialized " + $tss.toString() + ", Vaccine Group Priority " + $tss.seriesSelectionPriority);
end

rule "SeriesSelection: Initialize Next Seasonal TargetSeriesSelection"
	ruleflow-group "SeriesSelection"
	dialect "mvel"
	when
		$tss : TargetSeriesSelection(seriesSelectionStatus == SeriesSelectionStatus.SERIES_SELECTION_NOT_STARTED, seriesSelectionSeason != null)

		not TargetSeriesSelection(seriesSelectionStatus == SeriesSelectionStatus.SERIES_SELECTION_NOT_STARTED, seriesSelectionVaccineGroup != $tss.seriesSelectionVaccineGroup, seriesSelectionPriority > $tss.seriesSelectionPriority, seriesGroup < $tss.seriesGroup)
		not TargetSeriesSelection(seriesSelectionStatus == SeriesSelectionStatus.SERIES_SELECTION_NOT_STARTED, seriesSelectionVaccineGroup == $tss.seriesSelectionVaccineGroup,
			seriesSelectionSeason != null && seriesSelectionSeason.fullySpecifiedSeasonStartDate.isBefore($tss.seriesSelectionSeason.fullySpecifiedSeasonStartDate))
	then
		modify ($tss) {
			setSeriesSelectionStatus(SeriesSelectionStatus.SERIES_SELECTION_IN_PREPROCESS)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetSeriesSelection Initialized " + $tss.toString() + ", Vaccine Group Priority " + $tss.seriesSelectionPriority);
		drools.setFocus("SeriesSelection^SeasonalSeriesPatientAgeOfInterest");
end

rule "SeriesSelection: Default Series Selection Preprocess rule: invoke custom rules"
	ruleflow-group "SeriesSelection"
	dialect "mvel"
	when
		$tss : TargetSeriesSelection(seriesSelectionStatus == SeriesSelectionStatus.SERIES_SELECTION_IN_PREPROCESS)
	then
		$tss.setSeriesSelectionStatus(SeriesSelectionStatus.SERIES_SELECTION_IN_PROCESS);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Invoking Series Selection rules for vaccine group: " + $tss.seriesSelectionVaccineGroup);
		update($tss);
		drools.setFocus("SeriesSelection^customSeriesSelectionRules");
end

rule "SeriesSelection: For the Seasonal Series being evaluated for SeriesSelection that is not in the current season, set patient age time of interest to last date of season if no shots administered and invoke custom rules"
	dialect "mvel"
	ruleflow-group "SeriesSelection^SeasonalSeriesPatientAgeOfInterest"
	when
		$tss : TargetSeriesSelection(seriesSelectionStatus == SeriesSelectionStatus.SERIES_SELECTION_IN_PREPROCESS, seriesSelectionSeason != null)
		not TargetSeries(seriesRules.vaccineGroup == $tss.seriesSelectionVaccineGroup, selectedSeries == true, targetSeason == $tss.seriesSelectionSeason)
		$ts : TargetSeries(vaccineGroup == $tss.seriesSelectionVaccineGroup, selectedSeries == false,	targetSeason == $tss.seriesSelectionSeason, numberOfShotsAdministeredInSeries == 0)
		exists TargetSeries(vaccineGroup == $tss.seriesSelectionVaccineGroup, targetSeason != null, targetSeason.fullySpecifiedSeasonStartDate.isAfter($ts.targetSeason.fullySpecifiedSeasonStartDate))
	then
		kcontext.getKieRuntime().setGlobal("patientAgeTimeOfInterest", ICELogicHelper.toDate($ts.targetSeason.fullySpecifiedSeasonEndDate));
		$tss.setSeriesSelectionStatus(SeriesSelectionStatus.SERIES_SELECTION_IN_PROCESS);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "SeriesSelection: patientAgeTimeOfInterest set to season end date: " + ICELogicHelper.toDate($ts.targetSeason.fullySpecifiedSeasonEndDate));
		update($tss);
		drools.setFocus("SeriesSelection^customSeriesSelectionRules");
end

rule "SeriesSelection: For the Seasonal Series being evaluated for SeriesSelection that is not in the current season, set patient age time of interest to last shot of the series and invoke custom rules"
	dialect "mvel"
	ruleflow-group "SeriesSelection^SeasonalSeriesPatientAgeOfInterest"
	when
		$tss : TargetSeriesSelection(seriesSelectionStatus == SeriesSelectionStatus.SERIES_SELECTION_IN_PREPROCESS, seriesSelectionSeason != null)
		not TargetSeries(seriesRules.vaccineGroup == $tss.seriesSelectionVaccineGroup, selectedSeries == true, targetSeason == $tss.seriesSelectionSeason)
		$ts : TargetSeries(vaccineGroup == $tss.seriesSelectionVaccineGroup, selectedSeries == false,	targetSeason == $tss.seriesSelectionSeason, numberOfShotsAdministeredInSeries > 0)
		exists TargetSeries(vaccineGroup == $tss.seriesSelectionVaccineGroup, targetSeason != null, targetSeason.fullySpecifiedSeasonStartDate.isAfter($ts.targetSeason.fullySpecifiedSeasonStartDate))
	then
		kcontext.getKieRuntime().setGlobal("patientAgeTimeOfInterest", $ts.lastShotAdministeredInSeries.administrationDate);
		$tss.setSeriesSelectionStatus(SeriesSelectionStatus.SERIES_SELECTION_IN_PROCESS);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "SeriesSelection: patientAgeTimeOfInterest set to last shot date in series: " + $ts.lastShotAdministeredInSeries.administrationDate);
		update($tss);
		drools.setFocus("SeriesSelection^customSeriesSelectionRules");
end

rule "SeriesSelection: For the Seasonal Series being evaluated for SeriesSelection that is in the current season, set patient age time of interest to the execution time and invoke custom rules"
	dialect "mvel"
	ruleflow-group "SeriesSelection^SeasonalSeriesPatientAgeOfInterest"
	when
		$tss : TargetSeriesSelection(seriesSelectionStatus == SeriesSelectionStatus.SERIES_SELECTION_IN_PREPROCESS, seriesSelectionSeason != null)
		not TargetSeries(seriesRules.vaccineGroup == $tss.seriesSelectionVaccineGroup, selectedSeries == true, targetSeason == $tss.seriesSelectionSeason)
		$ts : TargetSeries(vaccineGroup == $tss.seriesSelectionVaccineGroup, selectedSeries == false, targetSeason == $tss.seriesSelectionSeason)
		not TargetSeries(vaccineGroup == $tss.seriesSelectionVaccineGroup, targetSeason != null, targetSeason.fullySpecifiedSeasonStartDate.isAfter($ts.targetSeason.fullySpecifiedSeasonStartDate))
	then
		kcontext.getKieRuntime().setGlobal("patientAgeTimeOfInterest", evalTime);
		$tss.setSeriesSelectionStatus(SeriesSelectionStatus.SERIES_SELECTION_IN_PROCESS);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "SeriesSelection: patientAgeTimeOfInterest set to execution time: " + evalTime);
		update($tss);
		drools.setFocus("SeriesSelection^customSeriesSelectionRules");
end

rule "SeriesSelection: Change Series Selection Status To Complete"
	ruleflow-group "SeriesSelection"
	dialect "mvel"
	salience 40
	when
		$tss : TargetSeriesSelection($ssvg : seriesSelectionVaccineGroup,
			seriesSelectionStatus == SeriesSelectionStatus.SERIES_SELECTION_IN_PROCESS || seriesSelectionStatus == SeriesSelectionStatus.SERIES_SELECTION_IN_POSTPROCESS, $sss : seriesSelectionSeason)
		TargetSeries(seriesRules.vaccineGroup == $ssvg, selectedSeries == true, targetSeason == $sss)
		not (TargetSeries(seriesRules.vaccineGroup == $ssvg, selectedSeries == false, targetSeason == $sss))
	then
		$tss.setSeriesSelectionStatus(SeriesSelectionStatus.SERIES_SELECTION_COMPLETE);
		update($tss);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetSeriesSelection: " + $tss.toString() + "; *Series* *Selected* " + $tss.getSelectedSeriesName());
end

rule "SeriesSelection: Retract All Series Not Selected in the same Series Group and Vaccine Group"
	ruleflow-group "SeriesSelection"
	dialect "mvel"
	salience 50
	when
		$tss : TargetSeriesSelection($ssvg : seriesSelectionVaccineGroup, $sss : seriesSelectionSeason,
			seriesSelectionStatus == SeriesSelectionStatus.SERIES_SELECTION_IN_PROCESS || seriesSelectionStatus == SeriesSelectionStatus.SERIES_SELECTION_IN_POSTPROCESS ||	seriesSelectionStatus == SeriesSelectionStatus.SERIES_SELECTION_COMPLETE)
		$selected : TargetSeries(seriesRules.vaccineGroup == $ssvg, selectedSeries == true, targetSeason == $sss)
		$ts : TargetSeries(seriesRules.vaccineGroup == $ssvg, selectedSeries == false, targetSeason == $sss, seriesRules.seriesGroup == $tss.seriesGroup)
	then
		for (TargetDose d : $ts.targetDoses) {
			ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetDose Retracted: " + d);
			retract(d);
		}
		retract($ts);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetSeries Retracted: " + $ts);
end

rule "SeriesSelection: Select already completed series that has the fewest doses defined if exists and no series was previously selected"
	ruleflow-group "SeriesSelection"
	dialect "mvel"
	activation-group "SeriesSelectionFewestDoses"
	salience 60
	when
		$tss : TargetSeriesSelection(seriesSelectionStatus == SeriesSelectionStatus.SERIES_SELECTION_IN_PROCESS || seriesSelectionStatus == SeriesSelectionStatus.SERIES_SELECTION_IN_POSTPROCESS)
		not (TargetSeries(selectedSeries == true, seriesRules.vaccineGroup == $tss.seriesSelectionVaccineGroup, targetSeason == $tss.seriesSelectionSeason))
		$ts1 : TargetSeries(seriesRules.vaccineGroup == $tss.seriesSelectionVaccineGroup, isSeriesComplete() == true, $numberOfDosesInSeries1 : seriesRules.numberOfDosesInSeries, targetSeason == $tss.seriesSelectionSeason)
		not (TargetSeries(seriesRules.vaccineGroup == $tss.seriesSelectionVaccineGroup, isSeriesComplete() == true, $numberOfDosesInSeries1 > seriesRules.numberOfDosesInSeries, targetSeason == $tss.seriesSelectionSeason, seriesRules.seriesGroup == $tss.seriesGroup))
	then
		$ts1.setSelectedSeries(true);
		$tss.setSelectedSeriesName($ts1.seriesName);
		$tss.setSeriesSelectionStatus(SeriesSelectionStatus.SERIES_SELECTION_COMPLETE);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "SeriesSelection: TargetSeries " + $ts1);
		update($ts1);
		update($tss);
end

rule "SeriesSelection: Select already _completed_ series with earliest completion date if exists and a different, _completed_ series was previously selected"
	ruleflow-group "SeriesSelection"
	dialect "java"
	salience 60
	activation-group "SeriesSelectionFewestDoses"
	when
		$tss : TargetSeriesSelection(seriesSelectionStatus == SeriesSelectionStatus.SERIES_SELECTION_IN_PROCESS || seriesSelectionStatus == SeriesSelectionStatus.SERIES_SELECTION_IN_POSTPROCESS)
		$ts1 : TargetSeries(seriesRules.vaccineGroup == $tss.seriesSelectionVaccineGroup, $id1 : targetSeriesIdentifier, selectedSeries == true, targetSeason == $tss.seriesSelectionSeason, $seriesComplete1 : isSeriesComplete(),
			$seriesGroup1 : seriesRules.SeriesGroup, $lastNecessaryShotAdministered1 : getValidShotByDoseNumber(seriesRules.numberOfDosesInSeries))
		$ts2 : TargetSeries(seriesRules.vaccineGroup == $tss.seriesSelectionVaccineGroup, targetSeriesIdentifier != $ts1.targetSeriesIdentifier, selectedSeries == false, targetSeason == $tss.seriesSelectionSeason, $seriesComplete2 : isSeriesComplete(),
			$seriesGroup2 : seriesRules.seriesGroup, $lastAdministeredShot2InSeries: lastShotAdministeredInSeries, $lastNecessaryShotAdministered2 : getValidShotByDoseNumber(seriesRules.numberOfDosesInSeries))
		eval($seriesComplete1 == true && $seriesComplete2 == true && $seriesGroup1 == $seriesGroup2 && ($lastAdministeredShot2InSeries == null ||
			($lastNecessaryShotAdministered1 != null && $lastNecessaryShotAdministered2 != null && $lastNecessaryShotAdministered2.getAdministrationDate() != null &&
				$lastNecessaryShotAdministered2.getAdministrationDate().before($lastNecessaryShotAdministered1.getAdministrationDate()))))
	then
		$ts1.setSelectedSeries(false);
		$ts2.setSelectedSeries(true);
		$tss.setSelectedSeriesName($ts2.getSeriesName());
		$tss.setSeriesSelectionStatus(SeriesSelectionStatus.SERIES_SELECTION_COMPLETE);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Previously Selected TargetSeries Retracted for Already Complete Series: " + $ts2);
		update($ts1);
		update($ts2);
end

rule "SeriesSelection.SelectOnlySeriesRemainingInVaccineGroup"
	ruleflow-group "SeriesSelection"
	dialect "mvel"
	salience 100
	when
		$tss : TargetSeriesSelection(seriesSelectionStatus == SeriesSelectionStatus.SERIES_SELECTION_IN_PROCESS || seriesSelectionStatus == SeriesSelectionStatus.SERIES_SELECTION_IN_POSTPROCESS)
		not TargetSeries(seriesRules.vaccineGroup == $tss.seriesSelectionVaccineGroup, selectedSeries == true)
		$ts : TargetSeries(seriesRules.vaccineGroup == $tss.seriesSelectionVaccineGroup, selectedSeries == false)
		accumulate($tsthis : TargetSeries(vaccineGroup == $tss.seriesSelectionVaccineGroup); $countInVG : count($tsthis); $countInVG == 1)
	then
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "SeriesSelection: TargetSeries " + $ts);
		$ts.setSelectedSeries(true);
		$tss.setSelectedSeriesName($ts.seriesName);
		update($ts);
end

rule "RecommendationForecast: Make a Record of all Non-Seasonal TargetSeries of the Vaccine Group for Series Selection Display purposes, if the Series Selection Display Option is Enabled"
	ruleflow-group "RecommendationForecast"
	dialect "mvel"
	when
		exists (ICEFactTypeFinding(iceResultFinding == SupportedFactConcept._OUTPUT_NUMBER_OF_DOSES_REMAINING.conceptCodeValue))
		$ts : TargetSeries(isSelectedSeries() == true, targetSeason == null)
		not SeriesDisplaySelection(targetSeries == $ts)
	then
		SeriesDisplaySelection ss = new SeriesDisplaySelection($ts);
		insert(ss);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Series Selection \": " + $ts.seriesName);
end

rule "RecommendationForecast: Maka a Record of Seasonal TargetSeries in the Current Season of the Vaccine Group for Series Selection Display purposes, if the Series Selection Display Option is Enabled"
	ruleflow-group "RecommendationForecast"
	dialect "mvel"
	when
		exists (ICEFactTypeFinding(iceResultFinding == SupportedFactConcept._OUTPUT_NUMBER_OF_DOSES_REMAINING.conceptCodeValue))
		$ts : TargetSeries(isSelectedSeries() == true, targetSeason != null, isSeriesComplete() == false)
		not SeriesDisplaySelection(targetSeries == $ts)
		not TargetSeries(vaccineGroup == $ts.vaccineGroup, targetSeason != null, targetSeason.fullySpecifiedSeasonStartDate.isAfter($ts.targetSeason.fullySpecifiedSeasonStartDate))
	then
		SeriesDisplaySelection ss = new SeriesDisplaySelection($ts);
		insert(ss);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Series Selection \": " + $ts.seriesName);
end

rule "RecommendationForecast.findMostRecentAdministeredLiveVirusVaccineDate"
	ruleflow-group "RecommendationForecast"
	dialect "mvel"
	salience 10
	when
		$lvd : LiveVirusFact(LiveVirusDateSet == false)
		exists (TargetSeries(recommendationStatus == RecommendationStatus.NOT_FORECASTED))
		exists (TargetDose(vaccineComponent.isLiveVirusVaccine == true))
		$maxdate : Date() from accumulate(TargetDose(vaccineComponent.isLiveVirusVaccine == true, $date : administrationDate), maxDate($date))
	then
		modify($lvd) {
			setLiveVirusDate($maxdate),
			setLiveVirusDateSet(true)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Found most recent live virus vaccine administered on " + $lvd.getLiveVirusDate());
end

rule "RecommendationForecast.findMostRecentAdministeredSelectAdjuvantProductVaccineDate"
	ruleflow-group "RecommendationForecast"
	dialect "mvel"
	salience 10
	when
		$dft : DateFactType(factName == "SELECT_ADJUVANT_PRODUCT_INTERVAL", factDateSet == false)
		exists (TargetSeries(recommendationStatus == RecommendationStatus.NOT_FORECASTED))
		exists (TargetDose(vaccineComponent.isSelectAdjuvantProduct == true))
		$maxdate : Date() from accumulate(TargetDose(vaccineComponent.isSelectAdjuvantProduct == true, $date : administrationDate), maxDate($date))
	then
		modify($dft) {
			setFactDate($maxdate)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Found most recent adjuvant product vaccine administered on " + $dft.getFactDate());
end

rule "RecommendationForecast.setNextSeasonalTargetSeriesForRecommendation"
	ruleflow-group "RecommendationForecast"
	dialect "mvel"
	when

		not TargetSeries(recommendationStatus == RecommendationStatus.FORECASTING_IN_PROGRESS || recommendationStatus == RecommendationStatus.FORECASTING_COMPLETE)
		$ts: TargetSeries(recommendationStatus == RecommendationStatus.NOT_FORECASTED, isSelectedSeries() == true, targetSeason != null)
		not TargetSeries(vaccineGroup == $ts.vaccineGroup, targetSeason != null, targetSeason.fullySpecifiedSeasonStartDate.isAfter($ts.targetSeason.fullySpecifiedSeasonStartDate))
		(
			TargetSeries(this == $ts, seriesRules.seriesGroup <= 0 || seriesRules.seriesGroup > 0 && seriesRules.seriesEndAge == null)
			or
        	not TargetSeries(this != $ts, vaccineGroup == $ts.vaccineGroup, targetSeason == null, $ts.seriesEndAgeDate != null, seriesStartAgeDate != null && seriesStartAgeDate > $ts.seriesEndAgeDate)
        )
	then
		modify($ts) {
			setRecommendationStatus(RecommendationStatus.FORECASTING_IN_PROGRESS)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Forecasting TargetSeries " + $ts);
		drools.setFocus("RecommendationForecast^preRecommendationValidation");
end

rule "RecommendationForecast.setNextNonSeasonalTargetSeriesForRecommendation"
	ruleflow-group "RecommendationForecast"
	dialect "mvel"
	when

		not TargetSeries(recommendationStatus == RecommendationStatus.FORECASTING_IN_PROGRESS || recommendationStatus == RecommendationStatus.FORECASTING_COMPLETE)
		$ts: TargetSeries(recommendationStatus == RecommendationStatus.NOT_FORECASTED, isSelectedSeries() == true, targetSeason == null)
		(
			TargetSeries(this == $ts, seriesRules.seriesGroup <= 0 || seriesRules.seriesGroup > 0 && seriesRules.seriesEndAge == null)
			or
        	not TargetSeries(this != $ts, vaccineGroup == $ts.vaccineGroup, $ts.seriesEndAgeDate != null, seriesStartAgeDate != null && seriesStartAgeDate > $ts.seriesEndAgeDate)
        )
	then
		RecommendationStatus newRecommendationStatus = RecommendationStatus.FORECASTING_IN_PROGRESS;
		modify($ts) {
			setRecommendationStatus(newRecommendationStatus)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Forecasting TargetSeries " + $ts);
		drools.setFocus("RecommendationForecast^preRecommendationValidation");
end

rule "RecommendationForecast.applyPostRecommendationCheck"
	ruleflow-group "RecommendationForecast"
	dialect "mvel"
	salience 20
	no-loop true
	when
		$targetSeries : TargetSeries(isPostForecastCheckCompleted() == false &&
			(recommendationStatus == RecommendationStatus.RECOMMENDED || recommendationStatus == RecommendationStatus.RECOMMENDED_IN_FUTURE ||
			recommendationStatus == RecommendationStatus.CONDITIONALLY_RECOMMENDED || recommendationStatus == RecommendationStatus.NOT_RECOMMENDED))
	then
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Post recommendation check for TargetSeries " + $targetSeries.getSeriesName());

		update($targetSeries);
		drools.setFocus("RecommendationForecast^postRecommendationCheck");
		drools.setFocus("RecommendationForecast^postCustomRecommendationCheck");
end

rule "RecommendationForecast.noteCompletionOfPostRecommendationCheck - Do _not_ reprocess recommendation rules"
	ruleflow-group "RecommendationForecast"
dialect "mvel"
	salience 10
	when
		$targetSeries : TargetSeries(isPostForecastCheckCompleted() == false,
			(recommendationStatus == RecommendationStatus.RECOMMENDED || recommendationStatus == RecommendationStatus.RECOMMENDED_IN_FUTURE ||
				recommendationStatus == RecommendationStatus.CONDITIONALLY_RECOMMENDED || recommendationStatus == RecommendationStatus.NOT_RECOMMENDED))
    then
        modify($targetSeries) {
            setRecommendationStatus(RecommendationStatus.FORECASTING_COMPLETE),
            setPostForecastCheckCompleted(true)
        };
        ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Note Completion of Post recommendation check for TargetSeries " + $targetSeries.getSeriesName());
end

rule "RecommendationForecast.noteCompletionOfPostRecommendationCheck - _Do_ reprocess recommendation rules"
	dialect "mvel"
	ruleflow-group "RecommendationForecast^postRecommendationCheck"
	when
		$targetSeries : TargetSeries(isPostForecastCheckCompleted() == false, recommendationStatus == RecommendationStatus.FORECASTING_IN_PROGRESS)
	then
		modify($targetSeries) {
			clearRecommendations(),
			setPostForecastCheckCompleted(true)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Note Completion of Post recommendation check for TargetSeries " + $targetSeries.getSeriesName());
		drools.setFocus("RecommendationForecast^preRecommendationValidation");
end

rule "RecommendationForecast.adjustEarliestDateDueToLiveVirusToFutureDate"
	dialect "mvel"
	ruleflow-group "RecommendationForecast^supplementalSeriesRule"
	when
		$lvd : LiveVirusFact(liveVirusDate != null, liveVirusDateSet == true)
		$targetSeries : TargetSeries($earliestDate : getFinalEarliestDate() != null,
			(recommendationStatus == RecommendationStatus.RECOMMENDED || recommendationStatus == RecommendationStatus.RECOMMENDED_IN_FUTURE ||
				recommendationStatus == RecommendationStatus.CONDITIONALLY_RECOMMENDED), isRecommendedVaccineOrVaccineGroupLevelRecommendationAnExpectedLiveVirusVaccine() == true,
				liveVirusDatesAccountedForInRecommendedFinalEarliestDate not contains $lvd.liveVirusDate)
		eval((TimePeriod.differenceInDays($lvd.liveVirusDate, evalTime) != 0 &&
			TimePeriod.calculateElapsedTimePeriod($lvd.liveVirusDate, $earliestDate, DurationType.DAYS, false).isLessThan(new TimePeriod(28, DurationType.DAYS))) ||
			(TimePeriod.differenceInDays($lvd.liveVirusDate, evalTime) == 0 &&
			(TimePeriod.calculateElapsedTimePeriod($lvd.liveVirusDate, $earliestDate, DurationType.DAYS, false).isLessThan(new TimePeriod(28, DurationType.DAYS)) &&
			TimePeriod.calculateElapsedTimePeriod($lvd.liveVirusDate, $earliestDate, DurationType.DAYS, false).isGreaterThan(new TimePeriod(0, DurationType.DAYS)))))
	then
		Date newRecommendationDate = TimePeriod.addTimePeriod($lvd.liveVirusDate, new TimePeriod(28, DurationType.DAYS));
		modify($targetSeries) {
			setFinalEarliestDate(newRecommendationDate),
			addLiveVirusDateAccountedForInRecommendedFinalEarliestDate($lvd.liveVirusDate),
			addSeriesRuleProcessed(drools.getRule().getName())
		};
      	ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Earliest date adjustment from " + $earliestDate + " to " + newRecommendationDate + " due to live virus vaccine administered on : " + $lvd.liveVirusDate + " in TargetSeries " + $targetSeries.getSeriesName());
end

rule "RecommendationForecast.adjustPriorEarliestDateDueToLiveVirusToCurrentDate"
	dialect "mvel"
	ruleflow-group "RecommendationForecast^supplementalSeriesRule"
	when
		$lvd : LiveVirusFact(liveVirusDate != null, liveVirusDateSet == true)
		$targetSeries : TargetSeries($earliestDate : getFinalEarliestDate() != null, $earliestDate < $lvd.liveVirusDate,
			(recommendationStatus == RecommendationStatus.RECOMMENDED || recommendationStatus == RecommendationStatus.RECOMMENDED_IN_FUTURE ||
				recommendationStatus == RecommendationStatus.CONDITIONALLY_RECOMMENDED), isRecommendedVaccineOrVaccineGroupLevelRecommendationAnExpectedLiveVirusVaccine() == true,
				liveVirusDatesAccountedForInRecommendedFinalEarliestDate not contains $lvd.liveVirusDate)
		eval(TimePeriod.differenceInDays($lvd.liveVirusDate, evalTime) == 0 &&
			TimePeriod.calculateElapsedTimePeriod($lvd.liveVirusDate, $earliestDate, DurationType.DAYS, false).isLessThan(new TimePeriod(-28, DurationType.DAYS)))
	then
		modify($targetSeries) {
			setFinalEarliestDate($lvd.liveVirusDate),
			addLiveVirusDateAccountedForInRecommendedFinalEarliestDate($lvd.liveVirusDate),
			addSeriesRuleProcessed(drools.getRule().getName())
		};
      	ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Earliest date adjustment from " + $earliestDate + " to " + $lvd.liveVirusDate + " due to live virus vaccine administered on : " + $lvd.liveVirusDate + " in TargetSeries " + $targetSeries.getSeriesName());
end

rule "RecommendationForecast.adjustRecommendedDateDueToLiveVirusToFutureDate"
	dialect "mvel"
	ruleflow-group "RecommendationForecast^supplementalSeriesRule"
	when
		$lvd : LiveVirusFact(liveVirusDate != null, liveVirusDateSet == true)
		$targetSeries : TargetSeries($recommendationDueDate : getFinalRecommendationDate() != null,
			(recommendationStatus == RecommendationStatus.RECOMMENDED || recommendationStatus == RecommendationStatus.RECOMMENDED_IN_FUTURE ||
				recommendationStatus == RecommendationStatus.CONDITIONALLY_RECOMMENDED), isRecommendedVaccineOrVaccineGroupLevelRecommendationAnExpectedLiveVirusVaccine() == true,
				liveVirusDatesAccountedForInRecommendedFinalDate not contains $lvd.liveVirusDate)
		eval((TimePeriod.differenceInDays($lvd.liveVirusDate, evalTime) != 0 &&
			TimePeriod.calculateElapsedTimePeriod($lvd.liveVirusDate, $recommendationDueDate, DurationType.DAYS, false).isLessThan(new TimePeriod(28, DurationType.DAYS))) ||
			(TimePeriod.differenceInDays($lvd.liveVirusDate, evalTime) == 0 &&
			(TimePeriod.calculateElapsedTimePeriod($lvd.liveVirusDate, $recommendationDueDate, DurationType.DAYS, false).isLessThan(new TimePeriod(28, DurationType.DAYS)) &&
			TimePeriod.calculateElapsedTimePeriod($lvd.liveVirusDate, $recommendationDueDate, DurationType.DAYS, false).isGreaterThan(new TimePeriod(0, DurationType.DAYS)))))
	then
		Date newRecommendationDate = TimePeriod.addTimePeriod($lvd.liveVirusDate, new TimePeriod(28, DurationType.DAYS));
		modify($targetSeries) {
			setFinalRecommendationDate(newRecommendationDate),
			addLiveVirusDateAccountedForInRecommendedFinalDate($lvd.liveVirusDate),
			addSeriesRuleProcessed(drools.getRule().getName())
		};
      	ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "evalTime " + evalTime + "; Recommendation date adjustment from " + $recommendationDueDate + " to " + newRecommendationDate + " due to live virus vaccine administered on : " + $lvd.liveVirusDate + " in TargetSeries " + $targetSeries.getSeriesName());
end

rule "RecommendationForecast.adjustRecommendedDateDueToLiveVirusToCurrentDate"
	dialect "mvel"
	ruleflow-group "RecommendationForecast^supplementalSeriesRule"
	when
		$lvd : LiveVirusFact(liveVirusDate != null, liveVirusDateSet == true)
		$targetSeries : TargetSeries($recommendationDueDate : getFinalRecommendationDate() != null, $recommendationDueDate < $lvd.liveVirusDate,
			(recommendationStatus == RecommendationStatus.RECOMMENDED || recommendationStatus == RecommendationStatus.RECOMMENDED_IN_FUTURE ||
				recommendationStatus == RecommendationStatus.CONDITIONALLY_RECOMMENDED), isRecommendedVaccineOrVaccineGroupLevelRecommendationAnExpectedLiveVirusVaccine() == true,
				liveVirusDatesAccountedForInRecommendedFinalDate not contains $lvd.liveVirusDate)
		eval(TimePeriod.differenceInDays($lvd.liveVirusDate, evalTime) == 0 &&
			TimePeriod.calculateElapsedTimePeriod($lvd.liveVirusDate, $recommendationDueDate, DurationType.DAYS, false).isLessThan(new TimePeriod(-28, DurationType.DAYS)))
	then
		modify($targetSeries) {
			setFinalRecommendationDate($lvd.liveVirusDate),
			addLiveVirusDateAccountedForInRecommendedFinalDate($lvd.liveVirusDate),
			addSeriesRuleProcessed(drools.getRule().getName())
		};
      	ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "evalTime " + evalTime + "; Recommendation date adjustment from " + $recommendationDueDate + " to " + $lvd.liveVirusDate + " due to live virus vaccine administered on : " + $lvd.liveVirusDate + " in TargetSeries " + $targetSeries.getSeriesName());
end

rule "RecommendationForecast.adjustEarliestDateDueToSelectAdjuvantProductToFutureDate"
	dialect "mvel"
	ruleflow-group "RecommendationForecast^supplementalSeriesRule"
	when
		$dft : DateFactType(factName == "SELECT_ADJUVANT_PRODUCT_INTERVAL", factDate != null, factDateSet == true, $dftDate : factDate)
		$targetSeries : TargetSeries($earliestDate : getFinalEarliestDate() != null,
			(recommendationStatus == RecommendationStatus.RECOMMENDED || recommendationStatus == RecommendationStatus.RECOMMENDED_IN_FUTURE ||
				recommendationStatus == RecommendationStatus.CONDITIONALLY_RECOMMENDED), isRecommendedVaccineOrVaccineGroupLevelRecommendationAnExpectedSelectAdjuvantProduct() == true)
		eval((TimePeriod.differenceInDays($dftDate, evalTime) != 0 &&
			TimePeriod.calculateElapsedTimePeriod($dftDate, $earliestDate, DurationType.DAYS, false).isLessThan(new TimePeriod(28, DurationType.DAYS))) ||
			(TimePeriod.differenceInDays($dftDate, evalTime) == 0 &&
			(TimePeriod.calculateElapsedTimePeriod($dftDate, $earliestDate, DurationType.DAYS, false).isLessThan(new TimePeriod(28, DurationType.DAYS)) &&
			TimePeriod.calculateElapsedTimePeriod($dftDate, $earliestDate, DurationType.DAYS, false).isGreaterThan(new TimePeriod(0, DurationType.DAYS)))))
	then
		Date newRecommendationDate = TimePeriod.addTimePeriod($dftDate, new TimePeriod(28, DurationType.DAYS));
		modify($targetSeries) {
			setFinalEarliestDate(newRecommendationDate),
			addAdjuvantDateAccountedForInRecommendedFinalDate($dftDate),
			addSeriesRuleProcessed(drools.getRule().getName())
		};
      	ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Earliest date adjustment from " + $earliestDate + " to " + newRecommendationDate + " due to select adjuvant product administered on : " + $dftDate + " in TargetSeries " + $targetSeries.getSeriesName());
end

rule "RecommendationForecast.adjustEarliestDateDueToSelectAdjuvantProductToCurrentDate"
	dialect "mvel"
	ruleflow-group "RecommendationForecast^supplementalSeriesRule"
	when
		$dft : DateFactType(factName == "SELECT_ADJUVANT_PRODUCT_INTERVAL", factDate != null, factDateSet == true, $dftDate : factDate)
		$targetSeries : TargetSeries($earliestDate : getFinalEarliestDate() != null, $earliestDate < $dftDate,
			(recommendationStatus == RecommendationStatus.RECOMMENDED || recommendationStatus == RecommendationStatus.RECOMMENDED_IN_FUTURE ||
				recommendationStatus == RecommendationStatus.CONDITIONALLY_RECOMMENDED), isRecommendedVaccineOrVaccineGroupLevelRecommendationAnExpectedSelectAdjuvantProduct() == true)
		eval(TimePeriod.differenceInDays($dftDate, evalTime) == 0 &&
			TimePeriod.calculateElapsedTimePeriod($dftDate, $earliestDate, DurationType.DAYS, false).isLessThan(new TimePeriod(-28, DurationType.DAYS)))
	then
		modify($targetSeries) {
			setFinalEarliestDate($dftDate),
			addAdjuvantDateAccountedForInRecommendedFinalDate($dftDate),
			addSeriesRuleProcessed(drools.getRule().getName())
		};
      	ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Earliest date adjustment from " + $earliestDate + " to " + $dftDate + " due to select adjuvant product administered on : " + $dftDate + " in TargetSeries " + $targetSeries.getSeriesName());
end

rule "RecommendationForecast.adjustRecommendedDateDueToSelectAdjuvantProductToFutureDate"
	dialect "java"
	ruleflow-group "RecommendationForecast^supplementalSeriesRule"
	when
		$dft : DateFactType(factName == "SELECT_ADJUVANT_PRODUCT_INTERVAL", factDate != null, factDateSet == true, $dftDate : factDate)
		$targetSeries : TargetSeries($recommendationDueDate : getFinalRecommendationDate() != null,
			(recommendationStatus == RecommendationStatus.RECOMMENDED || recommendationStatus == RecommendationStatus.RECOMMENDED_IN_FUTURE ||
				recommendationStatus == RecommendationStatus.CONDITIONALLY_RECOMMENDED), isRecommendedVaccineOrVaccineGroupLevelRecommendationAnExpectedSelectAdjuvantProduct() == true)
		eval((TimePeriod.differenceInDays($dftDate, evalTime) != 0 &&
			TimePeriod.calculateElapsedTimePeriod($dftDate, $recommendationDueDate, DurationType.DAYS, false).isLessThan(new TimePeriod(28, DurationType.DAYS))) ||
			(TimePeriod.differenceInDays($dftDate, evalTime) == 0 &&
			(TimePeriod.calculateElapsedTimePeriod($dftDate, $recommendationDueDate, DurationType.DAYS, false).isLessThan(new TimePeriod(28, DurationType.DAYS)) &&
			TimePeriod.calculateElapsedTimePeriod($dftDate, $recommendationDueDate, DurationType.DAYS, false).isGreaterThan(new TimePeriod(0, DurationType.DAYS)))))
	then
		Date newRecommendationDate = TimePeriod.addTimePeriod($dftDate, new TimePeriod(28, DurationType.DAYS));
		modify($targetSeries) {
			setFinalRecommendationDate(newRecommendationDate),
			addAdjuvantDateAccountedForInRecommendedFinalDate($dftDate),
			addSeriesRuleProcessed(drools.getRule().getName())
		};
      	ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Recommendation date adjustment from " + $recommendationDueDate + " to " + newRecommendationDate + " due to select adjuvant product administered on : " + $dftDate + " in TargetSeries " + $targetSeries.getSeriesName());
end

rule "RecommendationForecast.adjustRecommendedDateDueToSelectAdjuvantProductToCurrentDate"
	dialect "java"
	ruleflow-group "RecommendationForecast^supplementalSeriesRule"
	when
		$dft : DateFactType(factName == "SELECT_ADJUVANT_PRODUCT_INTERVAL", factDate != null, factDateSet == true, $dftDate : factDate)
		$targetSeries : TargetSeries($recommendationDueDate : getFinalRecommendationDate() != null, $recommendationDueDate < $dftDate,
			(recommendationStatus == RecommendationStatus.RECOMMENDED || recommendationStatus == RecommendationStatus.RECOMMENDED_IN_FUTURE ||
				recommendationStatus == RecommendationStatus.CONDITIONALLY_RECOMMENDED), isRecommendedVaccineOrVaccineGroupLevelRecommendationAnExpectedSelectAdjuvantProduct() == true)
		eval(TimePeriod.differenceInDays($dftDate, evalTime) == 0 &&
			TimePeriod.calculateElapsedTimePeriod($dftDate, $recommendationDueDate, DurationType.DAYS, false).isLessThan(new TimePeriod(-28, DurationType.DAYS)))
	then
		modify($targetSeries) {
			setFinalRecommendationDate($dftDate),
			addAdjuvantDateAccountedForInRecommendedFinalDate($dftDate),
			addSeriesRuleProcessed(drools.getRule().getName())
		};
      	ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Recommendation date adjustment from " + $recommendationDueDate + " to " + $dftDate + " due to select adjuvant product administered on : " + $dftDate + " in TargetSeries " + $targetSeries.getSeriesName());
end

rule "RecommendationForecast.adjustTargetSeriesEnclosedRecommendationWithRespectToEvalTime"
	dialect "mvel"
	ruleflow-group "RecommendationForecast^supplementalSeriesRule"
	no-loop true
	when
		$targetSeries : TargetSeries($recommendationDueDate : finalRecommendationDate)
		List(size > 0) from	accumulate($recs : Recommendation((recommendationStatus == RecommendationStatus.NOT_FORECASTED && recommendationReason != null) ||
				(recommendationStatus == RecommendationStatus.RECOMMENDED && $recommendationDueDate > evalTime) ||
				(recommendationStatus == RecommendationStatus.RECOMMENDED_IN_FUTURE && $recommendationDueDate <= evalTime)) from $targetSeries.finalRecommendations, collectList($recs))
	then
		if ($targetSeries.adjustRecommendationStatusAndReasonByEvalTime(evalTime) == false) {
			for (Recommendation r : $targetSeries.getFinalRecommendations()) {
				if (r.getRecommendationStatus() == RecommendationStatus.NOT_FORECASTED) {
					r.setRecommendationStatus($targetSeries.getRecommendationStatus);
				}
			}
		}
		$targetSeries.addSeriesRuleProcessed(drools.getRule().getName());
      	ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Enclosed Recommendation statuses adjusted in TargetSeries " + $targetSeries.getSeriesName());
		update($targetSeries);
end

rule "RecommendationForecast.adjustRecommendedStatusAndEnclosedRecommendationsWithRespectToEvalTime"
	dialect "mvel"
	ruleflow-group "RecommendationForecast^supplementalSeriesRule"
	when
		$targetSeries : TargetSeries($recommendationDueDate : getFinalRecommendationDate() != null,
			(recommendationStatus == RecommendationStatus.RECOMMENDED || recommendationStatus == RecommendationStatus.RECOMMENDED_IN_FUTURE || recommendationStatus == RecommendationStatus.CONDITIONALLY_RECOMMENDED),
			$recommendationDueDate > evalTime && recommendationStatus == RecommendationStatus.RECOMMENDED || $recommendationDueDate <= evalTime && recommendationStatus == RecommendationStatus.RECOMMENDED_IN_FUTURE)
	then
		$targetSeries.adjustRecommendationStatusAndReasonByEvalTime(evalTime);
		$targetSeries.addSeriesRuleProcessed(drools.getRule().getName());
      	ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Recommendation status and enclosed Recommendations adjusted for " + $recommendationDueDate + " in TargetSeries " + $targetSeries.getSeriesName());
		update($targetSeries);
end

rule "RecommendationForecast.doNotReturnForecastDateForConditionalRecommendations"
	dialect "java"
	ruleflow-group "RecommendationForecast^supplementalSeriesRule"
	when
		$ts : TargetSeries(recommendationStatus == RecommendationStatus.CONDITIONALLY_RECOMMENDED, isForecastDateDisplayedForConditionalRecommendations() == false,
			finalRecommendationDate != null || finalEarliestDate != null || finalOverdueDate != null)
	then
		$ts.setFinalRecommendationDate(null);
		update($ts);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetSeries " + $ts.getSeriesName());
end

rule "RecommendationForecast.recommendedAtVaccineGroupLevelIfRecommendedVaccinesNotConsistentWithRecommendationObjects"
	dialect "mvel"
	ruleflow-group "RecommendationForecast^supplementalSeriesRule"
	when
		$ts : TargetSeries(recommendationStatus == RecommendationStatus.RECOMMENDED || recommendationStatus == RecommendationStatus.RECOMMENDED_IN_FUTURE ||
				recommendationStatus == RecommendationStatus.CONDITIONALLY_RECOMMENDED, finalRecommendations != null, $tsFinalRecommendations : finalRecommendations)
		Set(size > 1) from accumulate(Recommendation(recommendedVaccine != null, $accRecommendedVaccine : recommendedVaccine) from $tsFinalRecommendations, collectSet($accRecommendedVaccine))
	then
		$ts.setRecommendationVaccine(null);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetSeries " + $ts.seriesName);
end

rule "RecommendationForecast.recommendedAtVaccineGroupLevelIfRecommendedVaccinesNotConsistentWithTargetSeries"
	dialect "mvel"
	ruleflow-group "RecommendationForecast^supplementalSeriesRule"
	when
		$ts : TargetSeries(recommendationStatus == RecommendationStatus.RECOMMENDED || recommendationStatus == RecommendationStatus.RECOMMENDED_IN_FUTURE ||
			recommendationStatus == RecommendationStatus.CONDITIONALLY_RECOMMENDED, finalRecommendations != null, $tsFinalRecommendations : finalRecommendations, recommendationVaccine != null,
			$tsRecommendedVaccine: recommendationVaccine)
		Set(size > 0) from accumulate(Recommendation(recommendedVaccine != null, recommendedVaccine != $tsRecommendedVaccine, $accRecommendedVaccine : recommendedVaccine)
			from $tsFinalRecommendations, collectSet($accRecommendedVaccine))
	then
		$ts.setRecommendationVaccine(null);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetSeries " + $ts.seriesName);
end



rule "RecommendationForecast.recommendedAtVaccineLevelIfRecommendedVaccinesConsistentWithRecommendationObjects"
	dialect "mvel"
	ruleflow-group "RecommendationForecast^supplementalSeriesRule"
	when
		$ts : TargetSeries(recommendationStatus == RecommendationStatus.RECOMMENDED || recommendationStatus == RecommendationStatus.RECOMMENDED_IN_FUTURE ||
			recommendationStatus == RecommendationStatus.CONDITIONALLY_RECOMMENDED, finalRecommendations != null, $tsFinalRecommendations : finalRecommendations)
		$recommendationVaccineSet : Set(size == 1) from accumulate(Recommendation(recommendedVaccine != null, $accRecommendedVaccine : recommendedVaccine) from $tsFinalRecommendations, collectSet($accRecommendedVaccine))
		$tsSame : TargetSeries(targetSeriesIdentifier == $ts.targetSeriesIdentifier, recommendationVaccine == null || recommendationVaccine != null && recommendationVaccine memberOf $recommendationVaccineSet)
		$recommendationVaccineList : List() from accumulate($acc2Recommendation : Recommendation(recommendedVaccine != null) from $tsFinalRecommendations, collectList($acc2Recommendation))
	then
		Iterator iter = $recommendationVaccineSet.iterator();
		if (iter.hasNext()) {
			$ts.setRecommendationVaccine((Vaccine) iter.next());
		}
		Iterator iter2 = $recommendationVaccineList.iterator();
		while (iter2.hasNext()) {
			((Recommendation) iter2.next()).setRecommendedVaccine(null);
		}
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetSeries " + $ts.seriesName);
end

rule "RecommendationForecast.recommendedAtVaccineGroupLevelIfNotRecommendedForecast"
	dialect "mvel"
	ruleflow-group "RecommendationForecast^supplementalSeriesRule"
	when
		$ts : TargetSeries(recommendationStatus == RecommendationStatus.NOT_RECOMMENDED, finalRecommendations != null, $tsFinalRecommendations : finalRecommendations)
	then
		$ts.setRecommendationVaccine(null);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetSeries " + $ts.seriesName);
end

rule "RecommendationForecast.recommendEarliestDateOnOrAfterLastShotGiven"
	dialect "mvel"
	ruleflow-group "RecommendationForecast^adjustRecommendationDates"
	when
		$ts : TargetSeries(finalEarliestDate != null)
		$td : TargetDose(associatedTargetSeries == $ts, administrationDate > $ts.finalEarliestDate)
		not TargetDose(associatedTargetSeries == $ts, administrationDate > $td.administrationDate)
	then
		modify($ts) {
			setFinalEarliestDate($td.administrationDate)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetSeries " + $ts.seriesName);
end

rule "RecommendationForecast.recommendRecommendedDateOnOrAfterLastShotGiven"
	dialect "mvel"
	ruleflow-group "RecommendationForecast^adjustRecommendationDates"
	when
		$ts : TargetSeries(finalRecommendationDate != null)
		$td : TargetDose(associatedTargetSeries == $ts, administrationDate > $ts.finalRecommendationDate)
		not TargetDose(associatedTargetSeries == $ts, administrationDate > $td.administrationDate)
	then
		modify($ts) {
			setFinalRecommendationDate($td.administrationDate)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetSeries " + $ts.seriesName);
end

rule "RecommendationForecast.recommendOverdueDateOnOrAfterLastShotGiven"
	dialect "mvel"
	ruleflow-group "RecommendationForecast^adjustRecommendationDates"
	when
		$ts : TargetSeries(finalOverdueDate != null)
		$td : TargetDose(associatedTargetSeries == $ts, administrationDate > $ts.finalOverdueDate)
		not TargetDose(associatedTargetSeries == $ts, administrationDate > $td.administrationDate)
	then
		modify($ts) {
			setFinalOverdueDate($td.administrationDate)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetSeries " + $ts.seriesName);
end

rule "RecommendationForecast.finalizeRecommendationsForSeries"
	ruleflow-group "RecommendationForecast"
	dialect "mvel"
	when
		$ts : TargetSeries(recommendationStatus == RecommendationStatus.FORECASTING_COMPLETE)
		not Recommendation(targetSeriesIdentifier == $ts.targetSeriesIdentifier)
	then
		$ts.finalizeRecommendationsForForecasting();
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Finalized recommendations for TargetSeries " + $ts.getSeriesName());

		update($ts);
		drools.setFocus("RecommendationForecast^supplementalSeriesRule");
		drools.setFocus("RecommendationForecast^adjustRecommendationDates");
end

rule "RecommendationForecast.addAnyRecommendationsOnFactListToSeries"
	ruleflow-group "RecommendationForecast"
	dialect "mvel"
	when
		$ts : TargetSeries(recommendationStatus == RecommendationStatus.FORECASTING_COMPLETE)
		$recommendation : Recommendation(targetSeriesIdentifier == $ts.targetSeriesIdentifier)
	then
		$ts.addInterimRecommendationForConsideration($recommendation, evalTime);
		retract($recommendation);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Finalized recommendations for TargetSeries " + $ts.getSeriesName());
		update($ts);
end

rule "RecommendationForecast.allRecommendationRulesProcessedForSeries"
	ruleflow-group "RecommendationForecast"
	dialect "mvel"
	salience 95
	when
		$ts : TargetSeries(recommendationStatus == RecommendationStatus.FORECASTING_IN_PROGRESS)
	then
		modify($ts) {
			setRecommendationStatus(RecommendationStatus.FORECASTING_COMPLETE)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetSeries " + $ts.seriesName);
end

rule "RecommendationForecast.recommendBasedOnEarliestAgeRule"
	ruleflow-group "RecommendationForecast"
	dialect "mvel"
	salience 100
	activation-group "earliestAgeCheck"
	when

		$evalTime : EvalTime()
		$ts : TargetSeries(recommendationStatus == RecommendationStatus.FORECASTING_IN_PROGRESS)
		$person : EvaluatedPerson()
	then
		$ts.recommendNextShotBasedOnEarliestAgeRule($person.demographics.birthTime, $evalTime.getEvalTimeValue());
		$ts.addSeriesRuleProcessed(drools.getRule().getName());
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetSeries " + $ts.seriesName);
end

rule "RecommendationForecast.recommendBasedOnEarliestIntervalRule"
	ruleflow-group "RecommendationForecast"
	dialect "mvel"
	salience 100
	activation-group "earliestIntervalCheck"
	when
		$evalTime : EvalTime()
		$ts : TargetSeries(recommendationStatus == RecommendationStatus.FORECASTING_IN_PROGRESS)
		$td : TargetDose(associatedTargetSeries == $ts, isShotIgnored() == false)
		not TargetDose(associatedTargetSeries == $ts, administeredShotNumberInSeries > $td.administeredShotNumberInSeries, isShotIgnored() == false)
		not ICEIntervalFactTypeFinding(intervalFactType == IntervalFactType.RECOMMENDED, iceResultFinding == SupportedFactConcept._DOSE_INTERVAL_OVERRIDE.conceptCodeValue, associatedCurrentTargetDose == $td)

	then
		$ts.recommendNextShotBasedOnEarliestIntervalRule($evalTime.getEvalTimeValue());
		$ts.addSeriesRuleProcessed(drools.getRule().getName());
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetSeries " + $ts.seriesName);
end

rule "RecommendationForecast.recommendBasedOnLatestRecommendedAgeRule"
	ruleflow-group "RecommendationForecast"
	dialect "mvel"
	salience 100
	activation-group "latestRecommendedAgeCheck"
	when

		$evalTime : EvalTime()
		$ts : TargetSeries(recommendationStatus == RecommendationStatus.FORECASTING_IN_PROGRESS)
		$person : EvaluatedPerson()
	then
		$ts.recommendNextShotBasedOnLatestRecommendedAgeRule($person.demographics.birthTime, $evalTime.getEvalTimeValue());
		$ts.addSeriesRuleProcessed(drools.getRule().getName());
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetSeries " + $ts.seriesName);
end

rule "RecommendationForecast.recommendBasedOnLatestRecommendedIntervalRule"
	ruleflow-group "RecommendationForecast"
	dialect "mvel"
	salience 100
	activation-group "latestRecommendedIntervalCheck"
	when
		$evalTime : EvalTime()
		$ts : TargetSeries(recommendationStatus == RecommendationStatus.FORECASTING_IN_PROGRESS)
		$td : TargetDose(associatedTargetSeries == $ts, isShotIgnored() == false)
		not TargetDose(associatedTargetSeries == $ts, administeredShotNumberInSeries > $td.administeredShotNumberInSeries, isShotIgnored() == false)
		not ICEIntervalFactTypeFinding(intervalFactType == IntervalFactType.RECOMMENDED, iceResultFinding == SupportedFactConcept._DOSE_INTERVAL_OVERRIDE.conceptCodeValue, associatedCurrentTargetDose == $td)

	then
		$ts.recommendNextShotBasedOnLatestRecommendedIntervalRule($evalTime.getEvalTimeValue());
		$ts.addSeriesRuleProcessed(drools.getRule().getName());
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetSeries " + $ts.seriesName);
end

rule "RecommendationForecast.recommendBasedOnEarliestRecommendedAgeRule"
	ruleflow-group "RecommendationForecast"
	dialect "mvel"
	salience 100
	activation-group "recommendationAgeCheck"
	when
		$evalTime : EvalTime()
		$ts : TargetSeries(recommendationStatus == RecommendationStatus.FORECASTING_IN_PROGRESS)
		$person : EvaluatedPerson()
	then
		$ts.recommendNextShotBasedOnEarliestRecommendedAgeRule($person.demographics.birthTime, $evalTime.getEvalTimeValue());
		$ts.addSeriesRuleProcessed(drools.getRule().getName());
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetSeries " + $ts.seriesName);
end

rule "RecommendationForecast.recommendBasedOnRecommendedIntervalRule"
	ruleflow-group "RecommendationForecast"
	dialect "mvel"
	salience 100
	activation-group "recommendationIntervalCheck"
	when
		$evalTime : EvalTime()
		$ts : TargetSeries(recommendationStatus == RecommendationStatus.FORECASTING_IN_PROGRESS)
		$td : TargetDose(associatedTargetSeries == $ts, isShotIgnored() == false)
		not TargetDose(associatedTargetSeries == $ts, administeredShotNumberInSeries > $td.administeredShotNumberInSeries, isShotIgnored() == false)
		not ICEIntervalFactTypeFinding(intervalFactType == IntervalFactType.RECOMMENDED, iceResultFinding == SupportedFactConcept._DOSE_INTERVAL_OVERRIDE.conceptCodeValue, associatedCurrentTargetDose == $td)

	then
		$ts.recommendNextShotBasedOnEarliestRecommendedIntervalRule($evalTime.getEvalTimeValue());
		$ts.addSeriesRuleProcessed(drools.getRule().getName());
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetSeries " + $ts.seriesName);

end

rule "RecommendationForecast.Do Not Apply Earliest Interval for Dose 1 if Prior Shot for Target Dose 1 was Invalid due to Below Minimum Age"
	ruleflow-group "RecommendationForecast"
	dialect "mvel"
	salience 101
	activation-group "earliestIntervalCheck"
	when
		$ts : TargetSeries(recommendationStatus == RecommendationStatus.FORECASTING_IN_PROGRESS, isSeriesComplete() == false, determineDoseNumberInSeries() == 1,
			$lastShotAdministered : lastShotAdministeredInSeries, $lastShotAdministered != null, $lastShotAdministered.doseNumberInSeries == 1,
			$lastShotAdministered.getAdministeredVaccine().isLiveVirusVaccine() == false, $lastShotAdministered.getAdministeredVaccine().isSelectAdjuvantProduct() == false)
		exists ICEFactTypeFinding(iceResultFinding == SupportedFactConcept._BELOW_MINIMUM_AGE.conceptCodeValue, associatedTargetDose == $lastShotAdministered)
	then
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetSeries " + $ts.seriesName);
end

rule "RecommendationForecast.Do Not Apply Recommended Interval for Dose 1 if Prior Shot for Target Dose 1 was Invalid due to Below Minimum Age"
	ruleflow-group "RecommendationForecast"
	dialect "mvel"
	salience 101
	activation-group "recommendationIntervalCheck"
	when
		$ts : TargetSeries(recommendationStatus == RecommendationStatus.FORECASTING_IN_PROGRESS, isSeriesComplete() == false, determineDoseNumberInSeries() == 1,
			$lastShotAdministered : lastShotAdministeredInSeries, $lastShotAdministered != null, $lastShotAdministered.doseNumberInSeries == 1,
			$lastShotAdministered.getAdministeredVaccine().isLiveVirusVaccine() == false, $lastShotAdministered.getAdministeredVaccine().isSelectAdjuvantProduct() == false)
		exists ICEFactTypeFinding(iceResultFinding == SupportedFactConcept._BELOW_MINIMUM_AGE.conceptCodeValue, associatedTargetDose == $lastShotAdministered)
	then
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetSeries " + $ts.seriesName);
end

rule "RecommendationForecast: Recommend Earliest Recommended Age Date in Next Series Season as Specified by Default Season Series Rule if no next Fully-Specified Season Defined and during the Off-Season of Current Seasonal Series"
	ruleflow-group "RecommendationForecast"
	dialect "mvel"
	salience 110
	activation-group "recommendationAgeCheck"
	when
		$ts : TargetSeries(recommendationStatus == recommendationStatus.FORECASTING_IN_PROGRESS, targetSeason != null, seriesRules.recurringDosesOccurAfterSeriesComplete() == false, $vg : vaccineGroup, targetSeason.dateIsApplicableToOffSeason(evalTime),
			$offSeasonEndDate : targetSeason.fullySpecifiedSeasonOffSeasonEndDate)
		not Season(isDefaultSeason() == false, vaccineGroup == $vg, ICELogicHelper.toDate(fullySpecifiedSeasonStartDate) == ICELogicHelper.toDate($offSeasonEndDate.plusDays(1)))
		$defaultSeason : Season(isDefaultSeason() == true, vaccineGroup == $vg)
		$s : SeriesRules(vaccineGroup == $vg, $defaultSeason memberOf seasons, getSeriesDoseRuleByDoseNumber(1) != null,
			$recommendedAge : getSeriesDoseRuleByDoseNumber(1).getEarliestRecommendedAge() != null)
		$person : EvaluatedPerson($birthDate : demographics.birthTime)
		eval(TimePeriod.compareElapsedTimePeriodToDateRange($birthDate, ICELogicHelper.toDate($offSeasonEndDate.plusDays(1)), $recommendedAge) > 0)
	then
		Date calcRecDate = TimePeriod.addTimePeriod($birthDate, $recommendedAge);
		Recommendation recommendation = new Recommendation($ts);
		recommendation.setRecommendationDate(calcRecDate);
		$ts.addInterimRecommendationForConsideration(recommendation, evalTime);
		$ts.addSeriesRuleProcessed(drools.getRule().getName());
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetSeries " + $ts);
end

rule "RecommendationForecast: Recommend at Earliest Recommended Age Date in Next Series Season as Specified by TargetSeries if Fully-Specified Season Defined and if during the Off-Season of Current Seasonal Series"
	ruleflow-group "RecommendationForecast"
	dialect "mvel"
	salience 110
	activation-group "recommendationAgeCheck"
	when
		$ts : TargetSeries(recommendationStatus == recommendationStatus.FORECASTING_IN_PROGRESS, targetSeason != null, seriesRules.recurringDosesOccurAfterSeriesComplete() == false, targetSeason.dateIsApplicableToOffSeason(evalTime),
			$offSeasonEndDate : targetSeason.fullySpecifiedSeasonOffSeasonEndDate, $offSeasonEndDate != null)
		$fullySpecifiedNextseason : Season(isDefaultSeason() == false, vaccineGroup == $ts.vaccineGroup, ICELogicHelper.toDate(fullySpecifiedSeasonStartDate) == ICELogicHelper.toDate($offSeasonEndDate.plusDays(1)))
		$sr : SeriesRules(vaccineGroup == $ts.vaccineGroup, $fullySpecifiedNextseason memberOf seasons, getSeriesDoseRuleByDoseNumber(1) != null,
			$recommendedAge : getSeriesDoseRuleByDoseNumber(1).getEarliestRecommendedAge() != null)
		$person : EvaluatedPerson($birthDate : demographics.birthTime)
		eval(TimePeriod.compareElapsedTimePeriodToDateRange($birthDate, ICELogicHelper.toDate($offSeasonEndDate.plusDays(1)), $recommendedAge) > 0)
	then
		Date calcRecDate = TimePeriod.addTimePeriod($birthDate, $recommendedAge);
		Recommendation recommendation = new Recommendation($ts);
		recommendation.setRecommendationDate(calcRecDate);
		$ts.addInterimRecommendationForConsideration(recommendation, evalTime);
		$ts.addSeriesRuleProcessed(drools.getRule().getName());
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetSeries " + $ts);
end

rule "RecommendationForecast: Recommend Next Season Earliest Start Date if during the Off-Season of Current Seasonal Series"
	ruleflow-group "RecommendationForecast"
	dialect "mvel"
	salience 110
	activation-group "earliestIntervalCheck"
	when
		$ts : TargetSeries(recommendationStatus == recommendationStatus.FORECASTING_IN_PROGRESS, targetSeason != null, seriesRules.recurringDosesOccurAfterSeriesComplete() == false, targetSeason.dateIsApplicableToOffSeason(evalTime))
	then
		Recommendation recommendation = new Recommendation($ts);
		recommendation.setEarliestDate(ICELogicHelper.toDate($ts.getTargetSeason().getFullySpecifiedSeasonOffSeasonEndDate().plusDays(1)));
		$ts.addInterimRecommendationForConsideration(recommendation, evalTime);
		$ts.addSeriesRuleProcessed(drools.getRule().getName());
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetSeries " + $ts);
end

rule "RecommendationForecast: Recommend Next Season Recommended Start Date if during the Off-Season of Current Seasonal Series"
	ruleflow-group "RecommendationForecast"
	dialect "mvel"
	salience 110
	activation-group "recommendationIntervalCheck"
	when
		$ts : TargetSeries(recommendationStatus == recommendationStatus.FORECASTING_IN_PROGRESS, targetSeason != null, seriesRules.recurringDosesOccurAfterSeriesComplete() == false, targetSeason.dateIsApplicableToOffSeason(evalTime))
	then
		Recommendation recommendation = new Recommendation($ts);
		recommendation.setRecommendationDate(ICELogicHelper.toDate($ts.getTargetSeason().getFullySpecifiedSeasonOffSeasonEndDate().plusDays(1)));
		$ts.addInterimRecommendationForConsideration(recommendation, evalTime);
		$ts.addSeriesRuleProcessed(drools.getRule().getName());
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetSeries " + $ts);
end

rule "RecommendationForecast: Recommend Next Season Start Date if Current Seasonal Series is Complete"
	ruleflow-group "RecommendationForecast"
	dialect "mvel"
	salience 100
	when
		$ts : TargetSeries(recommendationStatus == recommendationStatus.FORECASTING_IN_PROGRESS, targetSeason != null, targetSeason.fullySpecifiedSeasonOffSeasonEndDate != null, seriesRules.recurringDosesOccurAfterSeriesComplete() == false, isSeriesComplete() == true)
	then
		Recommendation recommendation = new Recommendation($ts);
		recommendation.setRecommendationDate(ICELogicHelper.toDate($ts.getTargetSeason().getFullySpecifiedSeasonOffSeasonEndDate().plusDays(1)));
		$ts.addInterimRecommendationForConsideration(recommendation, evalTime);
		$ts.addSeriesRuleProcessed(drools.getRule().getName());
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetSeries " + $ts);
end

rule "RecommendationForecast/Post Recommendation Check: Recommend Next Season Start Date if Final Recommendation Date during Off-Season"
	dialect "mvel"
	ruleflow-group "RecommendationForecast^postRecommendationCheck"
	when
		$ts : TargetSeries(isPostForecastCheckCompleted() == false, recommendationStatus == RecommendationStatus.RECOMMENDED || recommendationStatus == RecommendationStatus.RECOMMENDED_IN_FUTURE || recommendationStatus == RecommendationStatus.CONDITIONALLY_RECOMMENDED, finalRecommendationDate != null, $pcvRecommendationDate : finalRecommendationDate,
			targetSeason != null, finalRecommendationDate != null, targetSeason.fullySpecifiedSeasonOffSeasonStartDate != null, targetSeason.fullySpecifiedSeasonOffSeasonEndDate != null, seriesRules.recurringDosesOccurAfterSeriesComplete() == false)
		eval($ts.getFinalRecommendationDate().compareTo(ICELogicHelper.toDate($ts.getTargetSeason().getFullySpecifiedSeasonEndDate())) > 0 &&
			$ts.getFinalRecommendationDate().compareTo(ICELogicHelper.toDate($ts.getTargetSeason().getFullySpecifiedSeasonOffSeasonEndDate())) <= 0)
	then
		Recommendation recommendation = new Recommendation($ts);
		recommendation.setRecommendationDate(ICELogicHelper.toDate($ts.getTargetSeason().getFullySpecifiedSeasonOffSeasonEndDate().plusDays(1)));
		$ts.addInterimRecommendationForConsideration(recommendation, evalTime);
		$ts.addSeriesRuleProcessed(drools.getRule().getName());
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetSeries " + $ts);
end

rule "RecommendationForecast/Post Recommendation Check: Recommend Not Recommended and Complete if Final Recommendation Date after End Date and there is no Off-Season"
	dialect "mvel"
	ruleflow-group "RecommendationForecast^postRecommendationCheck"
	activation-group "postSeasonalSeriesNotRecommendedHandling"
	when
		$ts : TargetSeries(isPostForecastCheckCompleted() == false, recommendationStatus == RecommendationStatus.RECOMMENDED || recommendationStatus == RecommendationStatus.RECOMMENDED_IN_FUTURE || recommendationStatus == RecommendationStatus.CONDITIONALLY_RECOMMENDED, finalRecommendationDate != null, $pcvRecommendationDate : finalRecommendationDate,
			targetSeason != null, finalRecommendationDate != null, targetSeason.fullySpecifiedSeasonOffSeasonEndDate == null)
		eval($ts.getFinalRecommendationDate().compareTo(ICELogicHelper.toDate($ts.getTargetSeason().getFullySpecifiedSeasonEndDate())) > 0)
	then
		Recommendation $recommendation = new Recommendation($ts);
		$recommendation.setRecommendationStatus(RecommendationStatus.NOT_RECOMMENDED);
		$recommendation.setRecommendationReason(BaseDataRecommendationReason._NOT_RECOMMENDED_COMPLETE_REASON.getCdsListItemName());
		$ts.setSeriesComplete(true);
		$ts.addInterimRecommendationForConsideration($recommendation, evalTime);
		$ts.addSeriesRuleProcessed(drools.getRule().getName());
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "TargetSeries " + $ts);
end

rule "RecommendNotRecommendedIfImmuneToAllDiseasesInSeries"
	dialect "java"
	ruleflow-group "RecommendationForecast^preRecommendationValidation"
	when
		$targetSeries : TargetSeries(recommendationStatus == RecommendationStatus.FORECASTING_IN_PROGRESS, $diseasesSupportedByThisSeries : diseasesSupportedByThisSeries)
		do[invokeCustomRecommendationRules]
		Set(size == $diseasesSupportedByThisSeries.size()) from accumulate($di : DiseaseImmunity(dateOfImmunity <= evalTime, disease memberOf $diseasesSupportedByThisSeries), collectSet($di.getDisease()))
		$diseaseImmunityList : List() from accumulate($di : DiseaseImmunity(dateOfImmunity <= evalTime, disease memberOf $diseasesSupportedByThisSeries), collectList($di))
	then
		Recommendation $recommendation = new Recommendation($targetSeries);
		$recommendation.setRecommendationStatus(RecommendationStatus.NOT_RECOMMENDED);
		Iterator dilIter = $diseaseImmunityList.iterator();
		while (dilIter.hasNext()) {
			String src = ((DiseaseImmunity) dilIter.next()).getRecommendationReasonResult();
			if (src != null) {
				$recommendation.setRecommendationReason(src);
				break;
			}
		}
		$targetSeries.addInterimRecommendationForConsideration($recommendation, evalTime);
		$targetSeries.setSeriesComplete(true);
		modify ($targetSeries) {
		    setRecommendationStatus(RecommendationStatus.FORECASTING_COMPLETE)
		};
		$targetSeries.addSeriesRuleProcessed(drools.getRule().getName());
       	ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "in TargetSeries " + $targetSeries.getSeriesName());
	then[invokeCustomRecommendationRules]
       	ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Check complete.");
       	drools.setFocus("RecommendationForecast^customRecommendationRule");
end

function void setShotValidity(SubstanceAdministrationEvent sae, TargetDose td) {

	if (sae == null || td == null) {
		return;
	}

	BL currShotValidity = sae.getIsValid();
	if (currShotValidity == null || currShotValidity.isValue()) {
		BL shotValidity = new BL();
		shotValidity.setValue(td.getIsValid());
		sae.setIsValid(shotValidity);
	}

}

rule "ProcessResults: Return Evaluations"
	ruleflow-group "ProcessResults"
	dialect "mvel"
	salience 10
	when
		$sae : SubstanceAdministrationEvent()
		$td : TargetDose(doseId == $sae.id)
		$ts : TargetSeries(this == $td.associatedTargetSeries, $vaccineGroup : seriesRules.vaccineGroup, selectedSeries == true)
		not ICEFactTypeFinding(iceResultFinding == $sae.id, targetDose == $td)
		$evalTime: EvalTime()
	then
		PayloadHelper p = new PayloadHelper(schedule);
		p.outputNestedImmEvaluationResult(drools, namedObjects, $evalTime, focalPersonId, iceVersion, $sae, $vaccineGroup, $td, outputSupplementalText, true);
		$sae.setToBeReturned(true);
		ICEFactTypeFinding saeEvaluation = new ICEFactTypeFinding($sae.id, $td);
		insert(saeEvaluation);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Results processing: " + $td);
end

rule "ProcessResults(COVID-19): Return COVID-19 Season Evaluations - always resetting to dose 1 at the beginning of the Sept 2023 or Aug 2024 season start dates"
	ruleflow-group "ProcessResults"
	dialect "mvel"
	salience 11
	when
		not ICEFactTypeFinding(iceResultFinding == "COVID19_SEP2023_DOSE_NUMBER_RESET_DISABLED")
		$covidSeason : Season(seasonName in ("COVID19Sep2023Season", "COVID19Aug2024Season"), fullySpecifiedSeasonStartDate != null, fullySpecifiedSeasonEndDate != null, $seasonStartDate : ICELogicHelper.toDate(fullySpecifiedSeasonStartDate), $seasonEndDate : ICELogicHelper.toDate(fullySpecifiedSeasonEndDate))
		$sae : SubstanceAdministrationEvent()
		$td : TargetDose(doseId == $sae.id, associatedVaccineGroup == "VACCINE_GROUP_CONCEPT.850", associatedTargetSeries.targetSeasonExists() == true, associatedTargetSeries.targetSeason.seasonName == $covidSeason.seasonName, administrationDate >= $seasonStartDate, administrationDate <= $seasonEndDate)
		$ts : TargetSeries(this == $td.associatedTargetSeries, $vaccineGroup : seriesRules.vaccineGroup, selectedSeries == true, targetSeasonExists() == true, targetSeason.seasonName == $covidSeason.seasonName)
		not ICEFactTypeFinding(iceResultFinding == $sae.id, targetDose == $td)
		$numberOfPreviousDoses: Integer() from accumulate($acctd: TargetDose(associatedVaccineGroup == "VACCINE_GROUP_CONCEPT.850", associatedTargetSeries == $ts, isValid == true, administrationDate >= $seasonStartDate, administrationDate <= $td.administrationDate,
			administeredShotNumberInSeries < $td.administeredShotNumberInSeries), count($acctd))
		$evalTime: EvalTime()
	then
		PayloadHelper p = new PayloadHelper(schedule);
		int doseNumberToDisplay = $numberOfPreviousDoses.intValue() == 0 ? 1 : $numberOfPreviousDoses.intValue()+1;
		p.outputNestedImmEvaluationResult(drools, namedObjects, $evalTime, focalPersonId, iceVersion, $sae, $vaccineGroup, $td, outputSupplementalText, true, doseNumberToDisplay);
		$sae.setToBeReturned(true);
		ICEFactTypeFinding saeEvaluation = new ICEFactTypeFinding($sae.id, $td);
		insert(saeEvaluation);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Results processing: " + $td);
end

rule "ProcessResults(COVID-19): Return Sept 2023 Season Evaluations (CB2 - do not reset to 1 in the Sept 2023, Aug 2024 or later season)"
	ruleflow-group "ProcessResults"
	dialect "mvel"
	salience 11
	when
		exists ICEFactTypeFinding(iceResultFinding == "COVID19_SEP2023_DOSE_NUMBER_RESET_DISABLED")
		$sae : SubstanceAdministrationEvent()
		$td : TargetDose(doseId == $sae.id, associatedVaccineGroup == "VACCINE_GROUP_CONCEPT.850", associatedTargetSeries.targetSeasonExists() == true, administrationDate >= "12-Sep-2023")
		$ts : TargetSeries(this == $td.associatedTargetSeries, $vaccineGroup : seriesRules.vaccineGroup, selectedSeries == true, targetSeasonExists() == true)
		not ICEFactTypeFinding(iceResultFinding == $sae.id, targetDose == $td)
		$numberOfPreviousDoses: Integer() from accumulate($acctd: TargetDose(associatedVaccineGroup == "VACCINE_GROUP_CONCEPT.850", administrationDate < $td.administrationDate, isValid == true), count($acctd))
		$evalTime: EvalTime()
	then
		PayloadHelper p = new PayloadHelper(schedule);
		p.outputNestedImmEvaluationResult(drools, namedObjects, $evalTime, focalPersonId, iceVersion, $sae, $vaccineGroup, $td, outputSupplementalText, true, $numberOfPreviousDoses.intValue()+1);
		$sae.setToBeReturned(true);
		ICEFactTypeFinding saeEvaluation = new ICEFactTypeFinding($sae.id, $td);
		insert(saeEvaluation);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Results processing: " + $td);
end

rule "ProcessResults: Mark Unprocessed Shots as Vaccine Not Supported"
	ruleflow-group "ProcessResults"
	dialect "mvel"
	salience 10
	when
		exists ICEFactTypeFinding(iceResultFinding == "UNSUPPORTED_VACCINES_GROUP_FEATURE_ENABLED")
		ImmunizationConcept($ctid : conceptTargetId)
		$sae : SubstanceAdministrationEvent(id == $ctid)
		not TargetDose(doseId == $sae.id)
		$evalTime: EvalTime()
	then
		PayloadHelper p = new PayloadHelper(schedule);
		p.outputNestedImmEvaluationNotSupported(drools, namedObjects, $evalTime, focalPersonId, iceVersion, $sae, "VACCINE_GROUP_CONCEPT.999");
		$sae.setToBeReturned(true);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Results processing: " + $sae);
end

rule "ProcessResults: Return Recommendations for Vaccines Not Supported"
	extends "ProcessResults: Mark Unprocessed Shots as Vaccine Not Supported"
	ruleflow-group "ProcessResults"
	dialect "mvel"
	salience 10
	when
		not ObservationResult(observationValue != null && observationValue.concept != null &&
			observationValue.concept == PayloadHelper.getLocalCodeForRecommendationStatus(RecommendationStatus.RECOMMENDATION_NOT_AVAILABLE, schedule))
	then
		PayloadHelper p = new PayloadHelper(schedule);
		p.outputOtherImmRecommendationSubstanceAdministrationProposal(drools, namedObjects, focalPersonId, iceVersion);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Results processing");
end

rule "ProcessResults: Check Non-Seasonal Series Selection Consistency"
	ruleflow-group "ProcessResults"
	dialect "mvel"
	salience 20
	when
		$s : SeriesRules($vg : vaccineGroup)
		exists TargetSeries(vaccineGroup == $vg, targetSeason == null)
		accumulate($tsthis : TargetSeries(vaccineGroup == $vg, isSelectedSeries() == true, targetSeason == null); $countInVG : count($tsthis); $countInVG != 1)
	then
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "No *non-seasonal* series properly selected for vaccine group " + $vg + "; count of series was: " + $countInVG);
		ICELogicHelper.throwRuntimeException(new InconsistentConfigurationException("No *non-seasonal* series properly selected for vaccine group " + $vg + ". Count of Series was: " + $countInVG));
end

rule "ProcessResults: Check Seasonal SeriesSelection Consistency"
	ruleflow-group "ProcessResults"
	dialect "mvel"
	salience 20
	when
		$season: Season(isDefaultSeason() == false, $vg : vaccineGroup)
		exists TargetSeries(vaccineGroup == $vg, targetSeason != null, targetSeason == $season)
		accumulate($tsthis : TargetSeries(vaccineGroup == $vg, isSelectedSeries() == true, targetSeason == $season); $countInVG : count($tsthis); $countInVG != 1)
	then
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "No *seasonal* series properly selected for vaccine group " + $vg + "; count of series was: " + $countInVG);
		ICELogicHelper.throwRuntimeException(new InconsistentConfigurationException("No *seasonal* series properly selected for vaccine group " + $vg + ". Count of Series was: " + $countInVG));
end

rule "ProcessResults: Return Recommendation for Non-Seasonal Series"
	ruleflow-group "ProcessResults"
	dialect "mvel"
	lock-on-active true
	salience 10
	when
		$ts : TargetSeries(targetSeason == null)
		not TargetSeries(vaccineGroup == $ts.vaccineGroup, seriesRules.seriesGroup > $ts.seriesRules.seriesGroup)
		$evalTime: EvalTime()
	then
		PayloadHelper p = new PayloadHelper(schedule);
		SubstanceAdministrationProposal sap = p.outputRootImmRecommendationSubstanceAdministrationProposal(drools, namedObjects, focalPersonId, iceVersion, $ts, outputEarliestOverdueDates, outputSupplementalText);
		insert(sap);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Results processing");
end



rule "ProcessResults: Return Recommendations For Seasonal Series"
	ruleflow-group "ProcessResults"
	dialect "mvel"
	lock-on-active true
	salience 10
	when
		$ts : TargetSeries($vg : vaccineGroup, targetSeason != null, isSelectedSeries() == true, $tseasonStartDate : targetSeason.fullySpecifiedSeasonStartDate)
		not TargetSeries(vaccineGroup == $vg, seriesRules.seriesGroup > $ts.seriesRules.seriesGroup)
		not TargetSeries(vaccineGroup == $vg, targetSeason != null,	targetSeason.fullySpecifiedSeasonStartDate.isAfter($tseasonStartDate))
	then
		PayloadHelper p = new PayloadHelper(schedule);
		p.outputRootImmRecommendationSubstanceAdministrationProposal(drools, namedObjects, focalPersonId, iceVersion, $ts, outputEarliestOverdueDates, outputSupplementalText);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Results processing");
end

rule "Series Display(Abstract): Return Series Selection Display Options"
	ruleflow-group "ProcessResults"
	dialect "mvel"
	salience 8
	when
		exists (ICEFactTypeFinding(iceResultFinding == SupportedFactConcept._OUTPUT_NUMBER_OF_DOSES_REMAINING.conceptCodeValue))
		$ss : SeriesDisplaySelection(seriesDisplaySelectionType == SeriesDisplaySelectionType.SERIES_DISPLAY_NOT_SELECTED)
		$ts : TargetSeries(this == $ss.targetSeries, isSeriesComplete() == false && (recommendationStatus == RecommendationStatus.RECOMMENDED || recommendationStatus == RecommendationStatus.RECOMMENDED_IN_FUTURE) ||
			isSeriesComplete() == true && determineEffectiveNumberOfDosesInSeries() <= seriesRules.numberOfDosesInSeries)
	then
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Series Selection \": " + $ts.seriesName);
end

rule "Series Display: Mark Selected Series as Unambiguous for Display if there is only one configured series for the Vaccine Group"
		extends "Series Display(Abstract): Return Series Selection Display Options"
	ruleflow-group "ProcessResults"
	dialect "mvel"
	salience 8
	when
		accumulate($srthis : SeriesRules(vaccineGroup == $ts.vaccineGroup); $numberOfSeriesInVG : count($srthis); $numberOfSeriesInVG == 1)
		$sssame : SeriesDisplaySelection(this == $ss, seriesDisplaySelectionType == SeriesDisplaySelectionType.SERIES_DISPLAY_NOT_SELECTED)
	then
		modify ($ss) {
			setSeriesDisplaySelectionType(SeriesDisplaySelectionType.SERIES_DISPLAY_UNAMBIGUOUS)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Series Selection \": " + $ts.seriesName + "; " + SeriesDisplaySelectionType.SERIES_DISPLAY_UNAMBIGUOUS);
end

rule "Series Display: Mark Selected Series as Best Guess for Display when there are more than one configured series for the Vaccine Group"
		extends "Series Display(Abstract): Return Series Selection Display Options"
	ruleflow-group "ProcessResults"
	dialect "mvel"
	salience 8
	when
		accumulate($srthis : SeriesRules(vaccineGroup == $ts.vaccineGroup); $numberOfSeriesInVG : count($srthis); $numberOfSeriesInVG > 1)
		$sssame : SeriesDisplaySelection(this == $ss, seriesDisplaySelectionType == SeriesDisplaySelectionType.SERIES_DISPLAY_NOT_SELECTED)
	then
		modify ($ss) {
			setSeriesDisplaySelectionType(SeriesDisplaySelectionType.SERIES_DISPLAY_BEST_GUESS)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Series Selection \": " + $ts.seriesName + "; " + SeriesDisplaySelectionType.SERIES_DISPLAY_BEST_GUESS);
end

rule "Series Display: Invoke Series Display Custom Rules"
	ruleflow-group "ProcessResults"
	dialect "mvel"
	salience 7
	when
		exists (ICEFactTypeFinding(iceResultFinding == SupportedFactConcept._OUTPUT_NUMBER_OF_DOSES_REMAINING.conceptCodeValue))
		$ts : TargetSeries()
		exists SeriesDisplaySelection(targetSeries.vaccineGroup == $ts.vaccineGroup, targetSeries != $ts, seriesDisplaySelectionType == SeriesDisplaySelectionType.SERIES_DISPLAY_NOT_SELECTED)
		not SeriesDisplaySelection(targetSeries.vaccineGroup == $ts.vaccineGroup, seriesDisplaySelectionType == SeriesDisplaySelectionType.SERIES_DISPLAY_UNAMBIGUOUS)
	then
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Invoking custom series display logic for vaccine group: " + $ts.vaccineGroup);
		drools.setFocus("ProcessResults^customSeriesDisplayLogic");
end

rule "Series Display: For any remaining series display selections set to SERIES_DISPLAY_NOT_SELECTED, change the series display selection to SERIES_DISPLAY_NONE"
	ruleflow-group "ProcessResults"
	dialect "mvel"
	salience 6
	when
		exists (ICEFactTypeFinding(iceResultFinding == SupportedFactConcept._OUTPUT_NUMBER_OF_DOSES_REMAINING.conceptCodeValue))
		$ss : SeriesDisplaySelection(seriesDisplaySelectionType == SeriesDisplaySelectionType.SERIES_DISPLAY_NOT_SELECTED)
	then
		modify($ss) {
			setSeriesDisplaySelectionType(SeriesDisplaySelectionType.SERIES_DISPLAY_NONE)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Series Display Selection changed to SERIES_DISPLAY_NONE for: " + $ss);
end

rule "Series Display: Set Number of Doses Remaining to Recommendation for a Series that is Not Complete"
	ruleflow-group "ProcessResults"
	dialect "mvel"
	salience 5
	when
		exists (ICEFactTypeFinding(iceResultFinding == SupportedFactConcept._OUTPUT_NUMBER_OF_DOSES_REMAINING.conceptCodeValue))
		$ss : SeriesDisplaySelection(seriesDisplaySelectionType != SeriesDisplaySelectionType.SERIES_DISPLAY_NONE, isSeriesDisplaySelectionDeterminationComplete() == false, $numberOfDosesInSeries : targetSeries.seriesRules.numberOfDosesInSeries, $numberOfDosesAdministered : targetSeries.determineEffectiveNumberOfDosesInSeries())
		not ICEFactTypeFinding(iceResultFinding == SupportedFactConcept._OUTPUT_NUMBER_OF_DOSES_REMAINING.getConceptCodeValue(), associatedTargetSeries == $ss.targetSeries)
		$tssamevg : TargetSeries(vaccineGroup == $ss.vaccineGroup, isSeriesComplete() == false, recommendationStatus == RecommendationStatus.RECOMMENDED || recommendationStatus == RecommendationStatus.RECOMMENDED_IN_FUTURE)
	then
		int lNumberRemaining = $numberOfDosesInSeries - $numberOfDosesAdministered;
		String lStrNumberRemaining = String.valueOf(lNumberRemaining);
		modify($ss) {
			setNumberOfDosesRemaining(lStrNumberRemaining),
			setSeriesDisplaySelectionDeterminationComplete(true)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Doses remaining for series \"" + $ss.getTargetSeries().getSeriesRules().getSeriesName() + "\": " + lStrNumberRemaining);
end

rule "Series Display: Set Number of Doses Remaining to Zero Doses for a Series that is Not Recurring and Complete; 'however, one or more additional doses may still be recommended'"
	ruleflow-group "ProcessResults"
	dialect "mvel"
	no-loop true
	salience 5
	when
		exists (ICEFactTypeFinding(iceResultFinding == SupportedFactConcept._OUTPUT_NUMBER_OF_DOSES_REMAINING.conceptCodeValue))
		$ss : SeriesDisplaySelection(seriesDisplaySelectionType != SeriesDisplaySelectionType.SERIES_DISPLAY_NONE, isSeriesDisplaySelectionDeterminationComplete() == false)
		$tssamevg : TargetSeries(vaccineGroup == $ss.vaccineGroup, isSeriesComplete() == true, getSeriesRules().recurringDosesOccurAfterSeriesComplete() == false, recommendationStatus == RecommendationStatus.RECOMMENDED || recommendationStatus == RecommendationStatus.RECOMMENDED_IN_FUTURE)
	then
		String lStrNumberRemaining = "0 doses remaining in series; one or more additional doses may still be recommended";
		modify($ss) {
			setNumberOfDosesRemaining(lStrNumberRemaining),
			setSeriesDisplaySelectionDeterminationComplete(true)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Doses remaining for series \"" + $ss.getTargetSeries().getSeriesRules().getSeriesName() + "\": " + lStrNumberRemaining);
end

rule "Series Display: Set Number of Doses Remaining to Zero Doses for a Series that is Not Recurring and Complete"
	ruleflow-group "ProcessResults"
	dialect "mvel"
	no-loop true
	salience 5
	when
		exists (ICEFactTypeFinding(iceResultFinding == SupportedFactConcept._OUTPUT_NUMBER_OF_DOSES_REMAINING.conceptCodeValue))
		$ss : SeriesDisplaySelection(seriesDisplaySelectionType != SeriesDisplaySelectionType.SERIES_DISPLAY_NONE, isSeriesDisplaySelectionDeterminationComplete() == false)
		$tssamevg : TargetSeries(vaccineGroup == $ss.vaccineGroup, isSeriesComplete() == true, getSeriesRules().recurringDosesOccurAfterSeriesComplete() == false, recommendationStatus != RecommendationStatus.RECOMMENDED && recommendationStatus != RecommendationStatus.RECOMMENDED_IN_FUTURE)
	then
		String lStrNumberRemaining = "0";
		modify($ss) {
			setNumberOfDosesRemaining(lStrNumberRemaining),
			setSeriesDisplaySelectionDeterminationComplete(true)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Doses remaining for series \"" + $ss.getTargetSeries().getSeriesRules().getSeriesName() + "\": " + lStrNumberRemaining);
end

rule "Series Display: Set Number of Doses Remaining to 'Recurring' for a Series that is Complete and Recurring"
	ruleflow-group "ProcessResults"
	dialect "mvel"
	no-loop true
	salience 5
	when
		exists (ICEFactTypeFinding(iceResultFinding == SupportedFactConcept._OUTPUT_NUMBER_OF_DOSES_REMAINING.conceptCodeValue))
		$ss : SeriesDisplaySelection(seriesDisplaySelectionType != SeriesDisplaySelectionType.SERIES_DISPLAY_NONE, isSeriesDisplaySelectionDeterminationComplete() == false)
		$tssamevg : TargetSeries(vaccineGroup == $ss.vaccineGroup, isSeriesComplete() == true, getSeriesRules().recurringDosesOccurAfterSeriesComplete() == true, recommendationStatus == RecommendationStatus.RECOMMENDED || recommendationStatus == RecommendationStatus.RECOMMENDED_IN_FUTURE)
	then
		modify($ss) {
			setNumberOfDosesRemaining("Recurring"),
			setSeriesDisplaySelectionDeterminationComplete(true)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Doses remaining for series \"" + $ss.getTargetSeries().getSeriesRules().getSeriesName() + "\": Recurring");
end

rule "Series Display: Append N/A for Doses Remaining to Recommendation for a Series that is Not Recommended"
	ruleflow-group "ProcessResults"
	dialect "mvel"
	no-loop true
	salience 5
	when
		exists (ICEFactTypeFinding(iceResultFinding == SupportedFactConcept._OUTPUT_NUMBER_OF_DOSES_REMAINING.conceptCodeValue))
		$ss : SeriesDisplaySelection(seriesDisplaySelectionType != SeriesDisplaySelectionType.SERIES_DISPLAY_NONE, isSeriesDisplaySelectionDeterminationComplete() == false)
		$tssamevg : TargetSeries(vaccineGroup == $ss.vaccineGroup, recommendationStatus == RecommendationStatus.NOT_RECOMMENDED)
	then
		String lStrNumberRemaining = "0";
		modify($ss) {
			setNumberOfDosesRemaining(lStrNumberRemaining),
			setSeriesDisplaySelectionDeterminationComplete(true)
		};
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Doses remaining for series \"" + $ss.getTargetSeries().getSeriesRules().getSeriesName() + "\": " + lStrNumberRemaining);
end

rule "Series Display: Output Series Display Selections and Number of Doses Remaining for Each Vaccine Group"
	ruleflow-group "ProcessResults"
	dialect "mvel"
	no-loop true
	salience 3
	when
		exists (ICEFactTypeFinding(iceResultFinding == SupportedFactConcept._OUTPUT_NUMBER_OF_DOSES_REMAINING.conceptCodeValue))
		$ts : TargetSeries()
		$sap : SubstanceAdministrationProposal(id == $ts.targetSeriesIdentifier)
		$sdlist : List() from
			accumulate($sdthis : SeriesDisplaySelection(targetSeries.vaccineGroup == $ts.vaccineGroup, seriesDisplaySelectionType != SeriesDisplaySelectionType.SERIES_DISPLAY_NONE, isSeriesDisplaySelectionDeterminationComplete() == true), collectList($sdthis));

	then
		PayloadHelper p = new PayloadHelper(schedule);
		p.outputSeriesDisplaySelectionsAndDosesRemainingInEmbeddedSubstanceAdministrationProposals(drools, namedObjects, focalPersonId, $sdlist, $sap);
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Series Display Selection \": " + $ts.seriesName);
end

rule "BounceAllEntities"
	ruleflow-group "ProcessResults"
	dialect "mvel"
	when
		$entityBase : EntityBase( toBeReturned == false )
	then
		$entityBase.setToBeReturned( true );
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Results processing");
end

rule "BounceAllClinicalStatements"
	ruleflow-group "ProcessResults"
	dialect "mvel"
	when
		$cs : ClinicalStatement( toBeReturned == false )
	then
		$cs.setToBeReturned( true );
		ICELogicHelper.logDRLDebugMessage(drools.getRule().getName(), "Results processing");
end

