/*
 * Copyright 2014-2020 OpenCDS.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.opencds.config.api.model;


public enum DssOperation {
    EVALUATION_EVALUATE("EVALUATION.EVALUATE"),
    EVALUATION_EVALUATE_AT_SPECIFIED_TIME("EVALUATION.EVALUATE_AT_SPECIFIED_TIME"),
    EVALUATION_EVALUATE_ITERATIVELY("EVALUATION.EVALUATE_ITERATIVELY"),
    EVALUATION_EVALUATE_ITERATIVELY_AT_SPECIFIED_TIME("EVALUATION.EVALUATE_ITERATIVELY_AT_SPECIFIED_TIME"),
    METADATA_DISCOVERY_DESCRIBE_PROFILE("METADATA_DISCOVERY.DESCRIBE_PROFILE"),
    METADATA_DISCOVERY_DESCRIBE_SCOPING_ENTITY("METADATA_DISCOVERY.DESCRIBE_SCOPING_ENTITY"),
    METADATA_DISCOVERY_DESCRIBE_SCOPING_ENTITY_HIERARCHY("METADATA_DISCOVERY.DESCRIBE_SCOPING_ENTITY_HIERARCHY"),
    METADATA_DISCOVERY_DESCRIBE_SEMANTIC_REQUIREMENT("METADATA_DISCOVERY.DESCRIBE_SEMANTIC_REQUIREMENT"),
    METADATA_DISCOVERY_DESCRIBE_SEMANTIC_SIGNIFIER("METADATA_DISCOVERY.DESCRIBE_SEMANTIC_SIGNIFIER"),
    METADATA_DISCOVERY_DESCRIBE_TRAIT("METADATA_DISCOVERY.DESCRIBE_TRAIT"),
    METADATA_DISCOVERY_LIST_PROFILES("METADATA_DISCOVERY.LIST_PROFILES"),
    QUERY_FIND_KMS("QUERY.FIND_KMS"),
    QUERY_GET_KM_DATA_REQUIREMENTS("QUERY.GET_KM_DATA_REQUIREMENTS"),
    QUERY_GET_KM_DATA_REQUIREMENTS_FOR_EVALUATION_AT_SPECIFIED_TIME("QUERY.GET_KM_DATA_REQUIREMENTS_FOR_EVALUATION_AT_SPECIFIED_TIME"),
    QUERY_GET_KM_DESCRIPTION("QUERY.GET_KM_DESCRIPTION"),
    QUERY_GET_KM_EVALUATION_RESULT_SEMANTICS("QUERY.GET_KM_EVALUATION_RESULT_SEMANTICS"),
    QUERY_LIST_KMS("QUERY.LIST_KMS");

    private String dssName;

    private DssOperation(String operation) {
        this.dssName = operation;
    }
    
    public String getDssName() {
        return dssName;
    }
}
