package org.opencds.config.api.model;


public enum DssOperation {
    EVALUATION_EVALUATE("EVALUATION.EVALUATE"),
    EVALUATION_EVALUATE_AT_SPECIFIED_TIME("EVALUATION.EVALUATE_AT_SPECIFIED_TIME"),
    EVALUATION_EVALUATE_ITERATIVELY("EVALUATION.EVALUATE_ITERATIVELY"),
    EVALUATION_EVALUATE_ITERATIVELY_AT_SPECIFIED_TIME("EVALUATION.EVALUATE_ITERATIVELY_AT_SPECIFIED_TIME"),
    METADATA_DISCOVERY_DESCRIBE_PROFILE("METADATA_DISCOVERY.DESCRIBE_PROFILE"),
    METADATA_DISCOVERY_DESCRIBE_SCOPING_ENTITY("METADATA_DISCOVERY.DESCRIBE_SCOPING_ENTITY"),
    METADATA_DISCOVERY_DESCRIBE_SCOPING_ENTITY_HIERARCHY("METADATA_DISCOVERY.DESCRIBE_SCOPING_ENTITY_HIERARCHY"),
    METADATA_DISCOVERY_DESCRIBE_SEMANTIC_REQUIREMENT("METADATA_DISCOVERY.DESCRIBE_SEMANTIC_REQUIREMENT"),
    METADATA_DISCOVERY_DESCRIBE_SEMANTIC_SIGNIFIER("METADATA_DISCOVERY.DESCRIBE_SEMANTIC_SIGNIFIER"),
    METADATA_DISCOVERY_DESCRIBE_TRAIT("METADATA_DISCOVERY.DESCRIBE_TRAIT"),
    METADATA_DISCOVERY_LIST_PROFILES("METADATA_DISCOVERY.LIST_PROFILES"),
    QUERY_FIND_KMS("QUERY.FIND_KMS"),
    QUERY_GET_KM_DATA_REQUIREMENTS("QUERY.GET_KM_DATA_REQUIREMENTS"),
    QUERY_GET_KM_DATA_REQUIREMENTS_FOR_EVALUATION_AT_SPECIFIED_TIME("QUERY.GET_KM_DATA_REQUIREMENTS_FOR_EVALUATION_AT_SPECIFIED_TIME"),
    QUERY_GET_KM_DESCRIPTION("QUERY.GET_KM_DESCRIPTION"),
    QUERY_GET_KM_EVALUATION_RESULT_SEMANTICS("QUERY.GET_KM_EVALUATION_RESULT_SEMANTICS"),
    QUERY_LIST_KMS("QUERY.LIST_KMS");

    private String dssName;

    private DssOperation(String operation) {
        this.dssName = operation;
    }
    
    public String getDssName() {
        return dssName;
    }
}
