/*
 * Copyright 2014-2020 OpenCDS.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.opencds.config.migrate;

import java.nio.file.Paths

import org.opencds.config.migrate.utilities.FileUtility;

import spock.lang.Specification

class ConfigMigratorSpec extends Specification {

    ConfigMigrator cm
    
    def setup() {
        cm = new ConfigMigrator()
    }
    
    def "test migration"() {
//        given:
        def targetPath = Paths.get("/Users/phillip/projects/opencds/opencds/opencds-knowledge-repository-data/src/main/resources/resources_v1.3")
        def configResources = [
            (ConfigResourceType.CODE_SYSTEMS): new ConfigResource(location: "resourceAttributes", name: "openCDSCodeSystems.xml"),
            (ConfigResourceType.EXECUTION_ENGINES): new ConfigResource(location: "resourceAttributes", name: "openCdsExecutionEngines.xml"),
            (ConfigResourceType.KNOWLEDGE_MODULES): new ConfigResource(location: "resourceAttributes", name: "knowledgeModules.xml"),
            (ConfigResourceType.SEMANTIC_SIGNIFIERS): new ConfigResource(location: "resourceAttributes", name: "semanticSignifiers.xml"),
            (ConfigResourceType.SUPPORTED_CONCEPTS): new ConfigResource(location: "resourceAttributes", name: "supportedConceptsConfigFile.xml"),
            (ConfigResourceType.AUTOGEN_CONCEPT_MAPPINGS_SPEC): new ConfigResource(location: "conceptMappingSpecifications/autoGeneratedMappings"),
            (ConfigResourceType.MANUAL_CONCEPT_MAPPINGS_SPEC): new ConfigResource(location: "conceptMappingSpecifications/manualMappings"),
            (ConfigResourceType.EXECUTION_ENGINE_MODULES): new ConfigResource(location: "knowledgeModules")
            ]
        OpencdsBaseConfig config = new OpencdsBaseConfig("SIMPLE_FILE", "/Users/phillip/projects/opencds/opencds/opencds-knowledge-repository-data/src/main/resources/resources_v1.1", configResources);
        config.setFileUtility(new FileUtility());
        
//        when:
        cm.migrate(targetPath, config)
        
//        then:
        true
    }

}
