package Bounce_v1_6_1

import org.opencds.vmr.v1_0.internal.EvaluatedPerson;
import org.opencds.vmr.v1_0.internal.EvaluatedPersonAgeAtEvalTime
import org.opencds.vmr.v1_0.internal.ClinicalStatement
import org.opencds.vmr.v1_0.internal.Demographics;
import org.opencds.vmr.v1_0.internal.FocalPersonId;
import org.opencds.vmr.v1_0.internal.datatypes.IVLDate;
import org.opencds.vmr.v1_0.internal.datatypes.CD;
import org.opencds.vmr.v1_0.internal.FocalPersonId;
import org.opencds.vmr.v1_0.internal.ObservationResult
import org.opencds.vmr.v1_0.internal.ObservationValue
import org.opencds.vmr.v1_0.internal.EncounterEvent
import org.opencds.vmr.v1_0.internal.concepts.VmrOpenCdsConcept
import org.joda.time.Period;
import org.joda.time.PeriodType;
import java.util.Date;
import java.text.DecimalFormat;

import java.util.ArrayList;
import java.util.List;

global java.lang.String clientLanguage
global java.lang.String clientTimeZoneOffset
global java.lang.String focalPersonId
global java.util.Date evalTime
global java.util.HashSet assertions
global java.util.HashMap namedObjects
 

 
 
rule "agent-orange-exposure"
			dialect "java", no-loop true
			when
				$person : EvaluatedPerson()
				$ee:EncounterEvent($type:encounterType)
				
				eval($type.getOriginalText().equals("agent-orange"))	
				eval($type.getDisplayName().equals("Yes"))	
			then	
			java.util.Date now = new java.util.Date();
			IVLDate testDate = new IVLDate();
			testDate.setLow(now);
			testDate.setHigh(now);
	
			ObservationResult observationResult = new ObservationResult();
			observationResult.setObservationEventTime(testDate);
	 		String observationProposalId = "2.16.840.1.113883.3.1829.11.1.2.1";
	 		observationResult.setId(observationProposalId);
	 		observationResult.setEvaluatedPersonId($person.getId());
	 		observationResult.setSubjectIsFocalPerson(true);
			observationResult.setClinicalStatementToBeRoot(true);
			observationResult.setToBeReturned(true);
			
			DecimalFormat twoPlaces = new DecimalFormat("#.##");
			//Setup the ObservationFocus
			CD focus = new CD();
			focus.setCode("427272008");
			focus.setCodeSystem("snomed");
			focus.setCodeSystemName("snomed");
			focus.setDisplayName("VA's Advice for Agent Orange Exposure Risk");
			focus.setOriginalText("http://www.publichealth.va.gov/exposures/agentorange/conditions/");
			observationResult.setObservationFocus(focus);
			//Setup the ObservationValue
			ObservationValue value = new ObservationValue();
			value.setText("Please note that this patient has been exposed to Agent Orange, and may be eligible for benefits for related conditions. For a list of presumptive diseases associated with this exposure, please see: http://www.publichealth.va.gov/exposures/agentorange/conditions/"); 
			observationResult.setObservationValue(value);
			
			insert(observationResult);
			System.out.println("***************** Inserting ObservationResult\n");
			
			namedObjects.put("observationResult", observationResult);
							
end 
