package Test_v1_5_5
//same as Bounce_v1_0_0 except that it requries Drools 5.3

import java.text.DecimalFormat
import java.util.HashMap
import java.util.HashSet
import java.util.Date
import java.util.Arrays
import java.lang.Double
import org.opencds.common.ConsoleLogger
import org.opencds.common.ILogger
import org.opencds.common.utilities.AbsoluteTimeDifference
import org.opencds.common.utilities.DateUtility
import org.opencds.common.utilities.MiscUtility
import org.opencds.common.utilities.StreamUtility
import org.opencds.common.utilities.StringToArrayUtility
import org.opencds.common.utilities.StringUtility
import org.opencds.common.utilities.XMLDateUtility
import org.opencds.vmr.v1_0.internal.AdministrableSubstance
import org.opencds.vmr.v1_0.internal.AdverseEvent
import org.opencds.vmr.v1_0.internal.AdverseEventBase
import org.opencds.vmr.v1_0.internal.AppointmentProposal
import org.opencds.vmr.v1_0.internal.AppointmentRequest
import org.opencds.vmr.v1_0.internal.Assertion
import org.opencds.vmr.v1_0.internal.BodySite
import org.opencds.vmr.v1_0.internal.CDSContext
import org.opencds.vmr.v1_0.internal.CDSInput
import org.opencds.vmr.v1_0.internal.CDSOutput
import org.opencds.vmr.v1_0.internal.CDSResource
import org.opencds.vmr.v1_0.internal.ClinicalStatement
import org.opencds.vmr.v1_0.internal.ClinicalStatementRelationship
import org.opencds.vmr.v1_0.internal.Demographics
import org.opencds.vmr.v1_0.internal.DeniedAdverseEvent
import org.opencds.vmr.v1_0.internal.DeniedProblem
import org.opencds.vmr.v1_0.internal.DoseRestriction
import org.opencds.vmr.v1_0.internal.DosingSigElement
import org.opencds.vmr.v1_0.internal.EncounterBase
import org.opencds.vmr.v1_0.internal.EncounterEvent
import org.opencds.vmr.v1_0.internal.Entity
import org.opencds.vmr.v1_0.internal.EntityBase
import org.opencds.vmr.v1_0.internal.EntityRelationship
import org.opencds.vmr.v1_0.internal.EvalTime
import org.opencds.vmr.v1_0.internal.EvaluatedPerson
import org.opencds.vmr.v1_0.internal.EvaluatedPersonRelationship
import org.opencds.vmr.v1_0.internal.EvaluatedPersonAgeAtEvalTime
import org.opencds.vmr.v1_0.internal.Facility
import org.opencds.vmr.v1_0.internal.FocalPersonId
import org.opencds.vmr.v1_0.internal.Goal
import org.opencds.vmr.v1_0.internal.GoalBase
import org.opencds.vmr.v1_0.internal.GoalProposal
import org.opencds.vmr.v1_0.internal.GoalValue
import org.opencds.vmr.v1_0.internal.MissedAppointment
import org.opencds.vmr.v1_0.internal.NamedObject
import org.opencds.vmr.v1_0.internal.ObservationBase
import org.opencds.vmr.v1_0.internal.ObservationOrder
import org.opencds.vmr.v1_0.internal.ObservationProposal
import org.opencds.vmr.v1_0.internal.ObservationResult
import org.opencds.vmr.v1_0.internal.ObservationValue
import org.opencds.vmr.v1_0.internal.Organization
import org.opencds.vmr.v1_0.internal.OtherEvaluatedPerson
import org.opencds.vmr.v1_0.internal.Person
import org.opencds.vmr.v1_0.internal.Problem
import org.opencds.vmr.v1_0.internal.ProblemBase
import org.opencds.vmr.v1_0.internal.ProcedureBase
import org.opencds.vmr.v1_0.internal.ProcedureEvent
import org.opencds.vmr.v1_0.internal.ProcedureOrder
import org.opencds.vmr.v1_0.internal.ProcedureProposal
import org.opencds.vmr.v1_0.internal.RelationshipToSource
import org.opencds.vmr.v1_0.internal.ScheduledAppointment
import org.opencds.vmr.v1_0.internal.ScheduledProcedure
import org.opencds.vmr.v1_0.internal.Specimen
import org.opencds.vmr.v1_0.internal.SubstanceAdministrationBase
import org.opencds.vmr.v1_0.internal.SubstanceAdministrationEvent
import org.opencds.vmr.v1_0.internal.SubstanceAdministrationOrder
import org.opencds.vmr.v1_0.internal.SubstanceAdministrationProposal
import org.opencds.vmr.v1_0.internal.SubstanceDispensationEvent
import org.opencds.vmr.v1_0.internal.SupplyBase
import org.opencds.vmr.v1_0.internal.SupplyEvent
import org.opencds.vmr.v1_0.internal.SupplyOrder
import org.opencds.vmr.v1_0.internal.SupplyProposal
import org.opencds.vmr.v1_0.internal.UnconductedObservation
import org.opencds.vmr.v1_0.internal.UndeliveredProcedure
import org.opencds.vmr.v1_0.internal.UndeliveredSubstanceAdministration
import org.opencds.vmr.v1_0.internal.UndeliveredSupply
import org.opencds.vmr.v1_0.internal.VMR
import org.opencds.vmr.v1_0.internal.cdsinputspecification.CDSInputSpecification
import org.opencds.vmr.v1_0.internal.cdsinputspecification.ClinicalStatementInputSpecification
import org.opencds.vmr.v1_0.internal.cdsinputspecification.CodedAttributeRequirement
import org.opencds.vmr.v1_0.internal.cdsinputspecification.EvaluatedPersonInputSpecification
import org.opencds.vmr.v1_0.internal.cdsinputspecification.PatientInputSpecification
import org.opencds.vmr.v1_0.internal.cdsinputspecification.RelatedEntityInputSpecification
import org.opencds.vmr.v1_0.internal.cdsinputspecification.RelatedEvaluatedPersonInputSpecification
import org.opencds.vmr.v1_0.internal.cdsinputspecification.TimeAttributeRequirement
import org.opencds.vmr.v1_0.internal.concepts.AdverseEventAffectedBodySiteConcept
import org.opencds.vmr.v1_0.internal.concepts.AdverseEventAffectedBodySiteLateralityConcept
import org.opencds.vmr.v1_0.internal.concepts.AdverseEventAgentConcept
import org.opencds.vmr.v1_0.internal.concepts.AdverseEventConcept
import org.opencds.vmr.v1_0.internal.concepts.AdverseEventCriticalityConcept
import org.opencds.vmr.v1_0.internal.concepts.AdverseEventSeverityConcept
import org.opencds.vmr.v1_0.internal.concepts.AdverseEventStatusConcept
import org.opencds.vmr.v1_0.internal.concepts.BrandedMedicationConcept
import org.opencds.vmr.v1_0.internal.concepts.CDSInputTemplateConcept
import org.opencds.vmr.v1_0.internal.concepts.CDSOutputTemplateConcept
import org.opencds.vmr.v1_0.internal.concepts.ClinicalStatementRelationshipConcept
import org.opencds.vmr.v1_0.internal.concepts.ClinicalStatementTemplateConcept
import org.opencds.vmr.v1_0.internal.concepts.DataSourceTypeConcept
import org.opencds.vmr.v1_0.internal.concepts.DoseTypeConcept
import org.opencds.vmr.v1_0.internal.concepts.DosingSigConcept
import org.opencds.vmr.v1_0.internal.concepts.EncounterCriticalityConcept
import org.opencds.vmr.v1_0.internal.concepts.EncounterTypeConcept
import org.opencds.vmr.v1_0.internal.concepts.EntityRelationshipConcept
import org.opencds.vmr.v1_0.internal.concepts.EntityTemplateConcept
import org.opencds.vmr.v1_0.internal.concepts.EntityTypeConcept
import org.opencds.vmr.v1_0.internal.concepts.EthnicityConcept
import org.opencds.vmr.v1_0.internal.concepts.EvaluatedPersonRelationshipConcept
import org.opencds.vmr.v1_0.internal.concepts.GenderConcept
import org.opencds.vmr.v1_0.internal.concepts.GenericMedicationConcept
import org.opencds.vmr.v1_0.internal.concepts.GoalCodedValueConcept
import org.opencds.vmr.v1_0.internal.concepts.GoalCriticalityConcept
import org.opencds.vmr.v1_0.internal.concepts.GoalFocusConcept
import org.opencds.vmr.v1_0.internal.concepts.GoalStatusConcept
import org.opencds.vmr.v1_0.internal.concepts.GoalTargetBodySiteConcept
import org.opencds.vmr.v1_0.internal.concepts.GoalTargetBodySiteLateralityConcept
import org.opencds.vmr.v1_0.internal.concepts.ImmunizationConcept
import org.opencds.vmr.v1_0.internal.concepts.InformationAttestationTypeConcept
import org.opencds.vmr.v1_0.internal.concepts.InformationRecipientPreferredLanguageConcept
import org.opencds.vmr.v1_0.internal.concepts.InformationRecipientTypeConcept
import org.opencds.vmr.v1_0.internal.concepts.ManufacturerConcept
import org.opencds.vmr.v1_0.internal.concepts.MedicationClassConcept
import org.opencds.vmr.v1_0.internal.concepts.MedicationConcept
import org.opencds.vmr.v1_0.internal.concepts.ObservationCodedValueConcept
import org.opencds.vmr.v1_0.internal.concepts.ObservationCriticalityConcept
import org.opencds.vmr.v1_0.internal.concepts.ObservationFocusConcept
import org.opencds.vmr.v1_0.internal.concepts.ObservationInterpretationConcept
import org.opencds.vmr.v1_0.internal.concepts.ObservationMethodConcept
import org.opencds.vmr.v1_0.internal.concepts.ObservationTargetBodySiteConcept
import org.opencds.vmr.v1_0.internal.concepts.ObservationTargetBodySiteLateralityConcept
import org.opencds.vmr.v1_0.internal.concepts.ObservationUnconductedReasonConcept
import org.opencds.vmr.v1_0.internal.concepts.PreferredLanguageConcept
import org.opencds.vmr.v1_0.internal.concepts.ProblemAffectedBodySiteConcept
import org.opencds.vmr.v1_0.internal.concepts.ProblemAffectedBodySiteLateralityConcept
import org.opencds.vmr.v1_0.internal.concepts.ProblemConcept
import org.opencds.vmr.v1_0.internal.concepts.ProblemImportanceConcept
import org.opencds.vmr.v1_0.internal.concepts.ProblemSeverityConcept
import org.opencds.vmr.v1_0.internal.concepts.ProblemStatusConcept
import org.opencds.vmr.v1_0.internal.concepts.ProcedureApproachBodySiteConcept
import org.opencds.vmr.v1_0.internal.concepts.ProcedureApproachBodySiteLateralityConcept
import org.opencds.vmr.v1_0.internal.concepts.ProcedureConcept
import org.opencds.vmr.v1_0.internal.concepts.ProcedureCriticalityConcept
import org.opencds.vmr.v1_0.internal.concepts.ProcedureMethodConcept
import org.opencds.vmr.v1_0.internal.concepts.ProcedureTargetBodySiteConcept
import org.opencds.vmr.v1_0.internal.concepts.ProcedureTargetBodySiteLateralityConcept
import org.opencds.vmr.v1_0.internal.concepts.RaceConcept
import org.opencds.vmr.v1_0.internal.concepts.ResourceTypeConcept
import org.opencds.vmr.v1_0.internal.concepts.SubstanceAdministrationApproachBodySiteConcept
import org.opencds.vmr.v1_0.internal.concepts.SubstanceAdministrationApproachBodySiteLateralityConcept
import org.opencds.vmr.v1_0.internal.concepts.SubstanceAdministrationCriticalityConcept
import org.opencds.vmr.v1_0.internal.concepts.SubstanceAdministrationGeneralPurposeConcept
import org.opencds.vmr.v1_0.internal.concepts.SubstanceAdministrationTargetBodySiteConcept
import org.opencds.vmr.v1_0.internal.concepts.SubstanceAdministrationTargetBodySiteLateralityConcept
import org.opencds.vmr.v1_0.internal.concepts.SubstanceDeliveryMethodConcept
import org.opencds.vmr.v1_0.internal.concepts.SubstanceDeliveryRouteConcept
import org.opencds.vmr.v1_0.internal.concepts.SubstanceFormConcept
import org.opencds.vmr.v1_0.internal.concepts.SupplyConcept
import org.opencds.vmr.v1_0.internal.concepts.SupplyCriticalityConcept
import org.opencds.vmr.v1_0.internal.concepts.SupplyTargetBodySiteConcept
import org.opencds.vmr.v1_0.internal.concepts.SupplyTargetBodySiteLateralityConcept
import org.opencds.vmr.v1_0.internal.concepts.SystemUserPreferredLanguageConcept
import org.opencds.vmr.v1_0.internal.concepts.SystemUserTaskContextConcept
import org.opencds.vmr.v1_0.internal.concepts.SystemUserTypeConcept
import org.opencds.vmr.v1_0.internal.concepts.UndeliveredProcedureReasonConcept
import org.opencds.vmr.v1_0.internal.concepts.UndeliveredSubstanceAdministrationReasonConcept
import org.opencds.vmr.v1_0.internal.concepts.VmrOpenCdsConcept
import org.opencds.vmr.v1_0.internal.concepts.VMRTemplateConcept
import org.opencds.vmr.v1_0.internal.datatypes.AddressPartType
import org.opencds.vmr.v1_0.internal.datatypes.ADXP
import org.opencds.vmr.v1_0.internal.datatypes.ANY
import org.opencds.vmr.v1_0.internal.datatypes.AD
import org.opencds.vmr.v1_0.internal.datatypes.BL
import org.opencds.vmr.v1_0.internal.datatypes.CD
import org.opencds.vmr.v1_0.internal.datatypes.CS
import org.opencds.vmr.v1_0.internal.datatypes.EntityNamePartQualifier
import org.opencds.vmr.v1_0.internal.datatypes.EntityNamePartType
import org.opencds.vmr.v1_0.internal.datatypes.EntityNameUse
import org.opencds.vmr.v1_0.internal.datatypes.EN
import org.opencds.vmr.v1_0.internal.datatypes.ENXP
import org.opencds.vmr.v1_0.internal.datatypes.II
import org.opencds.vmr.v1_0.internal.datatypes.INT
import org.opencds.vmr.v1_0.internal.datatypes.IVLDate
import org.opencds.vmr.v1_0.internal.datatypes.IVLPQ
import org.opencds.vmr.v1_0.internal.datatypes.IVLINT
import org.opencds.vmr.v1_0.internal.datatypes.IVLQTY
import org.opencds.vmr.v1_0.internal.datatypes.IVLREAL
import org.opencds.vmr.v1_0.internal.datatypes.IVLRTO
import org.opencds.vmr.v1_0.internal.datatypes.PostalAddressUse
import org.opencds.vmr.v1_0.internal.datatypes.PQ
import org.opencds.vmr.v1_0.internal.datatypes.QTY
import org.opencds.vmr.v1_0.internal.datatypes.REAL
import org.opencds.vmr.v1_0.internal.datatypes.RTO
import org.opencds.vmr.v1_0.internal.datatypes.TEL
import org.opencds.vmr.v1_0.internal.datatypes.TelecommunicationAddressUse
import org.opencds.vmr.v1_0.internal.datatypes.TelecommunicationCapability
import org.opencds.vmr.v1_0.internal.datatypes.UncertaintyType
import org.opencds.vmr.v1_0.internal.datatypes.XP
import org.opencds.vmr.v1_0.internal.utilities.LogicHelperUtility

global java.lang.String clientLanguage
global java.lang.String clientTimeZoneOffset
global java.lang.String focalPersonId
global java.util.Date evalTime
global java.util.HashSet assertions
global java.util.HashMap namedObjects

function String parseTextForKeyValues(String[] keyValues, String text)
{
    String result = "";
    for (String key : keyValues) {
        if (text.contains(key)) {
            result = text;
            break;
        }
    }
    return result;
}

function Double parseTextForDouble(String txt){
	if(txt == null || txt.isEmpty())
		return 0.0;
	
	return Double.valueOf(txt);
}


global java.util.Date evalTime
global String clientLanguage
global String clientTimeZoneOffset
global String focalPersonId
global java.util.HashSet assertions
global java.util.HashMap namedObjects

declare INDICATOR
    @propertyReactive
	incidents 	: int
	noHgA1CTst	: boolean @key //has no HgA1C test in the last 12 mos. - default = true
end
//NOTE:  all demographics about the Patient are always returned in the result 
//			when the result is an outputVMR.

//NOTE2:  all ClinicalStatements, except ObservationResults are always returned as root elements

//NOTE3:  all Entities that have a relationship to a ClinicalStatement or to another Entity 
//			are always returned nested within that ClinicalStatement or Entity ONLY if that
//			ClinicalStatement or Entity is flagged toBeReturned.  

//NOTE4:  all Entities that are related directly to the patient will be returned or not
//			depending on the setting of the toBeReturned flag.

rule "Initialize"
	salience 100, no-loop
	when
	then
		insert(new INDICATOR(true));
		
end

rule "ICD9 Diabetes"
	dialect "java", no-loop true
	//lock-on-active true, no-loop true
	//no-loop true
	when
		$indicator : INDICATOR()
		//$indicator : INDICATOR($incidents:incidents)
		Date( $t : time ) from new Date()
		//Not exactly 2 years...
		$problem : Problem( problemEffectiveTime != nil, 
							problemEffectiveTime.low after[-731d] $t, 
							parseTextForDouble(problemCode.code) > 249.99, 
							parseTextForDouble(problemCode.code) < 259.94 )
	then
		modify($indicator) { setIncidents( $indicator.getIncidents() + 1) };
		System.out.println("\nICD9 Diabetes Result : "+$indicator.getIncidents()+"\n\t");
		System.out.println("\nICD9 Diabetes Result : "+$problem+"\n\t");
end

rule "HgA1C Test"
	dialect "java", no-loop true
	when
		$indicator : INDICATOR()
		Date( $t : time ) from new Date()
		//Not exactly 1 year...548-4 HEMOGLOBIN A1C/HEMOGLOBIN.TOTAL, 17856-6 HEMOGLOBIN A1C/HEMOGLOBIN.TOTAL
		$or : ObservationResult( observationEventTime != nil,
									observationEventTime.low after[-365d] $t, 
									$code : observationFocus.code,
									observationValue != nil,
									observationValue.text != nil,
									$observationValue : observationValue )
		eval(Arrays.asList("4548-4","17856-6").contains($code))
		eval(Double.parseDouble($observationValue.getText()) >= 6.5)
	then
		//$indicator.setNoHgA1CTst(false);
		//update($indicator);
		modify($indicator) { setNoHgA1CTst(false) };
		System.out.println("\nHgA1C Test Result : "+$or+"\n\t");
		System.out.println("observationValue in double =   " + Double.parseDouble($observationValue.getText()));
end

rule "Diabetes"
	dialect "java", no-loop true
	when
		$indicator : INDICATOR( incidents > 1, noHgA1CTst == false)
		FocalPersonId($patientId : id)
	then
		System.out.println("\nDIABETES TESTED POSITIVE ******************* \n\t");
		
		//Do the IVLDate
		java.util.Date now = new java.util.Date();
		IVLDate testDate = new IVLDate();
		testDate.setLow(now);
		testDate.setHigh(now);

		ObservationResult observationResult = new ObservationResult();
		observationResult.setObservationEventTime(testDate);
 		String observationProposalId = "2.16.840.1.113883.3.1829.11.1.2.1";
 		observationResult.setId(observationProposalId);
 		observationResult.setEvaluatedPersonId($patientId);
 		observationResult.setSubjectIsFocalPerson(true);
		observationResult.setClinicalStatementToBeRoot(true);
		observationResult.setToBeReturned(true);
		
		DecimalFormat twoPlaces = new DecimalFormat("#.##");
		//Setup the ObservationFocus
		CD focus = new CD();
		focus.setCode("427272008");
		focus.setCodeSystem("snomed");
		focus.setCodeSystemName("snomed");
		focus.setDisplayName("Recommendation to Physician");
		focus.setOriginalText("For people without diabetes, the normal range for the hemoglobin A1c test is between 4% and 5.6%. Hemoglobin A1c levels between 5.7% and 6.4% indicate increased risk of diabetes, and levels of 6.5% or higher indicate diabetes.");
		observationResult.setObservationFocus(focus);
		//Setup the ObservationValue
		ObservationValue value = new ObservationValue();
		value.setText("DIABETES TESTED POSITIV"); 
		observationResult.setObservationValue(value);
		
		insert(observationResult);
		System.out.println("***************** Inserting ObservationResult\n");
		namedObjects.put("observationResult", observationResult);

end