substitutions:
  _IMAGE_NAME: ice

steps:
  - name: buildpacksio/pack:latest
    id: build
    entrypoint: pack
    args:
      - "build"
      - "us-central1-docker.pkg.dev/${PROJECT_ID}/containers/${_IMAGE_NAME}:${BRANCH_NAME}"
      - "--tag"
      - "us-central1-docker.pkg.dev/${PROJECT_ID}/containers/${_IMAGE_NAME}:${SHORT_SHA}"
      - "--descriptor"
      - ".build_config/project.toml"
      - "--env"
      - "BP_IMAGE_LABELS=git.commit.id=$COMMIT_SHA"
      - "--publish"