ice_knowledge_config_location=/usr/local/tomcat/webapps/opencds-decision-support-service/opencds-ice-service/src/main/resources/config
ice_knowledge_drools_location=/usr/local/tomcat/webapps/opencds-decision-support-service/opencds-ice-service/src/main/resources/drools
ice_knowledge_common_subdirectory=knowledgeCommon
ice_knowledge_modules_subdirectory=knowledgeModule
ice_base_rules_scoping_entity_id=org.cdsframework
ice_base_rules_version=1.0.0
output_earliest_and_overdue_dates=Y
enable_dose_override_feature=N
output_supplemental_text=Y
enable_unsupported_vaccines_group=N
vaccine_group_exclusions=VACCINE_GROUP_CONCEPT.991,VACCINE_GROUP_CONCEPT.992
disable_covid19_sep2023_dose_number_reset=N
disable_output_earliest_and_overdue_dates_for_pneumococcal_adult_series=N
disable_drools_event_logging=Y
